### ISSUE TITLE
ranger crash while step in to nas-folder

### ISSUE THREAD

**Issue by pacmexx** [ranger/ranger#1020]
I mount my FritzNAS as usual but if I want to enter the folder ranger crash with follow message.
To step into the NAS with nautilus is no problem, a new installation of ranger brought no improvement.

ranger version: 1.8.1, executed with python 2.7.14
Locale: de_DE.UTF-8
Current file: /media/fritzbox/SanDisk-UltraFit-01
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 362, in loop
    ui.redraw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 295, in redraw
    self.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 322, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 100, in draw
    self._calc_bar()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 105, in _calc_bar
    self._get_left_part(bar)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 182, in _get_left_part
    left.add(strftime(self.timeformat, localtime(stat.st_mtime)), 'mtime')
ValueError: year out of range

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

**Comment by hut** [comment]
Weird. Could you please give us the output of this command?

`python -c 'import os; print(os.stat("/media/fritzbox/SanDisk-UltraFit-01").st_mtime)'`

**Comment by shadowxnex** [comment]
I had same error when I have tried to mount resource that couldn't be mounted.
My solution of this is #1023

**Comment by dllud** [comment]
I experience the same kind of crash when browsing an MTP directory mounted with `jmtpfs`. The first directory it shows under the mount point, named Internal storage, has a strange date value that crashes ranger.

As a quick fix I surrounded `fromtimestamp` with a try-except:
```python
 try:
    file_date = datetime.fromtimestamp(fobj.stat.st_mtime)
except ValueError:
    return '?'
```
