### ISSUE TITLE
Crashes when previewing files for which the current user doesn't have permissions

### ISSUE THREAD

**Issue by chronzerg** [ranger/ranger#1033]
#### Runtime Environment

- Operating system and version: macOS 10.13.2
- Terminal emulator and version: Terminal 2.8
- Python version: 2.7.14
- Ranger version/commit: ranger-master 1.9.0b6
- Locale: None.None

#### Current Behavior
When `use_preview_script` is set to `true`, and you hover over a file to which the current user does not have permission no view, Ranger crashes.

#### Expected Behavior
When doing the same thing in a Python3 environment, Ranger simply does not display a preview for files it cannot open. I would expect a Python2 environment to do the same.

#### Possible Solutions
It seems Ranger isn't catching the proper Python2 exceptions. When Python3 fails to open a file, it throws an OSError, which is currently caught by Ranger. When Python2 fails to open a file, it instead throws IOError, which isn't being caught.

#### Steps to reproduce
1. Start Ranger
2. Turn on the `use_preview_script` option (toggled via z-v)
3. Hover over a file which the current user doesn't have permissions to view

#### Traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/local/lib/python2.7/site-packages/ranger/core/fm.py", line 387, in loop
    ui.redraw()
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/ui.py", line 326, in redraw
    self.poke()
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/displayable.py", line 248, in poke
    displayable.poke()
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/widgets/view_miller.py", line 267, in poke
    if self.preview and self.is_collapsed != self._collapse():
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/widgets/view_miller.py", line 181, in _collapse
    result = not self.columns[-1].has_preview()
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 122, in has_preview
    if not self.target.has_preview():
  File "/usr/local/lib/python2.7/site-packages/ranger/container/file.py", line 91, in has_preview
    if self.is_binary():
  File "/usr/local/lib/python2.7/site-packages/ranger/container/file.py", line 66, in is_binary
    if self.firstbytes and CONTROL_CHARACTERS & self.firstbytes:
  File "/usr/local/lib/python2.7/site-packages/ranger/container/file.py", line 59, in firstbytes
    with open(self.path, 'rb') as fobj:
IOError: [Errno 13] Permission denied: '/Users/chronzerg/.rnd'
```

**Comment by toonn** [comment]
@chronzerg I'm closing this since I assume the PR fixes it. Feel free to re-open if it doesn't.
