### ISSUE TITLE
Can't set `column_ratious` after typing `set viewmode!` twice

### ISSUE THREAD

**Issue by kutsan** [ranger/ranger#1035]
#### Runtime Environment

- Operating system and version: macOS 10.12.6
- Terminal emulator and version: Alacritty https://github.com/jwilm/alacritty/commit/b396a9a75350c5b1c82f5aae06a68dbd035df83c
- Python version: 3.6.4
- Ranger version/commit: ranger-master 1.9.0b6
- Locale: en_US.UTF-8

#### Current Behavior

I tried to change `column_ratios` after changing `viewmode` but it is not working.

#### Expected Behavior

`column_ratios` should work even after changing `viewmode`.

#### Context

I use both `miller` and `multipane` viewmodes. Depending on context I need to change `viewmode` option from one to another. 

#### Steps to reproduce

_Default `viewmode` is `miller` and `column_ratios` is `2,2,3,3`._

1. `set viewmode multipane`
1. `set viewmode miller`
1. `set column_ratios 2,3`
1. `'NoneType' object has no attribute 'erase'`

#### Traceback

```
18:06:17 INFO ranger version: ranger-master 1.9.0b6
18:06:17 INFO Python version: 3.6.4 (default, Jan  6 2018, 11:51:15) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0
18:06:17 INFO Locale: en_US.UTF-8
18:06:17 INFO Process ID: 33344
18:06:28 ERRO Notification: 'NoneType' object has no attribute 'erase'
18:06:28 ERRO 'NoneType' object has no attribute 'erase'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ranger/core/actions.py", line 249, in execute_console
    cmd.execute()
  File "/usr/local/lib/python3.6/site-packages/ranger/config/commands.py", line 434, in execute
    self.fm.set_option_from_string(name, value)
  File "/usr/local/lib/python3.6/site-packages/ranger/core/actions.py", line 109, in set_option_from_string
    localpath, tags)
  File "/usr/local/lib/python3.6/site-packages/ranger/container/settings.py", line 176, in set
    self.signal_emit('setopt.' + name, **kws)
  File "/usr/local/lib/python3.6/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc()
  File "/usr/local/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 84, in rebuild
    self.resize(self.y, self.x, self.hei, self.wid)
  File "/usr/local/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 223, in resize
    self.pager.resize(pad, left, hei - pad * 2, max(1, self.wid - left - pad))
  File "/usr/local/lib/python3.6/site-packages/ranger/gui/displayable.py", line 175, in resize
    self.win.erase()
AttributeError: 'NoneType' object has no attribute 'erase'
```

**Comment by kutsan** [comment]
@hut Thanks!
