### ISSUE TITLE
Ranger won't open

### ISSUE THREAD

**Issue by roorco** [ranger/ranger#1055]
Ranger crashes when trying to open it in different terminal:
```

ranger version: ranger-stable 1.9.0
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: it_IT.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 177, in main
    fm.initialize()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 100, in initialize
    self.rifle.reload_config()
  File "/usr/lib/python3.6/site-packages/ranger/ext/rifle.py", line 172, in reload_config
    raise ValueError("Line without delimiter")
ValueError: Line without delimiter
```

**Comment by toonn** [comment]
You probably have a misconfigured `rifle.conf`.

**Comment by roorco** [comment]
yes it was indeed.
thanks

**Comment by toonn** [comment]
For anyone with a similar issue: This was caused by a faulty `rifle.conf`. Ranger is now stricter in the interpretation of the config.
