### ISSUE TITLE
Ranger failing to find libncursesw.so.5

### ISSUE THREAD

**Issue by Morpheus3000** [ranger/ranger#1066]
#### Runtime Environment

- Operating system and version: Fedora release 26 (Twenty Six)
- Terminal emulator and version: GNU bash, version 4.4.12(1)-release (x86_64-redhat-linux-gnu)
- Python version: Python3 (Anaconda)
- Ranger version/commit: Latest version from Master (as of 9th February 2018)
- Locale: US English

#### Current Behavior
I installed from source, since I don't have sudo rights. Trying to start Ranger gives me this error:
ImportError: libncursesw.so.5: cannot open shared object file: No such file or directory
#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

Traceback (most recent call last):
  File ".../anaconda3/bin/ranger", line 36, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File ".../anaconda3/lib/python3.6/site-packages/ranger/core/main.py", line 32, in main
    from ranger.container.settings import Settings
  File ".../anaconda3/lib/python3.6/site-packages/ranger/container/settings.py", line 13, in <module>
    from ranger.gui.colorscheme import _colorscheme_name_to_class
  File ".../anaconda3/lib/python3.6/site-packages/ranger/gui/colorscheme.py", line 30, in <module>
    from curses import color_pair
  File ".../anaconda3/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ImportError: libncursesw.so.5: cannot open shared object file: No such file or directory

**Comment by toonn** [comment]
Sounds like you're missing the ncurses libs, try installing [this package](https://rpmfind.net/linux/RPM/fedora/26/x86_64/n/ncurses-compat-libs-6.0-8.20170212.fc26.x86_64.html) maybe. No experience with fedora so this was found googling, not sure whether 'rpmfind.net' is reliable/up to date.

**Comment by gaddox** [comment]
Do `find / -name "*libncurses*"` and post the output. Could also be related to: https://forum.antergos.com/topic/7999/importerror-with-libncursesw-so-5
