### ISSUE TITLE
Ranger crash when trying to read desktop.ini from windows partition

### ISSUE THREAD

**Issue by metr1xx** [ranger/ranger#1079]
#### Runtime Environment

- Operating system and version: Arch Linux / 4.15.3-1-ARCH
- Terminal emulator and version: rxvt-unicode 9.22-5
- Python version: Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
- Ranger version/commit: ranger version: ranger-stable 1.9.0
- Locale: en_US.UTF-8

#### Current Behavior
Crashes on highlighting the file

#### Expected Behavior
Display the text of the file

#### Context

Looked through images on my ntfs-3g partition

#### Possible Solutions
I don't know

#### Steps to reproduce
1. Looked through images on my ntfs-3g partition
2. Hit a desktop.ini file after in the tree
3. Ranger crashed

#### Traceback

```
metr1xx@shinobi:~|⇒  ranger
ranger version: ranger-stable 1.9.0
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8
Current file: '/home/metr1xx/Windows/Users/mtrx/Desktop/desktop.ini'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character
```

**Comment by toonn** [comment]
Sounds similar to #1045, could you try the solution there?

**Comment by Vintodrimmer** [comment]
Same here:

```
ranger version: ranger-stable 1.9.0
Python version: 3.6.4 (default, Dec 19 2017, 18:03:06) [GCC 7.2.0]
Locale: en_US.UTF-8
Current file: '/media/Windows/Users/vinto/Desktop/desktop.ini'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
'''

Updating the scope.sh didn't help.

**Comment by metr1xx** [comment]
@toonn Ran this:

> metr1xx@shinobi:|⇒  sudo pacman -Syyu
> metr1xx@shinobi:|⇒  sudo pacman -Q ranger
> ranger 1.9.1-1
> metr1xx@shinobi:|⇒  rm /home/metr1xx/.config/ranger/scope.sh
> metr1xx@shinobi:|⇒  ranger --copy-config=scope                   
> creating: /home/metr1xx/.config/ranger/scope.sh

Still crashing at the same file.

**Comment by toonn** [comment]
@metr1xx the fix hasn't been accepted into master yet so it's definitely not in a release yet.
My fix will prevent ranger from crashing, it just won't preview the files, @FichteFoll did some excellent work that'll allow you to preview many of these files if you install the optional dependency `chardet`.
You could test my PR by cloning it if you want, there's also `ranger-master` in the AUR I believe so you could install that with pacaur for example, it installs the head of the master branch, I'm sure my change'll be in master by tomorrow.

**Comment by toonn** [comment]
@metr1xx I just went ahead and merged it to master so if you install the AUR package it should be fixed.
