### ISSUE TITLE
Ranger crashes, if there is a 'octave-workspace'

### ISSUE THREAD

**Issue by theova** [ranger/ranger#1086]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: termite v13
- Python version: Python 3.6.4
- Ranger version/commit: ranger-master 1.9.1
- locale: de_DE.UTF-8

#### Current Behavior
The file 'octave-workspace' generated from an interactive octave-cli session is stored in a directory. If I try to go into this directory with ranger, it crashes.

#### Traceback
```
Traceback (most recent call last):
  File "/home/theo/ranger/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/home/theo/ranger/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/home/theo/ranger/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/home/theo/ranger/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/home/theo/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/theo/ranger/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/home/theo/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/theo/ranger/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/home/theo/ranger/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/home/theo/ranger/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/home/theo/ranger/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/home/theo/ranger/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

```

Thank you very much for your work! Ranger is super nice!

**Comment by toonn** [comment]
When you go into that directory is this file highlighted or not?

**Comment by theova** [comment]
`octave-workspace` was the first file/element in this directory and I wasn't able to see the content of the directory.

I'm sorry, I can't reproduce it anymore. If it will reappear, I'll try to find out how to reproduce it.
