### ISSUE TITLE
Scope.sh can't handle text with nullbytes

### ISSUE THREAD

**Issue by gaddox** [ranger/ranger#1094]
#### Runtime Environment
ranger version: ranger-master 1.9.1
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8
Kernel: 4.15.3-2-ARCH x86_64

Affects all terminal emulators, and stops tty from interacting with the file.

#### Current Behavior
If you're using the scope.sh file previewer, when you highlight a file, with a type of "text/plain", but which contains a trailing nullbyte, the output will still be sent to Python and cause it to crash. 

#### Possible Solutions
See #1095

#### Steps to reproduce
0. Uncomment/edit in `rc.onf`, `set use_preview_script true` and comment out `set preview_script ~/.config/ranger/scope.sh`
1. Obtain a file that's under 41 bytes, has a mime-type of `text`, and has a trailing nullbyte.
a.  `echo -en "FooBar\x00" > BREAK_ME; file -i 'BREAK_ME'`
2. Run `ranger` and set the cursor bar on top of `BREAK_ME`
3. Crash

#### Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character
```

**Comment by toonn** [comment]
I patched this yesterday in #1091. I see you're running `ranger-git` from the AUR so you should get the patch if you update. My patch just suppresses the exception and doesn't show anything. @FichteFoll has implemented encoding detection with chardet so once that PR lands you should get previews in many more cases if you have chardet installed.
