### ISSUE TITLE
Ranger is crashing while trying to preview particular RTF file

### ISSUE THREAD

**Issue by kmws** [ranger/ranger#1107]
I have a folder with .rtf and .pdf file. rtf file is a first file in a folder. When I'm trying to enter this folder, ranger crashes (I guess the "previewer" fails to parse it).

I have other .rtf file in another folder and ranger behaves fine (it previews the file), so I assume something is wrong with this particular .rtf file. Still, I think ranger shouldn't just crash?

It occurs both on xfce4-terminal and in tmux.

=====

ranger version: ranger-stable 1.9.0
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_GB.UTF-8
Current file: '<snip>/readme.rtf'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

**Comment by toonn** [comment]
I think this was fixed in #1091, it was released in 1.9.1 I believe so either wait for the release to get to your distro or install the master branch. Feel free to reopen if that doesn't fix your problem.

**Comment by kmws** [comment]
Yes! Sorry for not checking the newest version.

**Comment by toonn** [comment]
Np, it happens, we're happy with issue reports in general : )

**Comment by dequis** [comment]
>I think this was fixed in #1091, it was released in 1.9.1 I believe

I got this with 1.9.1, looks like that PR was submitted and merged 3 days after the 1.9.1 release
