### ISSUE TITLE
OverflowError when moving files

### ISSUE THREAD

**Issue by sobjornstad** [ranger/ranger#1112]
#### Runtime Environment

- Operating system and version: Linux Mint 18.02 (Linux kernel 4.10.0, x86_64)
- Terminal emulator and version: gnome-terminal 3.18.3
- Python version: 2.7.12
- Ranger version/commit: ranger-stable 1.7.1 (from package repository)
- Locale: en_US.UTF-8

#### Current Behavior
Selected a folder and cut it. After pasting, ranger crashed moments later, after moving a couple of the contained files but not all of them.

#### Expected Behavior

Ranger finishes copying the files without crashing.

#### Context

The folder contained Audacity projects, which have a large number of .au files in several subfolders. I am doing a major reorganization of my filesystem and have moved many, many other files and folders recently and this is the first time I have experienced this error, so the large number of contained files is the only theory I have about why this occurred. I was not using any unusual features, movement commands, etc.

I restarted ranger, cut the files within the folder instead of the whole folder, and the issue did not recur. I would probably not bother reporting this had the message not asked me to, so if this is too hard to track down from just the traceback, no big deal.

#### Traceback

```
ranger version: 1.7.1, executed with python 2.7.12
Locale: en_US.UTF-8
Current file: [an unrelated directory which had the cursor over it when I did the paste]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 100, in draw
    self._print_result(self.result)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 310, in _print_result
    self.color_at(0, 0, int(barwidth), ("in_statusbar", "loaded"))
  File "/usr/lib/python2.7/dist-packages/ranger/gui/curses_shortcuts.py", line 67, in color_at
    self.win.chgat(y, x, wid, attr)
OverflowError: signed integer is greater than maximum

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by sobjornstad** [comment]
I just realized that the directory I cut was a symlink to another directory. This is presumably part of the issue. Some of the pointed contents did get copied successfully however.

**Comment by toonn** [comment]
I don't think this has been fixed, so thanks for reporting. I did notice you're still on 1.7.1 though, it would be great if you got reproduce this with 1.9.1.
