### ISSUE TITLE
Error when copying broken symlink in copytree mode

### ISSUE THREAD

**Issue by dzekus** [ranger/ranger#1116]
#### Runtime Environment

- Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
- Ranger version/commit: ranger-master 1.9.1
- Locale: en_US.UTF-8
#### Current Behavior
If I yank directory with broken symlink inside and then paste it somewhere, I get error.
#### Expected Behavior
Symlink should be copied "as is" - without dereferencing.
#### Possible Solutions
\# line 58 in shutil_generatorized.py
\- follow = follow_symlinks or not (os.path.islink(src) and os.path.islink(dst))
\+ follow = follow_symlinks and not (os.path.islink(src) and os.path.islink(dst))
#### Steps to reproduce
1. Create directories "foo" and "bar".
2. Create broken symlink inside "foo" (ln -s baz baz.link).
3. Yank (yy) "foo" and paste (pp) into "bar".
#### Traceback

```
Traceback (most recent call last):
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/loader.py", line 411, in work
    next(item.load_generator)
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/loader.py", line 126, in generate
    overwrite=self.overwrite,
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/ext/shutil_generatorized.py", line 256, in copytree
    raise Error(errors)
shutil.Error: [('/tmp/foo/baz.link', '/tmp/bar/foo/baz.link', "[Errno 2] No such file or directory: '/tmp/foo/baz.link'")]
```

**Comment by toonn** [comment]
I'm not sure the solution is to always copy symlinks verbatim, seems more useful to me to not break symlinks after copying.

**Comment by dzekus** [comment]
> I'm not sure the solution is to always copy symlinks verbatim, seems more useful to me to not break symlinks after copying.

Could you elaborate on this? So what is the planned fix?

**Comment by toonn** [comment]
Nothing planned yet.
Elaboration:
I have a relative symlink to `~/A` in a directory `~/somepath/B`, I copy `B` to `~/C`. I want the symlink in C to point to `../A`, not `../../A` and absolute symlinks should never be messed with. Copying the symlink verbatim would break a working symlink.

I could see copying broken symlinks verbatim but there's an edge case: What if `~/A` is mounted with nfs but only when you're at home or something. Even though the symlink may seem broken at the time of copy it's not really broken and should still be changed. I don't see a way to detect this case. Only way to get it to always work is turn all symlinks into absolute links but then there's trouble when copying across systems and when copying links somewhere to archive them in a zip or something.

**Comment by dzekus** [comment]
Yeah, nobody wants to break working symlinks - that's obvious.

Maybe it's just me, but I consider raising errors and stopping copy process a more severe problem than dangling symlinks. I would expect the default copy-paste operation (by default I mean \<yy\> and then \<pp\>) to work like e.g GNU cp in recursive mode or any other popular GUI file manager.

To racap: in my humble opinion, by default symlinks copied verbatim and other "edge cases" handled by user explicitly set options.

**Comment by toonn** [comment]
While I understand where you're coming from, I disagree, imo ranger should use an easy default. If you want `mv` or `cp`'s semantics you can always just use those.

**Comment by lahwaacz** [comment]
> While I understand where you're coming from, I disagree, imo ranger should use an easy default. If you want `mv` or `cp`'s semantics you can always just use those.

Firstly, `mv` and `cp` don't have a UI so I can't agree with your advice.

As for the "easy default": I would not call breaking the entire operation (which can't be resumed) just because of an edge case an easy default. Moreover, the edge case handling is still half-baked to say the least, e.g. if you have a symlink `./test/foo` -> `bar` (i.e. inside the `test` directory) and you yank and paste the `./test` directory tree, there is absolutely no reason to abort regardless if `bar` exists or not, because relative link target is inside the directory tree being copied.

Also, to add something to the bug report: IIRC, if you start multiple copy operations which will get queued after each other, a single broken symlink disrupts the whole queue, even if the other items would have been copied successfully by themselves.

**Comment by jakoprd** [comment]
this bug is extra annoying when you copy directory over network. ranger cancel operation. some files are missing in target host. so you must manualy find and fix all symlinks first. if source directory is read only, it is impossible use ranger for copying.

**Comment by vejkse** [comment]
@jakoprd Could you check with the latest unreleased version of the code?  I can’t reproduce it with it.  I think it was fixed by https://github.com/ranger/ranger/pull/2635 which is neither in 1.9.3 nor in 1.9.4.

**Comment by jakoprd** [comment]
it works now! i had probably some network connection issues. ranger still print error to statusbar when copy broken symlink, but files not missing now! sorry for my hasty reaction.

**Comment by toonn** [comment]
Closing as presumed fixed.
