### ISSUE TITLE
Error when expanding %c macro and copy buffer is empty

### ISSUE THREAD

**Issue by dzekus** [ranger/ranger#1117]
#### Runtime Environment

- Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
- Ranger version/commit: ranger-master 1.9.1
- Locale: en_US.UTF-8
#### Current Behavior
If I try to expand %c macro and copy buffer is empty, I get error. 
#### Expected Behavior
It should be similar to expanding %t macro when there are no tagged files, e.g. empty string.
#### Context

Checking contents of copy buffer.
#### Steps to reproduce
1. Uncut (uy)
2. Execute `:echo %c`
#### Traceback

```
Traceback (most recent call last):
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/actions.py", line 243, in execute_console
    escape=cmd.escape_macros_for_shell)
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/actions.py", line 275, in substitute_macros
    raise ValueError("Could not apply macros to `%s'" % string)
ValueError: Could not apply macros to `echo %c'
```

**Comment by toonn** [comment]
Are you running ranger with `--debug`? I can't reproduce this, I get an error message printed out inside ranger.

**Comment by dzekus** [comment]
No, I'm not using any flags. However, if run with `--debug` flag set, ranger crashes.

#### Steps to reproduce
- Start program `./ranger.py --debug`
- Execute `:echo %c`

#### Traceback
```
Traceback (most recent call last):
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/config/commands.py", line 923, in execute
    result = eval(code)  # pylint: disable=eval-used
  File "<string>", line 1, in <module>
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/gui/widgets/console.py", line 454, in execute
    self.fm.execute_console(self.line)
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/actions.py", line 243, in execute_console
    escape=cmd.escape_macros_for_shell)
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/actions.py", line 275, in substitute_macros
    raise ValueError("Could not apply macros to `%s'" % string)
ValueError: Could not apply macros to `echo %c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/fm.py", line 396, in loop
    ui.handle_input()
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/gui/ui.py", line 274, in handle_input
    self.handle_key(key)
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/gui/displayable.py", line 271, in press
    focused_obj.press(key)
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/gui/widgets/console.py", line 187, in press
    if not self.fm.ui.press(key):
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/gui/ui.py", line 224, in press
    quantifier=keybuffer.quantifier,
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/actions.py", line 251, in execute_console
    cmd.execute()
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/config/commands.py", line 931, in execute
    "following code: `%s`" % (err, code), bad=True)
  File "/mnt/hdd/RESCUENEWEST/github/ranger/ranger/core/actions.py", line 170, in notify
    raise Exception(str(obj))
Exception: The error `Could not apply macros to `echo %c'` was caused by evaluating the following code: `fm.ui.console.execute()`

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Do you have an old `commands.py`? Try running without configs using `ranger --clean`.

**Comment by dzekus** [comment]
Setting `--clean` changed nothing. I've tried different terminals, fresh clone, switching to python 2.7, ranger on ARM, but I always get the same result as shown above (although python 2 produces shorter traceback).

**Comment by toonn** [comment]
I still can't reproduce this. Did you run `--clean` without `--debug`? Not that I still get an "error" but it's inside ranger, not a traceback after a crash.

**Comment by dzekus** [comment]
To be more precise, here are some tested combinations.
### Variant 1
- Command to launch ranger: `python2 ./ranger.py --clean`
- Command inside ranger: `:echo %c`
- Outcome: error notification in status bar and traceback in log
- Ranger process status: **alive**
- Traceback: 
```
Message Log:              
19:47:48 INFO ranger version: ranger-master 1.9.1
19:47:48 INFO Python version: 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
19:47:48 INFO Locale: None.None
19:47:48 INFO Process ID: 25260
19:47:59 ERRO Notification: Could not apply macros to `echo %c'
19:47:59 ERRO Could not apply macros to `echo %c'
Traceback (most recent call last):
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 243, in execute_console
    escape=cmd.escape_macros_for_shell)
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 275, in substitute_macros
    raise ValueError("Could not apply macros to `%s'" % string)
ValueError: Could not apply macros to `echo %c'
```
### Variant 2
- Command to launch ranger: `python2 ./ranger.py --clean --debug`
- Command inside ranger: `:echo %c`
- Outcome: traceback outside of ranger
- Ranger process status: **crash**
- Traceback: 
```
ranger version: ranger-master 1.9.1
Python version: 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
Locale: None.None
Current file: '/mnt/hdd/ranger/doc'

Traceback (most recent call last):
  File "/mnt/hdd/ranger/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/mnt/hdd/ranger/ranger/core/fm.py", line 396, in loop
    ui.handle_input()
  File "/mnt/hdd/ranger/ranger/gui/ui.py", line 274, in handle_input
    self.handle_key(key)
  File "/mnt/hdd/ranger/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/mnt/hdd/ranger/ranger/gui/displayable.py", line 271, in press
    focused_obj.press(key)
  File "/mnt/hdd/ranger/ranger/gui/widgets/console.py", line 187, in press
    if not self.fm.ui.press(key):
  File "/mnt/hdd/ranger/ranger/gui/ui.py", line 224, in press
    quantifier=keybuffer.quantifier,
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 251, in execute_console
    cmd.execute()
  File "/mnt/hdd/ranger/ranger/config/commands.py", line 931, in execute
    "following code: `%s`" % (err, code), bad=True)
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 170, in notify
    raise Exception(str(obj))
Exception: The error `Could not apply macros to `echo %c'` was caused by evaluating the following code: `fm.ui.console.execute()`

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
### Variant 3
- Command to launch ranger: `python3 ./ranger.py --clean`
- Command inside ranger: `:echo %c`
- Outcome: error notification in status bar and traceback in log
- Ranger process status: **alive**
- Traceback: 
```
Message Log:              
19:53:59 INFO ranger version: ranger-master 1.9.1
19:53:59 INFO Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
19:53:59 INFO Locale: en_US.UTF-8
19:53:59 INFO Process ID: 25290
19:54:04 ERRO Notification: Could not apply macros to `echo %c'
19:54:04 ERRO Could not apply macros to `echo %c'
Traceback (most recent call last):
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 243, in execute_console
    escape=cmd.escape_macros_for_shell)
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 275, in substitute_macros
    raise ValueError("Could not apply macros to `%s'" % string)
ValueError: Could not apply macros to `echo %c'
```
### Variant 4
- Command to launch ranger: `python3 ./ranger.py --clean --debug`
- Command inside ranger: `:echo %c`
- Outcome: traceback outside of ranger
- Ranger process status: **crash**
- Traceback: 
```
ranger version: ranger-master 1.9.1
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8
Current file: '/mnt/hdd/ranger/doc'

Traceback (most recent call last):
  File "/mnt/hdd/ranger/ranger/config/commands.py", line 923, in execute
    result = eval(code)  # pylint: disable=eval-used
  File "<string>", line 1, in <module>
  File "/mnt/hdd/ranger/ranger/gui/widgets/console.py", line 454, in execute
    self.fm.execute_console(self.line)
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 243, in execute_console
    escape=cmd.escape_macros_for_shell)
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 275, in substitute_macros
    raise ValueError("Could not apply macros to `%s'" % string)
ValueError: Could not apply macros to `echo %c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/hdd/ranger/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/mnt/hdd/ranger/ranger/core/fm.py", line 396, in loop
    ui.handle_input()
  File "/mnt/hdd/ranger/ranger/gui/ui.py", line 274, in handle_input
    self.handle_key(key)
  File "/mnt/hdd/ranger/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/mnt/hdd/ranger/ranger/gui/displayable.py", line 271, in press
    focused_obj.press(key)
  File "/mnt/hdd/ranger/ranger/gui/widgets/console.py", line 187, in press
    if not self.fm.ui.press(key):
  File "/mnt/hdd/ranger/ranger/gui/ui.py", line 224, in press
    quantifier=keybuffer.quantifier,
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 251, in execute_console
    cmd.execute()
  File "/mnt/hdd/ranger/ranger/config/commands.py", line 931, in execute
    "following code: `%s`" % (err, code), bad=True)
  File "/mnt/hdd/ranger/ranger/core/actions.py", line 170, in notify
    raise Exception(str(obj))
Exception: The error `Could not apply macros to `echo %c'` was caused by evaluating the following code: `fm.ui.console.execute()`

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Note that this is the intended behavior. The error message in ranger is definitely more useful than a command running without an argument that you expected. What's your use case exactly? Running echo with an empty string is harmless but not everything is.
