### ISSUE TITLE
Broken pipe crash using process substitution

### ISSUE THREAD

**Issue by bchallenor** [ranger/ranger#1119]
#### Runtime Environment

- Operating system and version: NixOS unstable
- Terminal emulator and version: Blink (hterm)
- Python version: 2.7.14
- Ranger version/commit: 1.9.1 
- Locale: en_US.UTF-8

#### Current Behavior

```
$ ranger --choosedir >(echo)

ranger version: ranger-master 1.9.1
Python version: 2.7.14 (default, Sep 16 2017, 17:49:51) [GCC 7.3.0]
Locale: None.None
Current file: '/home'

Traceback (most recent call last):
  File "/nix/store/a2669py3h1h95wapk72b279sbac3c7ap-ranger-1.9.1/lib/python2.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/nix/store/a2669py3h1h95wapk72b279sbac3c7ap-ranger-1.9.1/lib/python2.7/site-packages/ranger/core/fm.py", line 419, in loop
    fobj.write(self.thisdir.path)
IOError: [Errno 32] Broken pipe

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

#### Expected Behavior

`ranger --choosedir >(echo)` does not crash.

#### Context

`echo` is just a minimal example to reproduce the crash - I realise it's not very useful! In reality I want to send the directory name to a different process. I was hoping that process substitution would work here as per the 1.9.1 release notes.

Note if `--choosedir` could write to stdout (e.g. with the special syntax: `--choosedir -`), this would be sufficient for me. Then I could use a pipe instead of process substitution.

**Comment by toonn** [comment]
I can reproduce this, both with and without the `=`:
```
[toonn@titan ~]$ ranger --choosedir=>(echo)
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_DK.UTF-8
Current file: '/home/toonn'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 396, in loop
    ui.handle_input()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 274, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 208, in handle_key
    self.press(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 224, in press
    quantifier=keybuffer.quantifier,
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 251, in execute_console
    cmd.execute()
  File "/usr/lib/python3.6/site-packages/ranger/config/commands.py", line 581, in execute
    self._exit_no_work()
  File "/usr/lib/python3.6/site-packages/ranger/config/commands.py", line 575, in _exit_no_work
    self.fm.exit()
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 62, in exit
    raise SystemExit
SystemExit

During handling of the above exception, another exception occurred:

BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 419, in loop
    fobj.write(self.thisdir.path)
BrokenPipeError: [Errno 32] Broken pipe

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by mxovd** [comment]
`ranger --choosedir >(echo)` is crashing for me too, but i'm not quite sure if it's supposed to work in the first place. 
`ranger --choosedir >(grep home) `and `ranger --choosedir=>(grep home) `are both working on my end

**Comment by craigbarnes** [comment]
This is probably because `ranger` relies on using `stdout` to write to the terminal; so it can't be redirected or used for any other purpose.

Most programs that want to allow using `stdout` for other purposes open `/dev/tty` at startup if fd 1 isn't a tty. In C, for example:

```
if (!isatty(STDOUT_FILENO)) {
    if (!freopen("/dev/tty", "w", stdout)) {
        perror("freopen");
        exit(1);
    }
}
```

Allowing `stdout` to be redirected would also allow editors to run `ranger` as a child process and read filenames via pipes instead of temporary files.

I have no idea how any of this is done in Python, otherwise I send a PR...

**Comment by craigbarnes** [comment]
I've been using a wrapper script to allow combining `ranger --choosefiles=...` with stdio redirection:

```sh
#!/bin/sh
set -eu

TMPFILE="$(mktemp)"
trap "rm -f '$TMPFILE'" INT QUIT TERM HUP EXIT
ranger --choosefiles="$TMPFILE" </dev/tty >/dev/tty
cat "$TMPFILE"
```

It'd be nice if ranger would support something like e.g. `--choosefiles=-` out of the box though. I have a rough idea of the changes required to allow it (as typically done in C), but no idea how to actually implement it in a Python program...
