### ISSUE TITLE
Ranger crashes when I scroll over a .sh file

### ISSUE THREAD

**Issue by RewoundVHS** [ranger/ranger#1131]
#### Runtime Environment

- Operating system and version: Arch Linux 
- Terminal emulator and version: Konsole 17.12.3
- Python version: 3.6.4
- Ranger version/commit:  ranger-master 1.9.1
- Locale: en_US.UTF-8

#### Current Behavior
Crashes when I press j to move down or h to move up to a file ending in .sh

#### Steps to reproduce
1. Download pia-installer-linux.tar.gz
2. Unzip
3. Scroll over unzipped .sh file

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

```

**Comment by toonn** [comment]
This was fixed in #1091, you seem to be running ranger-master from the AUR so just updating that should get you the fix.
Reopen if that doesn't resolve it.

**Comment by RewoundVHS** [comment]
I wasn't running the AUR version, I had the Arch Community repo version installed. I also tried the non-git version from the AUR and it hadn't been fixed there. After installing the ranger-git package from the AUR my issue was solved.

**Comment by toonn** [comment]
Ah, my bad. Didn't know that version showed as "ranger-master" too. Our master branch is pretty stable but if you don't like being on the cutting edge you can go back to the regular package after we release 1.9.2.
