### ISSUE TITLE
Ranger crashes on *.asm file preview

### ISSUE THREAD

**Issue by JAkutenshi** [ranger/ranger#1144]
#### Runtime Environment

- Operating system and version: ArchLinux
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Python version: Python version: 3.6.4
- Ranger version/commit: ranger version: ranger-master 1.9.1
- Locale: en_US.UTF-8

#### Current Behavior
Crashes for attemt to preview attached asm file.
[lab2.txt](https://github.com/ranger/ranger/files/1934482/lab2.txt)

#### Expected Behavior
Text preview in the third layout. Vim open it successfully.

#### Context

I can't moving in a dir with that file.

#### Possible Solutions
Add exception for "null characters"?

#### Steps to reproduce
1. cd dir with attached file
2. select attached file
3.  crash

#### Traceback

```
ranger version: ranger-master 1.9.1
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8
Current file: '/home/jakutenshi/study/teaching/OS/leti_os_2018/6383/TereshchenkoVN/lab2/lab2.asm'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character
```

**Comment by toonn** [comment]
I believe this was fixed in #1091. It'll be in the next release. If you can't wait you can install `ranger-git` from the AUR ; )

**Comment by JAkutenshi** [comment]
Hi, @toonn thanks, just ranger asked me to do report and i did it :) Glad to read that it fixed it and will be in release soon, thanks!

**Comment by toonn** [comment]
Yes, thank you for the report. We do appreciate it! : )
