### ISSUE TITLE
Ranger won't open. Might be a Python issue?

### ISSUE THREAD

**Issue by Orejo** [ranger/ranger#1153]
#### Runtime Environment

- Operating system and version: Arch Linux 4.15.15-1
- Terminal emulator and version: st 0.81
- Python version: 3.6.5
- Ranger version/commit: ranger-master 1.9.1
- Locale: None.None

#### Current Behavior
Ranger won't open. See the traceback below.

#### Traceback

```
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 177, in main
    fm.initialize()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.6/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.6/site-packages/ranger/container/bookmarks.py", line 223, in _load_dict
    for line in fobj:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 27: ordinal not in range(128)
```

Today I upgraded to the latest Python3 version 3.6.5-2 as there was a new version available through the Arch repos. Unfortunately, this might have broken ranger for me. I downgraded Python3 to the former version 3.6.5-1, which didn't solve the issue for me. I'm not really sure what and why this happens, but hope that you can help me.

I cloned the master branch and run ranger from there, but the error still persists.

**Comment by im-vmn** [comment]
I've encountered a similar issue. Here the output:

```
ranger version: ranger 1.9.3
Python version: 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 117, in main
    fm = FM(paths=paths)
         ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 79, in __init__
    self.mimetypes = mimetypes.MimeTypes()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/mimetypes.py", line 74, in __init__
    init()
  File "/usr/lib/python3.11/mimetypes.py", line 379, in init
    db.read(file)
  File "/usr/lib/python3.11/mimetypes.py", line 210, in read
    self.readfp(fp, strict)
  File "/usr/lib/python3.11/mimetypes.py", line 221, in readfp
    line = fp.readline()
           ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 8: invalid start byte
```

Ranger was installed with apt. I tried `LC_ALL=C.UTF-8 ranger ` and `en_US.UTF-8`, ranger wouldn't start, the same error. I was able to fix it by installing **python3-chardet** package.

**Comment by vejkse** [comment]
This doesn’t look like the same issue, above the error happened when loading ranger’s bookmarks, in your case it happens when loading mimetype configuration files — one of the following files:
```python
knownfiles = [
    "/etc/mime.types",
    "/etc/httpd/mime.types",                    # Mac OS X
    "/etc/httpd/conf/mime.types",               # Apache
    "/etc/apache/mime.types",                   # Apache 1
    "/etc/apache2/mime.types",                  # Apache 2
    "/usr/local/etc/httpd/conf/mime.types",
    "/usr/local/lib/netscape/mime.types",
    "/usr/local/etc/httpd/conf/mime.types",     # Apache 1.2
    "/usr/local/etc/mime.types",                # Apache 1.3
    ]
```
Your mimetype configuration file might not be UTF-8-encoded or might be corrupted.  I’m not sure why installing `python3-chardet` helped.
