### ISSUE TITLE
Ranger crashed on move to different (mounted) network directory

### ISSUE THREAD

**Issue by tom-i** [ranger/ranger#1165]
#### Runtime Environment

- Operating system and version: Fedora 28
- Terminal emulator and version: Tilda(1.4.1) + Tmux(2.7)
- Python version: 3.6.5
- Ranger version/commit: 1.7.2
- Locale: en_US.UTF-8

#### Current Behavior
Ranger crashed after time it has been running few days without contact. 
#### Expected Behavior
Go to different directory without crash.
#### Context

I just want to move to different mount network directory, which I have mounted on my computer. So maybe some problem with refresh mounted network directory?
#### Steps to reproduce
1. mount network directory to your computer
2. run ranger few hours (days)
3. try to move to different directory.
BUG - ranger crashed

#### Traceback

```
ranger version: 1.7.2, executed with python 3.6.5
Locale: en_US.UTF-8
Current file: /mnt/uztst013/opt/kcapps/kc68-rls
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browserview.py", line 98, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 166, in draw
    self._draw_directory()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 273, in _draw_directory
    text = current_linemode.filetitle(drawn, metadata)
  File "/usr/lib/python3.6/site-packages/ranger/core/linemode.py", line 83, in filetitle
    return "%s %s %s %s" % (file.get_permission_string(),
  File "/usr/lib/python3.6/site-packages/ranger/container/fsobject.py", line 388, in get_permission_string
    mode = self.stat.st_mode
AttributeError: 'NoneType' object has no attribute 'st_mode'
```

**Comment by toonn** [comment]
Not sure who's maintaining that package but like debian, fedora moves slow. There are options if you don't want to have to update by hand though, you could install through pip or nix.
