### ISSUE TITLE
Crash when previewing *.REG

### ISSUE THREAD

**Issue by leewdch** [ranger/ranger#1169]
#### Runtime Environment

- Operating system and version: Arch Linux 4.16.8-1-ARCH
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Python version: Python 3.6.5
- Ranger version/commit: ranger-master 1.9.1
- Locale: en_US.UTF-8

#### Current Behavior
As soon as I hover on a REG file in $HOME ranger crashes

#### Context

I wasn't actually trying to preview the file but simply hovering on it causes the crash

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character
[regfile.zip](https://github.com/ranger/ranger/files/1998804/regfile.zip)

```

I've attached the REG file

**Comment by leewdch** [comment]
[regfile.zip](https://github.com/ranger/ranger/files/1998807/regfile.zip)

**Comment by toonn** [comment]
Hmm, looks like what was fixed in #1091. Could you test with the latest master? I'm planning on cutting a release this week.

**Comment by holytrousers** [comment]
I had the same problem with desktop.ini files on a windows partition and the problem disappeared in the latest master. Thank you.

**Comment by toonn** [comment]
Thanks for reporting, @holytrousers 👍. I'm gonna leave this open until next release because it keeps popping up, should be soon™.
