### ISSUE TITLE
Ranger crashes on tty

### ISSUE THREAD

**Issue by barslmn** [ranger/ranger#1172]
Hi,

###### Issue
Ranger crashes when run in tty with my user. However it works when run by root.

###### Info
Machine: Thinkpad X220
OS : Debian Stretch

###### Ranger Info
ranger-stable 1.7.1
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]

###### Traceback:
```
Locale: en_US.UTF-8
Current file: /home/bar/Backup
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
    self._print_result(self.result)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/titlebar.py", line 151, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/curses_shortcuts.py", line 57, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
    value = fnc(*args)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/colorscheme.py", line 66, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/lib/python2.7/dist-packages/ranger/gui/color.py", line 38, in get_color
    curses.init_pair(size, fg, bg)
error: init_pair() returned ERR

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

Thanks for your time.

**Comment by toonn** [comment]
Do you get anything more when you run ranger with the `--debug` flag?

**Comment by barslmn** [comment]
It returns the same error.

**Comment by toonn** [comment]
I still can't reproduce this, what is the value of TERM if you don't set it to `xterm-256color`? For me it's `linux`.
Could you maybe test with a more recent ranger version? Either clone the repo and run `repo/ranger.py` or install through pip or nix.

**Comment by coolGi2007** [comment]
Can confirm this happens. It only happens when ranger is trying to preview a text file.
It could probably be fixed by checking if ranger is running in a terminal that supports the full range of colors or not (or by adding a try catch around the preview and falling back to 256 colors) 
This crash only happens in older terminals like xterm and tty, but not in newer terminals like kitty.
