### ISSUE TITLE
Crash when entering samba mounts

### ISSUE THREAD

**Issue by eugeene** [ranger/ranger#1180]
#### Runtime Environment

- Operating system and version: Ubuntu 18.04
- Terminal emulator and version: mate-terminal 1.20.0
- Python version: 2.7.15rc1
- Ranger version/commit: ranger-master 1.9.1
- Locale: None.None

#### Current Behavior
Ranger crashes when entering cifs-mounted directory.

#### Expected Behavior
Ranger should not crash allowing me to enter the cifs-mounted directory.

#### Context

I'm trying to enter my cifs-mounted directory.

#### Steps to reproduce
1. mount samba network dir usin cifs
2. open ranger
3. cry

#### Traceback

```
ranger version: ranger-master 1.9.1
Python version: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
Locale: None.None
Current file: '/mnt/smb'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 104, in draw
    self._calc_bar()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 109, in _calc_bar
    self._get_left_part(bar)
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 186, in _get_left_part
    left.add(strftime(self.timeformat, localtime(stat.st_mtime)), 'mtime')
ValueError: year out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by dllud** [comment]
This seems to be a duplicate of #1020.
