### ISSUE TITLE
Crash when viewing .sh file

### ISSUE THREAD

**Issue by poserman** [ranger/ranger#1181]
#### Runtime Environment
- Operating system and version: 
Arch, up to date 
- Terminal emulator and version: 
xfce4-terminal
- Ranger version/commit: 
ranger version: ranger-master 1.9.1
- Python version:  
Python version: 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
- Locale: 
Locale: en_US.UTF-8
- Text editor
Vim, which works fine by itself. Ranger worked a few days ago too. 

#### Current Behavior
when scrolling around, when it finds a .sh file, it crashes 

#### Expected Behavior
displays the file
#### Context
view a file, or scroll past it

#### Steps to reproduce
1. select Vim as your default text editor
2. scroll past a .sh file
3. 

#### Traceback

```
The option named `display_free_space_in_status_bar' does not exist
The option named `hint_collapse_threshold' does not exist
ranger version: ranger-master 1.9.1
Python version: 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
Locale: en_US.UTF-8
Current file: '/home/robert/Downloads/pia-v75-installer-linux.sh'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

```

**Comment by poserman** [comment]
nevermind. it was a specific file that seemed to have corrupted itself. my bad.

**Comment by toonn** [comment]
Nonetheless, this shouldn't happen anymore on master or in the next release ; )

**Comment by poserman** [comment]
ok thank you for that. it's a nice filemanager
