### ISSUE TITLE
Ranger crashes if selecting (hjkl) a photorec.ses file (photorec session file)

### ISSUE THREAD

**Issue by amriamine** [ranger/ranger#1183]
#### Runtime Environment
- Operating system and version: linux 4.4.131 x86_64
- Terminal emulator and version: xfce4-terminal 0.8.7.4
- Python version: 3.6
- Locale: en_US
- Ranger version: ranger-master 1.9.1
#### Current Behavior
crash
#### Expected Behavior
Show the text of the file
#### Context
Just going through files i have
#### Possible Solutions
Some null char checking ?
#### Steps to reproduce
1. Move selection on file

#### Traceback
ranger version: ranger-master 1.9.1
Python version: 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
Locale: en_US.UTF-8
Current file: '/home/aminos/Downloads/photorec.ses'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

### File to reproduce with 
/dev/sda partition_gpt,9,blocksize,65536,fileopt,everything,disable,flv,enable,mkv,enable,mpg,enable,options,paranoid,keep_corrupted_file_no,mode_ext2,wholespace,search,status=ext2_on,1244432256,inter
1242171392-1242777599
1242852096-1242859519
1242950400-1242990591
1243065088-1243457535
1243471744-1953523711
- hex output of the file:
 23313530303331353234340a2f6465762f73646120706172746974696f6e
5f6770742c392c626c6f636b73697a652c36353533362c66696c656f7074
2c65766572797468696e672c64697361626c652c666c762c656e61626c65
2c6d6b762c656e61626c652c6d70672c656e61626c652c6f7074696f6e73
2c706172616e6f69642c6b6565705f636f727275707465645f66696c655f
6e6f2c6d6f64655f657874322c77686f6c6573706163652c736561726368
2c7374617475733d657874325f6f6e2c313234343433323235362c696e74
65720a313234323137313339322d313234323737373539390a3132343238
35323039362d313234323835393531390a313234323935303430302d3132
34323939303539310a313234333036353038382d31323433343537353335
0a313234333437313734342d313935333532333731310a00000000000000
000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
*...
000000000000000000000000000000000000000000000000000000000000

**Comment by toonn** [comment]
This should be fixed on master, coming in the next release. Thanks for the report, I'm closing this in favor of #1169, which'll be closed after next release. Feel free to reopen the issue if you manage to reproduce the failure on master.
