### ISSUE TITLE
ValueError: embedded null character still not fixed on ranger-master 1.9.1

### ISSUE THREAD

**Issue by adyouri** [ranger/ranger#1197]
The other [issues](https://github.com/ranger/ranger/issues?utf8=%E2%9C%93&q=embedded+null), seem to suggest that this was fixed in the `ranger-master 1.9.1` version (is that the latest one?), which I have, but it isn't fixed for me.

I just upgraded using `pacman`, which I assume has the latest version.

#### Context
Ranger crashes with a `ValueError: embedded null character` whenever I navigate trough certain files (jpg, png, mp4, mp3, odt, and some others).
Navigating through other files like `.txt`, `.py`, `.md`, `.zip`, `.pdf` `.json` and folders works fine though.

#### Runtime Environment
- Operating system and version: Manjaro Linux 17.1.10
- Terminal emulator and version: `termite v13`, also happens in `rxvt-unicode (urxvt) v9.22`

```
ranger version: ranger-master 1.9.1
Python version: 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
Locale: en_US.UTF-8
Current file: '/home/abd/Downloads/Telegram Desktop/2018-05-07-10-42-09-119.jpg'
```

#### Traceback

```
ranger version: ranger-master 1.9.1
Python version: 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
Locale: en_US.UTF-8
Current file: '/home/abd/Downloads/Telegram Desktop/2018-05-07-10-42-09-119.jpg'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character
```

Thank you for maintaining this great piece of software!

**Comment by toonn** [comment]
Ok, this *is* a little confusing. Ranger always reports its version as `ranger-master $VERSION`. This doesn't actually imply it is equivalent to the `HEAD` of the `master` branch.

Since you said you installed with pacMAN, not pacAUR, you just have the latest release, which is `1.9.1`. If you install `ranger-git` from the AUR (using pacaur for example), ranger'll still report its version as `ranger-master 1.9.1` but it'll actually be the most recent commit on `master`.

Not to worry though, release `1.9.2` will have the fix and is coming soon™.

**Comment by adyouri** [comment]
Thank you @toonn, `pacaur -S ranger-git` fixed this issue!

I thought the one I installed with `pacman` was the latest version.

**Comment by toonn** [comment]
Ah, was just confirmed that this was a slip-up in the last release. Normally releases report just `ranger $version`.
