### ISSUE TITLE
ValueError: embedded null character

### ISSUE THREAD

**Issue by chrissound** [ranger/ranger#1226]
Saw this error today: 

Hopefully this is enough information.

```
ranger version: ranger-master 1.9.1
Python version: 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
Locale: en_US.UTF-8
Current file: '/mnt/hdd3/stats%2Finstalls%2Finstalls_devarch.numberflash_201605_overview.csv'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

ranger crashed. Please report this traceback at:

```

**Comment by toonn** [comment]
This was probably fixed in #1091, I'm working on a new release that'll fix it for everyone.

**Comment by includereserved** [comment]
This crash also occurs for me, specifically in a Windows generated desktop.ini

**Comment by axper** [comment]
Same issue here. Just happened randomly out of nowhere.

**Comment by includereserved** [comment]
@axper not randomly, because the file you glossed over had a null character in it

**Comment by axper** [comment]
Yes, I can confirm, happens only on a specific file. Here it is.
[requirements.txt](https://github.com/ranger/ranger/files/2232300/requirements.txt)

**Comment by includereserved** [comment]
That file is encoded in UTF-16 which I think is overkill for what's in it

**Comment by rmassidda** [comment]
Same problem here on Arch with version 1.9.1 from the repo.
Instead with _v1.9.2-38-g16949531_ from the master branch it doesn't crash, but still doesn't show a correct preview of the null terminated file. 
In my case opening it with Vim prints `Octave-1-L^@`, while for Ranger it seems to be an empty file.

**Comment by toonn** [comment]
@rmassidda, the "fix" just bails out from previewing the file. However, it's possible installing `chardet` for the python that runs ranger can get it previewed if the encoding is not utf-8.

**Comment by rmassidda** [comment]
`chardet 3.0.4` is installed, but the preview is still blank. 
Running `chardetect octave-workspace`, where _octave-workspace_ is the faulty file, results in ascii with confidence 1.0, so the issue should not be relative to the encoding.

**Comment by toonn** [comment]
I'm labeling this as a feature request to display files with nulls using `^@`.
