### ISSUE TITLE
Ranger crash in Linuxmint 19

### ISSUE THREAD

**Issue by nowindows** [ranger/ranger#1242]
#### Runtime Environment

ranger-stable 1.8.1
python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]

Release Linux Mint 19 Tara 64-bit
Kernel Linux 4.15.0-29-generic x86_64
MATE 1.20.1

 Mate Terminal 1.20.0
Python 2.7.15rc1
ranger version: 1.8.1, executed with python 2.7.15rc1
Locale: en_US.UTF-8

#### Current Behavior
crashes on start

#### Expected Behavior
worked fine in Linuxmint 18.3

#### Context

Ranger is great for large (number of files) directory browsing

#### Steps to reproduce
Start ranger in Terminator or Mate Terminal 1.20.0 in Linuxmint 19 

#### Traceback

ranger version: 1.8.1, executed with python 2.7.15rc1
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 126, in main
    fm.initialize()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 110, in initialize
    self.tags = Tags(self.confpath('tagged'))
  File "/usr/lib/python2.7/dist-packages/ranger/container/tags.py", line 21, in __init__
    open(self._filename, 'w')
IOError: [Errno 13] Permission denied: '/home/joe/.config/ranger/tagged'

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

**Comment by nowindows** [comment]
Issue resolved. Had root owner of ..../.config/ranger directory.
