### ISSUE TITLE
When I select a pdf file, ranger crashed.

### ISSUE THREAD

**Issue by dogname** [ranger/ranger#1247]
#### Runtime Environment

- Operating system and version:  Arch Linux x86_64
- Terminal emulator and version: urxvt 9.22-7
- Python version: 3.7.0
- Ranger version/commit: 1.9.1-2
- Locale: en_US.UTF-8

#### Current Behavior
When I select a pdf file, ranger will crash, but not all pdf, only some will cause it,  I don't know the commonality of them
#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 100, in draw
    for line, i in zip(line_gen, range(self.hei)):
RuntimeError: generator raised StopIteration
```

**Comment by toonn** [comment]
Thanks for the report #1244 should've solved this. Could you try running the latest master? `ranger-git` in the AUR or simply clone the repo and run ranger.py with python 3.7.
