### ISSUE TITLE
Ranger Crashing after update

### ISSUE THREAD

**Issue by micrus** [ranger/ranger#1250]
#### Runtime Environment

- Operating system and version:  ArchLinux
- Terminal emulator and version:  U-rxvt
- Python version: 3.7.0
- Ranger version/commit: ranger-master 1.9.1
- Locale: 

#### Context

I have this error signal (with the ranger crash) every time I go over a coulple of file I have. I noticed that both of them are pdf file. First of the last update all was great.

#### Traceback

> 
> Current file: 'xxxxxx.pdf'
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 236, in _generate_lines
>     raise StopIteration
> StopIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
>     fm.loop()
>   File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
>     ui.redraw()
>   File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
>     self.draw()
>   File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
>     DisplayableContainer.draw(self)
>   File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
>     displayable.draw()
>   File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
>     DisplayableContainer.draw(self)
>   File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
>     displayable.draw()
>   File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
>     self._draw_file()
>   File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
>     Pager.draw(self)
>   File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 100, in draw
>     for line, i in zip(line_gen, range(self.hei)):
> RuntimeError: generator raised StopIteration
>

**Comment by alchemistbroth80** [comment]
same issue
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 236, in _generate_lines
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 100, in draw
    for line, i in zip(line_gen, range(self.hei)):
RuntimeError: generator raised StopIteration

**Comment by toonn** [comment]
This has been fixed on master in #1244. Either wait for a release or install ranger-git from the AUR or install the current master in another way.
