### ISSUE TITLE
Ranger crashes while opening a file named `index.html`

### ISSUE THREAD

**Issue by codeunik** [ranger/ranger#1254]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: urxvt
- Python version: 3.7.0
- Ranger version/commit: 1.9.1
- Locale: en_US.UTF-8

#### Context
Ranger crashes while opening a file named `index.html`.

#### Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 100, in draw
    for line, i in zip(line_gen, range(self.hei)):
RuntimeError: generator raised StopIteration
```

**Comment by mxovd** [comment]
This is already fixed in #1244 , you can clone the latest git

**Comment by toonn** [comment]
Yep, three possible "solutions", wait for a release, install the master version (ranger-git in the AUR) or downgrade python.

@mxovd thanks for keeping an eye on these issues.
Is there a way we can get arch users to actually search our issues before opening a new one? We like the initiative of reporting issues but this feels like chasing our tails. I'm gonna open up an issue with a clear title and keep it open, not sure what else we can do.

**Comment by kapsh** [comment]
@toonn hello! This issue affects mostly Arch users now because, you know, Arch is living in future. But for all who willingly wants to use 3.7 as default Python it renders ranger unusable. As one of them I would be glad to see officially released version with fix included. Thank you.

**Comment by Vifon** [comment]
We're working on it, @kapsh. Unfortunately our time is very limited, so merging all the pending patches and preparing a release in our free time takes at least a few weeks (we're on it!!). In the meantime you can run the `master` branch from Github by installing it manually. Thank you for your patience.

I'm closing it as it's already fixed on `master`.
