### ISSUE TITLE
Crash when scrolling through list of files

### ISSUE THREAD

**Issue by Anarcroth** [ranger/ranger#1262]
#### Runtime Environment
- Operating system and version: Arch Linux x86_64, 4.17.14-arch1-1-ARCH
- Terminal emulator and version: xterm-256color XTerm(333)
- Ranger version: ranger-master 1.9.1
- Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
- Locale: en_US.UTF-8

#### Current Behavior
While scrolling through a list of files with various sizes, then at random files, ranger crashes. Does the same thing on different types of files - `.webm`, `.png`, `.pdf`

#### Expected Behavior
Not to crash.

#### Context
Trying to scroll through my files.

#### Possible Solutions
Sorry, no idea :(

#### Steps to reproduce
1. Open ranger
2. Start scrolling through files
3. Crash

#### Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 236, in _generate_lines
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 100, in draw
    for line, i in zip(line_gen, range(self.hei)):
RuntimeError: generator raised StopIteration
```

**Comment by toonn** [comment]
Fixed in #1244. Wait for a release, run master (ranger-git in the AUR) or downgrade python.
