### ISSUE TITLE
ranger crashed while viewing a flated directory.

### ISSUE THREAD

**Issue by aranmohyeddin** [ranger/ranger#1274]
#### Runtime Environment
- Operating system and version: Linux 4.18.1-arch1-1-ARCH #1 SMP PREEMPT Wed Aug 15 21:11:55 UTC 2018 x86_64 GNU/Linux
- Terminal emulator and version: kitty 0.11.3 created by Kovid Goyal
- ranger version: ranger-master 1.9.1
- Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
- Locale: en_US.UTF-8

#### Context
I made my movies directory(there are some directories in it that include movies and subtitles and some movie files and some srt files without any container.) flat and then I just held j for going down for a few seconds and then this happened.

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.7/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character
```

**Comment by toonn** [comment]
This was fixed in #1091. The fix is coming in the next release. If you can't wait you can run `ranger-git` from the AUR.
There's another bug with running ranger with py3.7 which was fixed in #1244, that'll also be in the next release and already is available through `ranger-git`.
