### ISSUE TITLE
ranger crashes on particular pdf file 

### ISSUE THREAD

**Issue by DQuomsieh** [ranger/ranger#1282]
#### Runtime Environment

- Operating system and version: Manjaro 17.1 with i3wm 
- Terminal emulator and version: Bash 
- Python version: 3.7
- Ranger version/commit: 1.9.1 
- Locale: en_GB.UTF-8

#### Current Behavior
Crashes when going over a particular pdf file. Could it be because the contents of the pdf file are hand written? I have uploaded the file. 
[Heaps.pdf](https://github.com/ranger/ranger/files/2320476/Heaps.pdf)

#### Steps to reproduce
1.  Open ranger
2.  Go to directory with Heaps.pdf
3.  Hover over Heaps.pdf

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 236, in _generate_lines
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 100, in draw
    for line, i in zip(line_gen, range(self.hei)):
RuntimeError: generator raised StopIteration
```

**Comment by toonn** [comment]
This is because you're running python 3.7 and it was fixed in #1244.
Further discussion should go in #1255.
