### ISSUE TITLE
Ranger crashes on css editing after Manjaro 17.1.12 updating

### ISSUE THREAD

**Issue by roorco** [ranger/ranger#1286]
I update my system Manjaro to 17.1.12 release.
After that I started to have some issues on ranger.
It didn't recognize anymore my colorscheme and I had to regenerate my locale.
Now it is crashing everytime I try edit a css file or a scss file, even if I try to enter in a folder that contains css or scss files. I suppose the problem is about the preview.
Here you are the traceback, I hope can be useful, I use ranger a lot!
Thank you

#### Traceback

```
anger version: ranger-master 1.9.1
Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
Locale: it_IT.UTF-8
Current file: '/srv/http/MODRI/05.THEME/gridfolio/sass/custom.scss'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 236, in _generate_lines
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 100, in draw
    for line, i in zip(line_gen, range(self.hei)):
RuntimeError: generator raised StopIteration

```

**Comment by toonn** [comment]
cf. #1255
