### ISSUE TITLE
NameError: name 'Command' is not defined

### ISSUE THREAD

**Issue by jocap** [ranger/ranger#1328]
#### Runtime Environment

```
ranger version: ranger-master 1.9.1
Python version: 3.6.4 (default, Mar 27 2018, 09:58:38) [GCC 4.2.1 Compatible OpenBSD Clang 5.0.1 (tags/RELEASE_501/final)]
Locale: None.None
```
#### Current Behavior

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ranger/core/main.py", line 120, in main
    load_settings(fm, args.clean)
  File "/usr/local/lib/python3.6/site-packages/ranger/core/main.py", line 350, in load_settings
    import commands as commands_custom
  File "/home/john/.config/ranger/commands.py", line 3, in <module>
    class fzf_select(Command):
NameError: name 'Command' is not defined
```

#### Context

I've defined a new command in `commands.py` like this:

```python
class fzf_select(Command):
    def execute(self):
        # ...
```

... but ranger crashes on startup, producing the stack trace above.

Have I missed something?

**Comment by toonn** [comment]
Running `ranger --copy-config=commands` should help with this actually. It provides all the scaffolding you should need to write custom commands.
