### ISSUE TITLE
padding_right=false crash

### ISSUE THREAD

**Issue by 4nd3r** [ranger/ranger#133]
similar report by someone else in savannah:
https://savannah.nongnu.org/bugs/?42338

my configuration:

```
set column_ratios 1
set preview_files false
set preview_directories false
set collapse_preview true
```

i use ranger(s) with single column without previews and often in narrow tile meaning that every px is important :-) and when i set **padding_right=false** to use all available space...

```
ranger version: 1.6.1, executed with python 2.7.3
Locale: en_GB.UTF-8
Current file: None
Traceback (most recent call last):
  File "/opt/ranger/ranger/core/main.py", line 120, in main
    fm.initialize()
  File "/opt/ranger/ranger/core/fm.py", line 113, in initialize
    self.ui.initialize()
  File "/opt/ranger/ranger/gui/ui.py", line 88, in initialize
    self.update_size()
  File "/opt/ranger/ranger/gui/ui.py", line 281, in update_size
    self.browser.resize(self.settings.status_bar_on_top and 2 or 1, 0, y - 2, x)
  File "/opt/ranger/ranger/gui/widgets/browserview.py", line 296, in resize
    self.columns[i].resize(pad, left - 1, hei - pad * 2, 1)
  File "/opt/ranger/ranger/gui/widgets/browsercolumn.py", line 51, in resize
    Widget.resize(self, y, x, hei, wid)
  File "/opt/ranger/ranger/gui/displayable.py", line 156, in resize
    "(x = %d, y = %d)" % (self, x, y), bad=True)
  File "/opt/ranger/ranger/core/actions.py", line 125, in notify
    raise Exception(str(text))
Exception: Warning: Subwindow origin below zero for <BrowserColumn at level 1> (x = -1, y = 0)
```

using **draw_borders=true**  solves the issue,
but then i get ugly borders and still miss valuable space :-)

i poked around in related files and looks like there is somekind of miscalculation in resizing, but since i'm not really familiar with ranger codebase, i wasn't able to produce patch which wouldn't break other features:

```
diff --git a/ranger/gui/widgets/browserview.py b/ranger/gui/widgets/browserview.py
index 618d15a..638c036 100644
--- a/ranger/gui/widgets/browserview.py
+++ b/ranger/gui/widgets/browserview.py
@@ -293,7 +293,7 @@ class BrowserView(Widget, DisplayableContainer):
                 if not cut_off:
                     wid = int(self.wid - left + 1 - pad)
                 else:
-                    self.columns[i].resize(pad, left - 1, hei - pad * 2, 1)
+                    self.columns[i].resize(pad, left, hei - pad * 2, 1)
                     self.columns[i].visible = False
                     continue
```

maybe someone more experienced with ranger source can help me out?

**Comment by nfnty** [comment]
Fixed by 60ee8098c34c4f682e7cf47b60103b11bc0db5f0.
