### ISSUE TITLE
Crashes while opening Windows's Downloads directory

### ISSUE THREAD

**Issue by CUBERLEON** [ranger/ranger#1336]
#### Runtime Environment

- Operating system and version: Linux 4.18.12-arch1-1-ARCH
- Terminal emulator and version: konsole 18.08.2
- Python version: 3.7.0
- Ranger version/commit: ranger-master 1.9.1
- Locale: Locale: en_US.UTF-8

#### Steps to reproduce
1. Open Windows's Downloads directory.

#### Traceback

```
Current file: '/mnt/windows/Users/liu/Downloads/desktop.ini'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.7/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character
```

**Comment by toonn** [comment]
This was fixed in #1091, which is in 1.9.2. If you're running the ranger-git from the AUR all you have to do is update.
