### ISSUE TITLE
preview

### ISSUE THREAD

**Issue by morozik11** [ranger/ranger#1345]
ranger version: 1.7.1, executed with python 2.7.13
Locale: ru_RU.UTF-8
Current file: /home/stas/picture
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 362, in loop
    self.image_displayer.quit()
  File "/usr/lib/python2.7/dist-packages/ranger/ext/img_display.py", line 130, in quit
    self.process.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1253, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1243, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] Нет такого процесса

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

**Comment by toonn** [comment]
Could you try with ranger 1.9.2? It's hard to debug issues with such an old version of ranger.
