### ISSUE TITLE
Ranger crashes when opening image file with long file name (using feh)

### ISSUE THREAD

**Issue by cawleymillward** [ranger/ranger#1379]
#### Runtime Environment
Fedora 28 (4.18.17-200) - 64 bit
GNOME Terminal - 3.28.2 with VTE 0.52.2 +GNUTLS
Python 2.7.15
Ranger 1.9.2
Locale: en_GB.utf8

#### Current Behavior
When using 'open_with feh', Ranger crashes and the error below in the traceback section shows.

#### Expected Behavior
For Ranger to open feh with the image directed.

#### Context
Just trying to open and view the image.

#### Steps to reproduce
1.  Navigate to directory with long name.
2. Press 'R' (or any shortcut with 'open_with' bound), then type 'feh'.

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 400, in loop
    ui.handle_input()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 269, in handle_input
    self.handle_mouse()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 283, in click
    if displayable.click(event):
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_base.py", line 188, in click
    if DisplayableContainer.click(self, event):
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 283, in click
    if displayable.click(event):
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 101, in click
    self.fm.move(right=0)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 514, in move
    result = self.execute_file(selection, mode=mode)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 463, in execute_file
    return self.rifle.execute(filenames, mode, label, flags, None)
  File "/usr/lib/python3.6/site-packages/ranger/ext/rifle.py", line 435, in execute
    Popen_forked(cmd, env=self.hook_environment(os.environ))
  File "/usr/lib/python3.6/site-packages/ranger/ext/popen_forked.py", line 23, in Popen_forked
    subprocess.Popen(*args, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'
```

**Comment by Vifon** [comment]
Try using `set open_all_images false` in your rc.conf.

**Comment by cawleymillward** [comment]
Thank you so much! Can confirm this fixes the crash.

Setting `set open_all_images false` prevents ranger from crashing when opening lengthy file names.

**Comment by toonn** [comment]
@Vifon, this sounds pretty unfortunate. Is there a way we can automatically limit the expanded argument list in case we automatically expanded it in the first place?

I could imagine people wanting `open_all_images` even if some directories have too many image files.

**Comment by toonn** [comment]
Yes, that's what I was thinking too.

**Comment by dsh2** [comment]
I think, the issue is not closed, because the nature of an option is that the user chooses its value -- within reasonable limits which must be enforced by the optionee, i.e. ranger. 

Can you please open it again?
