### ISSUE TITLE
Open image as argv[1] on console

### ISSUE THREAD

**Issue by corbolais** [ranger/ranger#1382]
Hi,

Just came across the following crash while opening a long path image file. Might be related to #1379.

#### Runtime Environment
Running Debian Buster, konsole Version 18.04.0

#### Traceback

```
ranger by-date/run/slow/content/live/test/2018/11/seventeenbysix-eightone-230x200.jpg
ranger version: ranger 1.9.2
Python version: 3.6.7 (default, Oct 21 2018, 08:08:16) [GCC 8.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/titlebar.py", line 42, in draw
    self._calc_bar()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/titlebar.py", line 82, in _calc_bar
    self._get_left_part(bar)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/titlebar.py", line 106, in _get_left_part
    and (self.fm.thisdir.path.startswith(self.fm.home_path + "/")
AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by toonn** [comment]
Hmm, this is a regression.

**Comment by toonn** [comment]
Closing this in favor of a more general duplicate #1386.
