### ISSUE TITLE
`ranger/ranger.py <file>` crash

### ISSUE THREAD

**Issue by techtonik** [ranger/ranger#1386]
#### Runtime Environment
- Operating system and version:  Ubuntu 18.10

#### Context
Trying to troubleshoot https://github.com/ranger/ranger/issues/1385

#### Traceback

```
$ ranger/ranger.py ~/.config/neofetch/config.conf 
ranger version: ranger-master 1.9.2
Python version: 2.7.15+ (default, Oct  2 2018, 22:12:08) [GCC 8.2.0]
Locale: None.None

Traceback (most recent call last):
  File "/home/techtonik/p/ranger/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/home/techtonik/p/ranger/ranger/core/fm.py", line 398, in loop
    ui.redraw()
  File "/home/techtonik/p/ranger/ranger/gui/ui.py", line 342, in redraw
    self.finalize()
  File "/home/techtonik/p/ranger/ranger/gui/ui.py", line 397, in finalize
    DisplayableContainer.finalize(self)
  File "/home/techtonik/p/ranger/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/home/techtonik/p/ranger/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by techtonik** [comment]
MIght be a https://github.com/ranger/ranger/issues/930

**Comment by toonn** [comment]
No, #930 was a different problem.

**Comment by alexpalade** [comment]
I also have this problem. It works with "--selectfile", but the man page says it's superseded by the positional arguments. Environment: ranger 1.9.2, Python version: 3.7.1, Arch Linux, Linux 4.19.4.arch1-1.

**Comment by qoxxxx** [comment]
Adding my traceback since it looks different :
```
>>> /home/user/app/ranger/ranger.py /tmp/test.txt
ranger version: ranger-master 1.9.2
Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Locale: None.None

Traceback (most recent call last):
  File "/home/user/app/ranger/ranger/core/main.py", line 190, in main
    fm.loop()
  File "/home/user/app/ranger/ranger/core/fm.py", line 398, in loop
    ui.redraw()
  File "/home/user/app/ranger/ranger/gui/ui.py", line 341, in redraw
    self.draw()
  File "/home/user/app/ranger/ranger/gui/ui.py", line 368, in draw
    DisplayableContainer.draw(self)
  File "/home/user/app/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/user/app/ranger/ranger/gui/widgets/titlebar.py", line 42, in draw
    self._calc_bar()
  File "/home/user/app/ranger/ranger/gui/widgets/titlebar.py", line 82, in _calc_bar
    self._get_left_part(bar)
  File "/home/user/app/ranger/ranger/gui/widgets/titlebar.py", line 106, in _get_left_part
    and (self.fm.thisdir.path.startswith(self.fm.home_path + "/")
AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by hut** [comment]
Please check again with the newest version from git. The proper way to open files directly was with `rifle <filename>` rather than `ranger <filename>`, since rifle allows you to provide the flags and mode-numbers that you can also pass to ranger's `open_with` command, thereby giving more flexibility.

However, for people who simply want to open a file without choosing any options, I reactivated this feature, and now you can use `ranger <filename>` again.

Still, of course, the crash was a bug and it should've shown an error message instead.

**Comment by toonn** [comment]
@hut, please revert that change.
`rifle` already does a better job. `ranger /path/to/dir` is supposed to open a directory and `ranger /path/to/file` is supposed to open `/path/to` and highlight `file`.

**Comment by techtonik** [comment]
Maybe a `-o, --open` option that still allows to start ranger and open a file inside, so that when view exits, the user is left in ranger session?

**Comment by toonn** [comment]
Nope, we're reverting this. There's already a command for rifle if you want rifle behavior.

**Comment by techtonik** [comment]
@toonn can `rifle` leave me in ranger session after exit?

**Comment by toonn** [comment]
@techtonik, you misunderstand me. The behavior @hut summoned back from the grave is the behavior `rifle` has. The proper behavior for `ranger /path/to/file` is to open ranger in the directory `/path/to` and highlighting `file`.

**Comment by aouerfelli** [comment]
I can confirm that #1830 fixes this.
