### ISSUE TITLE
No image previews on tty (Linux terminal)

### ISSUE THREAD

**Issue by betovidal** [ranger/ranger#1391]
#### Runtime Environment

- Operating system and version: Debian 9.6 stretch
- Terminal emulator and version: tty (GNU coreutils) 8.26, st.
- Python version: 3.5.3
- Ranger version/commit: ranger-master 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior

Running $ranger --debug from tty1 throws an error with the message "Index out of range". Image previews are correctly displayed from st.

#### Expected Behavior

It should be able to display image previews. It shows them correctly on st, but not on tty1.

#### Context

Same as above.

#### Possible Solutions

To do a quick inspection, is it possible for me to add a print call somewhere and that'd be redirected to the log file?

Anyway, this is the line where ranger reports the error, so probably there's something not managed correctly by ranger on my side.

136             xpixels, ypixels = int(output[0]), int(output[1])

#### Steps to reproduce
1. Log in tty1
2. Run $ranger --debug
3. Try to see an image preview

Configuration looks like this:

set preview_images true
set show_hidden true
set draw_borders true

#### Traceback
08:12:36.964 INFO [ranger.core.main] ranger version: ranger-master 1.9.2
08:12:36.965 INFO [ranger.core.main] Python version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
08:12:36.965 INFO [ranger.core.main] Locale: en_US.UTF-8
08:12:36.965 INFO [ranger.core.main] Process ID: 6022
08:12:36.965 DEBU [ranger.core.main] cache dir: '/home/home_user/.cache/ranger'
08:12:36.965 DEBU [ranger.core.main] config dir: '/home/home_user/.config/ranger'
08:12:36.965 DEBU [ranger.core.main] data dir: '/home/home_user/.local/share/ranger'
08:12:36.971 DEBU [ranger.core.main] Unable to access plugin directory: /home/home_user/.config/ranger/plugins
08:12:36.971 DEBU [ranger.core.actions] Sourcing config file '/usr/local/lib/python3.5/dist-packages/ranger/config/rc.conf'
08:12:36.978 DEBU [ranger.core.actions] Sourcing config file '/home/home_user/.config/ranger/rc.conf'
08:12:39.546 CRIT [ranger.core.main] ranger version: ranger-master 1.9.2
Python version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
Locale: en_US.UTF-8
Current file: '/home/home_user/Pictures/bg.jpeg'

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/local/lib/python3.5/dist-packages/ranger/core/fm.py", line 402, in loop
    ui.draw_images()
  File "/usr/local/lib/python3.5/dist-packages/ranger/gui/ui.py", line 407, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/local/lib/python3.5/dist-packages/ranger/gui/widgets/pager.py", line 124, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/local/lib/python3.5/dist-packages/ranger/core/actions.py", line 172, in notify
    raise obj
  File "/usr/local/lib/python3.5/dist-packages/ranger/gui/widgets/pager.py", line 119, in draw_image
    self.wid, self.hei)
  File "/usr/local/lib/python3.5/dist-packages/ranger/ext/img_display.py", line 147, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
  File "/usr/local/lib/python3.5/dist-packages/ranger/ext/img_display.py", line 194, in _generate_w3m_input
    fontw, fonth = self._get_font_dimensions()
  File "/usr/local/lib/python3.5/dist-packages/ranger/ext/img_display.py", line 136, in _get_font_dimensions
    xpixels, ypixels = int(output[0]), int(output[1])
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by Vifon** [comment]
I can reproduce it.

**Comment by toonn** [comment]
In ranger code you can use `self.fm.notify` to get things in the log.

**Comment by betovidal** [comment]
Thanks @toonn, I'll keep that in mind.

Applying the changes described [here](https://lists.gnu.org/archive/html/ranger-users/2013-06/msg00003.html) I can see image previews on tty, with the only difference of the function call being like this:

`TTY = subprocess.check_output(['tty'], universal_newlines=True).rstrip('\n')`

because I kept getting the error "Expecting a byte instead of a str".

Font size for tty is usually 8x16, and the command "$stty size" reports the values 58 105 for me, so my tty has a size of 1024x768 pixels.

This value is hardcoded in the patch. I know a little of python and a lot less about how the kernel reports these values. So I don't see a reasonable solution other than the hardcoded values.

This solves my problem, but other people might find it hard to do so. I don't have experience making push requests, but if I find a solution for this, I'll try to share it.

**Comment by toonn** [comment]
Maybe you can figure out the resolution from somewhere in `/sys`, like on the [arch wiki here](
https://wiki.archlinux.org/index.php/Uvesafb#Checking_Current_Resolution). I'm not sure which path would be right though, if you have multiple displays for example.

As for pull requests it's rather simple, fork the ranger repo, make your changes on an branch then navigate to our PR tab and open a new one, comparing across forks.

**Comment by jumper149** [comment]
I had the same issue and fixed it with adding the user to the `video` group.
I guess ranger tries to draw directly to the framebuffer `/dev/fb0` but I have not checked the source code of ranger whether that is actually the case.

**Comment by toonn** [comment]
Well, ranger has nothing to do with the drawing really. It's w3mimgdisplay that's doing the drawing, I'm a little surprised it even works tbh.

**Comment by jumper149** [comment]
I agree, I got lucky there.
This usecase should be documented somewhere. Maybe like a little section for running ranger in tty.

**Comment by betovidal** [comment]
@jumper149 I haven't tried that, but by then I was already in the video group when I gave it a go.

With @toonn 's comment I can see that it was never really intended for ranger to do that, so maybe it should be left like that? I know I like to be able to display images from the Linux terminal and so does "niku" and Emanuel Guevel (both the authors of the email and the code respectively), but I'm not sure if this should go into the main repo since it's an unusual thing for someone to want these days. I would like to try and push a commit solving this problem, and with holidays coming soon I'll have more chances to do so.

**Comment by Vifon** [comment]
@betovidal I can confirm it *did* work a few years ago though. It might be a w3m-img regression and not ranger but it's just a guess right now. If you'd like to tackle it, you're more than welcome.

**Comment by zelmor** [comment]
Present in Debian Buster too (2018DEC29). Ranger does not display images in terminal emulator.

xfce4-terminal v0.8.7.4
ranger v1.9.2-4
python 3.7.2rc1

**Comment by toonn** [comment]
@zelmor, that's a different issue, this one's about the linux console, not X terminal emulators. The problem you're facing is because you're using a libVTE terminal, those generally don't work well with w3mimgdisplay, nothing we can do tbh. Ask the libVTE project to implement kitty's image protocol.

**Comment by zelmor** [comment]
@toonn it worked previously in Debian Stable using the same emulator, so I am not sure. What terminal emulator do you recommend using for ranger functionality?

**Comment by toonn** [comment]
@zelmor, either find out what version of xfce4-terminal and w3mimgdisplay work well together or use one of the terminals with native support like kitty, terminology or urxvt (this one's somewhat hackish).

Another more experimental alternative is to install ueberzug and use the similarly name previewing method (only available on master for now). It requires X, so definitely doesn't help with this issue about the linux console, but is a bit less of a hack than w3mimgdisplay.

**Comment by zelmor** [comment]
@toonn thanks for the response, I've since moved to `terminator` but that doesn't support the functionality either. Oh well, I'll just use the shotwell I guess. I just like to stick to terminal applications whenever possible.

**Comment by ulcuber** [comment]
For me solved by workaround:

- using `fbterm`
- compiling `w3m` with fbcon use flag (Gentoo, Portage): `www-client/w3m fbcon`

Also ranger should use `w3m`:

`set preview_images_method w3m`
