### ISSUE TITLE
--copy-config locale issue on Mac os X with iTerm2

### ISSUE THREAD

**Issue by toonn** [ranger/ranger#1415]
```
~> ranger --copy-config=rc
Traceback (most recent call last):
  File "/nix/store/dapv0ldc6pw0hsq3fdqfpc9aii6xwqq1-ranger-1.9.1/bin/.ranger-wrapped", line 36, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
  File "/nix/store/dapv0ldc6pw0hsq3fdqfpc9aii6xwqq1-ranger-1.9.1/lib/python3.6/site-packages/ranger/__init__.py", line 40, in <module>
    from ranger.core.main import main  # NOQA pylint: disable=wrong-import-position
  File "/nix/store/dapv0ldc6pw0hsq3fdqfpc9aii6xwqq1-ranger-1.9.1/lib/python3.6/site-packages/ranger/core/main.py", line 22, in <module>
    'Locale: {0}'.format('.'.join(str(s) for s in locale.getlocale())),
  File "/nix/store/zdw6v0s91x1d4r2pjj44vk8cz40m99kx-python3-3.6.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/nix/store/zdw6v0s91x1d4r2pjj44vk8cz40m99kx-python3-3.6.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by toonn** [comment]
Hmm, this issue seems specific to iterm2, tbh I have no idea what's going on, ranger always gives this error when trying to start it. Running `env LC_CTYPE=en_US.UTF-8 ranger` does work.

I'm closing this because it's probably locale issues specific to iterm2.
