### ISSUE TITLE
exception: argument list too long

### ISSUE THREAD

**Issue by castilma** [ranger/ranger#1488]
#### Runtime Environment

- Operating system and version:  nixos 18.03
- Terminal emulator and version: xfce4-terminal 0.6.3
- Python version:  2.7.14
- Ranger version/commit: 1.9.1
- Locale: de_DE.UTF-8

#### Current Behavior
ranger crashes.
#### Expected Behavior
ranger does not crash
#### Context

I just tried browsing through a folder with 46000 pictures.
#### Steps to reproduce
(I'm not sure, what i exactly did and can't reproduce right now)
1. create a folder with a lot of pictures
2. navigate ranger into it.
3. sort by size
4. try to look at the preview of the pictures.
5. ranger crashes

#### Traceback

```
ranger version: ranger-master 1.9.1
Python version: 2.7.14 (default, Sep 16 2017, 17:49:51) [GCC 7.3.0]
Locale: None.None
Current file: '/home/mcd/undel/magic/002C2FE31000-0.jpg'

Traceback (most recent call last):
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/core/fm.py", line 396, in loop
    ui.handle_input()
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/gui/ui.py", line 269, in handle_input
    self.handle_mouse()
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/gui/displayable.py", line 283, in click
    if displayable.click(event):
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/gui/widgets/view_base.py", line 142, in click
    if DisplayableContainer.click(self, event):
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/gui/displayable.py", line 283, in click
    if displayable.click(event):
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 95, in click
    self.fm.move(right=0)
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/core/actions.py", line 487, in move
    result = self.execute_file(selection, mode=mode)
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/core/actions.py", line 441, in execute_file
    return self.rifle.execute(filenames, mode, label, flags, None)
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/ext/rifle.py", line 376, in execute
    Popen_forked(cmd, env=self.hook_environment(os.environ))
  File "/nix/store/j78vb162q30b2y6vh6rfi5n7yjb8znla-ranger-1.9.1/lib/python2.7/site-packages/ranger/ext/popen_forked.py", line 23, in Popen_forked
    subprocess.Popen(*args, **kwargs)
  File "/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
```

**Comment by Vifon** [comment]
It's a known behavior, add `set open_all_images false` to your config to fix it.

**Comment by toonn** [comment]
Lol, this is terrible. Oh shell, you and your quirks.
Pretty annoying but I don't think there's anything we can do? Specific programs might support different ways of passing arguments but there's no general solution afaik?

**Comment by Vifon** [comment]
@toonn, in theory we could check the argument list length limit and turn off this option if we'd exceed it. Personally I don't think this corner case is worth the additional complexity. What we realistically could do is catch this exception and display a more meaningful error with the possible fix. I'll do that tomorrow.
