### ISSUE TITLE
Ranger crash after resizing a terminal window in multipane mode

### ISSUE THREAD

**Issue by nQ8hzkZw** [ranger/ranger#1513]
#### Steps to reproduce
1. Switch to multipane viewmode `~`.
2. Open 3 or 4 tabs ALT+2, ALT+3, ALT+4.
3. Resize (vertically and horizontally) terminal window to a smaller size.

#### Traceback

```
ranger version: ranger-master 1.9.2
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
Locale: en_US.UTF-8
Current file: '/media/ramdisk/ranger-master/doc'

Traceback (most recent call last):
  File "/media/ramdisk/ranger-master/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
_curses.error: addwstr() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/ramdisk/ranger-master/ranger/core/main.py", line 190, in main
    fm.loop()
  File "/media/ramdisk/ranger-master/ranger/core/fm.py", line 398, in loop
    ui.redraw()
  File "/media/ramdisk/ranger-master/ranger/gui/ui.py", line 341, in redraw
    self.draw()
  File "/media/ramdisk/ranger-master/ranger/gui/ui.py", line 368, in draw
    DisplayableContainer.draw(self)
  File "/media/ramdisk/ranger-master/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/media/ramdisk/ranger-master/ranger/gui/widgets/view_base.py", line 43, in draw
    DisplayableContainer.draw(self)
  File "/media/ramdisk/ranger-master/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/media/ramdisk/ranger-master/ranger/gui/widgets/browsercolumn.py", line 186, in draw
    self._draw_directory()
  File "/media/ramdisk/ranger-master/ranger/gui/widgets/browsercolumn.py", line 323, in _draw_directory
    self.execute_curses_batch(line, drawn.display_data[key])
  File "/media/ramdisk/ranger-master/ranger/gui/widgets/browsercolumn.py", line 122, in execute_curses_batch
    self.addstr(text, attr)
  File "/media/ramdisk/ranger-master/ranger/gui/curses_shortcuts.py", line 42, in addstr
    self.win.move(y, x)
_curses.error: wmove() returned ERR

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
This doesn't happen with the default viewmode? It looks like a curses bug.

**Comment by nQ8hzkZw** [comment]
In default viewmode it doesn't crash. 
Is there a way to workaround this bug? I already tried to wrap the problematic line into try/except, but it doesn't helped:
```python
try:
    self.win.move(y, x)
except curses.error:
    pass
```

**Comment by toonn** [comment]
I'd look at the code for `view_miller.py` if it doesn't crash with the default, it's possible it was fixed there and we forgot to fix the multipane view.

**Comment by nQ8hzkZw** [comment]
Somehow I managed to fix the crash problem.
The problem was that `self.container` wasn't cleared properly in `for` loop. `view_miller.py` has the same problem, but it does not cause a crash.
I also added some basic borders support to multipane view.
Here is my "fixed" `view_multipane.py`:

```python
# This file is part of ranger, the console file manager.
# License: GNU GPL version 3, see the file "AUTHORS" for details.

from __future__ import (absolute_import, division, print_function)

import curses
from ranger.gui.widgets.view_base import ViewBase
from ranger.gui.widgets.browsercolumn import BrowserColumn
from ..displayable import DisplayableContainer


class ViewMultipane(ViewBase):

    def __init__(self, win):
        ViewBase.__init__(self, win)

        self.fm.signal_bind('tab.layoutchange', self._layoutchange_handler)
        self.fm.signal_bind('tab.change', self._tabchange_handler)
        self.rebuild()
        
        self.old_draw_borders = self.settings.draw_borders

    def _layoutchange_handler(self):
        if self.fm.ui.browser == self:
            self.rebuild()

    def _tabchange_handler(self, signal):
        if self.fm.ui.browser == self:
            if signal.old:
                signal.old.need_redraw = True
            if signal.new:
                signal.new.need_redraw = True
            self.rebuild()

    def rebuild(self):
        self.columns = []
        self.container = []

        for name, tab in self.fm.tabs.items():
            column = BrowserColumn(self.win, 0, tab=tab)
            column.main_column = True
            column.display_infostring = True
            if name == self.fm.current_tab:
                self.main_column = column
            self.columns.append(column)
            self.add_child(column)
        self.resize(self.y, self.x, self.hei, self.wid)

    def resize(self, y, x, hei=None, wid=None):
        ViewBase.resize(self, y, x, hei, wid)
        column_width = int((wid - len(self.columns) + 1) / len(self.columns))
        left = 0
        top = 0
        for column in self.columns:
            column.resize(top, left, hei, max(1, column_width))
            left += column_width + 1
            column.need_redraw = True
        self.need_redraw = True

    def _draw_borders(self, border_types):
        win = self.win

        self.color('in_browser', 'border')
        for child in self.columns[:-1]:
            if 'separators' in border_types or 'outline' in border_types:
                try:
                    win.vline(0, child.x + child.wid, curses.ACS_VLINE, self.hei)
                except curses.error:
                    pass

    def draw(self):
        if self.need_clear:
            self.win.erase()
            self.need_redraw = True
            self.need_clear = False
        for tab in self.fm.tabs.values():
            directory = tab.thisdir
            if directory:
                directory.load_content_if_outdated()
                directory.use()
        DisplayableContainer.draw(self)
        if self.settings.draw_borders:
            draw_borders = self.settings.draw_borders.lower()
            if draw_borders in ['both', 'true']:
                border_types = ['separators', 'outline']
            else:
                border_types = [draw_borders]
            self._draw_borders(border_types)
        if self.draw_bookmarks:
            self._draw_bookmarks()
        elif self.draw_hints:
            self._draw_hints()
        elif self.draw_info:
            self._draw_info(self.draw_info)

    def poke(self):
        ViewBase.poke(self)

        if self.old_draw_borders != self.settings.draw_borders:
            self.resize(self.y, self.x, self.hei, self.wid)
            self.old_draw_borders = self.settings.draw_borders
```

**Comment by toonn** [comment]
If it doesn't cause the crash in `view_miller.py` how can it be the root of the problem? This needs further looking into.
