### ISSUE TITLE
High CPU usage when selecting a not accessible directory

### ISSUE THREAD

**Issue by nQ8hzkZw** [ranger/ranger#1537]
#### Runtime Environment

- Operating system and version: Linux Mint 19.1
- Terminal emulator and version: mate-terminal (1.20.0)
- Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
- Ranger version/commit: ranger-master 1.9.2
- Locale: en_US.utf8

#### Steps to reproduce
1. `$ ./ranger.py -c /tmp`.
2. Create a directory from another terminal `$ sudo mkdir /tmp/test` 
and make it not accessible `$ sudo chmod 700 /tmp/test/`.
3. Select the directory `test` in ranger.

#### Possible Solutions
The following workaround works fine for local filesystem, but doesn't work for remote `sshfs`.
../ranger/container/fsobject.py:
```diff
-from os import lstat, stat
+from os import lstat, stat, access, R_OK

-        self.accessible = True if new_stat else False
+        self.accessible = True if access(path, R_OK) else False
```

**Comment by vejkse** [comment]
I could reproduce it once with the latest commit (6d5e0d8d) and I got this repeated error with `W`/`:display_log`:
```
00:05:26 ERRO Notification: Loader work process failed: None (Percent: 0)
00:05:26 ERRO [Errno 13] Permission denied: '/tmp/test'
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/ranger/core/loader.py", line 445, in work
    next(item.load_generator)
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/container/directory.py", line 370, in load_bit_by_
    filelist = os.listdir(mypath)
PermissionError: [Errno 13] Permission denied: '/tmp/test'
```
But the steps to reproduce it seem brittle, there may be a crucial detail missing, all further attempts to reproduce it failed.

I found a more robust way of reproducing this error:
1. `ranger --clean /` (importantly, `preview_directories` is thus set to the default `true`).
2. Go to a directory for which you do not have read permission, e.g. `root` (without being root).  You will see the message `not accessible` on red background in place of the content of the directory.
3. `:set automatically_count_files false` (it is `true` by default) and reset with Ctrl-R or `:reset` and go back to that directory.  Now, an error message `Loader work process failed: None (Percent: 0)` appears and the “loading” sign `...` appears instead of the `not accessible` message.  ranger uses 100% CPU.  If I move to another directory, CPU usage falls back to normal.
4. I can make things worse with `:set update_title true`.  Now, when I’m on that directory in ranger, not only ranger uses 100% CPU but also my window manager (xmonad).

`W`/`:display_log` shows the same error as above repeated a huge number of times.

The fix above is still working (for local files), it just has to be updated:
```diff
-from os import lstat, stat
+from os import lstat, stat, access, R_OK

-        self.accessible = bool(new_stat)
+        self.accessible = access(path, R_OK)
```
