### ISSUE TITLE
ranger crashes right after install

### ISSUE THREAD

**Issue by cgnitash** [ranger/ranger#1552]
Hi,

I'm on Ubuntu 14.04. Just installed ranger using the following
```
git clone  https://github.com/ranger/ranger.git
cd ranger
sudo make install
```
First time I run ranger, I get this traceback
```
ranger version: ranger-master 1.9.2
Python version: 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
Locale: None.None

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 402, in load_settings
    load_custom_commands(system_comm_path, custom_comm_path)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 389, in load_custom_commands
    custom_comm_path)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 378, in import_file
    module = imp.load_source(name, path)
  File "/home/cgnitash/.config/ranger/commands.py", line 412, in <module>
    class setlocal(set_):
  File "/home/cgnitash/.config/ranger/commands.py", line 417, in setlocal
    PATH_RE = re.compile(r'^\s*path="?(.*?)"?\s*$')
NameError: name 're' is not defined

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
#1249 seems identical. Could you try my advice there?

**Comment by cgnitash** [comment]
Yes,the old version of commands.py was the issue. Thanks.
