### ISSUE TITLE
Crash on bulkrename with `[Errno 0] Error`

### ISSUE THREAD

**Issue by oschrenk** [ranger/ranger#1589]
#### Runtime Environment

- Operating system and version: 10.14.6 Beta (18G29g)
- Terminal emulator and version:  alacritty 0.33-rc1
- Python version: 2.7..10
- Ranger version/commit: 1.9.2
- Locale: None.None
-$EDITOR: nvim
-nvim: NVIM v0.4.0-2044-g16ee24082

#### Current Behavior
Crashes `bulkename` file `Users/oliver/Downloads/Category Theory/Category Theory 10.2 - Monoid in the category of endofunctors-GmgoPd7VQ9Q.mp4`

#### Expected Behavior
Not crask on `:bulkrename`

#### Context
Can't rename files in bulk

#### Possible Solutions
Use Finder to rename

#### Steps to reproduce
1. Have list of files
2. Use Visual Mode to select them
3. Open command mode using `:`
4. Type `bulkrename`
5. in vim buffer rename files
6. exit using `:wq`
7. Crash

#### Traceback
```
ranger version: ranger 1.9.2
Python version: 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
Locale: None.None
Current file: '/Users/oliver/Downloads/Category Theory/Category Theory 10.2 - Monoid in the category of endofunctors-GmgoPd7VQ9Q.mp4'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/fm.py", line 400, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 274, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/displayable.py", line 271, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/widgets/console.py", line 187, in press
    if not self.fm.ui.press(key):
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 224, in press
    quantifier=keybuffer.quantifier,
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/actions.py", line 272, in execute_console
    cmd.execute()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/config/commands.py", line 938, in execute
    "following code: `%s`" % (err, code), bad=True)
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/actions.py", line 176, in notify
    raise Exception(str(obj))
Exception: The error `[Errno 0] Error` was caused by evaluating the following code: `fm.ui.console.execute()`
```

**Comment by toonn** [comment]
Hmm, could you try regular vim? I'm not familiar enough with nvim to know its autosave behavior.

**Comment by oschrenk** [comment]
Hmpf. After doing the renaming by hand, and moving files around I can't even reproduce the original error. Will re-open issue once and if I run into this again. Sorry for the noise - but now I know to test it with both nvim and vim. Thanks for the input !

**Comment by toonn** [comment]
Oh, too bad. Would be weird if it was spurious. The test with vim is just the first in a journey to pinpoint the issue, since I haven't had issues, if we can narrow it down to "nvim throws an error we don't expect," that'd be progress : )

Thanks for the report any way, it's the only way we can improve ranger!
