### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by prosoitos** [ranger/ranger#1591]
First time I experience a crash from ranger. Please ignore if it is no big deal. I am not concerned by it since it usually doesn't happen. Only reporting it in case it is useful.

```sh
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
Locale: en_CA.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 339, in redraw
    self.finalize()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 394, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

OS: 5.1.9-arch1-1-ARCH

**Comment by prosoitos** [comment]
Never-mind, I found the problem: one tab was saved on closed, but its path doesn't exist anymore (renamed directory). Each time I tried to access that tab to delete it, ranger crashes.

The only way I found to get out of this though was to set `save_tabs_on_exit` to `false`, relaunch ranger, then change it back to true. And I consequently lost all my other tabs. It would have been much more convenient to be able to access the tab (with a message "path inaccessible" or something like that) to delete it. That's the behaviour I observe when I try to access the path of an unmounted device.

**Comment by toonn** [comment]
Thanks for the report, I'm working on something related in #1540.

You can find out the path to where ranger saves the tabs like this: `:eval fm.notify(fm.datapath('tabs'))`. If ranger keeps crashing because of your config you can run `ranger --clean` to run with the default config.
Once you know the path I think you can simply remove the path and probably a NUL character and it should remove the offending tab. Might be better to just change the offending path actually, so as not to mess with the structure of the file ranger expects.

**Comment by prosoitos** [comment]
Ah great. Thanks! Sorry I missed your issue on this. Thanks for the work on addressing this :slightly_smiling_face: 

Should I close this issue since #1540 is so closely related?

**Comment by prosoitos** [comment]
`:eval fm.notify(fm.datapath('tabs'))` gives $HOME/.local/share/ranger, which makes sense since I have bookmarks, history and tags there. But there is no tab file nor directory in there.

**Comment by prosoitos** [comment]
Oh, sorry, after changing `save_tabs_on_exit` to `false`, it appeared. I guess it was missing because of the crash.

**Comment by toonn** [comment]
Let's leave this open.

**Comment by prosoitos** [comment]
That tab file is missing most of the time, even when my tabs do get restored. There must be something weird in my settings. This is quite confusing.

**Comment by toonn** [comment]
It's possible that the file is removed whenever ranger's running. Also possible ranger's using a different path for some reason. The file is definitely removed if it didn't contain valid paths.
The `datadir` (where this gets saved) should always be `~/.local/share/ranger` *unless* `XDG_DATA_HOME` is an absolute path.

**Comment by prosoitos** [comment]
I found the problem with the missing file. Sorry for the noise on that last point.

**Comment by toonn** [comment]
It'd be great if you could state here what the problem/solution was, for posterity : )

**Comment by prosoitos** [comment]
Oh, I did not explain because it was 100% user error :stuck_out_tongue: 

I had 2 instances of ranger open and I had not realized it. With only one instance running, the file is there without problem.

**Comment by prosoitos** [comment]
Similar, though not exactly the same, crash report. Similar cause.

```sh
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
Locale: en_CA.UTF-8
Current file: '/media/googledrive'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_directory()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 325, in _draw_directory
    text = current_linemode.filetitle(drawn, metadata)
  File "/usr/lib/python3.7/site-packages/ranger/core/linemode.py", line 87, in filetitle
    fobj.get_permission_string(), fobj.user, fobj.group, fobj.relative_path)
  File "/usr/lib/python3.7/site-packages/ranger/container/fsobject.py", line 348, in get_permission_string
    mode = self.stat.st_mode
AttributeError: 'NoneType' object has no attribute 'st_mode'
```

**Comment by sgon00** [comment]
Hi, I met a similar problem today. With external drives are unmounted and tabs session saved those paths in tabs, ranger will crash when I switch to that tab. 

I currently workaround it by either mounting the external drives or `:tab_close <tab_num>` before switching to that tab.

When designing the fix to this problem, I recommend considering different scenarios/requirements. Different users may want to achieve different results. Thus, it's better open some kind of dialogs to ask what user wants to handle in such situation, there might be:

1. exit ranger and keep this session in the stack. Therefore, user can mount the external drive (fs) and run ranger again to use that session. 

2. close all unreachable tabs and keep reachable ones

3. remove the session from the stack and then open a clean ranger session

4. keep the session at the stack and open a clean ranger session

5. open the session and keep unreachable tabs. When the user navigates to an unreachable tab, ask what user want to do? close the tab? OR keep it and back to the previous tab?

Thanks.

**Comment by qrvd** [comment]
Related to **sgon00**'s report, Ranger generally crashes when we switch to a non-existent directory's tab.

Steps to reproduce:

1. Navigate to some directory `A`
2. Open a tab and navigate to another directory `B`
3. Delete directory `A`  from outside Ranger.
4. Switch tab back to the now-deleted `A` (for example by hitting shortcut `gt`).

Traceback on the latest `master` commit 6d5e0d8dc4cc5ddf53211e19f48c5b5e9ee47b18:

```
ranger version: ranger-master v1.9.3-853-g6d5e0d8d
Python version: 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/home/qrvd/bin/ranger.git/ranger/core/main.py", line 215, in main
    fm.loop()
  File "/home/qrvd/bin/ranger.git/ranger/core/fm.py", line 514, in loop
    ui.redraw()
  File "/home/qrvd/bin/ranger.git/ranger/gui/ui.py", line 340, in redraw
    self.draw()
  File "/home/qrvd/bin/ranger.git/ranger/gui/ui.py", line 367, in draw
    DisplayableContainer.draw(self)
  File "/home/qrvd/bin/ranger.git/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/home/qrvd/bin/ranger.git/ranger/gui/widgets/statusbar.py", line 110, in draw
    self._calc_bar()
  File "/home/qrvd/bin/ranger.git/ranger/gui/widgets/statusbar.py", line 116, in _calc_bar
    self._get_right_part(bar)
  File "/home/qrvd/bin/ranger.git/ranger/gui/widgets/statusbar.py", line 268, in _get_right_part
    if self.fm.thisdir.flat:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'flat'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by vejkse** [comment]
This last issue looks the same as https://github.com/ranger/ranger/issues/2993.

**Comment by qrvd** [comment]
Thanks for the link
