### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pointer'

### ISSUE THREAD

**Issue by kdheepak** [ranger/ranger#1600]
I'm getting the following error when I open ranger on an image file

```
$ ranger ~/Desktop/Screen\ Shot\ 2019-06-19\ at\ 3.38.29\ PM.png
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Mar 27 2019, 16:54:48) [Clang 4.0.1 (tags/RELEASE_401/final)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/Users/$USER/miniconda3/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/Users/$USER/miniconda3/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/Users/$USER/miniconda3/lib/python3.7/site-packages/ranger/gui/ui.py", line 339, in redraw
    self.finalize()
  File "/Users/$USER/miniconda3/lib/python3.7/site-packages/ranger/gui/ui.py", line 394, in finalize
    DisplayableContainer.finalize(self)
  File "/Users/$USER/miniconda3/lib/python3.7/site-packages/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/Users/$USER/miniconda3/lib/python3.7/site-packages/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

#### Runtime Environment

- Operating system and version: 
MacOS Sierra - 10.12.6
- Terminal emulator and version: 
iTerm2 - Build 3.3.0beta12
- Python version: 
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
- Ranger version/commit: 1.9.2

Any suggestions on what might be going on? This is my first time using ranger, so I might be missing something.

I've also updated the rc.conf file with the settings for iTerm2

```
set preview_images true
set preview_images_method iterm2
```

**Comment by kdheepak** [comment]
If I try to use ranger to open the folder, I get the broken image icon.

<img width="1680" alt="Screen Shot 2019-06-20 at 1 58 23 AM" src="https://user-images.githubusercontent.com/1813121/59831928-04b89700-9300-11e9-8338-acbafd8fa687.png">

**Comment by kdheepak** [comment]
This is possibly related to #864.

**Comment by kdheepak** [comment]
I see that my original error is related to #1386.

**Comment by kdheepak** [comment]
I should mention that I'm NOT using tmux. I've ran `ranger --copy-config=all` and then edited the `rc.conf` to use the iTerm2 method. `imgcat` is in my PATH variable and works in the terminal for this image without any issue.

**Comment by kdheepak** [comment]
I've also tried viewing images <42k and they still show the same broken image icon.

**Comment by kdheepak** [comment]
It turns out image previews don't work with Python3. But they work fine in Python2. I still get the same error in the parent post but since that is covered in another issue I will close this one.
