### ISSUE TITLE
Ranger crashes when loading a custom ranger configuration file 

### ISSUE THREAD

**Issue by ReneFroger** [ranger/ranger#1602]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: Terminator
- Python version: 2.7
- Ranger version/commit:  ranger-stable 1.8.1

Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0]

#### Current Behavior
```
ranger --confdir=/home/[username]/Dropbox/Dot/.config/ranger/rc.conf  
ranger version: 1.8.1, executed with python 2.7.15rc1
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 126, in main
    fm.initialize()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 110, in initialize
    self.tags = Tags(self.confpath('tagged'))
  File "/usr/lib/python2.7/dist-packages/ranger/container/tags.py", line 23, in __init__
    self.sync()
  File "/usr/lib/python2.7/dist-packages/ranger/container/tags.py", line 77, in sync
    f = open(self._filename, 'r')
IOError: [Errno 20] Not a directory: '/home/[username]/Dropbox/Dot/.config/ranger/rc.conf/tagged'

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

#### Expected Behavior
Ranger loads the configuration file.

#### Context
I would like to load my configuration file with my custom settings.

**Comment by toonn** [comment]
You're supposed to pass a directory. `--confdir=/home/[username]/Dropbox/Dot/.config/ranger` in your case.

Though I grant you a nicer error message would be welcome.

**Comment by ReneFroger** [comment]
Thanks for your clarification, it's appreciated.

**Comment by toonn** [comment]
I'm actually gonna keep this open as a reminder to fix the error message.
