### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by 717g301github** [ranger/ranger#1607]
ranger version: 1.8.1, executed with python 3.6.8G free  3/47  Top
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 362, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 295, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 322, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/statusbar.py", line 100, in draw
    self._calc_bar()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/statusbar.py", line 106, in _calc_bar
    self._get_right_part(bar)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/statusbar.py", line 245, in _get_right_part
    max_pos = len(target) - self.column.hei
  File "/usr/lib/python3.6/site-packages/ranger/container/directory.py", line 663, in __len__
    assert self.content_loaded
AssertionError

**Comment by toonn** [comment]
1.8.1 is quite old. Can you reproduce this with 1.9.2 or master?

**Comment by 717g301github** [comment]
I cannot find how to reproduce it.

**Comment by toonn** [comment]
Thank you : )
