### ISSUE TITLE
Crash report: I tried to delete a large folder on external drive

### ISSUE THREAD

**Issue by prosoitos** [ranger/ranger#1622]
I tried twice, it failed twice. Had to delete folder from terminal.

#### Runtime Environment

- Operating system and version: 5.1.16-arch1-1-ARCH
- Terminal emulator and version: Version : 9.22-9
- Python version: Version : 3.7.3-2
- Ranger version/commit: Version : 1.9.2-1
- Locale: LC_COLLATE=C

#### Traceback

```
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]
Locale: en_CA.UTF-8
Current file: '/media/usb1/audiobook/archive'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_directory()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 325, in _draw_directory
    text = current_linemode.filetitle(drawn, metadata)
  File "/usr/lib/python3.7/site-packages/ranger/core/linemode.py", line 87, in filetitle
    fobj.get_permission_string(), fobj.user, fobj.group, fobj.relative_path)
  File "/usr/lib/python3.7/site-packages/ranger/container/fsobject.py", line 348, in get_permission_string
    mode = self.stat.st_mode
AttributeError: 'NoneType' object has no attribute 'st_mode'
```

**Comment by prosoitos** [comment]
And another crash, this time trying to access an external drive:

```sh
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]
Locale: en_CA.UTF-8
Current file: '/media/usb2/bird_backup'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_directory()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 325, in _draw_directory
    text = current_linemode.filetitle(drawn, metadata)
  File "/usr/lib/python3.7/site-packages/ranger/core/linemode.py", line 87, in filetitle
    fobj.get_permission_string(), fobj.user, fobj.group, fobj.relative_path)
  File "/usr/lib/python3.7/site-packages/ranger/container/fsobject.py", line 348, in get_permission_string
    mode = self.stat.st_mode
AttributeError: 'NoneType' object has no attribute 'st_mode'
```

**Comment by toonn** [comment]
Might have to handle this too in #1540.

**Comment by prosoitos** [comment]
Another crash. Seems unrelated, but hard to tell. Happy to move it to a new issue:

```sh
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]
Locale: en_CA.UTF-8
Current file: '/home/marie/.restic/'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_directory()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 325, in _draw_directory
    text = current_linemode.filetitle(drawn, metadata)
  File "/usr/lib/python3.7/site-packages/ranger/core/linemode.py", line 87, in filetitle
    fobj.get_permission_string(), fobj.user, fobj.group, fobj.relative_path)
  File "/usr/lib/python3.7/site-packages/ranger/container/fsobject.py", line 348, in get_permission_string
    mode = self.stat.st_mode
AttributeError: 'NoneType' object has no attribute 'st_mode'
```

This time I cut and pasted files from one folder to another just after having changed their owner. I usually don't have issues with cut and paste, so I suspect it is the `chown` that did not get processed properly.

**Comment by prosoitos** [comment]
Another one, this time deleted one of these files. Something's up. All those crashes must be related.

```sh
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]
Locale: en_CA.UTF-8
Current file: '/home/marie/.restic/exclude_all.txt'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_directory()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/browsercolumn.py", line 325, in _draw_directory
    text = current_linemode.filetitle(drawn, metadata)
  File "/usr/lib/python3.7/site-packages/ranger/core/linemode.py", line 87, in filetitle
    fobj.get_permission_string(), fobj.user, fobj.group, fobj.relative_path)
  File "/usr/lib/python3.7/site-packages/ranger/container/fsobject.py", line 348, in get_permission_string
    mode = self.stat.st_mode
AttributeError: 'NoneType' object has no attribute 'st_mode'
```

**Comment by toonn** [comment]
Yep, ranger's handling of things related to `stat` isn't great. There's too much caching and not enough cache invalidation which leads to bad assumptions. Check the PR I linked for more details if you want.

**Comment by prosoitos** [comment]
Oh, sorry: only reading this now as I have been extremely busy lately.

I don't remember what I had done then, but something that I notice regularly is that running `chown` needs a restart for the change to be visible (running `linemode permissions` does not show the change) and when trying to access a folder that was not accessible before the `chown` command can lead to crashes (in contrast, running `chmod` works instantly without issue).

**Comment by antirais** [comment]
Also stumbled upon this bug. Bug seems to be triggered constantly when deleting big files, e.g ISO-s over ~2GB.

```python
ranger version: ranger 1.9.2
Python version: 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
Locale: en_US.UTF-8
Current file: '/home/user/isos/ubuntu_server_18.04.ova'

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_directory()
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/browsercolumn.py", line 325, in _draw_directory
    text = current_linemode.filetitle(drawn, metadata)
  File "/usr/lib/python3.8/site-packages/ranger/core/linemode.py", line 87, in filetitle
    fobj.get_permission_string(), fobj.user, fobj.group, fobj.relative_path)
  File "/usr/lib/python3.8/site-packages/ranger/container/fsobject.py", line 348, in get_permission_string
    mode = self.stat.st_mode
AttributeError: 'NoneType' object has no attribute 'st_mode'
```
