### ISSUE TITLE
vcs.py crashes when upstream branch in git repo is gone

### ISSUE THREAD

**Issue by Ablesius** [ranger/ranger#1644]
#### Runtime Environment

- Operating system and version: Arch Linux 5.2.1-arch1-1-ARCH
- Terminal emulator and version: termite v15
- Python version: 3.7.3
- Ranger version/commit: 1.9.2
- Locale: en_GB.UTF-8

#### Current Behavior
In a git repository on a branch where the upstream branch has gone (by rename of the remote branch), the vcs.py plugin crashes.

#### Expected Behavior
vcs plugin continues working, since upstream branch does not normally affect the output of the plugin in the UI.

#### Context
-

#### Possible Solutions
?

#### Steps to reproduce
1. dummy repo with upstream branch on github
2. rename the remote branch, update the git repo locally
3. view the directory in ranger, perhaps resetting with ^-r 

#### Traceback

not exactly a traceback, but as much as I can copy from the output with `W`:
```
 File "/usr/lib/python3.7/site-packages/ranger/ext/vcs/vcs.py", line 134, in _run
    raise VcsError('{0:s}: {1:s}'.format(str(cmd), path))
ranger.ext.vcs.vcs.VcsError: ['git', 'rev-list', '--left-right', 'refs/remotes/origin/cleanup/SHX-1799_TODO_LIST_REPROMPT...refs/heads/cleanup/SH-5112_TODO_LIST_REPROMPT']: /home/luyin/Documen
09:12:09 ERRO Notification: VCS Exception: View log for more info
09:12:09 ERRO ['git', 'rev-list', '--left-right', 'refs/remotes/origin/cleanup/SHX-1799_TODO_LIST_REPROMPT...refs/heads/cleanup/SH-5112_TODO_LIST_REPROMPT']: /home/luyin/Documents/Job/Freelanc
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/ext/vcs/vcs.py", line 125, in _run
    output = spawn.check_output(cmd, cwd=path, decode=not retbytes)
  File "/usr/lib/python3.7/site-packages/ranger/ext/spawn.py", line 41, in check_output
    raise error
subprocess.CalledProcessError: Command '['git', 'rev-list', '--left-right', 'refs/remotes/origin/cleanup/SHX-1799_TODO_LIST_REPROMPT...refs/heads/cleanup/SH-5112_TODO_LIST_REPROMPT']' returne

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/ext/vcs/vcs.py", line 250, in update_root
    self.obj.vcsremotestatus = self.data_status_remote()
  File "/usr/lib/python3.7/site-packages/ranger/ext/vcs/git.py", line 163, in data_status_remote
    output = self._run(['rev-list', '--left-right', '{0:s}...{1:s}'.format(remote, head)])
  File "/usr/lib/python3.7/site-packages/ranger/ext/vcs/vcs.py", line 134, in _run
    raise VcsError('{0:s}: {1:s}'.format(str(cmd), path))
ranger.ext.vcs.vcs.VcsError: ['git', 'rev-list', '--left-right', 'refs/remotes/origin/cleanup/SHX-1799_TODO_LIST_REPROMPT...refs/heads/cleanup/SH-5112_TODO_LIST_REPROMPT']: /home/luyin/Documen
```

**Comment by toonn** [comment]
I agree it shouldn't crash. You do lose info if you can't access the remote though.
