### ISSUE TITLE
No image preview

### ISSUE THREAD

**Issue by pvpscript** [ranger/ranger#1677]
#### Runtime Environment

- Operating system and version:  Debian 10 Buster
- Terminal emulator and version: lxterminal 0.3.2
- Python version: 3.7.3
- Ranger version/commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
When I navigate to an image or pdf it doesn't preview, it shows exiftool text instead. And if run with --debug flag it gives the error shown in the traceback section.

More info:
-> The same thing happens on st
-> w3m navigator doesn't show images. (apparently, this was relevant in another issue)

#### Traceback

```
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
Locale: en_US.UTF-8
Current file: '/home/p3t3r/metrics.png'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 398, in loop
    ui.draw_images()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 404, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 114, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 172, in notify
    raise obj
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 111, in draw_image
    self.wid, self.hei)
  File "/usr/lib/python3/dist-packages/ranger/ext/img_display.py", line 145, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
  File "/usr/lib/python3/dist-packages/ranger/ext/img_display.py", line 194, in _generate_w3m_input
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException

```

**Comment by pvpscript** [comment]
I un-commented the line in rc.conf that says `set preview_script ~/.config/ranger/scope.sh` and now, when I navigate to an image; pdf or video, it shows the following error:
`Loaded work process failed: Getting preview of ... (Percent: 0)`

If I run ranger with the `--debug` flag, it gives the following **traceback**:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/loader.py", line 411, in work
    next(item.load_generator)
  File "/usr/lib/python3/dist-packages/ranger/core/loader.py", line 230, in generate
    self.signal_emit('after', process=process, loader=self)
  File "/usr/lib/python3/dist-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 1111, in on_after
    text = self.read_text_file(path, 1024 * 32)
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 1179, in read_text_file
    return codecs.decode(data, guessed_encoding, 'replace')
TypeError: decode() argument 2 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 388, in loop
    loader.work()
  File "/usr/lib/python3/dist-packages/ranger/core/loader.py", line 420, in work
    exception=ex,
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 176, in notify
    raise Exception(str(obj))
Exception: Loader work process failed: Getting preview of /home/p3t3r/image.png (Percent: 0)
```

If I navigate to a *.deb; *.tar.gz; *.zip; etc... file, it gives the same error (Loaded work...) and only the first Traceback from above.

**Comment by toonn** [comment]
If you uncomment that you also have to `ranger --copy-config=scope` so there's a preview script at that location. Only do both of these things *if* you want to customize scope though, otherwise updates can become a manual process.

Let's start from 0. Do you have `preview_images` set to `true`, and `preview_images_method` set to `w3m`? Do you have a `w3mimgpreview` binary *somewhere* on your system? (Use find(1) to check if you don't know.) If you do, do image previews work in Xterm?

**Comment by pvpscript** [comment]
I previously did the ranger `--copy-config=scope` thing, so I have everything on `~/.config/ranger`.
I also do have `preview_images` set to true; my `preview_image_method` is set to `w3m` and I also have `w3mimgpreview`
xterm can display images without problem (to test it, I did w3m xkcd.org), but the same error happens when I run ranger on it.

**Comment by pvpscript** [comment]
Okay, actually it was my bad. I commented wrongly a part of the `scope.sh`. Now, the xterm is able to display the images, but `lxterminal` doesn't and if run with `--debug` flag, it prompts the traceback of the issue's start.

```
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
Locale: en_US.UTF-8
Current file: '/home/p3t3r/metrics.png'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 398, in loop
    ui.draw_images()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 404, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 114, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 172, in notify
    raise obj
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 111, in draw_image
    self.wid, self.hei)
  File "/usr/lib/python3/dist-packages/ranger/ext/img_display.py", line 145, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
  File "/usr/lib/python3/dist-packages/ranger/ext/img_display.py", line 194, in _generate_w3m_input
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException
```

**Comment by toonn** [comment]
Then this is probably because lxterminal doesn't emulate Xterm close enough for w3mimgpreview to work. I'm afraid there's nothing we can do about that. You'll probably have better luck with the `ueberzug` method that'll be in the next release.

**Comment by pvpscript** [comment]
That's too bad... I really hope `ueberzug` works on `lxterminal`
Thanks for the support.

**Comment by toonn** [comment]
Yes, ueberzug makes a different tradeoff. It relies on X. So no previews in a tty for example.
