### ISSUE TITLE
Search feature in ranger throwing an error

### ISSUE THREAD

**Issue by mentalityrl** [ranger/ranger#1720]
#1652 ## Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Current Behavior
Search function throws an error

#### Expected Behavior
Move to the searched file/dir

#### Steps to reproduce
1. Open Ranger
2. Press forward slash /
3. Type Something

#### Traceback

```
ranger version: ranger-master 
Python version: 3.7.4 (default, Oct  4 2019, 06:57:26) [GCC 9.2.0]
Locale: en_US.UTF-8
Current file: '/home/bryan/fusee-interfacee-tk'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 404, in loop
    ui.handle_input()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 279, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 209, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 271, in press
    focused_obj.press(key)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/console.py", line 217, in type_key
    self.on_line_change()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/console.py", line 510, in on_line_change
    if cmd and cmd.quick():
  File "/home/bryan/.config/ranger/commands.py", line 1211, in quick
    if self._count(move=asyoutype) == 1 and self.AUTO_OPEN in self.flags:
  File "/home/bryan/.config/ranger/commands.py", line 1276, in _count
    deq = deque(cwd.files)
NameError: name 'deque' is not defined

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by toonn** [comment]
Looks like you don't have a proper `commands.py`, it imports `deque` at the top. `ranger --copy-config=commands-full` should get you an example to work off of in your config dir.

**Comment by toonn** [comment]
Note that if you don't want to customize anything you're better off not having the config files at all.

**Comment by mentalityrl** [comment]
That fixed the issue. However:

```╭─bryan@Archie  ~ ‹node-›  ‹› (torrent-server-admin-dashboard*)
╰─$ ranger --copy-config=commands-full
Unknown config file `commands-full'
```
 Throws an error. --copy-config=commands works.

Bryan Jones

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by toonn** [comment]
Oh, sorry, `commands_full`.
