### ISSUE TITLE
Command not found: `ueberzug'

### ISSUE THREAD

**Issue by GutsyHeart** [ranger/ranger#1745]
#### Runtime Environment

- Operating system and version: Artix Linux x86_64
- Terminal emulator and version: st 0.8.2
- Python version: 3.7.4
- Ranger version/commit: ranger-master
- Locale: ru_RU.UTF-8

#### Current Behavior
The image preview works, but after closing the ranger the error is:
Exception: Command not found: `ueberzug'

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 470, in load_settings
    fm.source(custom_conf)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 407, in source
    self.execute_console(line)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 238, in execute_console
    self.notify("Command not found: `%s'" % command_name, bad=True)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 176, in notify
    raise Exception(str(obj))
Exception: Command not found: `ueberzug'




Name            : python-ueberzug
Version         : 18.1.4-1
Description     : ueberzug is an python script which aims to replace w3mimgdisplay
Architecture    : any
URL             : https://github.com/seebye/ueberzug
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libxext  python-pillow  python  python-xlib  python-docopt  python-psutil  python-attrs
Optional Deps   : None
Required By     : None
Optional For    : ranger-git
Conflicts With  : python-ueberzug-git

Name            : ranger-git
Version         : 1.9.2.378.g9614b6cf-1
Description     : A simple, vim-like file manager.
Architecture    : any
URL             : https://ranger.github.io/
Licenses        : GPL
Groups          : None
Provides        : ranger
Depends On      : python
Optional Deps   : atool: for previews of archives
                  file: for determining file types [installed]
                  highlight: for syntax highlighting of code
                  libcaca: for ASCII-art image previews [installed]
                  mediainfo: for viewing information about media files [installed]
                  perl-image-exiftool: for viewing information about media files
                  poppler: for pdf previews [installed]
                  python-bidi: for bidi algorithm support
                  python-chardet: in case of encoding detection problems [installed]
                  python-ueberzug: w3mimgdisplay alternative [installed]
                  sudo: to use the "run as root"-feature [installed]
                  transmission-cli: for viewing bittorrent information
                  w3m: for previews of images and html pages
Required By     : None
Optional For    : None


```

**Comment by toonn** [comment]
Hmm, can you call ueberzug on the command line?

**Comment by GutsyHeart** [comment]
```
➜  ~ ueberzug
Usage:
    ueberzug MODULE [options]
➜  ~
➜  ~
➜  ~
➜  ~ ranger --debug
ranger version: ranger-master
Python version: 3.7.4 (default, Oct  4 2019, 17:26:22) [GCC 9.2.0]
Locale: ru_RU.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 470, in load_settings
    fm.source(custom_conf)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 407, in source
    self.execute_console(line)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 238, in execute_console
    self.notify("Command not found: `%s'" % command_name, bad=True)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 176, in notify
    raise Exception(str(obj))
Exception: Command not found: `ueberzug'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by chu4ng** [comment]
Can you show `PATH` and `which ueberzug`?

**Comment by hut** [comment]
Hi @GutsyHeart, do you still have this problem?
