### ISSUE TITLE
errs out on uncapitalize rename

### ISSUE THREAD

**Issue by zachvalenta** [ranger/ranger#1768]
Runtime Environment

ranger version: ranger 1.9.2
Python version: 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
Locale: None.None

Current Behavior

Errs out when trying to rename file from capitalized to uncapitalized e.g. from `Frisell.mp3` to `frisell.mp3`

```sh
/V/m/r/b/d/2002-joyful-noise $ ranger --debug
ranger version: ranger 1.9.2
Python version: 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
Locale: None.None
Current file: '/Volumes/music-usb/rock/blues/derek-trucks/2002-joyful-noise/Frisell.mp3'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/fm.py", line 400, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 274, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/displayable.py", line 271, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/widgets/console.py", line 187, in press
    if not self.fm.ui.press(key):
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 224, in press
    quantifier=keybuffer.quantifier,
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/actions.py", line 272, in execute_console
    cmd.execute()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/config/commands.py", line 938, in execute
    "following code: `%s`" % (err, code), bad=True)
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/actions.py", line 176, in notify
    raise Exception(str(obj))
Exception: The error `Can't rename: file already exists!` was caused by evaluating the following code: `fm.ui.console.execute()`
```

**Comment by toonn** [comment]
You're probably trying a rename on a case-insensitive file system.

**Comment by zachvalenta** [comment]
Gotcha. I was confused because I was able to rename w/ `mv` but not with `ranger`.

**Comment by toonn** [comment]
I'm still gonna call this a bug actually. Renaming a file might overwrite another. So why not itself?
