### ISSUE TITLE
Ranger crashes in kde konsole with ueberzug preview option

### ISSUE THREAD

**Issue by verga** [ranger/ranger#1806]
#### Runtime Environment

- Operating system and version: OpenSuse Tumbleweed
- Terminal emulator and version: konsole 19.12.0
- Python version: (python3) Python 3.7.3
- Ranger version/commit: ranger 1.9.3
- Locale: 

#### Current Behavior
ranger crashes at startup
#### Expected Behavior
preview in konsole with ueberzug option
#### Context

Ranger works if the preview option ``set preview_images_method ueberzug`` is commented in ``rc.conf``

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException
```

**Comment by toonn** [comment]
I can't reproduce this. Does it happen if you don't have ueberzug on the `PATH`?

**Comment by verga** [comment]
ueberzug is on the path; at least it can be invoked on the shell; I think
indeed it might be a path problem
Is there some environmental variable I can define?
I installed ueberzug with pip, but most of python packages and x11
libraries using opensuse repository (there is no official opensuse package
for ueberzug)

Le ven. 10 janv. 2020 à 20:32, Toon Nolten <notifications@github.com> a
écrit :

**Comment by toonn** [comment]
@verga, can you reproduce the problem if ueberzug is *not* on the PATH? So keep the settings you have but redefine PATH: `env PATH=/bin:/usr/bin ranger` (some things may have to be available, like `file` and `less` and `vim`).

**Comment by verga** [comment]
In my system ueberzug is under /usr/bin; therefore changing the path keeping /usr/bin does not change things; uninstalling ueberzug gives however the same error. Perhaps ``ranger`` is not finding ``ueberzug`` under ``/usr/bin``

**Comment by toonn** [comment]
No, this means your ranger isn't finding the `UeberzugImageDisplayer` class in the registry. Which is bizarre. Could you try running from a fresh checkout of master? No need to install. Just run `./ranger.py --clean` from the repo.

**Comment by verga** [comment]
I cloned the master repository and run ``./ranger.py --clean``, it crashes with the error:

```
Traceback (most recent call last):
  File "./ranger.py", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/home/verga/Downloads/ranger/ranger/core/main.py", line 32, in main
    from ranger.container.settings import Settings
  File "/home/verga/Downloads/ranger/ranger/container/settings.py", line 13, in <module>
    from ranger.gui.colorscheme import _colorscheme_name_to_class
  File "/home/verga/Downloads/ranger/ranger/gui/colorscheme.py", line 30, in <module>
    from curses import color_pair
ImportError: No module named curses
```
``ncurses`` and ``python3-ncurses`` are well installend in my system; e.g. ``import curses`` works in ipython console.

**Comment by verga** [comment]
Using explicitly python3 with the command
```
python3 ranger.py --clean
```
from the master repository works.

I also modified rc.conf to run with the ``ueberzug`` preview option, and got the same error as in the 1.9.3 version

**Comment by toonn** [comment]
Can you check that this file `/usr/lib/python3.7/site-packages/ranger/ext/img_display.py` has an ueberzug class decorated with the `"ueberzug"` key?

**Comment by verga** [comment]
I've found these lines in ``img_display.py"

```
@register_image_displayer("ueberzug")
class UeberzugImageDisplayer(ImageDisplayer):
...
```

in ``/usr/lib/python3.7/site-packages/ranger/ext``

**Comment by toonn** [comment]
Very curious. Could you run this: `eval from ranger.ext.img_display import IMAGE_DISPLAYER_REGISTRY as IDR; self.fm.notify(IDR)`

Then check what it looks like using the log `W`.

**Comment by verga** [comment]
Hello,

This gives the dictionary: ``{..., 'ueberzug': <class ' ranger.ext.img_display.UeberzugImageDisplayer'>}``

I found something new! 
If I ``set preview_images_method ueberzug`` inside ``ranger`` everything works fine!
Then, I removed the old rc.conf , and recreate it using ``ranger --copy-config=rc``, and modified the preview option. Now the preview works (even if I do not understand why...)

Thank you very much for your work!

**Comment by toonn** [comment]
That's bizarre. `ranger --clean` should've ignored your personal config too.

**Comment by lyjdwh** [comment]
you need to set `set preview_images_method ueberzug` other `set preview_images_method ueberzug #w3m`

**Comment by lyjdwh** [comment]
you need to `set preview_images_method ueberzug` other than `set preview_images_method ueberzug #w3m`

**Comment by toonn** [comment]
Ah, @verga, might you have done this too, comment out the default `#w3m`? Ranger probably looks for `ueberzug #w3m` in the registry if you do that.
