### ISSUE TITLE
Crash when trying to open file from command line

### ISSUE THREAD

**Issue by cdutsov** [ranger/ranger#1832]
#### Runtime Environment

Arch Linux
ranger package: aur/ranger-git 1.9.2.333.gfcb01c2c-1
ranger version: ranger-master
Python version: 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
Locale: en_US.UTF-8

#### Current Behavior
Crash with error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 344, in redraw
    self.finalize()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 399, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'
```
This happens when trying to open a file from command line like:
$ ranger /home/user/file.jpg
If I try to open a folder from command line, it works perfectly.
I have tried to disable image previews but the problem persists.
#### Possible Solutions
The `main_column` object in view_base.py seems to be always `None`. 

If I can provide more info, please ask.

**Comment by toonn** [comment]
This is a known issue, closing in favor of #1386.
