### ISSUE TITLE
ranger crashes after python update

### ISSUE THREAD

**Issue by pallatinus** [ranger/ranger#1846]
ranger version: ranger 1.9.3
Python version: 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/usr/lib/python3.8/site-packages/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/usr/lib/python3.8/site-packages/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException

**Comment by toonn** [comment]
Hmm, this'd usually happen if you're trying to set a non-existent previewing method.

**Comment by pallatinus** [comment]
> Hmm, this'd usually happen if you're trying to set a non-existent previewing method.
> 
> We _should_ make the exception a little clearer, maybe include the key that was tried.

Ranger was crashing at launch and this problem occurred after I've updated Python today. 
Interestingly, I've comment out 'set preview_images_method w3m' and it came back to work. But then I uncomment it and ranger is still working.
This is quite odd.

**Comment by toonn** [comment]
Oh, forgot to reopen this. If multiple people are running into it we should definitely find out what's happening.
