### ISSUE TITLE
resizing/moving windows in small containers crashes ranger when two or more ranger-tabs are open

### ISSUE THREAD

**Issue by salkin-mada** [ranger/ranger#1888]
related to #1610 and #1513 I believe.

#### Runtime Environment
- Operating system and version: Debian 10 (buster)
- Compositor: Wayland
- Window Manager: Sway
- Terminal emulator: kitty v0.15.1
- Python version: 3.7.3
- Ranger version: 1.9.2
- Ranger Viewmode: Multipane
- Locale: en_GB.UTF-8

#### Context
To have a lot of stuff going on in one workspace and several things in one container. And using mod+f (fullscreen) to jump into a workable size of chosen window when needed. 

#### Steps to reproduce
1. open three sway windows with one instance of kitty per container/view (mod+enter) - (two "above" divided vertically and one long horizontal "below"), and run ranger in the upper left corner container/sway window
2. in the kitty window with ranger running create 3 additional (or more) terminal windows inside this container (ctrl+shift+enter)
3. open one more tab in ranger and navigate to a long-ish path (/blabla/Desktop/something/more/stuff/yes/and/here) in both tabs
4. in the sway window/container where ranger and the 3 additional kitty windows are located try to re-arrange(move) the terminals around using ctrl+shift+l - this crashes ranger in my setup

(sorry for the possible confusing usage of container/window/view, hope i makes sense)

#### Traceback

```
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
Locale: en_GB.UTF-8
Current file: '/home/salkin/Downloads/ofxCv-master.zip'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
_curses.error: addwstr() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_base.py", line 43, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_directory()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 321, in _draw_directory
    self.execute_curses_batch(line, drawn.display_data[key])
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 121, in execute_curses_batch
    self.addstr(text, attr)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 42, in addstr
    self.win.move(y, x)
_curses.error: wmove() returned ERR
```

```
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
Locale: en_GB.UTF-8
Current file: '/home/salkin/Desktop/DOT_DRAW'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
_curses.error: addwstr() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_base.py", line 43, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_directory()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 321, in _draw_directory
    self.execute_curses
_batch(line, drawn.display_data[key])
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 121, in execute_curses_batch
    self.addstr(text, attr)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 42, in addstr
    self.win.move(y, x)
_curses.error: wmove() returned ERR
```

**Comment by salkin-mada** [comment]
If this is an exact copy of #1513 I can close this issue and post findings in the comments of #1513. Let me know.
