### ISSUE TITLE
Crash with man page ?+[m]

### ISSUE THREAD

**Issue by aicsx** [ranger/ranger#1892]
#### Runtime Environment

- Operating system and version: KISS linux - rolling
- Terminal emulator and version: st 0.8.2
- Python version: 3.8.2
- Ranger version/commit: ranger-master 1.9.3
- Locale:  it_IT.UTF-8

#### Context
it's crash at command: ?+m for view man page

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3.8/site-packages/ranger/config/commands.py", line 1257, in callback
    self.fm.display_help()
  File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 1006, in display_help
    if process.poll() == 16:
AttributeError: 'NoneType' object has no attribute 'poll'
```

**Comment by toonn** [comment]
Is this repeatable? Does it happen in other terminals, does it happen in other locales, does it happen with a different python version?

**Comment by toonn** [comment]
I can't reproduce it. Does `man ranger` work fine for you?

**Comment by aicsx** [comment]
i build mandoc and now ranger work without problem. a warning would have been more useful than a crash, but the important thing is to have solved it. It means that in mandoc dependencies it is necessary. Can you close it's . Thank you! Good job.
