### ISSUE TITLE
ranger startup problems

### ISSUE THREAD

**Issue by WDF-VIORuleZ** [ranger/ranger#1893]
#### Runtime Environment

- Operating system and version: 4.19.111-1-MANJARO x86_64 GNU/Linux
- Terminal emulator and version: termite v15
- Python version: 3.8.2
- Ranger version/commit: ranger-master
- Locale: en_US.UTF-8

#### Current Behavior
After launching ranger inside the terminal emulator the execution stops with the appearance of the following crash report

#### Expecteda Behavior
not crashing i guess?

#### Steps to reproduce
1.  Launch ranger from the terminal

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 173, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.8/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'
```

**Comment by toonn** [comment]
Hmm, this should be fixed [on master](https://github.com/ranger/ranger/pull/1852), are you actually running the master branch?

**Comment by fatmyxtap** [comment]
Hi everyone, I have a similar problem.

**Comment by toonn** [comment]
Try running master, this has been fixed.
