### ISSUE TITLE
Ranger Crashes on Startup with "No directory given"

### ISSUE THREAD

**Issue by Mikee-3000** [ranger/ranger#1896]
Hi, 

Out of the sudden (everything worked fine 20 minutes ago) I'm getting the following error:
```
ranger version: ranger-master
Python version: 3.8.2 (default, Feb 26 2020, 22:21:03) [GCC 9.2.1 20200130]
Locale: en_IE.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 173, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.8/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.8/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.8/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
I'm on Manjaro Linux. 
Using a different terminal doesn't help.
Please let me know if this is enough or if you need me to do any testing.

#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by Mikee-3000** [comment]
ranger works after removing all contents from `~/.local/share/ranger/bookmarks` . Stupidly, I didn't backup the file before deleting so I can't tell what bookmark was the issue.

**Comment by toonn** [comment]
Could it be you had a bookmark (maybe by accident?) to a directory you removed?

**Comment by Mikee-3000** [comment]
I think that's what happen - in which case apologies for opening a silly issue.

**Comment by toonn** [comment]
Np, I think reporting which bookmarks couldn't be loaded is better than crashing.

**Comment by tyn1998** [comment]
> ranger works after removing all contents from `~/.local/share/ranger/bookmarks` . Stupidly, I didn't backup the file before deleting so I can't tell what bookmark was the issue.

I just met the same problem. Reinstalling ranger or rebooting system didn't fix that, but removing all this directory solved the problem. Thank you~

**Comment by qrvd** [comment]
In my case, I had bookmarked a directory, and then deleted it and created a file with the same name as that directory. That caused the assertion to fail `assert not os.path.isfile(path), "No directory given!"` and crash Ranger (because it expects every existing bookmark to be a directory not a file)

**Comment by pmaoui** [comment]
I've also been trapped and had to find  answer here. 
Having ranger just to ignore deleted files and silently remove them from the config instead of crashing would be a nice idea :)

**Comment by toonn** [comment]
Yep, this issue is still open because we need to fix it. I don't want to silently remove bookmarks though. You might have bookmarks on an external disk or a network drive that isn't always connected. Just logging that they're being ignored is the right solution IMO.

**Comment by goetzc** [comment]
I just got the same issue and can reproduce the crash.

```
$ ranger
ranger version: ranger 1.9.3
Python version: 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.10/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

In this case, it's a `'` bookmark for a file (not directory) that does exist. The specific case is that I had a directory which later was removed and became the name for a file (same path). If I remove or edit this specific bookmark in `~/.local/share/ranger/bookmarks`, ranger opens fine.

The issue looks to be that ranger expects any bookmark to be a directory and if instead it finds a file, it crashes at startup: https://github.com/ranger/ranger/blob/391f061cb0b0cfa8266c0651f2a6d948f22e01dd/ranger/container/directory.py#L149-L150

**Comment by Yehoslav** [comment]
> 
> In this case, it's a `'` bookmark for a file (not directory) that does exist. The specific case is that I had a directory which later was removed and became the name for a file (same path). If I remove or edit this specific bookmark in `~/.local/share/ranger/bookmarks`, ranger opens fine.
> 
> The issue looks to be that ranger expects any bookmark to be a directory and if instead it finds
>  a file, it crashes at startup:
> 
> https://github.com/ranger/ranger/blob/391f061cb0b0cfa8266c0651f2a6d948f22e01dd/ranger/container/directory.py#L149-L150

The same exact thing happened to me, I bookmarked a folder by accident and then removed it and created a file with the same name. After that ranger was crashing.

I think it would be helpful to at least print the path that caused the error, to be able to easier remove it manually from the bookmarks.

**Comment by Rhinoforces** [comment]
> ranger works after removing all contents from `~/.local/share/ranger/bookmarks` . Stupidly, I didn't backup the file before deleting so I can't tell what bookmark was the issue.

I had the same issue so I looked in my bookmarks and realized that I have changed my wpa_supplicant to a wifi, so ranger was looking for that wpa_supplicant bookmark. That was the only one in there so I just deleted it. Works like a charm!

**Comment by CaptainAsbestos** [comment]
In my case, I found a possible explanation. The bookmarks I had left were in drives which I had unmounted, and that was why ranger was crashing.
