### ISSUE TITLE
ranger crashed

### ISSUE THREAD

**Issue by Augists** [ranger/ranger#1898]
#### Runtime Environment

- Operating system and version: macOS Catalina 10.15.3
- Terminal emulator and version: Terminal 2.10
- Python version: 2.7.16(Default)
- Ranger version/commit: 1.9.3
- Locale: None.None

#### Current Behavior

I selected some files and used  'dT'  to trash. Then I got this message below.

```
Current file: '/Users/xxx/Desktop/Screen Shot 2020-04-03 at 10.02.37 AM.png'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

#### Expected Behavior

Put them into the trash

#### Possible Solutions

I don't know if it is possible to select some and try to delete or trash them together. Sorry to bother u.

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
Current file: '/Users/xxx/Desktop/Screen Shot 2020-04-03 at 10.02.37 AM.png'



Traceback (most recent call last):

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 201, in main

    fm.loop()

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 383, in loop

    ui.handle_input()

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 266, in handle_input

    self.handle_key(key)

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 196, in handle_key

    elif not DisplayableContainer.press(self, key):

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/displayable.py", line 275, in press

    focused_obj.press(key)

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 188, in press

    self.type_key(key)

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 214, in type_key

    self._answer_question(answer)

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 197, in _answer_question

    callback(answer)

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/config/commands.py", line 759, in _question_callback

    self.fm.execute_file(files, label='trash')

  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/actions.py", line 459, in execute_file

    filenames = [f.path for f in files]

AttributeError: 'str' object has no attribute 'path'



ranger crashed. Please report this traceback at:

https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
This should be fixed on master.

**Comment by ZZZZone** [comment]
same issue

**Comment by toonn** [comment]
@ZZZZone, on the master branch?

**Comment by toonn** [comment]
Tracking this in #1798
