### ISSUE TITLE
ranger crash when argument is a pdf

### ISSUE THREAD

**Issue by jtrakk** [ranger/ranger#1905]
I accidentally ran `ranger my.pdf` and ranger crashed. It says to report it so I'm reporting it. 

```
ranger version: ranger 1.9.3
Python version: 3.7.6 (default, Dec 18 2019, 19:23:55) [GCC 9.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/nix/store/ikvxspq9aq9igxf17d7n7qyvqrq1qgnz-ranger-1.9.3/lib/python3.7/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/nix/store/ikvxspq9aq9igxf17d7n7qyvqrq1qgnz-ranger-1.9.3/lib/python3.7/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/nix/store/ikvxspq9aq9igxf17d7n7qyvqrq1qgnz-ranger-1.9.3/lib/python3.7/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/nix/store/ikvxspq9aq9igxf17d7n7qyvqrq1qgnz-ranger-1.9.3/lib/python3.7/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/nix/store/ikvxspq9aq9igxf17d7n7qyvqrq1qgnz-ranger-1.9.3/lib/python3.7/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/nix/store/ikvxspq9aq9igxf17d7n7qyvqrq1qgnz-ranger-1.9.3/lib/python3.7/site-packages/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'

```

**Comment by toonn** [comment]
Whoops, I think this is a known issue that didn't get fixed. It probably happens with any file you pass.
