### ISSUE TITLE
infinite recourse on copying folder into sub-folder

### ISSUE THREAD

**Issue by sadid** [ranger/ranger#1925]
#### Runtime Environment
```
ranger version: ranger 1.9.3
Python version: 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]
Locale: en_US.UTF-8

```
- Operating system and version:  Archlinux (5.4.32-1-lts)
- Terminal emulator and version: urxvt
- Python version: 3.8.2

#### Current Behavior
1. Create folder/sub-folder `parent/child`
2. Copy parent and paste it into child

The result will be infinite nested sub-folders `parent/child/parent/child/parent/child/...`

#### Expected Behavior
just like cp it should create one level of nest aka `parent/child/parent/child` in the folder structure.

#### Possible Solutions

1. Using standard `cp` (at least in Linux/Mac) might be helpful. However, I'm not aware of special decision on using implement copy mechanism
2. ranger --debug crash (while ranger don't). It can be detected at least.

#### Steps to reproduce
1. Create folder/sub-folder `parent/child`
2. Copy parent and paste it into child

#### Extra Note

Trash-Cli also remove the file but trash-empty will give error as:
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

However, `rm -rf` can fix the problem.

#### Trackback
This happens only on `ranger --debug` and not regular renger:
```
ranger version: ranger 1.9.3
Python version: 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/loader.py", line 423, in work
    next(item.load_generator)
  File "/usr/lib/python3.8/site-packages/ranger/core/loader.py", line 127, in generate
    for n in shutil_g.copytree(
  File "/usr/lib/python3.8/site-packages/ranger/ext/shutil_generatorized.py", line 242, in copytree
    raise Error(errors)
shutil.Error: [('/home/sadid/Desktop/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child', '/home/sadid/Desktop/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child', "[Errno 36] File name too long: '/home/sadid/Desktop/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child/parent/child'")]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 371, in loop
    loader.work()
  File "/usr/lib/python3.8/site-packages/ranger/core/loader.py", line 428, in work
    self.fm.notify(
  File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 177, in notify
    raise Exception(str(obj))
Exception: Loader work process failed: copying: /home/sadid/Desktop/parent (0) (Percent: 0)

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by qrvd** [comment]
I have a patch that resolves this, we needed to avoid recursively copying the destination directory after creating it.
