### ISSUE TITLE
Improving error report

### ISSUE THREAD

**Issue by tom-i** [ranger/ranger#1943]
#### Runtime Environment

- Operating system and version: Armbian 9.14
- Terminal emulator and version: 
- Python version: 2.7.13
- Ranger version/commit: 1.7.1
- Locale: en_US.UTF-8

#### Current Behavior
Monty want's to improve error report. 
I had an issue with missing `file` package in my armbian system, it was impossible to know, how to solve the problem without external help.
#### Expected Behavior
Error report should be more informative.
#### Steps to reproduce
1. remove `file` package
2. select some files
3. `:bulkrename`
`[Errno 2] No such file or directory` message appears
#### Traceback

```
nashome@espressobin:~$ ranger --debug
ranger version: 1.7.1, executed with python 2.7.13
Locale: en_US.UTF-8
Current file: /home/nashome/deluge-1.3.15.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 344, in loop
    ui.handle_input()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 145, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 261, in press
    focused_obj.press(key)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/console.py", line 172, in press
    if not self.fm.ui.press(key):
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 162, in press
    quantifier=keybuffer.quantifier)
  File "/usr/lib/python2.7/dist-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib/python2.7/dist-packages/ranger/config/commands.py", line 720, in execute
    p(err)
  File "/usr/lib/python2.7/dist-packages/ranger/config/commands.py", line 713, in execute
    result = eval(code)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/console.py", line 365, in execute
    self.fm.execute_console(self.line)
  File "/usr/lib/python2.7/dist-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib/python2.7/dist-packages/ranger/config/commands.py", line 841, in execute
    self.fm.execute_file([File(listpath)], app='editor')
  File "/usr/lib/python2.7/dist-packages/ranger/core/actions.py", line 348, in execute_file
    return self.rifle.execute(filenames, mode, label, flags, None)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/rifle.py", line 311, in execute
    for count, cmd, lbl, flgs in self.list_commands(files, mimetype):
  File "/usr/lib/python2.7/dist-packages/ranger/ext/rifle.py", line 283, in list_commands
    if not self._eval_condition(test, files, None):
  File "/usr/lib/python2.7/dist-packages/ranger/ext/rifle.py", line 185, in _eval_condition
    return self._eval_condition2(condition, files, label)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/rifle.py", line 211, in _eval_condition2
    return bool(re.search(argument, self._get_mimetype(files[0])))
  File "/usr/lib/python2.7/dist-packages/ranger/ext/rifle.py", line 253, in _get_mimetype
    stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by vejkse** [comment]
This issue can be closed: it has been fixed by #2001 (not yet released).
