### ISSUE TITLE
Ranger crashes when trashing multiple marked files

### ISSUE THREAD

**Issue by Isti115** [ranger/ranger#1951]
#### Runtime Environment

- Operating system and version: Arch Linux (updated around 2020. 05. 01.)
- Terminal emulator and version: termite v15
- Python version: 3.8.2
- Ranger version/commit: 1.9.3
- Locale: EN-US

#### Current Behavior
Ranger crashed.

#### Expected Behavior
Move the marked files to the trash directory.

#### Context

I  have marked multiple files in a directory one by one using Space, then tried to move them to the  trash using d T Enter y

#### Steps to reproduce
1. Mark files in a directory
2. Press d T Enter y

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]
Locale: en_US.UTF-8
Current file: '/home/isti/Documents/University/msc-diplomamunka/code/Test.agda'

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3.8/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
  File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Isti115** [comment]
Sorry, I didn't look around enough, this is definitely a duplicate of #1798.

**Comment by toonn** [comment]
Closing as duplicate, thanks for the report! : )
