### ISSUE TITLE
Crash in Fedora 32, Xterm

### ISSUE THREAD

**Issue by Dmitryi** [ranger/ranger#1965]
Operating system and version: Fedora 32 x86_64
Terminal emulator and version: xterm
ranger version: ranger 1.9.2
Python version: 3.8.2 (default, Feb 28 2020, 00:00:00) [GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)]
Locale: ru_RU.UTF-8
Current file: '/home/f32/.xsession-errors'

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 400, in loop
    ui.handle_input()
  File "/home/f32/.config/ranger/plugins/multiple_keyboard.py", line 99, in handle_input
    tkeys = key_translate(keys)
  File "/home/f32/.config/ranger/plugins/multiple_keyboard.py", line 69, in key_translate
    ch = b''.join([bytes.fromhex('{0:X}'.format(i)) for i in keys]).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 4: unexpected end of data

**Comment by toonn** [comment]
That's a problem with the "multiple_keyboard" plugin, report the issue on their tracker.
