### ISSUE TITLE
Ranger won't launch

### ISSUE THREAD

**Issue by mtwb47** [ranger/ranger#2007]
Receiving the following error when launching Ranger. 

```
ranger version: ranger 1.9.3
Python version: 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.8/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.8/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.8/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
This started happening without any updates to the system. It worked one time and then it did this the next time. 
OS: Arcolinux
Linux Kernel : 5.7.4
zsh 4.8
bash 5.0.17

**Comment by mtwb47** [comment]
launching ranger with -c will allow it to launch. Don't know what that means though. I'm assuming something in rc.conf is what is causing this? 

--I'm going to go change it so the icons don't show up, I'm betting that's the issue. font awesome is always screwing things up

**Comment by mtwb47** [comment]
Okay, even getting rid of the ranger config files and having ranger rebuild them with the defaults won't let ranger load without the -c flag. So it wasn't the icon or anything I added to the config.

**Comment by toonn** [comment]
Looks like you have a non-existing dir bookmarked. Could be the `` ` `` bookmark for the last-visited directory. Probably easiest to remove the bookmarks file which should be in `${XDG_DATA_HOME}/ranger/bookmarks`.

**Comment by mtwb47** [comment]
Yup that worked. I'm guessing this is less a bug, and more my fingers hit a key somewhere along the line without me knowing it.

**Comment by toonn** [comment]
It's possible but we should just warn about the invalid bookmarks rather than crash.

**Comment by hulmakerik** [comment]
I have exactly this issue too. The problem started after running the polybar. ranger -c works

**Comment by hulmakerik** [comment]
I have exactly this issue too. The problem started after running the polybar. ranger -c works. Problem remains even after disabling polybar at the start.

**Comment by lkblkb** [comment]
Can confirm. I often connect to a shared drive on a local network and if I'm away from the network, ranger will not launch.

**Comment by qrvd** [comment]
I was able to reproduce this by setting a bookmark, exiting ranger, and replacing the bookmarked directory with an empty file of the same name (this case is probably analogous to that of crashing due to broken symlinks/nonexistent paths).

I've come up with a preliminary fix for this, give it a try and see if it solves the problem for you: tree https://github.com/qrvd/ranger/tree/bookmarks-issue-2007 / commit https://github.com/qrvd/ranger/commit/705ef2b3f51520a93ae90b1290f0e187f30b1239

Beware, this is a work in progress, so although I think it's safe, backup your Ranger bookmarks before you run this.

I'm still uncertain whether this is the best way to implement the fix since the `Bookmarks` class is a bit counterintuitive. Would appreciate any advice on changes

**Comment by hut** [comment]
Looks like a duplicate of https://github.com/ranger/ranger/issues/1896 . Closing for now. If I'm mistaken, please let me know and I'll reopen.
