### ISSUE TITLE
Ranger won't launch, but error slightly different from the one two days ago

### ISSUE THREAD

**Issue by samuelj123** [ranger/ranger#2012]
```
ranger version: ranger 1.9.3
Python version: 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
Locale: en_IN.ISO8859-1

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3/dist-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
This happened after I upgraded ubuntu to 20.04. 
I removed the book-marks file, purged and re-installed ranger as well...

**Comment by toonn** [comment]
I believe this is the same issue: #1805.
This has since been fixed on master and will be in the next release, hopefully soon™.
It's a little unfortunate, I think the simplest fix is to install screen : /
