### ISSUE TITLE
ranger crashed while trying to trash a file under macos

### ISSUE THREAD

**Issue by galanakis** [ranger/ranger#2050]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. Pick a file
2. press d
3. Trash

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 2.7.16 (default, Jul  5 2020, 02:24:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.21) (-macos10.15-objc-
Locale: None.None
Current file: '/Users/galanakis/temp/verticales'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Hmm, could you test the master branch? This might've been fixed.

**Comment by schaschko** [comment]
> Hmm, could you test the master branch? This might've been fixed.

I can confirm this bug. Tried with the most recent clone from master branch (s. below traceback) and also with the version I installed via apt on ubuntu 20.04. Problem only occurs with :trash, not with :delete. I have trash-cli installed.

> ranger version: ranger-master v1.9.3-99-g240d8a0e
> Python version: 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
> Locale: en_US.UTF-8
> Current file: '/home/fl/projekte/ext/test123'
> 
> Traceback (most recent call last):
>   File "/home/fl/projekte/ext/ranger/ranger/config/commands.py", line 993, in execute
>     result = eval(code)  # pylint: disable=eval-used
>   File "<string>", line 1, in <module>
>   File "/home/fl/projekte/ext/ranger/ranger/gui/widgets/console.py", line 456, in execute
>     self.fm.execute_console(self.line)
>   File "/home/fl/projekte/ext/ranger/ranger/core/actions.py", line 269, in execute_console
>     cmd.execute()
>   File "/home/fl/projekte/ext/ranger/ranger/config/commands.py", line 753, in execute
>     self.fm.execute_file(files, label='trash')
>   File "/home/fl/projekte/ext/ranger/ranger/core/actions.py", line 430, in execute_file
>     filenames = [f.path for f in files]
>   File "/home/fl/projekte/ext/ranger/ranger/core/actions.py", line 430, in <listcomp>
>     filenames = [f.path for f in files]
> AttributeError: 'str' object has no attribute 'path'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/fl/projekte/ext/ranger/ranger/core/main.py", line 203, in main
>     fm.loop()
>   File "/home/fl/projekte/ext/ranger/ranger/core/fm.py", line 382, in loop
>     ui.handle_input()
>   File "/home/fl/projekte/ext/ranger/ranger/gui/ui.py", line 276, in handle_input
>     self.handle_key(key)
>   File "/home/fl/projekte/ext/ranger/ranger/gui/ui.py", line 206, in handle_key
>     elif not DisplayableContainer.press(self, key):
>   File "/home/fl/projekte/ext/ranger/ranger/gui/displayable.py", line 272, in press
>     focused_obj.press(key)
>   File "/home/fl/projekte/ext/ranger/ranger/gui/widgets/console.py", line 188, in press
>     if not self.fm.ui.press(key):
>   File "/home/fl/projekte/ext/ranger/ranger/gui/ui.py", line 221, in press
>     self.fm.execute_console(
>   File "/home/fl/projekte/ext/ranger/ranger/core/actions.py", line 269, in execute_console
>     cmd.execute()
>   File "/home/fl/projekte/ext/ranger/ranger/config/commands.py", line 1000, in execute
>     fm.notify("The error `%s` was caused by evaluating the "
>   File "/home/fl/projekte/ext/ranger/ranger/core/actions.py", line 175, in notify
>     raise Exception(str(obj))
> Exception: The error `'str' object has no attribute 'path'` was caused by evaluating the following code: `fm.ui.console.execute()`
> 
> ranger crashed. Please report this traceback at:
> https://github.com/ranger/ranger/issues

**Comment by camxcube** [comment]
I have the same issue.

## Runtime Environment

Operating system and version:  macOS Catalina 10.15.6 (19G73) 
Terminal emulator and version: iTerm 2 (3.3.12)
Python version: 2.7.16 (default, Jul  5 2020, 02:24:03)
Ranger version/commit: 1.9.3 (installed from brew)
Locale: None. None

## Current Behavior

Ranger crashed after trying to trash some files. 

## Expected Behavior

Should be ok to send marked files to trash bin.

## Context

Under normal status.

## Possible Solutions

Nil

## Steps to reproduce

1.  Pick at least one file and mark it.
2. Press 'dT' > 'Enter' to try to trash the file.
3. Ranger crashed


```
ranger version: ranger 1.9.3
Python version: 2.7.16 (default, Jul  5 2020, 02:24:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.21) (-macos10.15-objc-
Locale: None.None
Current file: '/Users/Cam/.emacs.d/.gitignore'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by camxcube** [comment]
#1898

This issue may has connection to this.

**Comment by toonn** [comment]
Closing in favor of #1798
