### ISSUE TITLE
Master branch makes fzf_select custom command complain

### ISSUE THREAD

**Issue by kevinhwang91** [ranger/ranger#2071]
#### Runtime Environment

- Operating system and version: ArchLinux
- Terminal emulator and version: alacritty 0.5.0
- Python version: 3.8.5
- Ranger version/commit: ranger-master
- Locale:  en_US.UTF-8

#### Current Behavior
fzf_select can change directory but complain `'NoneType' object is not subscriptable`.

#### Expected Behavior
change directory and be silent.

#### Context

It works as expected for 1.9.3 version.

#### Steps to reproduce
1. run fzf_select command in ranger git root directory;
2. select `build/lib`;
3. change the directory to `build/lib`, but notify `'NoneType' object is not subscriptable`;

#### Traceback

```
Message Log:
21:48:19 INFO ranger version: ranger-master
21:48:19 INFO Python version: 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]
21:48:19 INFO Locale: en_US.UTF-8
21:48:19 INFO Process ID: 73182
21:48:25 ERRO Notification: 'NoneType' object is not subscriptable
21:48:25 ERRO 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/actions.py", line 269, in execute_console
    cmd.execute()
  File "/home/kevin/.config/ranger/plugins/fzf_find.py", line 31, in execute
    self.fm.cd(fzf_file)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/actions.py", line 600, in cd
    self.enter_dir(path, remember=remember)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/actions.py", line 585, in enter_dir
    result = self.thistab.enter_dir(path, history=history)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by toonn** [comment]
Oh, good bug report. Could you try this patch?
```
diff --git a/ranger/core/tab.py b/ranger/core/tab.py
index 64edf120..1771ffa2 100644
--- a/ranger/core/tab.py
+++ b/ranger/core/tab.py
@@ -69,7 +69,10 @@ class Tab(FileManagerAware, SettingsAware):  # pylint: disable=too-many-instance
 
     def _set_pointer(self, value):
         self._pointer = value
-        self._pointed_obj = self.thisdir.files[self._pointer]
+        try:
+            self._pointed_obj = self.thisdir.files[self._pointer]
+        except TypeError:
+            pass
 
     pointer = property(_get_pointer, _set_pointer)

```

**Comment by toonn** [comment]
Actually, I opened a PR.

**Comment by kevinhwang91** [comment]
Using the patch, the complaint is gone. If you merge it into master, close this issue by the way, thanks.
