### ISSUE TITLE
Ranger crashed

### ISSUE THREAD

**Issue by wk30** [ranger/ranger#2073]
#### Runtime Environment

- Operating system and version: MacOS 10.15.6
- Terminal emulator and version: iTerm2 Build 3.3.10beta4
- Python version: 2.7.17 (python -V)
- Ranger version/commit: 1.9.3
- Locale: 
LANG=""
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

#### Current Behavior
Just use ranger .
#### Expected Behavior
open the current directory
#### Traceback

```
ranger version: ranger 1.9.3
Python version: 2.7.16 (default, Jul  5 2020, 02:24:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.21) (-macos10.15-objc-
Locale: None.None

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ImgDisplayUnsupportedException
```

**Comment by toonn** [comment]
Looks like you have image previews enabled but you haven't properly configured the image_preview_method.

**Comment by wk30** [comment]
@toonn Thank you very much.
