### ISSUE TITLE
ranger crashes when opened in urxvt, runs fine when run in tmux session inside same urxvt instance

### ISSUE THREAD

**Issue by Awan** [ranger/ranger#2076]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Python version: Python 3.8.5
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.8/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```
![image](https://user-images.githubusercontent.com/42554663/90214102-f0dbc880-de10-11ea-89f2-c84388061d9e.png)

**Comment by toonn** [comment]
This should no longer happen on master. It might be triggered by your TERM setting but either way it's a fixed issue.
