### ISSUE TITLE
Filter in master branch makes ranger crash

### ISSUE THREAD

**Issue by kevinhwang91** [ranger/ranger#2086]
#### Runtime Environment

- Operating system and version: ArchLinux
- Terminal emulator and version: alacritty 0.5.0
- Python version: 3.8.5
- Ranger version/commit: ranger-master
- Locale:  en_US.UTF-8

#### Current Behavior
if no target after filtering, ranger crash

#### Expected Behavior
display empty rather than crash

#### Context
Even though I have patched https://github.com/ranger/ranger/pull/2072, ranger still crashes.

#### Steps to reproduce
1. open ranger in git root directory;
2. enter console mode `:filter ^f`;
3. no target  after filtering, ranger crash;

#### Traceback

```
ranger version: ranger-master
Python version: 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/main.py", line 210, in main
    fm.loop()
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/gui/ui.py", line 274, in handle_input
    self.handle_key(key)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/gui/ui.py", line 204, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/config/commands.py", line 1551, in quick
    self.fm.thisdir.refilter()
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/home/kevin/.local/lib/python3.8/site-packages/ranger/core/tab.py", line 73, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Good catch! I think you've caught multiple edge cases that affect the change I made so far : )
