### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by kabolov** [ranger/ranger#2088]
ranger version: ranger 1.9.3
Python version: 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Locale: None.None
Current file: '/Users/aleksandr.kabolov/.CFUserTextEncoding'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/browsercolumn.py", line 206, in _draw_file
    path = self.target.get_preview_source(self.wid, self.hei)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/container/file.py", line 96, in get_preview_source
    return self.fm.get_preview(self, width, height)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/actions.py", line 1123, in get_preview
    os.makedirs(ranger.args.cachedir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/aleksandr.kabolov/.cache/ranger'

**Comment by toonn** [comment]
Hmm, could this be a catalina issue? I'm not sure what to do about it. How can a user not have permissions to create directories in their own home directory?
