### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by magicalbanana** [ranger/ranger#2104]
#### Runtime Environment

- Operating system and version: Ubuntu 20.04.1 LTS
- Terminal emulator and version: kitty
- Python version: 3.7
- Ranger version/commit: 240d8a0e
- Locale: US

#### Current Behavior
```
╰─$ ranger                                                                                                                                                                                                      1 ↵
Traceback (most recent call last):
  File "/home/kareem/.pyenv/versions/3.7.5/bin/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/home/kareem/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ranger/core/main.py", line 32, in main
    from ranger.container.settings import Settings
  File "/home/kareem/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ranger/container/settings.py", line 13, in <module>
    from ranger.gui.colorscheme import _colorscheme_name_to_class
  File "/home/kareem/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ranger/gui/colorscheme.py", line 30, in <module>
    from curses import color_pair
  File "/home/kareem/.pyenv/versions/3.7.5/lib/python3.7/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by toonn** [comment]
Something's up with your setup. This error is happening in the python curses library which is part of the stdlib afaik. So the most likely problem is an installation issue. You seem to be in a virtual environment so wiping and reinstalling shouldn't be too hard.

**Comment by magicalbanana** [comment]
@toonn I think you're right. I changed my python version to 3.8.1 and it works fine now.
