### ISSUE TITLE
ImportError: cannot import name dim

### ISSUE THREAD

**Issue by Magic-Knight** [ranger/ranger#2105]
### Runtime Environment

- Operating system and version:  Ubuntu 16.04
- Terminal emulator and version:  
- Python version: 2.7.12 
- Ranger version/commit: 1.7.1
- Locale: en_US.UTF-8

#### Current Behavior
ranger crashed 
#### Expected Behavior
work normally
#### Context

install ranger on Ubuntu 16.04 by typing `apt install ranger` and it crashed when I typed `ranger`,  the same operation on Ubuntu 18.04 LTS worked properly .
#### Steps to reproduce
1.  install ranger on Ubuntu 16.04
2.  open ranger

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 93, in main
    load_settings(fm, arg.clean)
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 274, in load_settings
    fm.source(default_conf)
  File "/usr/lib/python2.7/dist-packages/ranger/core/actions.py", line 300, in source
    self.execute_console(line)
  File "/usr/lib/python2.7/dist-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib/python2.7/dist-packages/ranger/config/commands.py", line 336, in execute
    self.fm.set_option_from_string(name, value)
  File "/usr/lib/python2.7/dist-packages/ranger/core/actions.py", line 82, in set_option_from_string
    self.settings.set(option_name, self._parse_option_value(option_name, value), localpath, tags)
  File "/usr/lib/python2.7/dist-packages/ranger/container/settings.py", line 129, in set
    self.signal_emit('setopt.'+name, **kws)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/signals.py", line 256, in signal_emit
    fnc(signal)
  File "/usr/lib/python2.7/dist-packages/ranger/container/settings.py", line 101, in _sanitize
    _colorscheme_name_to_class(signal)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/colorscheme.py", line 122, in _colorscheme_name_to_class
    globals(), locals(), [scheme_name], 0), scheme_name)
  File "/root/.config/ranger/colorschemes/default.py", line 7, in <module>
    from ranger.gui.color import (
ImportError: cannot import name dim

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by toonn** [comment]
Yeah, sorry, that version is years old and we can no longer support it. Just install a recent version, from the repo for example.

**Comment by Magic-Knight** [comment]
I get it， Thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ranger/ranger"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 凌晨2:55
收件人:&nbsp;"ranger/ranger"<ranger@noreply.github.com&gt;;
抄送:&nbsp;"魔幻骑士"<835437582@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ranger/ranger] ImportError: cannot import name dim (#2105)





 
Yeah, sorry, that version is years old and we can no longer support it. Just install a recent version, from the repo for example.
