### ISSUE TITLE
rifle: re.error: bad escape (end of pattern) at position 34

### ISSUE THREAD

**Issue by Earnestly** [ranger/ranger#2111]
#### Runtime Environment
- Operating system and version: Linux
- Terminal emulator and version: xterm XTerm(360)
- Python version: Python 3.8.5
- Ranger version/commit: ranger version: ranger 1.9.3
- Locale: en_GB.UTF-8

When attempting to use `match` in `rifle.conf` where the regex is a youtube url containing `\=` I receive the following backtrace:
```
Traceback (most recent call last):
  File "/usr/bin/rifle", line 546, in <module>
    main()
  File "/usr/bin/rifle", line 531, in main
    for count, cmd, label, flags in rifle.list_commands(positional):
  File "/usr/bin/rifle", line 303, in list_commands
    if not self._eval_condition(test, files, None):
  File "/usr/bin/rifle", line 187, in _eval_condition
    return self._eval_condition2(condition, files, label)
  File "/usr/bin/rifle", line 209, in _eval_condition2
    return bool(re.search(argument, files[0]))
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 511, in _parse
    sourceget()
  File "/usr/lib/python3.8/sre_parse.py", line 256, in get
    self.__next()
  File "/usr/lib/python3.8/sre_parse.py", line 245, in __next
    raise error("bad escape (end of pattern)",
re.error: bad escape (end of pattern) at position 34
```

My `rifle.conf` contains:
```
match https://www\.youtube\.com/watch\?v\=.*, X, flag f = mpv --profile=url --ytdl-raw-options='user-agent="Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"' "$@"
```

If I don't escape the `=` then when attempting to use `rifle <youtube video url>` I get the error:
```
/bin/sh: .*,: command not found
```

Is there a way to match the `=` in this usage?

I'm currently working around this by simply not including the `=` in the regex part of the `match`.

**Comment by toonn** [comment]
Can confirm this bug, it's obvious from [the code here](https://github.com/ranger/ranger/blob/master/ranger/ext/rifle.py#L171).

You could try passing a unicode escape instead `\u003d` in this case but I'm not sure that'll work.

**Comment by Earnestly** [comment]
Yeah, unfortunately `\u003d` in this case doesn't result in a match
