### ISSUE TITLE
ranger does not start error No such file or directory: 'screen'

### ISSUE THREAD

**Issue by LeducH** [ranger/ranger#2123]
#### Runtime Environment

- Operating system and version: `Arch Linux x86_64 ; 5.8.14-arch1-1`
- Terminal emulator and version: `termite v15`
- Python version: `Python 3.8.6`
- Ranger version/commit: check error message
- Locale: 

#### Current Behavior
ranger does not start. shows error message

#### Expected Behavior
ranger starts

#### Context

I affects me very much. I want to start the app 

#### Possible Solutions
why is `screen` relevant

#### Steps to reproduce
1. start `termite` 
2. type `ranger` and the enter
3. 

#### Traceback

```
$ ranger 
ranger version: ranger 1.9.3
Python version: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
Locale: en_IE.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.8/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:

https://github.com/ranger/ranger/issues

$ echo $TERM                                                                                                                                                                                               
xterm-256color

```

**Comment by toonn** [comment]
Fixed in #1852.

**Comment by LeducH** [comment]
how is this solved?

**Comment by toonn** [comment]
On master, not in 1.9.3.
