### ISSUE TITLE
Rancher crashes when using Filter-as-you-type "f" after setting

### ISSUE THREAD

**Issue by Azlx** [ranger/ranger#2125]
#### Runtime Environment

- Operating system and version: macOS Catalina 10.15.4
- Terminal emulator and version: iTerm2 3.3.9
- Python version: 3.8.6
- Ranger version/commit: ranger-master 
- Locale: en_US.UTF-8

#### Current Behavior
1. Set map f console scout -ftsea%space in rc.conf
2. In Ranger, press f to enter the file name, and then enter a space to report an error

#### Traceback
```
ranger version: ranger-master
Python version: 3.8.6 (default, Oct  8 2020, 14:06:32) [Clang 12.0.0 (clang-1200.0.32.2)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/local/lib/python3.8/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/local/lib/python3.8/site-packages/ranger/config/commands.py", line 1546, in quick
    self.fm.thisdir.refilter()
  File "/usr/local/lib/python3.8/site-packages/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/local/lib/python3.8/site-packages/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/local/lib/python3.8/site-packages/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/local/lib/python3.8/site-packages/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/local/lib/python3.8/site-packages/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/local/lib/python3.8/site-packages/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/local/lib/python3.8/site-packages/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/local/lib/python3.8/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/local/lib/python3.8/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/local/lib/python3.8/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/local/lib/python3.8/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Hmm, could you try latest master? I wonder if this was fixed recently.

**Comment by Azlx** [comment]
I tried to clone the project again on the new macos, but the same error

### Traceback
```
ranger version: ranger-master
Python version: 3.9.0 (default, Oct  6 2020, 04:17:54) [Clang 12.0.0 (clang-1200.0.32.2)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/config/commands.py", line 1546, in quick
    self.fm.thisdir.refilter()
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```
### system info
```
 OS: macOS Catalina 10.15.7 19H2 x86_64
 Host: MacBookPro16,2
 Kernel: 19.6.0
 Shell: zsh 5.7.1
 CPU: Intel i5-1038NG7 (8) @ 2.00GHz
 GPU: Intel Iris Plus Graphics
 Terminal: iTerm2
 Locale: en_US.UTF-8
 GPU Driver: macOS Default Graphics Drive
```

======================================================================


And I also encountered the same error when I tried in manjaro's virtual machine

### Traceback
```
ranger version: ranger-master 
Python version: 3.8.5 (default, Sep  5 2020, 10:50:12) [GCC 10.2.0]
Locale: zh_CN.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/config/commands.py", line 1546, in quick
    self.fm.thisdir.refilter()
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.8/site-packages/ranger_fm-1.9.3-py3.8.egg/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
### system info
```
OS: Manjaro Linux x86_64 
Host: Parallels Virtual Platform None 
Kernel: 5.4.52-1-MANJARO 
Uptime: 26 mins 
Packages: 1195 (pacman) 
Shell: bash 5.0.18 
Resolution: 2880x1800 
DE: Plasma 5.19.5 
WM: KWin 
WM Theme: Sweet-Dark 
Theme: Sweet [Plasma], Breath [GTK2/3] 
Icons: candy-icons [Plasma], candy-icons [GTK2/3] 
Terminal: konsole 
Terminal Font: Noto Mono 10 
CPU: Intel i5-1038NG7 (2) @ 1.996GHz 
GPU: 01:00.0 Parallels, Inc. Accelerated Virtual Video Adapter 
Memory: 683MiB / 3909MiB
```

**Comment by toonn** [comment]
I still can't reproduce this. Can you reproduce it when running `ranger --clean` and just running the command rather than mapping? Or mapping the command while `ranger --clean` is running rather than from the config file?

**Comment by Azlx** [comment]
Latest test results:

1. This problem does not occur after using "brew install range"

2. Git clone v1.9.3 and  run `python setup.py install --optimize=1 --record=install_ log.txt `,  this problem did not occur

3. Git clone master and  run `python setup.py install --optimize=1 --record=install_ log.txt `,  this problem still exists

4. A new error is reported after running  `ranger -- clean` and `Scout - ftsea% space`

### Traceback
```
$ ranger --clean
ranger version: ranger-master
Python version: 3.9.0 (default, Oct  6 2020, 04:17:54) [Clang 12.0.0 (clang-1200.0.32.2)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/config/commands.py", line 1521, in execute
    self.fm.move(right=1)
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/local/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
