### ISSUE TITLE
Crashes on start when executing on a remote host through ssh when local terminal on host is tmux

### ISSUE THREAD

**Issue by prasannavl** [ranger/ranger#2138]
#### Runtime Environment

- Operating system and version: Ubuntu 20.04 LTS
- Terminal emulator and version: tmux 3.0a (on the local machine and sshd into remote with ranger)
- Ranger version: ranger 1.9.3
- Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
- Locale: en_IN.ISO8859-1

#### Current Behavior

Crashes (with traceback below) when executed through ssh on remote machine, when the local host is running tmux. All default config - installed through the Linux distro, no manual config given. 

Flow of commands + Steps to reproduce: 

```
tmux
ssh `machine-with-ranger`
ranger
``` 

It appears to be searching for `screen` and failing from the traceback.

#### Expected Behavior

The remote terminal shouldn't be interfering with ranger's behaviour. 

#### Traceback

```
$ ranger
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
Locale: en_IN.ISO8859-1

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3/dist-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by toonn** [comment]
This should be fixed on master. Could you check? You can run ranger.py straight from the repo.

**Comment by Granddave** [comment]
I had the same issue and can verify that the current master (`7cbdd92`) works fine.

- Tmux on host 3.0a
- Remote: Ubuntu 20.04 with `ranger 1.9.3-1build1`
- `TERM=screen-256color`

```
ranger version: ranger 1.9.3
Python version: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3/dist-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Thanks for the report, tentatively closing this issue!
