### ISSUE TITLE
Another Fzf integration problem

### ISSUE THREAD

**Issue by Yekutiel** [ranger/ranger#2142]
#### Runtime Environment
Lubuntu 20.04 LTS.
Ranger 1.9.3
Python 3.8.5
Fzf 0.20.0

#### Context
I want to use Fzf from within Ranger.

#### I searched through the issues on Github
I searched for `fzf` on this Ranger Github and found this issue which does **not** look similar to mine https://github.com/ranger/ranger/issues/1937#issue-608504129

#### What I did
I copied and pasted the text at https://github.com/ranger/ranger/wiki/Custom-Commands#fzf-integration into `/home/y/.config/ranger/commands.py` 

However, after doing so, when I attempted to run Ranger, I saw the following error message...

#### Traceback
```
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 413, in load_settings
    load_custom_commands(system_comm_path, custom_comm_path)
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 399, in load_custom_commands
    commands_custom = import_file('commands',
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 383, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783,in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/y/.config/ranger/commands.py", line 1, in <module>
    class fzf_select(Command):
NameError: name 'Command' is not defined

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

#### Getting Ranger to open
I then deleted the contents of `/home/y/.config/ranger/commands.py` and saved `commands.py` as a blank document. Then I was able to successfully open Ranger. But, of course, Fzf did not work from within Ranger after I did that.

Do you know how to solve this problem?

**Comment by Yekutiel** [comment]
#### Context
In an attempt to provide more debugging information I just added https://github.com/ranger/ranger/wiki/Custom-Commands#search-with-fd (a **different** custom command) into `/home/y/.config/ranger/commands.py`.

#### What I did
I copied and pasted the text at https://github.com/ranger/ranger/wiki/Custom-Commands#search-with-fd  into /home/y/.config/ranger/commands.py

However, after doing so, when I attempted to run Ranger, I saw the following error message...

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 413, in load_settings
    load_custom_commands(system_comm_path, custom_comm_path)
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 399, in load_custom_commands
    commands_custom = import_file('commands',
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 383, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783,in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/y/.config/ranger/commands.py", line 3, in <module>
    class fd_search(Command):
NameError: name 'Command' is not defined

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by chu4ng** [comment]
Can you post your commands.py here?
>  File "/home/y/.config/ranger/commands.py", **line 1**, in <module>
>  class fzf_select(Command):

I think you paste code for fzf/fd integration in top of commands.py file instead paste it in bottom.

**Comment by Yekutiel** [comment]
Thanks! Based on your suggestion I solved that problem!

> I think you paste code for fzf/fd integration in top of commands.py file instead paste it in bottom.

Oh, no. It's worse than that. I actually neglected to put from `ranger.api.commands import Command` in **altogether**.
