### ISSUE TITLE
TypeError when applying duplicate filter

### ISSUE THREAD

**Issue by paddybu** [ranger/ranger#2168]
####  Runtime Environment

- Operating system and version: Archlinux
- Terminal emulator and version: tilix 1.9.1
- Python version: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
- Ranger version: happens on 1.9.3 (archlinux repos) and ranger-master v1.9.3-141-gfc3dcfe8
- Locale: en_US.UTF-8

#### Current Behavior
When applying the duplicate filter to the filter stack (with either `."` or `:filter_stack add duplicate`), ranger shows the attached error in the logs.

#### Possible Solutions
Replacing line 17 in ranger/ext/hash.py with `h.update(filepath.encode())` seems to fix the problem.

#### Steps to reproduce
1. Open ranger
2. Execute one of the commands mentioned

#### Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 198, in handle_key
    self.press(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 211, in press
    self.fm.execute_console(
  File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 271, in execute_console
    cmd.execute()
  File "/usr/lib/python3.8/site-packages/ranger/config/commands.py", line 1681, in execute
    SIMPLE_FILTERS[self.arg(2)](self.rest(3))
  File "/usr/lib/python3.8/site-packages/ranger/core/filter_stack.py", line 138, in __init__
    self.duplicates = self.get_duplicates()
  File "/usr/lib/python3.8/site-packages/ranger/core/filter_stack.py", line 148, in get_duplicates
    for dups in group_by_hash(self.fm.thisdir.files_all):
  File "/usr/lib/python3.8/site-packages/ranger/core/filter_stack.py", line 107, in group_by_hash
    chunk = next(chunks)
  File "/usr/lib/python3.8/site-packages/ranger/ext/hash.py", line 17, in hash_chunks
    h.update(filepath)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by toonn** [comment]
#2130 fixes this.

**Comment by andkaha** [comment]
The bug seems to occur only when the filter is applied in directories with subdirectories.

As a side note, newer Python versions mentions "Strings" rather than "Unicode-objects" in the error message. The following is a traceback using a more recent Python than what was used in the original issue submission: 

```none
ranger version: ranger 1.9.4
Python version: 3.13.13 (main, Apr 24 2026, 14:17:31) [Clang 19.1.7 ]
Locale: en_GB.UTF-8
Current file: '/home/myself/Documents'

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
    ~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
    ~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/ranger/gui/ui.py", line 198, in handle_key
    self.press(key)
    ~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/ranger/gui/ui.py", line 211, in press
    self.fm.execute_console(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        keybuffer.result,
        ^^^^^^^^^^^^^^^^^
        wildcards=keybuffer.wildcards,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        quantifier=keybuffer.quantifier,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/ranger/core/actions.py", line 271, in execute_console
    cmd.execute()
    ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/ranger/config/commands.py", line 1681, in execute
    SIMPLE_FILTERS[self.arg(2)](self.rest(3))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ranger/core/filter_stack.py", line 138, in __init__
    self.duplicates = self.get_duplicates()
                      ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/ranger/core/filter_stack.py", line 148, in get_duplicates
    for dups in group_by_hash(self.fm.thisdir.files_all):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ranger/core/filter_stack.py", line 107, in group_by_hash
    chunk = next(chunks)
  File "/usr/local/lib/python3.13/site-packages/ranger/ext/hash.py", line 17, in hash_chunks
    h.update(filepath)
    ~~~~~~~~^^^^^^^^^^
TypeError: Strings must be encoded before hashing

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
