### ISSUE TITLE
Mouse input unhandled after wake

### ISSUE THREAD

**Issue by yatish609** [ranger/ranger#2173]
**Runtime Environment**
DE - Xfce4
Terminal - xfce4-terminal
Python version: 3.9.0 (default, Oct  7 2020, 23:09:01) [GCC 10.2.0]
Locale: en_IN.UTF-8

**Issue**
Ranger crashes when mouse input is given after wake up from the lock screen (no hibernate or suspend). 

Crash log:

~~~
ranger version: ranger-master 
Python version: 3.9.0 (default, Oct  7 2020, 23:09:01) [GCC 10.2.0]
Locale: en_IN.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 271, in handle_input
    self.handle_mouse()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 188, in click
    if DisplayableContainer.click(self, event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 86, in click
    self.fm.enter_dir(self.target.path)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 585, in enter_dir
    result = self.thistab.enter_dir(path, history=history)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range
~~~

**Comment by chu4ng** [comment]
I think it's relate with: #2071 and PR #2072.
