### ISSUE TITLE
ranger 1.9.3: AttributeError: 'Tags' object has no attribute 'tags'

### ISSUE THREAD

**Issue by fwy** [ranger/ranger#2200]
This issue is very similar to [https://github.com/ranger/ranger/issues/851](https://github.com/ranger/ranger/issues/851), but for a newer version of ranger.

#### Runtime Environment
- Operating system and version: msys2 (msys2-runtime 3.1.7-4) on Windows 10
- Terminal emulator and version: bash 5.1.004-1
- Python version: 3.8.6
- Ranger version/commit: 1.9.3
- Locale: en-US.UTF-8

#### Current Behavior
Ranger crashes immediately.

#### Expected Behavior
Ranger runs without crashing.

#### Context
Trying to run ranger on Windows from a bash shell.
I also cloned the GIT repo and ran ranger.py as suggested, but received almost the same error as shown below.

#### Steps to reproduce
1. Install using python: pip install ranger-fm
2. Run ranger at bash command line

#### Traceback
```
ranger version: ranger 1.9.3
Python version: 3.8.6 (default, Oct 23 2020, 14:59:35) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/browsercolumn.py", line 189, in draw
    self._draw_directory()
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/browsercolumn.py", line 295, in _draw_directory
    tagged = self.fm.tags and drawn.realpath in self.fm.tags
  File "/usr/lib/python3.8/site-packages/ranger/container/tags.py", line 28, in __contains__
    return item in self.tags
AttributeError: 'Tags' object has no attribute 'tags'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by toonn** [comment]
Try moving `$XDG_CONFIG_HOME/ranger/tags` out of the way. I suspect your tags file contains a path that no longer exists.

**Comment by fwy** [comment]
Thanks for the quick reply.  However, there is no tags file in $XDG_CONFIG_HOME/ranger.  I tried deleting the directory, but it made no difference and was re-created on the next attempt to start ranger.

I noticed the $HOME/.local/ranger directory containing the files bookmarks and history, but it also contained no tags file.

I do have 'tags' files generated from ctags in various directories on the system, but not in any part of the ranger installation that I can find.

**Comment by toonn** [comment]
Does `ranger --clean` work fine?

**Comment by toonn** [comment]
I think the problem is we're hiding the relevant exception, could you apply this simple patch and report the exception you get?
```
diff --git a/ranger/container/tags.py b/ranger/container/tags.py
index 50d5ff72..ea071d86 100644
--- a/ranger/container/tags.py
+++ b/ranger/container/tags.py
@@ -72,7 +72,7 @@ class Tags(object):
             else:
                 fobj = open(self._filename, 'r')
         except OSError:
-            pass
+            raise
         else:
             self.tags = self._parse(fobj)
             fobj.close()
```

**Comment by fwy** [comment]
Yes, ranger --clean works.  (I missed this option.)

**Comment by fwy** [comment]
Yes, the specific exception was hidden.  Here is the output with your patch.

ranger version: ranger 1.9.3
Python version: 3.8.6 (default, Oct 23 2020, 14:59:35) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 116, in initialize
    self.tags = Tags(self.datapath('tagged'))
  File "/usr/lib/python3.8/site-packages/ranger/container/tags.py", line 25, in __init__
    self.sync()
  File "/usr/lib/python3.8/site-packages/ranger/container/tags.py", line 76, in sync
    fobj = open(self._filename, 'r', errors='replace')
**FileNotFoundError: [Errno 2] No such file or directory: '/:\\Users\\fwy\\.local\\share/ranger/tagged'**

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

It looks like the Windows pathname is being mangled.  I suspect this might be a side effect of running in msys2, where Windows pathnames are expressed with forward slashes, not back slashes.  In msys2, this .local directory would be written '/c/Users/fwy/.local/share/ranger'.

**Comment by toonn** [comment]
@fwy, my patch in #2204 doesn't fix this but I'd appreciate if you could check it at least reports a useful error message,  check the log with `W`.

**Comment by fwy** [comment]
With your last 3 commits modifying tags.py, the following errors are displayed when running ranger or ranger --clean, so I can't get far enough to use the W option.

$ ranger
Traceback (most recent call last):
  File "/usr/bin/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 34, in main
    from ranger.core.fm import FM
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 21, in <module>
    from ranger.container.tags import Tags, TagsDummy
  File "/usr/lib/python3.8/site-packages/ranger/container/tags.py", line 11, in <module>
    from ranger import PY3
ImportError: cannot import name 'PY3' from 'ranger' (/usr/lib/python3.8/site-packages/ranger/__init__.py)


The file __init__.py does exist in the right location and appears to be valid.  In msys2, the path '/usr/lib/python3.8/site-packages/ranger/__init__.py' is correct.  The native Windows path is 'C:\msys64\usr\lib\python3.8\site-packages\ranger\__init__py'.

**Comment by toonn** [comment]
Well that's baffling. `tags.py` already imported that name before my patches so I'm not sure why it'd suddenly stop working. How did you patch the installed ranger? And does it work if you simply run it from the repository?

**Comment by fwy** [comment]
Sorry, when run from my local git repository with ./ranger.py it does work.  When I tried earlier, I noticed that only the file tags.py had been changed by your patches and just copied it into my local 1.9.3 installation.  That was sloppy, I suppose other important commits were missing from 1.9.3 that made a difference.

**Comment by toonn** [comment]
Np, do you get a more useful error about the tags file now?

**Comment by fwy** [comment]
It seems to be working OK with no tags file errors.  The message log from the W command shows only the ranger and python versions, locale, and process id.

**Comment by toonn** [comment]
So the original problem disappeared? Could you try reproducing it by removing `.local/shared/ranger/tagged`? Pre and post patch if it's not too much trouble?

**Comment by fwy** [comment]
There is no .local/shared/ranger/tagged file in my environment either before or after the patch, while ranger is running or after.  I am not familiar with this file or other ranger internals, so let me know if I should try other tests.

**Comment by toonn** [comment]
Oh, of course. No error will show up unless ranger tries to write the tags. So you'll have to tag something, `t` toggles the default tag. Immediately afterwards you should see something in the log.

**Comment by fwy** [comment]
On the t command, a 'no such file or directory' error was displayed.  Here is the message log with the error.

![image](https://user-images.githubusercontent.com/4481175/103441255-3bb87a00-4c12-11eb-9975-2ce122844bc3.png)

No file 'tagged' exists in the .local/share/ranger/ directory.

**Comment by toonn** [comment]
Ok, at least you get to see the error now rather than crashing with no information.

I have no idea why the path turns out the way it is. Do you have `XDG_CONFIG_HOME` or `XDG_DATA_HOME` set?
The path ranger uses is `~/.local/share/ranger`, literally. It then adds "tagged" using `os.path.join` so it's bizarre that only the slash between ".local" and "share" ends up being a backslash.

**Comment by fwy** [comment]
My XDG_CONFIG_HOME and XDG_DATA_HOME are set to 'C:\Users\fwy\.config' and 'C:\Users\fwy\.local\share' respectively, where my home directory is 'C:\Users\fwy'.  However, msys2 can handle mixed Windows- and UNIX-style pathnames, and based on problems seen sometimes with other packages I strongly suspect that is the issue here.  It looks like ranger is expanding the '~' path prefix to the full home directory, but it may be referencing an environment variable that is set to a Windows path with backslashes rather than the corresponding msys2 (Linux-like) path.  In that case, probably the leading Windows drive letter 'C' was replaced with the leading slash in order to reference an absolute path on Linux.  The result is a hybrid path of Windows and Linux segments that is invalid.

I haven't looked at the ranger source code yet, but you may find the 'cygpath' command useful when running in cygwin or msys2 environments.   Given a Windows, msys2, or mixed pathname, it will return the cygwin/msys2 or Windows equivalent depending on the '-u' or '-w' arguments.  Examples:

$ cygpath -u \\Users\\fwy\\.local\\share/ranger/tagged
/c/Users/fwy/.local/share/ranger/tagged

$ cygpath -u \\Users\\fwy\\.local\\share\\ranger\\tagged
/c/Users/fwy/.local/share/ranger/tagged

$ cygpath -u \\Users\\fwy
/c/Users/fwy

$ cygpath -u C:\\Users\\fwy
/c/Users/fwy

$ cygpath -w /c/Users/fwy
C:\Users\fwy

$ cygpath -w \\Users\\fwy
C:\Users\fwy

This is useful in scripts in order to normalize pathnames to one standard or the other.

**Comment by fwy** [comment]
I am not a python developer, but with the help of [this post](https://stackoverflow.com/questions/10884268/convert-posix-win-path-in-cygwin-python-w-o-calling-cygpath) I was able to hack a simple fix to avoid the tagging error.  It isn't suitable for a pull request, but you will get the idea.  The win_path method converts a cygwin or msys2 path to a Windows pathname with simple regex replacements.  With this change to tags.py (see attached text file) file tagging and untagging seems to work in my msys2 environment.

[tags.py.txt](https://github.com/ranger/ranger/files/5792076/tags.py.txt)

**Comment by codehhr** [comment]
> Does `ranger --clean` work fine?

Yeah, It works !

**Comment by toonn** [comment]
@codehhr, ok, so when your run ranger with the `--clean` option it tries not to use any of your local configuration and data files. This means if ranger works with that option then the problem is most likely in either a configuration file you edited or one of the data files got "corrupted," for instance, if you remove a path outside of ranger and that path is still in the bookmarks file, then ranger will fail to initialize its bookmarks.
