### ISSUE TITLE
Ranger crashes on right click when window is small

### ISSUE THREAD

**Issue by AndreiSva** [ranger/ranger#2205]
#### Runtime Environment

- Operating system and version: Manjaro 5.4.85
- Terminal emulator and version: Konsole 20.12.0
- Python version: 3.9.1
- Ranger version/commit: ranger-master
- Locale: en_CA.UTF-8

#### Current Behavior
When the terminal where ranger is running is small, clicking on a folder other than the focused folder causes ranger to crash.

#### Expected Behavior
Ranger should register the click and select the clicked folder.

#### Context
I often use ranger in a small terminal window alongside lots of others. This bug led me to accidentally quit out of ranger multiple times and require me to navigate back to where I was before to continue my work.

#### Possible Solutions
Introduce an if statement in tab.py that only changes the pointed object if self.thisdir.files is not none. I have submitted a pull request which applies this fix.

#### Steps to reproduce
1. Open ranger in a small terminal window.
2. Right click on anything other than the focused folder.

#### Traceback

```
ranger version: ranger-master 
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: en_CA.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 271, in handle_input
    self.handle_mouse()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 188, in click
    if DisplayableContainer.click(self, event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 97, in click
    self.fm.enter_dir(clicked_file.path, remember=True)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 585, in enter_dir
    result = self.thistab.enter_dir(path, history=history)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by AndreiSva** [comment]
#2206
