### ISSUE TITLE
Ranger crashes after pasting cut files (two panes)

### ISSUE THREAD

**Issue by vonshednob** [ranger/ranger#2207]
#### Runtime Environment

- Operating system and version: Manjaro i3
- Terminal emulator and version: kitty 0.19.3 with fish 3.1.2
- Python version: 3.9.1
- Ranger version/commit: 1.9.3 (1.9.3.143.g5047d9e5-1)
- Locale: en_GB.UTF-8

#### Current Behavior

Pasting one or multiple files crashes ranger.

#### Expected Behavior

Pasting one or multiple files should not crash ranger.

#### Context

I'd like to move a bunch of files using `dd` and `pp`. This crashes since the update to python 3.9.

#### Possible Solutions

Copy and delete afterwards still works without crashing. Downgrading back to python 3.8 is not really an option though.

#### Steps to reproduce
1. Have `set viewmode multipane` in `rc.conf` (not sure whether this is absolutely required, but that's my configuration)
2. Start ranger in `~`
3. `:mkdir tmp`
4. `gn` (open a new pane)
5. enter `~/tmp` directory
6. At this point ranger should have two panes open, one in home, one in `~/tmp`
7. select a file in `~`
8. `dd` (cut the file)
9. `gn` (go to next pane)
10. `pp` (paste the file)

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 376, in loop
    ui.redraw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 370, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 257, in draw
    displayable.draw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_multipane.py", line 64, in draw
    ViewBase.draw(self)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 43, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 257, in draw
    displayable.draw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 189, in draw
    self._draw_directory()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 275, in _draw_directory
    self._set_scroll_begin()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 555, in _set_scroll_begin
    self.scroll_begin = self._get_scroll_begin()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 522, in _get_scroll_begin
    index = self._get_index_of_selected_file() or 0
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 417, in _get_index_of_selected_file
    return self.tab.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 62, in _get_pointer
    and self.thisdir.files[self._pointer] != self._pointed_obj
IndexError: list index out of range

```

**Comment by toonn** [comment]
Thanks for the report. Similar to #2205 and some other issues.
