### ISSUE TITLE
When I upgrade the python to python 3.9 I get error how to solve it?

### ISSUE THREAD

**Issue by woshichuanqilz** [ranger/ranger#2208]
#### Runtime Environment

- Operating system and version: 
manjaro 20.2
- Terminal emulator and version: 
alacritty 0.6.0
- Python version: 
python 3.9
- Ranger version/commit: 
- Locale: 

#### Current Behavior
when I start ranger 
I get error like this:
> Traceback (most recent call last):
  File "/usr/bin/ranger", line 37, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
  File "/usr/lib/python3.9/site-packages/ranger/__init__.py", line 53, in <module>
    VERSION = version_helper()
  File "/usr/lib/python3.9/site-packages/ranger/__init__.py", line 25, in version_helper
    git_describe = subprocess.Popen(['git', 'describe'],
  File "/home/lizhe/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/lizhe/anaconda3/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: fork_exec() takes exactly 21 arguments (17 given)

Seems related to the python version. But I dont know how to fix it.
* I try to change the shebang of the /usr/bin/ranger to anaconda3/python3.8 but not work
Error msg is no module named ranger. I already install it by pip command.
So how to solve it ?

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
Looks like a weird mixing of your system python and the anaconda distribution. I don't know how to fix this.
If you want to install ranger with pip make sure you install `ranger-fm`.

Maybe ask for help in the anaconda, manjaro or arch communities?

**Comment by chu4ng** [comment]
I think you need delete all ranger-files on system-side(don't catch configs) and install in future from one source, example pacman, pip or source code from git.

**Comment by hazgal** [comment]
All was running like an oiled machine until python upgrade.
Here is the output:
`ranger version: ranger 1.9.3
Python version: 3.9.1 (default, Dec  9 2020, 14:39:22) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.9/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.9/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues`

Running ranger with sudo, however, works.

**Comment by woshichuanqilz** [comment]
My issue is solved by remove then anaconda from env path. Any one encounter this can have a try. 

ranger version: ranger-master
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: en_US.UTF-8

**Comment by toonn** [comment]
@hazgal, two things. One, it looks like somehow you have a path in your bookmarks which points to a file rather than a directory? Second, AssertionErrors shouldn't happen because the shebang line starts python with the optimize flag, which suppresses those. So your `ranger.py` shebang was patched and other stuff too potentially.

**Comment by sanp-w** [comment]
> All was running like an oiled machine until python upgrade.
> Here is the output:
> 
> ```
> ranger version: ranger 1.9.3
> Python version: 3.9.1 (default, Dec  9 2020, 14:39:22) [GCC 9.3.0]
> Locale: en_US.UTF-8
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 171, in main
>     fm.initialize()
>   File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 127, in initialize
>     self.bookmarks.load()
>   File "/usr/lib/python3.9/site-packages/ranger/container/bookmarks.py", line 47, in load
>     new_dict = self._load_dict()
>   File "/usr/lib/python3.9/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
>     dct[key] = self.bookmarktype(value)
>   File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 150, in __init__
>     assert not os.path.isfile(path), "No directory given!"
> AssertionError: No directory given!
> 
> ranger crashed. Please report this traceback at:
> https://github.com/ranger/ranger/issues
> ```
> 
> Running ranger with sudo, however, works.

 I hava the same problem with you ,and I cannot fix it . Did you successfully solve this problem? I want to know how to fix it , please.

**Comment by chu4ng** [comment]
@sanp-w 
>Did you successfully solve this problem? I want to know how to fix it , please.

Can you delete `bookmarks` and `history` files from `$HOME/.local/share/ranger` dir?
Or just rename them.

**Comment by sanp-w** [comment]
> @sanp-w
> 
> > Did you successfully solve this problem? I want to know how to fix it , please.
> 
> Can you delete `bookmarks` and `history` files from `$HOME/.local/share/ranger` dir?
> Or just rename them.

fine! It works . Thank you very much.
