### ISSUE TITLE
IndexError when applying duplicate filter

### ISSUE THREAD

**Issue by snowman** [ranger/ranger#2209]
#### Runtime Environment

- Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
- Ranger version: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
When applying the duplicate filter to the filter stack (with either `."`
or `:filter_stack add duplicate`), ranger shows the attached error in
the logs.

#### Possible Solutions
When there are no duplicate files, skip it.

#### Steps to reproduce
1. `$ cd /tmp`
2. `$ git clone https://github.com/ranger/ranger`
3. `$ cd ranger`
3. Apply patch [Fix hash filter by toonn #2130](https://github.com/ranger/ranger/pull/2130)
4. `$ ./ranger.py --debug`
5. Execute one of the commands mentioned, it'll crash
6. `$ cp ranger.py ranger.py.copy`
7. Open ranger again and run execute one of the commands mentioned,
   it'll show duplicate files only.

#### Traceback

```
Traceback (most recent call last):
  File "/tmp/ranger/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/tmp/ranger/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/tmp/ranger/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/tmp/ranger/ranger/gui/ui.py", line 208, in handle_key
    self.press(key)
  File "/tmp/ranger/ranger/gui/ui.py", line 221, in press
    self.fm.execute_console(
  File "/tmp/ranger/ranger/core/actions.py", line 269, in execute_console
    cmd.execute()
  File "/tmp/ranger/ranger/config/commands.py", line 1718, in execute
    self.fm.thisdir.refilter()
  File "/tmp/ranger/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/tmp/ranger/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/tmp/ranger/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/tmp/ranger/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/tmp/ranger/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/tmp/ranger/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/tmp/ranger/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/tmp/ranger/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/tmp/ranger/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/tmp/ranger/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/tmp/ranger/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Looks like you need #2072. This isn't specific to filters, see #2205 for example.

**Comment by snowman** [comment]
Okay, after manually test, it should be 

```python
try:
    self._pointed_obj = self.thisdir.files[self._pointer]
except IndexError:
    pass
except TypeError:
    pass
```
