### ISSUE TITLE
Ranger crashes when navigating to folders.

### ISSUE THREAD

**Issue by thepenguinthatwants** [ranger/ranger#2217]
Operating system:
manjaro

After updating my system for some reasons python became quite unstable as it crashes easily when I navigate to folders.
I use to go to certain folders using bookmarks and then when going further it starts to  crash.

```
ranger version: ranger-master
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: en_US.UTF-8Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1520, in execute
    self.fm.move(right=1)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptableranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Looks like #2072 should have fixed this. Since you're running ranger-master it might be as simple as just updating?

**Comment by thepenguinthatwants** [comment]
Hi,
As I installed using package manager and its right now 1.9.3.
How do I update to 1.9.4?

**Comment by toonn** [comment]
1.9.4 hasn't been release yet. But in the stacktrace you shared the version is "ranger-master" not "1.9.3", so I assumed you'd installed `ranger-git` from the AUR.

**Comment by sirsurthur** [comment]
Hello, 

I just experienced the same bug while navigating between folders.

Let me know if you need any more information,

====

[julien@arch ~]$ ranger

ranger version: ranger-master 
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: fr_FR.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 271, in handle_input
    self.handle_mouse()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 188, in click
    if DisplayableContainer.click(self, event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 81, in click
    self.fm.move_parent(direction)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 560, in move_parent
    self.thistab.enter_dir(parent.files[parent.pointer + n])
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by toonn** [comment]
That was fixed in #2072, if you run the master branch you won't run into it.

**Comment by thepenguinthatwants** [comment]
> 1.9.4 hasn't been release yet. But in the stacktrace you shared the version is "ranger-master" not "1.9.3", so I assumed you'd installed `ranger-git` from the AUR.

Nah I've used the official repos.
Hopefully 1.9.4 will get this fixed. Ranger has become my to go tool to jump into bookmarked folders and to continue.

**Comment by toonn** [comment]
No released version of ranger even has this bug. It only occurred on recent versions of the master branch. So either install 1.9.3 or update to the latest version of master and it should be fixed. Just tested myself and I can't trigger the bug on either 1.9.3 nor on master so I'm closing this issue.

Both rangers in this issue reported their version as "ranger-master" which means they're not official releases. If you got these from a normal distro package and not from something like the AUR, you should report this to the package maintainer because it's probably a mistake.

**Comment by thepenguinthatwants** [comment]
Hmm I couldnt get this bug to appear in arch, but on manjaro it does occur.
Version as ranger-1.9.3.143.g5047d9e5-1

Most likely this distro has something funky.

**Comment by toonn** [comment]
That's very possible. Manjaro also insists on shipping a terribly old (and maybe altered) version of `scope.sh`.
