### ISSUE TITLE
ranger crashes upon attempting to trash a file.

### ISSUE THREAD

**Issue by PastelProgrammer** [ranger/ranger#2219]
#### Runtime Environment

- Operating system and version: Manjaro Linux
- Terminal emulator and version: Konsole
- Python version: 3.9.1
- Ranger version/commit: ranger-master
- Locale:  en_US.UTF-8

#### Context

i was testing deleting files to get more practice in using ranger.
#### Steps to reproduce
1. attempt to trash any given file by typing dT.

#### Traceback

```
ranger version: ranger-master 
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: en_US.UTF-8
Current file: '/home/pastel/Documents/testing/hi.txt'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 215, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 198, in _answer_question
    callback(answer)
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 760, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 430, in execute_file
    filenames = [f.path for f in files]
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 430, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues


```

**Comment by toonn** [comment]
Closing in favor of #1798.
