### ISSUE TITLE
Mac 

### ISSUE THREAD

**Issue by kono3d** [ranger/ranger#2226]
ranger version: ranger-master
Python version: 2.7.16 (default, Nov 23 2020, 08:01:20) [GCC Apple LLVM 12.0.0 (clang-1200.0.30.4) [+internal-os, ptrauth-isa=sign+stri
Locale: None.None

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ranger_fm-1.9.3-py2.7.egg/ranger/core/main.py", line 173, in main
    fm.initialize()
  File "/Library/Python/2.7/site-packages/ranger_fm-1.9.3-py2.7.egg/ranger/core/fm.py", line 115, in initialize
    self.tags = Tags(self.datapath('tagged'))
  File "/Library/Python/2.7/site-packages/ranger_fm-1.9.3-py2.7.egg/ranger/container/tags.py", line 28, in __init__
    self.sync()
  File "/Library/Python/2.7/site-packages/ranger_fm-1.9.3-py2.7.egg/ranger/container/tags.py", line 81, in sync
    fobj = open(self._filename, 'r')
IOError: [Errno 21] Is a directory: '/Users/vision3d/.local/share/ranger/tagged'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by toonn** [comment]
Not sure how that became a directory but it should be a file, try removing it. (Maybe check the contents first to be sure.)
