### ISSUE TITLE
"IndexError: list index out of range" when using filter

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#2230]
#### Runtime Environment

- Operating system and version: `Manjaro+Cinnamon`
- Terminal emulator and version: `Alacritty v0.7.1`
- Python version: `v3.9.1`
- Ranger version/commit: `ranger-master, installed from Manjaro offical repo, v1.9.3.143.g5047d9e5-1`
- Locale: `en_US.UTF-8`

#### Current Behavior

`ranger` cannot handle the`]` character in ranger filter function.

#### Expected Behavior

ranger should handle the `]` character as it does for `[`. Maybe there are other symbols that make ranger crash since some actions make ranger crash before, I just didn't pay attension.

#### Steps to reproduce
1. `ranger` in a random directory such as my HOME or `/tmp`
2. `zf` to filter, 
3. input exact `]`,  it is just a mistake, but it causes ranger's crash.

I tried to reproduce the issue without `~/.config/ranger`, it is the same result.

#### Traceback

The following is the result of `ranger --debug` and reproduce the above steps:
**BTW:** the following result is the same with `ranger` without `--debug`.

```
>> ranger --debug
ranger version: ranger-master
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1545, in quick
    self.fm.thisdir.refilter()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by sarrietav-dev** [comment]
Same here, but it happened when I typed the `/` key.

**Comment by chu4ng** [comment]
Can you check this issue with master-version from git?
#2072 PR did should fix this error.
Your 5047d9e5 version come before needed f1c5ff1 commit.
I think you need update ranger from git or manually make changes in ranger code. Or wait branch update in  pip/aur/pacman.

**Comment by c02y** [comment]
> Same here, but it happened when I typed the `/` key.

Same here for `/`, so I said, `Maybe there are other symbols that make ranger crash since some actions make ranger crash before, I just didn't pay attension.`

**Comment by toonn** [comment]
Both of these stem from the same problem, which was fixed. If you cannot update to the master branch you could try patching your local installation. Otherwise you'll have to wait for release 1.9.4, which is probably months away.

**Comment by c02y** [comment]
@toonn  Yes, thanks, I just tried it, the issue is fixed.
