### ISSUE TITLE
NetBSD 9.1-evbarm, unable to start ranger, mouse_event.py", line 12 -> no attribute like curses.BUTTON1_PRESSED

### ISSUE THREAD

**Issue by arnyekveto** [ranger/ranger#2248]
#### Runtime Environment

- Operating system and version: NetBSD 9.1,
architecture: uname -m = evbarm, uname -p = earmv7hf
machine: OrangePi Zero (sunxi)
- Terminal emulator and version:
 NetBSD.earmv7hf::orange@OrangePi0:~$ bash --version
GNU bash, version 5.0.17(1)-release (armv7--netbsdelf-eabihf)
- Python version:
- Python 2.7.18 (default, Jun 22 2020, 15:44:08) 
[GCC 7.4.0] on netbsd9
- Ranger version/commit: Ranger 1.9.x 
- Locale: 
NetBSD.earmv7hf::orange@OrangePi0:~$ locale
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="C"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=""

#### Current Behavior
crashing on import curses in mouse gui part
#### Expected Behavior
ranger starts, woot! :-)
#### Context
I give a try to discover curses module in python2.7:
etBSD.earmv7hf::orange@OrangePi0:~/Projects/ranger$ python2.7
Python 2.7.18 (default, Jun 22 2020, 15:44:08) 
[GCC 7.4.0] on netbsd9
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>> curses
<module 'curses' from '/usr/pkg/lib/python2.7/curses/__init__.pyc'>
>>> dir(curses)
['A_ALTCHARSET', 'A_ATTRIBUTES', 'A_BLINK', 'A_BOLD', 'A_CHARTEXT', 'A_COLOR', 'A_DIM', 'A_INVIS', 'A_NORMAL', 'A_PROTECT', 'A_REVERSE', 'A_STANDOUT', 'A_UNDERLINE', 'COLOR_BLACK', 'COLOR_BLUE', 'COLOR_CYAN', 'COLOR_GREEN', 'COLOR_MAGENTA', 'COLOR_RED', 'COLOR_WHITE', 'COLOR_YELLOW', 'ERR', 'KEY_A1', 'KEY_A3', 'KEY_B2', 'KEY_BACKSPACE', 'KEY_BEG', 'KEY_BREAK', 'KEY_BTAB', 'KEY_C1', 'KEY_C3', 'KEY_CANCEL', 'KEY_CATAB', 'KEY_CLEAR', 'KEY_CLOSE', 'KEY_COMMAND', 'KEY_COPY', 'KEY_CREATE', 'KEY_CTAB', 'KEY_DC', 'KEY_DL', 'KEY_DOWN', 'KEY_EIC', 'KEY_END', 'KEY_ENTER', 'KEY_EOL', 'KEY_EOS', 'KEY_EXIT', 'KEY_F0', 'KEY_F1', 'KEY_F10', 'KEY_F11', 'KEY_F12', 'KEY_F13', 'KEY_F14', 'KEY_F15', 'KEY_F16', 'KEY_F17', 'KEY_F18', 'KEY_F19', 'KEY_F2', 'KEY_F20', 'KEY_F21', 'KEY_F22', 'KEY_F23', 'KEY_F24', 'KEY_F25', 'KEY_F26', 'KEY_F27', 'KEY_F28', 'KEY_F29', 'KEY_F3', 'KEY_F30', 'KEY_F31', 'KEY_F32', 'KEY_F33', 'KEY_F34', 'KEY_F35', 'KEY_F36', 'KEY_F37', 'KEY_F38', 'KEY_F39', 'KEY_F4', 'KEY_F40', 'KEY_F41', 'KEY_F42', 'KEY_F43', 'KEY_F44', 'KEY_F45', 'KEY_F46', 'KEY_F47', 'KEY_F48', 'KEY_F49', 'KEY_F5', 'KEY_F50', 'KEY_F51', 'KEY_F52', 'KEY_F53', 'KEY_F54', 'KEY_F55', 'KEY_F56', 'KEY_F57', 'KEY_F58', 'KEY_F59', 'KEY_F6', 'KEY_F60', 'KEY_F61', 'KEY_F62', 'KEY_F63', 'KEY_F7', 'KEY_F8', 'KEY_F9', 'KEY_FIND', 'KEY_HELP', 'KEY_HOME', 'KEY_IC', 'KEY_IL', 'KEY_LEFT', 'KEY_LL', 'KEY_MARK', 'KEY_MAX', 'KEY_MESSAGE', 'KEY_MIN', 'KEY_MOUSE', 'KEY_MOVE', 'KEY_NEXT', 'KEY_NPAGE', 'KEY_OPEN', 'KEY_OPTIONS', 'KEY_PPAGE', 'KEY_PREVIOUS', 'KEY_PRINT', 'KEY_REDO', 'KEY_REFERENCE', 'KEY_REFRESH', 'KEY_REPLACE', 'KEY_RESET', 'KEY_RESIZE', 'KEY_RESTART', 'KEY_RESUME', 'KEY_RIGHT', 'KEY_SAVE', 'KEY_SBEG', 'KEY_SCANCEL', 'KEY_SCOMMAND', 'KEY_SCOPY', 'KEY_SCREATE', 'KEY_SDC', 'KEY_SDL', 'KEY_SELECT', 'KEY_SEND', 'KEY_SEOL', 'KEY_SEXIT', 'KEY_SF', 'KEY_SFIND', 'KEY_SHELP', 'KEY_SHOME', 'KEY_SIC', 'KEY_SLEFT', 'KEY_SMESSAGE', 'KEY_SMOVE', 'KEY_SNEXT', 'KEY_SOPTIONS', 'KEY_SPREVIOUS', 'KEY_SPRINT', 'KEY_SR', 'KEY_SREDO', 'KEY_SREPLACE', 'KEY_SRESET', 'KEY_SRIGHT', 'KEY_SRSUME', 'KEY_SSAVE', 'KEY_SSUSPEND', 'KEY_STAB', 'KEY_SUNDO', 'KEY_SUSPEND', 'KEY_UNDO', 'KEY_UP', 'OK', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__revision__', '_os', '_sys', 'baudrate', 'beep', 'can_change_color', 'cbreak', 'color_content', 'color_pair', 'curs_set', 'def_prog_mode', 'def_shell_mode', 'delay_output', 'doupdate', 'echo', 'endwin', 'erasechar', 'error', 'filter', 'flash', 'flushinp', 'getsyx', 'getwin', 'halfdelay', 'has_colors', 'has_ic', 'has_il', 'has_key', 'init_color', 'init_pair', 'initscr', 'intrflush', 'is_term_resized', 'isendwin', 'keyname', 'killchar', 'longname', 'meta', 'napms', 'newpad', 'newwin', 'nl', 'nocbreak', 'noecho', 'nonl', 'noqiflush', 'noraw', 'pair_content', 'pair_number', 'putp', 'qiflush', 'raw', 'reset_prog_mode', 'reset_shell_mode', 'resetty', 'resize_term', 'resizeterm', 'savetty', 'setsyx', 'setupterm', 'start_color', 'termattrs', 'termname', 'tigetflag', 'tigetnum', 'tigetstr', 'tparm', 'typeahead', 'unctrl', 'ungetch', 'use_default_colors', 'use_env', 'version', 'wrapper']
>>> vars(curses)
{'KEY_END': 360, 'tigetstr': <built-in function tigetstr>, 'KEY_SPRINT': 399, 'setupterm': <built-in function setupterm>, 'COLOR_YELLOW': 3, 'KEY_SSAVE': 404, 'newwin': <built-in function newwin>, 'KEY_SR': 337, 'KEY_F34': 298, 'KEY_F35': 299, 'KEY_F36': 300, 'has_key': <built-in function has_key>, 'use_default_colors': <built-in function use_default_colors>, 'KEY_F31': 295, 'KEY_F32': 296, 'KEY_F33': 297, 'KEY_COMMAND': 357, '__package__': 'curses', 'KEY_F38': 302, 'KEY_F39': 303, 'KEY_PPAGE': 339, 'color_content': <built-in function color_content>, 'resizeterm': <built-in function resizeterm>, 'KEY_UP': 259, 'flash': <built-in function flash>, 'cbreak': <built-in function cbreak>, 'savetty': <built-in function savetty>, 'KEY_MESSAGE': 365, 'KEY_SFIND': 389, 'KEY_BREAK': 257, 'A_COLOR': 66977792, 'COLOR_CYAN': 6, 'noqiflush': <built-in function noqiflush>, 'A_BOLD': 8192, 'KEY_DL': 328, 'KEY_MOVE': 366, 'KEY_DC': 330, '__file__': '/usr/pkg/lib/python2.7/curses/__init__.pyc', 'KEY_EOL': 335, 'color_pair': <built-in function color_pair>, 'noraw': <built-in function noraw>, 'KEY_SBEG': 378, 'KEY_EOS': 334, 'KEY_SCANCEL': 379, 'A_BLINK': 2048, 'keyname': <built-in function keyname>, 'erasechar': <built-in function erasechar>, 'OK': 0, 'use_env': <built-in function use_env>, '__path__': ['/usr/pkg/lib/python2.7/curses'], 'def_shell_mode': <built-in function def_shell_mode>, 'KEY_LL': 347, 'resetty': <built-in function resetty>, 'A_PROTECT': 32768, 'KEY_F37': 301, 'KEY_SEOL': 387, 'longname': <built-in function longname>, 'KEY_F30': 294, 'pair_number': <built-in function pair_number>, 'KEY_REFRESH': 373, 'KEY_F7': 271, 'KEY_UNDO': 408, 'A_INVIS': 16384, 'meta': <built-in function meta>, '_sys': <module 'sys' (built-in)>, 'resize_term': <built-in function resize_term>, 'KEY_F19': 283, 'KEY_F16': 280, 'KEY_F17': 281, 'KEY_F14': 278, 'A_REVERSE': 1024, 'KEY_F12': 276, 'KEY_F13': 277, 'KEY_F10': 274, 'KEY_F11': 275, 'getwin': <built-in function getwin>, 'flushinp': <built-in function flushinp>, 'KEY_F6': 270, 'A_DIM': 4096, 'KEY_F0': 264, 'KEY_F1': 265, 'KEY_F2': 266, 'KEY_F3': 267, 'termname': <built-in function termname>, 'KEY_F8': 272, 'KEY_F9': 273, 'KEY_BTAB': 353, 'KEY_CTAB': 341, 'version': '2.2', 'baudrate': <built-in function baudrate>, 'pair_content': <built-in function pair_content>, 'is_term_resized': <built-in function is_term_resized>, 'A_UNDERLINE': 512, 'KEY_CLOSE': 356, 'KEY_SREPLACE': 401, 'KEY_SHOME': 391, '__builtins__': {'bytearray': <type 'bytearray'>, 'IndexError': <type 'exceptions.IndexError'>, 'all': <built-in function all>, 'help': Type help() for interactive help, or help(object) for help about object., 'vars': <built-in function vars>, 'SyntaxError': <type 'exceptions.SyntaxError'>, 'unicode': <type 'unicode'>, 'UnicodeDecodeError': <type 'exceptions.UnicodeDecodeError'>, 'memoryview': <type 'memoryview'>, 'isinstance': <built-in function isinstance>, 'copyright': Copyright (c) 2001-2020 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'NameError': <type 'exceptions.NameError'>, 'BytesWarning': <type 'exceptions.BytesWarning'>, 'dict': <type 'dict'>, 'input': <built-in function input>, 'oct': <built-in function oct>, 'bin': <built-in function bin>, 'SystemExit': <type 'exceptions.SystemExit'>, 'StandardError': <type 'exceptions.StandardError'>, 'format': <built-in function format>, 'repr': <built-in function repr>, 'sorted': <built-in function sorted>, 'False': False, 'RuntimeWarning': <type 'exceptions.RuntimeWarning'>, 'list': <type 'list'>, 'iter': <built-in function iter>, 'reload': <built-in function reload>, 'Warning': <type 'exceptions.Warning'>, '__package__': None, 'round': <built-in function round>, 'dir': <built-in function dir>, 'cmp': <built-in function cmp>, 'set': <type 'set'>, 'bytes': <type 'str'>, 'reduce': <built-in function reduce>, 'intern': <built-in function intern>, 'issubclass': <built-in function issubclass>, 'Ellipsis': Ellipsis, 'EOFError': <type 'exceptions.EOFError'>, 'locals': <built-in function locals>, 'BufferError': <type 'exceptions.BufferError'>, 'slice': <type 'slice'>, 'FloatingPointError': <type 'exceptions.FloatingPointError'>, 'sum': <built-in function sum>, 'getattr': <built-in function getattr>, 'abs': <built-in function abs>, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, 'print': <built-in function print>, 'True': True, 'FutureWarning': <type 'exceptions.FutureWarning'>, 'ImportWarning': <type 'exceptions.ImportWarning'>, 'None': None, 'hash': <built-in function hash>, 'ReferenceError': <type 'exceptions.ReferenceError'>, 'len': <built-in function len>, 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'frozenset': <type 'frozenset'>, '__name__': '__builtin__', 'ord': <built-in function ord>, 'super': <type 'super'>, '_': None, 'TypeError': <type 'exceptions.TypeError'>, 'license': Type license() to see the full license text, 'KeyboardInterrupt': <type 'exceptions.KeyboardInterrupt'>, 'UserWarning': <type 'exceptions.UserWarning'>, 'filter': <built-in function filter>, 'range': <built-in function range>, 'staticmethod': <type 'staticmethod'>, 'SystemError': <type 'exceptions.SystemError'>, 'BaseException': <type 'exceptions.BaseException'>, 'pow': <built-in function pow>, 'RuntimeError': <type 'exceptions.RuntimeError'>, 'float': <type 'float'>, 'MemoryError': <type 'exceptions.MemoryError'>, 'StopIteration': <type 'exceptions.StopIteration'>, 'globals': <built-in function globals>, 'divmod': <built-in function divmod>, 'enumerate': <type 'enumerate'>, 'apply': <built-in function apply>, 'LookupError': <type 'exceptions.LookupError'>, 'open': <built-in function open>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'basestring': <type 'basestring'>, 'UnicodeError': <type 'exceptions.UnicodeError'>, 'zip': <built-in function zip>, 'hex': <built-in function hex>, 'long': <type 'long'>, 'next': <built-in function next>, 'ImportError': <type 'exceptions.ImportError'>, 'chr': <built-in function chr>, 'xrange': <type 'xrange'>, 'type': <type 'type'>, '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", 'Exception': <type 'exceptions.Exception'>, 'tuple': <type 'tuple'>, 'UnicodeTranslateError': <type 'exceptions.UnicodeTranslateError'>, 'reversed': <type 'reversed'>, 'UnicodeEncodeError': <type 'exceptions.UnicodeEncodeError'>, 'IOError': <type 'exceptions.IOError'>, 'hasattr': <built-in function hasattr>, 'delattr': <built-in function delattr>, 'setattr': <built-in function setattr>, 'raw_input': <built-in function raw_input>, 'SyntaxWarning': <type 'exceptions.SyntaxWarning'>, 'compile': <built-in function compile>, 'ArithmeticError': <type 'exceptions.ArithmeticError'>, 'str': <type 'str'>, 'property': <type 'property'>, 'GeneratorExit': <type 'exceptions.GeneratorExit'>, 'int': <type 'int'>, '__import__': <built-in function __import__>, 'KeyError': <type 'exceptions.KeyError'>, 'coerce': <built-in function coerce>, 'PendingDeprecationWarning': <type 'exceptions.PendingDeprecationWarning'>, 'file': <type 'file'>, 'EnvironmentError': <type 'exceptions.EnvironmentError'>, 'unichr': <built-in function unichr>, 'id': <built-in function id>, 'OSError': <type 'exceptions.OSError'>, 'DeprecationWarning': <type 'exceptions.DeprecationWarning'>, 'min': <built-in function min>, 'UnicodeWarning': <type 'exceptions.UnicodeWarning'>, 'execfile': <built-in function execfile>, 'any': <built-in function any>, 'complex': <type 'complex'>, 'bool': <type 'bool'>, 'ValueError': <type 'exceptions.ValueError'>, 'NotImplemented': NotImplemented, 'map': <built-in function map>, 'buffer': <type 'buffer'>, 'max': <built-in function max>, 'object': <type 'object'>, 'TabError': <type 'exceptions.TabError'>, 'callable': <built-in function callable>, 'ZeroDivisionError': <type 'exceptions.ZeroDivisionError'>, 'eval': <built-in function eval>, '__debug__': True, 'IndentationError': <type 'exceptions.IndentationError'>, 'AssertionError': <type 'exceptions.AssertionError'>, 'classmethod': <type 'classmethod'>, 'UnboundLocalError': <type 'exceptions.UnboundLocalError'>, 'NotImplementedError': <type 'exceptions.NotImplementedError'>, 'AttributeError': <type 'exceptions.AttributeError'>, 'OverflowError': <type 'exceptions.OverflowError'>}, 'KEY_RESET': 345, 'halfdelay': <built-in function halfdelay>, 'KEY_SELECT': 385, 'KEY_HOME': 262, 'KEY_F63': 327, '__name__': 'curses', 'KEY_F61': 325, 'KEY_F60': 324, 'init_color': <built-in function init_color>, 'setsyx': <built-in function setsyx>, 'has_colors': <built-in function has_colors>, 'KEY_CATAB': 342, 'KEY_SRSUME': 403, 'KEY_SOPTIONS': 397, 'COLOR_WHITE': 7, 'KEY_F25': 289, 'KEY_SUSPEND': 407, 'filter': <built-in function filter>, 'getsyx': <built-in function getsyx>, 'isendwin': <built-in function isendwin>, 'tigetnum': <built-in function tigetnum>, 'tigetflag': <built-in function tigetflag>, 'KEY_F23': 287, 'has_ic': <built-in function has_ic>, 'KEY_F21': 285, 'ERR': -1, 'KEY_F4': 268, 'curs_set': <built-in function curs_set>, 'has_il': <built-in function has_il>, 'echo': <built-in function echo>, 'KEY_IL': 329, 'KEY_RESIZE': 512, 'KEY_CANCEL': 355, 'KEY_SRESET': 344, 'KEY_COPY': 358, 'A_ALTCHARSET': 65536, 'KEY_IC': 331, 'initscr': <function initscr at 0x7381a7b0>, 'unctrl': <built-in function unctrl>, '__revision__': '$Id$', 'putp': <built-in function putp>, 'KEY_F62': 326, 'COLOR_RED': 1, 'COLOR_BLACK': 0, 'wrapper': <function wrapper at 0x7381a830>, 'beep': <built-in function beep>, 'KEY_RESTART': 375, 'KEY_SDC': 383, 'KEY_F29': 293, 'can_change_color': <built-in function can_change_color>, 'KEY_BACKSPACE': 263, 'KEY_SEXIT': 388, '__doc__': 'curses\n\nThe main package for curses support for Python.  Normally used by importing\nthe package, and perhaps a particular module inside it.\n\n   import curses\n   from curses import textpad\n   curses.initscr()\n   ...\n\n', 'KEY_F18': 282, 'KEY_F45': 309, 'KEY_F44': 308, 'KEY_F47': 311, 'KEY_F46': 310, 'KEY_F41': 305, 'KEY_MARK': 364, 'KEY_F43': 307, 'KEY_F42': 306, 'KEY_SSUSPEND': 405, 'napms': <built-in function napms>, 'KEY_F48': 312, 'KEY_FIND': 362, 'KEY_NEXT': 367, 'KEY_PRINT': 346, 'KEY_PREVIOUS': 370, 'termattrs': <built-in function termattrs>, 'KEY_DOWN': 258, 'doupdate': <built-in function doupdate>, 'COLOR_BLUE': 4, '_os': <module 'os' from '/usr/pkg/lib/python2.7/os.pyc'>, 'KEY_SCREATE': 382, 'KEY_SDL': 384, 'nonl': <built-in function nonl>, 'KEY_SRIGHT': 402, 'start_color': <function start_color at 0x7381a870>, 'A_STANDOUT': 256, 'KEY_SHELP': 390, 'KEY_A1': 348, 'KEY_SNEXT': 396, 'KEY_A3': 349, 'error': <class '_curses.error'>, 'qiflush': <built-in function qiflush>, 'tparm': <built-in function tparm>, 'KEY_F52': 316, 'KEY_F53': 317, 'KEY_F50': 314, 'KEY_F51': 315, 'KEY_F56': 320, 'KEY_F57': 321, 'KEY_CLEAR': 333, 'KEY_F55': 319, 'KEY_SUNDO': 406, 'KEY_SCOPY': 381, 'KEY_F58': 322, 'KEY_F59': 323, 'killchar': <built-in function killchar>, 'def_prog_mode': <built-in function def_prog_mode>, 'KEY_REDO': 371, 'raw': <built-in function raw>, 'typeahead': <built-in function typeahead>, 'KEY_MIN': 257, 'ungetch': <built-in function ungetch>, 'KEY_SPREVIOUS': 398, 'KEY_F40': 304, 'reset_shell_mode': <built-in function reset_shell_mode>, 'KEY_SEND': 386, 'KEY_ENTER': 343, 'init_pair': <built-in function init_pair>, 'endwin': <built-in function endwin>, 'KEY_F54': 318, 'A_CHARTEXT': 255, 'COLOR_MAGENTA': 5, 'nocbreak': <built-in function nocbreak>, 'KEY_SMESSAGE': 394, 'KEY_MAX': 576, 'KEY_RIGHT': 261, 'KEY_B2': 350, 'delay_output': <built-in function delay_output>, 'A_NORMAL': 0, 'KEY_BEG': 354, 'KEY_EXIT': 361, 'KEY_SF': 336, 'KEY_SMOVE': 395, 'COLOR_GREEN': 2, 'KEY_SLEFT': 393, 'KEY_F5': 269, 'KEY_F49': 313, 'KEY_RESUME': 376, 'KEY_F27': 291, 'KEY_OPTIONS': 369, 'KEY_NPAGE': 338, 'KEY_F24': 288, 'KEY_F15': 279, 'KEY_F22': 286, 'KEY_EIC': 332, 'KEY_F20': 284, 'KEY_STAB': 340, 'nl': <built-in function nl>, 'KEY_SCOMMAND': 380, 'KEY_F28': 292, 'KEY_OPEN': 368, 'intrflush': <built-in function intrflush>, 'KEY_REPLACE': 374, 'KEY_SAVE': 377, 'KEY_CREATE': 359, 'A_ATTRIBUTES': 67108608, 'KEY_SREDO': 400, 'KEY_MOUSE': 409, 'KEY_REFERENCE': 372, 'KEY_F26': 290, 'newpad': <built-in function newpad>, 'noecho': <built-in function noecho>, 'reset_prog_mode': <built-in function reset_prog_mode>, 'KEY_HELP': 363, 'KEY_LEFT': 260, 'KEY_SIC': 392, 'KEY_C3': 352, 'KEY_C1': 351}
>>> 

#### Possible Solutions
N/A
#### Steps to reproduce
1. Install NetBSD9.1 on OrangePi Zero ARM board, install stock python2.7, pip2.7 install ranger-fm.
2. issue command: ranger
3. 

#### Traceback

```
Traceback (most recent call last):
  File "./ranger.py", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/home/orange/Projects/ranger/ranger/core/main.py", line 36, in main
    from ranger.core.fm import FM
  File "/home/orange/Projects/ranger/ranger/core/fm.py", line 22, in <module>
    from ranger.gui.ui import UI
  File "/home/orange/Projects/ranger/ranger/gui/ui.py", line 19, in <module>
    from .mouse_event import MouseEvent
  File "/home/orange/Projects/ranger/ranger/gui/mouse_event.py", line 9, in <module>
    class MouseEvent(object):
  File "/home/orange/Projects/ranger/ranger/gui/mouse_event.py", line 12, in MouseEvent
    curses.BUTTON1_PRESSED,
AttributeError: 'module' object has no attribute 'BUTTON1_PRESSED'

```

**Comment by toonn** [comment]
Hmm, does the error change if you have a mouse plugged in when starting ranger?

**Comment by arnyekveto** [comment]
Hi, I cannot access the machine. :-(

**Comment by toonn** [comment]
: / Then I think we need someone who's familiar with curses on such platforms or somebody with access to such a device so we can have them test things and slowly figure it out.

**Comment by arnyekveto** [comment]
Hi, I managed to start ranger on the same box, though... I did rewrite of every mouse related function in two files:
gui/mouse_event.py
gui/ui.py
to pass or return False, doing so to avoid calling/reading/writing curses.BUTTONX_Y stuff.
So ranger runs now, though, the display have major issues, it is black-and-white with occasional blinking and underlined text, the layout is totally fallen apart.

ranger-fm runs without any error message though.

Something is major incompatible in NetBSD's curses implementation.

NetBSD.earmv7hf::orange@OrangePi0:~$ ranger --version
ranger version: ranger 1.9.3
Python version: 2.7.18 (default, Jun 22 2020, 15:44:08) [GCC 7.4.0]
Locale: None.None

NetBSD.earmv7hf::orange@OrangePi0:~$ echo $TERM
xterm-256color

![netbsd-ranger-fm](https://user-images.githubusercontent.com/24780550/108758372-4f65ca00-754b-11eb-8597-7f69291e4f5a.gif)

[netbsd.mod.ranger.zip](https://github.com/ranger/ranger/files/6024628/netbsd.mod.ranger.zip)

**Comment by toonn** [comment]
Hmm, do other ncurses-based programs exhibit similar problems, like midnight commander for example?

**Comment by arnyekveto** [comment]
mc runs nicely on the target machine, when I ssh into I can use my mouse with mc.

**Comment by arnyekveto** [comment]
I found the stock unit test under libs:
NetBSD.earmv7hf::orange@OrangePi0:/usr/pkg/lib/python2.7/test$ pwd
/usr/pkg/lib/python2.7/test
NetBSD.earmv7hf::orange@OrangePi0:/usr/pkg/lib/python2.7/test$ python2.7 test_curses.py
......
.s
.
.
.
.
.
.
.
.
.
.
.
.
.
.
----------------------------------------------------------------------
Ran 22 tests in 2.583s

OK (skipped=1)

It runs.

Inside the file the header part is quite weird:
 Test script for the curses module
#
# This script doesn't actually display anything very coherent. but it
# does call (nearly) every method and function.
#
# Functions not tested: {def,reset}_{shell,prog}_mode, getch(), getstr(),
# init_color()
# Only called, not tested: getmouse(), ungetmouse()

Whatever, it does not throw errors related to curses.BUTTON


[test_curses.zip](https://github.com/ranger/ranger/files/6028864/test_curses.zip)

**Comment by toonn** [comment]
Don't know of any python curses programs maybe you can find some on [the cheeseshop](https://pypi.org/)?

**Comment by arnyekveto** [comment]
I will look around, definitely. Though NetBSD just irks me now. :-) I managed to run ranger on so many OS, like linuxes (fedora, ubuntu, debian, centos), FreeBSD, HaikuOS without any issue...
