### ISSUE TITLE
My ranger reported this wrong ,but can run with env LC_ALL=en_US.UTF-8 ranger --clean

### ISSUE THREAD

**Issue by thaoeu** [ranger/ranger#2250]
ranger version: ranger-master 
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 173, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 126, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.9/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.9/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

    Operating system and version: Manjaro
    Terminal emulator and version: Konsole&st
    Python version: Python version: 3.9.1
    Ranger version/commit: 1.9.3.143.g5047d9e5-1 
    
I tried to reinstall and empty the ranger directory ,but still can't work.

In addition, use` env LC_ALL=en_US.UTF-8 ranger --clean `to run.

**Comment by toonn** [comment]
Bookmarks may not be kept in the config directory. Check `${XDG_DATA_HOME:-~/.local/share}/ranger`.

**Comment by toonn** [comment]
Sounds like #2007, so I'm closing this in favor of that issue.
