### ISSUE TITLE
Ranger crashed. I guess the command ":find" can't handle the case where the query result doesn't exist.

### ISSUE THREAD

**Issue by RolfMa** [ranger/ranger#2253]
#### Runtime Environment

- Operating system and version: manjaro latest
- Terminal emulator and version: zsh 5.8
- Python version: 3.9.1
- Ranger version/commit: ranger master
- Locale: en_US.UTF-8

#### Steps to reproduce
1. Start ranger.
2. Press f.
3. Input a name of an empty directory.

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1520, in execute
    self.fm.move(right=1)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
This was fixed in #2072.
