### ISSUE TITLE
Ranger crashed

### ISSUE THREAD

**Issue by CallumBaston** [ranger/ranger#2258]
#### Runtime Environment

- Operating system and version: Arch Linux, Latest
- Terminal emulator and version: xterm, Latest
- Python version: 3.9.1
- Ranger version/commit: 1.9.3
- Locale: en_GB.UTF-8

#### Current Behavior
Ranger Crashes
#### Expected Behavior
Ranger allows me to explore files
#### Steps to reproduce
1. Mount SD card as root to /mnt/usb
2. Type the command 'ranger /mnt/usb'
3. Ranger crashes

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.9.1 (default, Feb  6 2021, 06:49:13) [GCC 10.2.0]
Locale: en_GB.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by chu4ng** [comment]
I think it's #2072 problem.
Can you to clone master branch and check again?

**Comment by CallumBaston** [comment]
Cloned from master. Same steps same problem.

ranger version: ranger-master v1.9.3-187-g20cc5e86
Python version: 3.9.1 (default, Feb  6 2021, 06:49:13) [GCC 10.2.0]
Locale: en_GB.UTF-8

Traceback (most recent call last):
  File "/home/baston/gitlab/ranger/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/home/baston/gitlab/ranger/ranger/core/fm.py", line 376, in loop
    ui.redraw()
  File "/home/baston/gitlab/ranger/ranger/gui/ui.py", line 344, in redraw
    self.finalize()
  File "/home/baston/gitlab/ranger/ranger/gui/ui.py", line 401, in finalize
    DisplayableContainer.finalize(self)
  File "/home/baston/gitlab/ranger/ranger/gui/displayable.py", line 265, in finalize
    displayable.finalize()
  File "/home/baston/gitlab/ranger/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by toonn** [comment]
No, this is a different problem. Passing a path is currently broken.

**Comment by CallumBaston** [comment]
Ah, I'll just close this and wait for a fix on release.
