### ISSUE TITLE
ranger crashes when using :find

### ISSUE THREAD

**Issue by Schurick** [ranger/ranger#2270]
#### Runtime Environment
- Operating system and version: Manjaro Linux, KDE-Plasma 5.21.1, 64-bit
- Terminal emulator and version: Xfce 4.16

#### Steps to reproduce
1. Press 'f'
2. Press any letters (crashes sometime at first, second or third letter, respectively)

#### Traceback
ranger version: ranger-master 
Python version: 3.9.1 (default, Feb  6 2021, 06:49:13) [GCC 10.2.0]
Locale: de_DE.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1520, in execute
    self.fm.move(right=1)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by miku86** [comment]
Seems to be the same issue like #2269.

**Comment by Schurick** [comment]
> Seems to be the same issue like #2269.

Yes, but in my case it occurs by pressing any key, not only 'V'.

**Comment by toonn** [comment]
I believe this was fixed in #2058, could you check whether the problem occurs on master?

**Comment by Schurick** [comment]
> I believe this was fixed in #2058, could you check whether the problem occurs on master?

Problem does not occur in master-branch. Thanks.
