### ISSUE TITLE
Ranger crashes while opening directory containg pictyre with ueberzug as preview method

### ISSUE THREAD

**Issue by yagarea** [ranger/ranger#2278]
#### Runtime Environment

- Operating system and version: Linux arch-thinkpad 5.11.6-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux
- Terminal emulator and version: alacritty 0.7.2 (5ac8060b)
- Python version: Python 3.9.2
- Ranger version/commit: ranger version: ranger 1.9.3
- Locale: fish

#### Current Behavior
Crashed

#### Expected Behavior
Not crash

#### Context
I get this error when opening directory containng photos.

#### Possible Solutions
make it not crash. I use ueberzug as preview method.

#### Steps to reproduce
open `ranger ~/Pictures`

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException
```

**Comment by toonn** [comment]
Python 3.9 somehow made the `IMAGE_DISPLAYER_REGISTRY` very flaky but I don't know why.

**Comment by yagarea** [comment]
I don't know if someone did anything with this but it works now  on my machine.
