### ISSUE TITLE
Ranger crashed

### ISSUE THREAD

**Issue by zuntik** [ranger/ranger#2289]
#### Runtime Environment

- Operating system and version: Archlinux up to date
- Terminal emulator and version: Konsole 20.12.13
- Python version: 3.9.2
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Context

I think I was in the tasks window. There were lots of tasks listed, I think. but it crashed too quickly.

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Locale: en_US.UTF-8
Current file: not gonna say
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/taskview.py", line 74, in finalize
    self.fm.ui.win.move(y, self.x)
_curses.error: wmove() returned ERR
```

**Comment by toonn** [comment]
Hmm, this traceback isn't very enlightening. Do report back if you manage to reproduce this.

**Comment by jk121960** [comment]
Hi, I crashed too, but this was arbitrarily on different "filters" I was filtering for the word toolbox and it would crash on the "t" but in other directories the "t" was fine, by the looks of the error it looks like it is crashing when the filter is not found with an out of range index

Trace 
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1545, in quick
    self.fm.thisdir.refilter()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range
```

**Comment by toonn** [comment]
@jk121960, please don't hijack unrelated issues. Feel free to open a new one. Your error looks like something that was fixed on the master branch so try cloning the repo and simply running ranger from there, no need to install even.

**Comment by jk121960** [comment]
Sorry, Ok thanks

Gerald Klein DBA

***@***.***

***@***.***

708-599-0352


The Manual said install Windows 10 or better so I installed Linux


Arch, Gentoo I3, Ranger & Vim the coding triple threat.

Linux registered user #548580

Brought to you by the Amish Mafia
