### ISSUE TITLE
Crash when running 'ranger file'

### ISSUE THREAD

**Issue by leofah** [ranger/ranger#2294]
#### Runtime Environment

- Operating system and version: Archlinux with Kernel 5.11.10-arch1-1 (up to date)
- Terminal emulator and version: alacritty 0.7.2 (5ac8060b)
- Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
- Ranger version/commit: 1.9.3
- Locale: n_US.UTF-8

#### Current Behavior

Running ```$ ranger file``` crashes ranger with any file.

#### Expected Behavior

According to the man page ranger should open with the file selected.
```      path ...      Each path will be opened in a tab and if the path is a file it will be selected.  Omitting this is equivalent to providing the current directory.```

#### Context

The Issue has no real problem. One could just open the directory and then navigate to the file. However the behavior is different than written in the documentation.

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'
```

**Comment by toonn** [comment]
This is a known issue. Could you try to find the existing issue so they can be linked?

**Comment by zneix** [comment]
I wanted to report the same issue on the same setup as issue author, but with a little bit different traceback
```ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Locale: en_GB.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/titlebar.py", line 42, in draw
    self._calc_bar()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/titlebar.py", line 82, in _calc_bar
    self._get_left_part(bar)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/titlebar.py", line 106, in _get_left_part
    and (self.fm.thisdir.path.startswith(self.fm.home_path + "/")
AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by leofah** [comment]
Similar Traceback as in #2211. Same Problem as in #1905 #1832 #1386 and maybe more.
