### ISSUE TITLE
ranger don't start on AIX

### ISSUE THREAD

**Issue by arozehnal** [ranger/ranger#2341]
#### Runtime Environment

- Operating system and version: AIX 7.1
- Terminal emulator and version: vt320
- Python version: 3.7
- Ranger version/commit:  1.9.3
- Locale:  LANG=cs_CZ

Installed from clone -> make install 
finished OK
then running 'ranger'

crashed during start

ranger version: ranger-master v1.9.3-145-g521d9f89
Python version: 3.7.6 (default, Feb 28 2020, 04:49:11) [GCC 8.3.0]
Locale: cs_CZ.ISO8859-2
 
Traceback (most recent call last):
  File "/work/RO/ranger/ranger/core/main.py", line 173, in main
    fm.initialize()
  File "/work/RO/ranger/ranger/core/fm.py", line 131, in initialize
    self.ui.initialize()
  File "/work/RO/ranger/ranger/gui/ui.py", line 119, in initialize
    curses.use_default_colors()
AttributeError: module 'curses' has no attribute 'use_default_colors'

I have installed RPM ncurses-6.2-1.ppc
[install_log.txt](https://github.com/ranger/ranger/files/6564031/install_log.txt)

**Comment by chu4ng** [comment]
I have ncurses 6.2-2, but `python -c "import curses; print(curses.version)"` give me "2.2" version.
Can you see version curses from python?

Also from [docs](https://docs.python.org/3/library/curses.html#module-curses):
> While curses is most widely used in the Unix environment, versions are available for Windows, DOS, and possibly other systems as well. This extension module is designed to match the API of ncurses, an open-source curses library hosted on Linux and the BSD variants of Unix.

**Comment by arozehnal** [comment]
Hmm, maybe there will be a some problem...

I have installed this versions of Python:
Python 2.7.18
Python 3.7.6

python -c "import curses; print(curses.version)"
2.2

python3 -c "import curses; print(curses.version)"
b'2.2'

rpm -qa|grep curses
ncurses-6.2-1.ppc

according to install_log.txt ranger was installed as 'python3 modul'.
So, I first try to run 'python3 ./ranger.py'
It ended in an error (see above).
But the same error is printed when I run  'python ./ranger.py'.

I'm sorry, I'm newbie to Python, but I have experienced that porting open source on AIX is sometimes difficult  :-(

Any suggestion?

**Comment by toonn** [comment]
Hmm, the curses documentation doesn't even mention that function being new from a certain version. So I don't understand how it could be missing. Maybe AIX ncurses doesn't support the underlying function?

Have you tried other python programs that use curses? Don't know of good examples.
