### ISSUE TITLE
ranger via ssh

### ISSUE THREAD

**Issue by dugres** [ranger/ranger#2348]
#### Steps to reproduce
1. ssh to host
2. launch ranger

#### Traceback
```
ranger version: ranger 1.9.3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/lib/python3.7/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/local/lib/python3.7/dist-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/local/lib/python3.7/dist-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/local/lib/python3.7/dist-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/local/lib/python3.7/dist-packages/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'
```

**Comment by miku86** [comment]
Which OS do you use?

Because your Python version looks old.

```
> ranger --version
ranger version: ranger 1.9.3
Python version: 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
Locale: en_GB.UTF-8
```

**Comment by toonn** [comment]
3.7 should be fine. Could you try running the master branch, this error is familiar?
Ranger doesn't have any problems with running on the other side of an ssh connection ime.

**Comment by dugres** [comment]
I'm using Debian 10

**Comment by toonn** [comment]
Did you try running ranger from the master branch?
