### ISSUE TITLE
Ranger crash from under root in byobu

### ISSUE THREAD

**Issue by vladimir-se** [ranger/ranger#2359]
If run ranger in byobu from root session him crash with error:

```
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
Locale: ru_RU.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3/dist-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] : 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
How fix this? Thnx!

**Comment by toonn** [comment]
I think this was fixed on the master branch, could you try running that?

**Comment by vladimir-se** [comment]
Everything works, thank you!
