### ISSUE TITLE
Add a human-readable hint to the ImgDisplayUnsupportedException

### ISSUE THREAD

**Issue by danielcieslinski** [ranger/ranger#2373]
Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ImgDisplayUnsupportedException

**Comment by toonn** [comment]
Without any context there's no way I can help you.

**Comment by danielcieslinski** [comment]
It was an error with the image preview configuration. I suggest adding comment to the exception,  to check the rc.conf file

**Comment by toonn** [comment]
That's a reasonable suggestion : )
So I take it you typoed a preview method?

**Comment by danielcieslinski** [comment]
I had it set to `mpv`, change to `kitty`, as it's the one that I wanna use anyway.

**Comment by toonn** [comment]
@danielcieslinski, could you test PR #2375? Feel free to make suggestions to improve it further.
