### ISSUE TITLE
Error on plugin ranger_devicons

### ISSUE THREAD

**Issue by Coldivy** [ranger/ranger#2374]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 433, in load_settings
    fobj = open(fm.confpath('plugins', '__init__.py'), 'w')
PermissionError: [Errno 13] Permission denied: '/home/coldivy/.config/ranger/plugins/__init__.py'

**Comment by toonn** [comment]
Problems with plugins should be reported on the plugin's issue tracker.
This seems like a problem with the permissions in your `.config/ranger` directory though. Should be fine to run `chmod u+w -R ~/.config/ranger`.
