### ISSUE TITLE
scout index error crash

### ISSUE THREAD

**Issue by basaran** [ranger/ranger#2380]
#### Runtime Environment
- Operating system and version: 
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.0.7
Codename:       Ornara
- Terminal emulator and version: alacritty 0.8.0 (a1b13e68)
- Python version: Python 3.9.5
- Ranger version/commit: 
ranger version: ranger-master
Python version: 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
- Locale:  en_US.UTF-8

#### Current Behavior
on any filter, execute command: `scout -ipt` and after typing a few characters it would sometimes crash with:

might be related to https://github.com/ranger/ranger/issues/2125

#### Traceback

```
ranger version: ranger-master
Python version: 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1545, in quick
    self.fm.thisdir.refilter()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range
```

**Comment by chu4ng** [comment]
Can you post your `/usr/lib/python3.9/site-packages/ranger/core/tab.py`? (70-75 lines are enough)
I think we already handle this error.

**Comment by toonn** [comment]
Yeah, this looks like it was fixed on master. Could you try running that to verify?

**Comment by basaran** [comment]
Hello, here it is:

```
    def _set_pointer(self, value):
        self._pointer = value
        self._pointed_obj = self.thisdir.files[self._pointer]

    pointer = property(_get_pointer, _set_pointer)
```

**Comment by chu4ng** [comment]
@basaran 
That's it. Now we have https://github.com/ranger/ranger/blob/8181077f3b0afc7b6258a85d3a03b7bce23d316c/ranger/core/tab.py#L70-L75
Just update your ranger to the master-branch.

**Comment by toonn** [comment]
Fixed on master.
