### ISSUE TITLE
Ranger crashes in root account.

### ISSUE THREAD

**Issue by reallyohwell** [ranger/ranger#2384]
ranger --version
ranger version: ranger 1.9.3
Python version: 3.9.5 (default, Jun 14 2021, 10:43:55) [GCC 10.3.0]
Locale: en_US.UTF-8

Gentoo linux: 5.10.27-gentoo
xfce4-terminal

python --version
Python 3.9.5

Ranger works in my own account. But when I su into another account, I get this:
ranger
ranger version: ranger 1.9.3
Python version: 3.9.5 (default, Jun 14 2021, 10:43:55) [GCC 10.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.9/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

NOTE: This happens when I am running tmux. With xfce4-terminal and no tmux, it does not crash.
Interestingly it does not crash in my usual home account, inside tmux. 

```

**Comment by toonn** [comment]
I think this is fixed on master, could you check?

**Comment by Oxore** [comment]
I've encountered with the same issue on 1.9.3 from Gentoo Linux repository.

I confirm that this is fixed on master. The exact version is `ranger-master v1.9.3-387-g7e6a0aa6`.
