### ISSUE TITLE
Sporadic crashes 

### ISSUE THREAD

**Issue by acampove** [ranger/ranger#2390]
#### Runtime Environment

- Operating system and version: Linux linux 5.11.4-1-rt11-MANJARO #1 SMP Fri May 21 00:10:17 CEST 2021 x86_64 GNU/Linux
- Terminal emulator and version: kitty 0.20.3 created by Kovid Goyal
- Python version: 3.9.5
- Ranger version/commit: ranger-master 
- Locale: en_HK.UTF-8

#### Current Behavior
Crashes

#### Expected Behavior
Should not crash

#### Steps to reproduce
1. Open ranger
2. Work with ranger, use previews with PNG files.
3. It might crash eventually

#### Traceback

```
ranger version: ranger-master 
Python version: 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
Locale: en_HK.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 271, in handle_input
    self.handle_mouse()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 188, in click
    if DisplayableContainer.click(self, event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 81, in click
    self.fm.move_parent(direction)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 560, in move_parent
    self.thistab.enter_dir(parent.files[parent.pointer + n])
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
```

**Comment by chu4ng** [comment]
I'm not sure it is master-branch.
We have:
https://github.com/ranger/ranger/blob/8181077f3b0afc7b6258a85d3a03b7bce23d316c/ranger/core/tab.py#L70-L75
So there is no way to crash on this line by TypeError.

**Comment by acampove** [comment]
Yeah, you are right, I see that I went out of master to a specific branch:

![image](https://user-images.githubusercontent.com/14037062/125274937-0323f680-e341-11eb-9548-21635f471cf9.png)
