### ISSUE TITLE
Crash after specific key presses

### ISSUE THREAD

**Issue by HoolaBoola** [ranger/ranger#2407]
Steps to reproduce:

1. Open ranger
2. Press "f"
3. Enter ".l" (lowercase L, though seems to happen no matter which letter)

Ranger should continue to work, but instead crashes.

Here is the traceback:

```
ranger version: ranger-master 
Python version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1545, in quick
    self.fm.thisdir.refilter()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range
```

**Comment by toonn** [comment]
Can you test the master branch, I believe this has been fixed?

**Comment by HoolaBoola** [comment]
Thanks, tested. Does appear to be fixed.

Closing the issue

**Comment by toonn** [comment]
Thank you!
