### ISSUE TITLE
Ranger mouse crash on empty folder

### ISSUE THREAD

**Issue by luanrivello** [ranger/ranger#2421]
#### Runtime Environment
- Operating system and version: Manjaro Linux
- Terminal emulator and version: kitty 0.22.2
- ranger version: ranger-master 
- Python version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
- Locale: en_US.UTF-8

#### Current Behavior
Using the mouse to open an empty foulder causes it to crash

#### Expected Behavior
Using the mouse to open an empty folder should enter it

#### Context
I clicked to focus on the terminal and it crashed

#### Steps to reproduce
1. run ranger
2. click with the mouse to open an empty folder on the right hand side

#### Traceback
```
ranger version: ranger-master 
Python version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 271, in handle_input
    self.handle_mouse()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 188, in click
    if DisplayableContainer.click(self, event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 86, in click
    self.fm.enter_dir(self.target.path)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 585, in enter_dir
    result = self.thistab.enter_dir(path, history=history)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range
```

**Comment by toonn** [comment]
This sounds very similar to an issue that was fixed on the master branch. Could you test that? (I know your version reports as "ranger-master" but that doesn't mean it's a recent enough checkout of master.)

**Comment by luanrivello** [comment]
I manually installed the most recent version and its solved the problem.
