### ISSUE TITLE
[minor] crash if invalid preview_images_method in config

### ISSUE THREAD

**Issue by pirate486743186** [ranger/ranger#2424]
Just set preview_images_method to something random. Ranger will crash on start up,

it should have done something more graceful. It should have complained that the setting is invalid. Then,either fallback to something else of not start.

**Comment by toonn** [comment]
Hmm, I do get a custom error:

```
Traceback (most recent call last):
  File "/Users/toonn/src/ranger/ranger/core/main.py", line 172, in main
    fm.initialize()
  File "/Users/toonn/src/ranger/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/Users/toonn/src/ranger/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/Users/toonn/src/ranger/ranger/ext/img_display.py", line 107, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/Users/toonn/src/ranger/ranger/ext/img_display.py", line 87, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException: "invalid" does not appear to be a valid setting for preview_images_method.
```

We don't have a good method to fall back to, really, but I'm open to suggestions.
