### ISSUE TITLE
I can't enable the preview.

### ISSUE THREAD

**Issue by counter-attack-me2me** [ranger/ranger#2429]
#### Runtime Environment

- Operating system and version: 
1. VirtualBox version：6.1.22 r144080 (Qt5.6.2)
2. ubuntu Virtual machine version
```bash

a@a-virtualbox:~/Desktop$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

3. docker version （installed in the ubuntu Virtual machine）
```bash
a@a-virtualbox:~/Desktop$ docker -v
Docker version 20.10.7, build f0df350
```
4. docker image information：
I pulled the image by `docker pull dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt` and developed based on it.
5. docker ubuntu image version

```bash
$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
```
- Terminal emulator and version: 
  1. ubuntu Virtual machine terminal emulator version
    1.`QTerminal 0.14.1`
        2.
        ```bash
        a@a-virtualbox:~/Desktop$ bash --version
        bash --version
        GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
        Copyright (C) 2019 Free Software Foundation, Inc.
        License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
        This is free software; you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.
        ```
  2. docker image terminal emulator version
    1.`Guake 3.6.3`
    2.$ tmux -V
    `tmux 3.0a`
    3.zsh version
        ```bash
        $ zsh --version
        zsh 5.8 (x86_64-ubuntu-linux-gnu)
        ```
   
- Python version:
```bash
$ python -V
Python 3.8.10
```
- Ranger version/commit & Locale used: 
    ```bash
    ranger --version
    ranger version: ranger-master 
    Python version: 3.8.10 (default, Jun  2 2021,   10:49:15) [GCC 9.4.0]
    Locale: zh_CN.UTF-8
    ```

- Locale: 
```bash
$ locale
LANG=
LANGUAGE=
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=zh_CN.UTF-8
```

#### Current Behavior
![no image to preview](https://github.com/counter-attack-me2me/github_markdown/blob/master/screen0.jpg?raw=true)

#### Expected Behavior
![no image to preview](https://github.com/counter-attack-me2me/github_markdown/blob/master/45711975-6be7c600-bb8b-11e8-83d6-b9e8e8e9d29d.png?raw=true)

#### Context

I want to **preview the image** in the zsh based on the Guake emulator.

#### Possible Solutions
  Enable the file previews.

#### Steps to reproduce

1.  ranger installation process & debug 
    ```bash
    git clone https://github.com/ranger/ranger
    cd ranger
    sudo make install        
    ```
    ```bash
    $ ranger --debug
    :display_log
    ```
    - output message
    ```bash
    root@a1ac94480705 /root/armor/armor_detector/src/seu-detect
    Message Log:
    11:32:34.513 INFO [ranger.core.main] ranger version:    ranger-master 
    11:32:34.513 INFO [ranger.core.main] Python version: 3.8.10     (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
    11:32:34.513 INFO [ranger.core.main] Locale: zh_CN.UTF-8
    11:32:34.513 INFO [ranger.core.main] Process ID: 365706
    11:32:34.513 DEBU [ranger.core.main] cache dir: '/root/.    cache/ranger'
    11:32:34.513 DEBU [ranger.core.main] config dir: '/root/.   config/ranger'
    11:32:34.513 DEBU [ranger.core.main] data dir: '/root/. local/share/ranger'
    11:32:34.522 DEBU [ranger.core.main] Loaded custom commands     from '/root/.config/ranger/commands.py'
    11:32:34.522 DEBU [ranger.core.main] Unable to access   plugin directory: /root/.config/ranger/plugins
    11:32:34.522 DEBU [ranger.core.actions] Sourcing config     file '/usr/local/lib/python3.8/dist-packages/ranger/config/ rc.conf'
    11:32:34.530 DEBU [ranger.core.actions] Sourcing config     file '/root/.config/ranger/rc.conf'
    11:32:34.537 INFO [ranger.core.main] Running as root,   disabling the file previews.

    ```
    - both `/root/.config/ranger/rc.conf` and `/usr/local/lib/  python3.8/dist-packages/ranger/config/ rc.conf` have been     changed.
    ```bash
       set preview_images true 
       set preview_images_method w3m
    ```
2. I also tried to just run and don't install to  solve  the  problem. But  the  result  is  similar.
    ```bash
    git clone https://github.com/ranger/ranger
    cd ranger
    ```
    ```bash
    $ ./ranger.py  --debug
    :display_log
    ```
    - output message
    ```bash
    root@a1ac94480705 /root/armor/armor_detector/src/seu-detect
    Message Log:
    11:32:34.513 INFO [ranger.core.main] ranger version:    ranger-master 
    11:32:34.513 INFO [ranger.core.main] Python version: 3.8.10     (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
    11:32:34.513 INFO [ranger.core.main] Locale: zh_CN.UTF-8
    11:32:34.513 INFO [ranger.core.main] Process ID: 365706
    11:32:34.513 DEBU [ranger.core.main] cache dir: '/root/.    cache/ranger'
    11:32:34.513 DEBU [ranger.core.main] config dir: '/root/.   config/ranger'
    11:32:34.513 DEBU [ranger.core.main] data dir: '/root/. local/share/ranger'
    11:32:34.522 DEBU [ranger.core.main] Loaded custom commands     from '/root/.config/ranger/commands.py'
    11:32:34.522 DEBU [ranger.core.main] Unable to access   plugin directory: /root/.config/ranger/plugins
    11:36:32.619 DEBU [ranger.core.actions] Sourcing config file '/root/temp_ranger/ranger/config/rc.conf'
    11:32:34.530 DEBU [ranger.core.actions] Sourcing config file '/root/.config/ranger/rc.conf'
    11:32:34.537 INFO [ranger.core.main] Running as root,   disabling the file previews.

    ```
    - both `/root/.config/ranger/rc.conf` and `/root/temp_ranger/ranger/config/rc.conf` have been     changed.
    ```bash
       set preview_images true 
       set preview_images_method w3m
    ``` 

#### Traceback

```

```
#### Some questions want to know（maybe not related to my problems）
1. (Although I know it is not rational to develp c++ programs in docker later，**Is there any way to transfer docker images to lxc（which is recommended by others）?**)

**Comment by counter-attack-me2me** [comment]
#### I followed this [wiki tutorial](https://github.com/ranger/ranger/wiki/Image-Previews) and I tried the first three methods and the fourth method with [the help](https://github.com/ranger/ranger/issues/1549)， but I all failed.

> At last ， I still chose the **w3m**.
1. w3m installation (**finished**)
  
```bash
$ sudo apt install w3m-img 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
w3m-img is already the newest version (0.5.3-37).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
2. ranger setting


```bash
$ echo $RANGER_LOAD_DEFAULT_RC    
FALSE

$ ranger --copy-config=all                                                                                                                 
already exists: /root/.config/ranger/rifle.conf                                                                                            
already exists: /root/.config/ranger/commands.py                                                                                           
already exists: /root/.config/ranger/commands_full.py                                                                                      
already exists: /root/.config/ranger/rc.conf                                                                                               
already exists: /root/.config/ranger/scope.sh                                                                                              
                                                                                                                                           
> Please note that configuration files may change as ranger evolves.                                                                       
  It's completely up to you to keep them up to date.
```
- now it is only sourcing the custom setting file


```bash
root@a1ac94480705 /root/armor/armor_detector/src/seu-detect
Message Log:
01:32:16.245 INFO [ranger.core.main] ranger version: ranger-master 
01:32:16.245 INFO [ranger.core.main] Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
01:32:16.245 INFO [ranger.core.main] Locale: zh_CN.UTF-8
01:32:16.245 INFO [ranger.core.main] Process ID: 266641
01:32:16.245 DEBU [ranger.core.main] cache dir: '/root/.cache/ranger'
01:32:16.245 DEBU [ranger.core.main] config dir: '/root/.config/ranger'
01:32:16.245 DEBU [ranger.core.main] data dir: '/root/.local/share/ranger'
01:32:16.256 DEBU [ranger.core.main] Loaded custom commands from '/root/.config/ranger/commands.py'
01:32:16.257 DEBU [ranger.core.main] Unable to access plugin directory: /root/.config/ranger/plugins
01:32:16.257 DEBU [ranger.core.actions] Sourcing config file '/root/.config/ranger/rc.conf'
01:32:16.265 INFO [ranger.core.main] Running as root, disabling the file previews.
```
3. set ranger by keyboard shortcut

```bash
# defined in the /root/.config/ranger/rc.conf
map zi    set preview_images!                                                                                                          
map zm    set mouse_enabled!
```

- the zm shortcut is effective, but the zi has no effect.
  
4. TERM setting

```bash
$ echo$TERM                                                  
xterm-256color
```
5. python package settings

```bash
$ pip show pillow-simd 
Name: Pillow-SIMD
Version: 7.0.0.post3
Summary: Python Imaging Library (Fork)
Home-page: https://github.com/uploadcare/pillow-simd
Author: Alex Clark (PIL Fork Author)
Author-email: aclark@python-pillow.org
License: HPND
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: 

$ pip show pillow      
WARNING: Package(s) not found: pillow

$ pip install ranger-fm
Looking in indexes: http://pypi.douban.com/simple
Requirement already satisfied: ranger-fm in /usr/local/lib/python3.8/dist-packages (1.9.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

$ ls /usr/local/lib/python3.8/dist-packages/ | g ranger                                                                                    
ranger                                                                                                                                     
ranger_fm-1.9.3-py3.8.egg-info

```
6. some package that I am not sure whether they have effects.

```bash
$ apt-cache show imagemagick                                                                                                                             
Package: imagemagick                                                        
Architecture: amd64                                                                                                                                                                             
Version: 8:6.9.10.23+dfsg-2.1ubuntu11.4                              
Multi-Arch: foreign                                                                                                                                      
Priority: optional                                                                                                                                                        
Section: universe/graphics                                                                                                                                                                      
Origin: Ubuntu                                                                                                                                                                                  
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>                                                                      
Original-Maintainer: ImageMagick Packaging Team <pkg-gmagick-im-team@lists.alioth.debian.org>                                              
Bugs: https://bugs.launchpad.net/ubuntu/+filebug                     
Installed-Size: 124                                                                                                                                                                             
Depends: imagemagick-6.q16 (>= 8:6.9.2.10+dfsg-2~)                                                           
Filename: pool/universe/i/imagemagick/imagemagick_6.9.10.23+dfsg-2.1ubuntu11.4_amd64.deb                                                                 
Size: 14416                                                                                                                                              
MD5sum: 014957cdc225ba8cb50d91bbc369a644                                    
SHA1: 0907e509c155209654049d95d6406e0eb66cf00c                                                               
SHA256: a3e277af0430ac56856a8beaa4e7f8827d28b2de191b7d5364a09fb2ccbc4ec6                                                                                                                                                   
SHA512: f08815f39ac6c384ad636add9aef7cb06aa14992b4032ac6a100101f2d8390b8b48b66f603e05587552f7a6b8e16f3e36b647ce4b37eedf4defe6db5255f8ac3                                  
Homepage: https://www.imagemagick.org/                                                                                                                                    
Description: image manipulation programs -- binaries                                                                                                                                            
Description-md5: 454d44b3e8d4177be027105c6c73b6f9                                                                                                                                               
Task: ubuntustudio-video, ubuntustudio-publishing, ubuntustudio-graphics                                                                                                                                                   

Package: imagemagick                                  
Architecture: amd64                                   
Version: 8:6.9.10.23+dfsg-2.1ubuntu11                                                                        
Multi-Arch: foreign                                   
Priority: optional                                    
Section: universe/graphics                            
Origin: Ubuntu                                        
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>                                                                                                                                                      
Original-Maintainer: ImageMagick Packaging Team <pkg-gmagick-im-team@lists.alioth.debian.org>                                                                                                                              
Bugs: https://bugs.launchpad.net/ubuntu/+filebug                                                             
Installed-Size: 123                                   
Depends: imagemagick-6.q16 (>= 8:6.9.2.10+dfsg-2~)                                                           
Filename: pool/universe/i/imagemagick/imagemagick_6.9.10.23+dfsg-2.1ubuntu11_amd64.deb                                                                                                                                     
Size: 14416                                           
MD5sum: db203c6a1d6146fac446347432f79fa5                                                                     
SHA1: 29f4e48754a83d7456a69e34c346331983475250                                                               
SHA256: e07dd47520e8507c90954cac2cfeeb59480f207e5d41c5ab91219bbb073d7505                                                                                                                                                   
Homepage: https://www.imagemagick.org/                                                                       
Description: image manipulation programs -- binaries                                                         
Description-md5: 454d44b3e8d4177be027105c6c73b6f9                                                            
Task: ubuntustudio-video, ubuntustudio-publishing, ubuntustudio-graphics
```

#### additional debugs
1. check package 
`:eval import PIL`
no more message is shown in the log and no trackbacks had happened.
2. 

#### problems solution had been found.
1. preview is forbidden for some reason logining as root.
    - so I changed user and can preview file always.
2. however I still can‘t preview images always with only zsh and Guake(**no tmux**)
- w3m
    - tracebacks
    
    ```bash
    czg@a1ac94480705 /home/czg/Desktop/    tmux_cheat_sheet_1440-1.   jpg                                                                               
    Message Log:
    03:22:40 INFO ranger version:ranger-master 
    03:22:40 INFO Python version: 3.8.10(default,      Jun  2 2021, 10:49:15) [GCC9.4.0]
    03:22:40 INFO Locale: zh_CN.UTF-8
    03:22:40 INFO Process ID: 1005161
    03:22:47 ERRO Notification: "w3m" does notappear       to be a valid setting forpreview_images_method.
    03:22:47 ERRO "w3m" does not appear to bea valid       setting forpreview_images_method.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8dist-packages/     ranger/gui/widgetspager.py", line 118, in      draw_image
        self.fm.image_displayer.draw(selfimage, self.      x, self.y,
      File "/usr/local/lib/python3.8dist-packages/     ranger/extimg_display.py", line 188, in draw
        input_gen = self._generate_w3m_inpu(path,      start_x, start_y, width,
      File "/usr/local/lib/python3.8dist-packages/     ranger/extimg_display.py", line 237, in       _generate_w3m_input
        raise ImgDisplayUnsupportedException
    ranger.ext.img_display.    ImgDisplayUnsupportedException: "w3m" doesnot      appear to be a valid settingfor   preview_images_method.
    ```
- ueberzug
    - environment

    ```bash
    # xdpyinfo | grep version
    version number:    11.0
    X.Org version: 1.20.9
    ```


    - installation process     
        
    ```bash
    # pip show ueberzug 
    Name: ueberzug
    Version: 18.1.9
    Summary: ueberzug is a command line util which  allows to display images in combination with X11
    Home-page: https://github.com/seebye/ueberzug
    Author: Nico Baeurer
    Author-email: None
    License: GPLv3
    Location: /usr/local/lib/python3.8/dist-packages
    Requires: pillow, docopt, attrs, python-xlib
    Required-by:

    # sudo apt install  libx11-dev libxtst-dev  python3-docopt python3-xlib python3-pil
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    libxtst-dev is already the newest version (2:1.2.   3-1).
    python3-docopt is already the newest version (0.6.  2-2.2ubuntu1).
    python3-xlib is already the newest version (0.  23-2build1).
    libx11-dev is already the newest version (2:1.6.    9-2ubuntu1.2).
    python3-pil is already the newest version (7.0. 0-4ubuntu0.4).
    0 upgraded, 0 newly installed, 0 to remove and 0    not upgraded.

    ```
    - terminal result
     
    ```bash
    czg@a1ac94480705 /home/czg/Desktop/ tmux_cheat_sheet_1440-1. jpg                                                                              
    Message Log:
    03:36:39 INFO ranger version: ranger-master 
    03:36:39 INFO Python version: 3.8.10 (default,  Jun  2 2021, 10:49:15) [GCC 9.4.0]
    03:36:39 INFO Locale: zh_CN.UTF-8
    03:36:39 INFO Process ID: 1067604
    ```

    - result image

| ![alt tubn!](https://github.com/counter-attack-me2me/github_markdown/blob/master/screen01.jpg?raw=true"ti") |
|:--:|
| <b>No image is rendered which is weird.</b>|
- however **urxvt** can render the image correctly！:thinking:      
    - I was really happy！ :smile:

| ![alt tubn!](https://github.com/counter-attack-me2me/github_markdown/blob/master/screen02.jpg?raw=true"ti") |
|:--:|
| <b>amazing ！</b>| 

#### I hope my solution can be helpful to others :smile: and someone can help me solve the problems with `w3m and ueberzug` !

**Comment by toonn** [comment]
I'm not sure guake is compatible with any of the previewing methods unfortunately. Does guake support SIXEL? Support for that is in the works.

If you can get previews to work in another terminal then the most likely culprit is the terminal that doesn't work.

**Comment by pirate486743186** [comment]
image previews are a bit hacky. They can easily fail. It's worse then wine.
Like toon said, it's only a few terminals that work.

* for guake, i started it from mate-terminal, a vte terminal where the preview works, the w3m preview of guake appeared in the first terminal instead of guake.... (same with w3m the browser)
* the ueberzug preview seams to work....  If you split the screen,the preview can land on the wrong screen. If you changed tabs, the preview is always visible.... These are the normal limitations of this method.
* The other methods are very terminal specific and it's not suprising that they don't work at all for guake.

They are technical limitations in what can be done. Since you are into programming, you could use the mpv method (not rolled out yet, you have to copy paste code from the wiki). This method shows the images in an mpv instance.
