### ISSUE TITLE
Cannot preview images with terminator

### ISSUE THREAD

**Issue by acampove** [ranger/ranger#2439]
#### Runtime Environment

- Operating system and version: Linux linux 5.11.4-1-rt11-MANJARO #1 SMP Fri May 21 00:10:17 CEST 2021 x86_64 GNU/Linux
- Terminal emulator and version: terminator 2.1.1
- Python version: Python 3.9.6
- Ranger version/commit: Python version: 3.9.6
- Locale: en_HK.UTF-8

#### Current Behavior

I try to preview `png` files but I cannot see anything.

#### Expected Behavior

I should see a preview.

#### Context

I cannot see previews of images. I am trying to see previews of images.

#### Possible Solutions

I do not know how to solve this, that's why I am opening an issue here.

#### Steps to reproduce
1. Open terminator
2. Open ranger inside terminator
3. Navigate to a `png` file and see that there is no preview.

Also in the `rc.conf` I wrote:

```
set preview_images true
set preview_images_method w3m
```

I attached that file:

[rc.txt](https://github.com/ranger/ranger/files/7072337/rc.txt)

Finally, when in terminator I do:

`w3m image.png`

I can see the image.

#### Traceback

There is no crash, I just cannot see any preview.
```

```

**Comment by toonn** [comment]
Are you using ranger master? I broke previews recently, running with `ranger --debug` would cause a crash.

**Comment by acampove** [comment]
Hi,

Thanks for your reply. I guess I am using ranger-master:

```
ranger version: ranger-master 
Python version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Locale: en_HK.UTF-8
```

I installed ranger using the Manjaro package manager. Should I uninstall it and download the source and build myself?  What tag should I use?

Cheers.

**Comment by toonn** [comment]
Try running `ranger --debug`, see if it crashes.

**Comment by acampove** [comment]
Yes, it crashes:

```
 17:45:10 angelcampoverde@linux ranger --debug
ranger version: ranger-master 
Python version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Locale: en_HK.UTF-8
Current file: '/home/angelcampoverde/Pictures/ntuple_prod_versions.png'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 380, in loop
    ui.draw_images()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 411, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/pager.py", line 122, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 171, in notify
    raise obj
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/pager.py", line 118, in draw_image
    self.fm.image_displayer.draw(self.image, self.x, self.y,
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 620, in draw
    self._late_init()
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 564, in _late_init
    raise ImgDisplayUnsupportedException(
ranger.ext.img_display.ImgDisplayUnsupportedException: kitty previews only work in kitty and outside tmux. Make sure your TERM contains the string "kitty"

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by toonn** [comment]
Well, you seem to be using the "kitty" preview method? That only works with the Kitty terminal afaik. You'll have to try either w3m or ueberzug.

**Comment by acampove** [comment]
Hi,

I had put it back to kitty, because that is the only terminal I can use ranger previews with. However I want to use terminator because of the many other features that it offers. I set the previews back to `w3m` and I see:

```
ranger version: ranger-master 
Python version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Locale: en_HK.UTF-8
Current file: '/home/angelcampoverde/Pictures/ntuple_prod_versions.png'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 380, in loop
    ui.draw_images()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 411, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/pager.py", line 124, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 171, in notify
    raise obj
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/pager.py", line 118, in draw_image
    self.fm.image_displayer.draw(self.image, self.x, self.y,
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 175, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width,
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 222, in _generate_w3m_input
    fontw, fonth = self._get_font_dimensions()
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 165, in _get_font_dimensions
    xpixels, ypixels = int(output[0]), int(output[1])
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Is `W3MIMGDISPLAY_PATH` set in your environment?
If not check the first path where you find w3mimgdisplay:
```
'/usr/lib/w3m/w3mimgdisplay',
'/usr/libexec/w3m/w3mimgdisplay',
'/usr/lib64/w3m/w3mimgdisplay',
'/usr/libexec64/w3m/w3mimgdisplay',
'/usr/local/libexec/w3m/w3mimgdisplay'
```

Then run `/your/path/w3mimgdisplay -test`.

**Comment by acampove** [comment]
Hi,

Thanks for your reply. And:

1. No, it was not in my environment and I did:

- export W3MIMGDISPLAY_PATH="/home/angelcampoverde/.local/bin/w3mimgdisplay"

in `~/.bashrc`

2. I ran the command and nothing happens:
```
 18:05:29 angelcampoverde@linux 
 18:05:29 angelcampoverde@linux /home/angelcampoverde/.local/bin/w3mimgdisplay -test
 18:05:38 angelcampoverde@linux 
```
3. I made sure that:
```
 75 # Use one of the supported image preview protocols
 76 set preview_images true
 77 
 78 # Set the preview image method. Supported methods:
...
121 #set preview_images_method urxvt
122 set preview_images_method w3m 
123 
```

And I finally tried to get the preview without `--debug` but it does not show anything. When I use `--debug` it crashes as soon as I move into a directory. I would really like to keep using terminator and I really like the image preview feature, so far the only way to have both is to use also kitty, but at the end I only use kitty for image previews.

Cheers.

**Comment by toonn** [comment]
Does `w3mimgdisplay -test` give any output in Xterm or Kitty? The reason it's crashing is we parse the output of that command to get the size of the preview pane, if we can't get that we can't use the method for previews. Ueberzug should work regardless of the terminal you're running though.

**Comment by acampove** [comment]
Hi,

I tried ueberzug, but I get:

![image](https://user-images.githubusercontent.com/14037062/131985869-325fbc7f-d7bc-44b3-b3be-13343ea5e9b1.png)

There seems to be two ways to get this package and I picked up the `python-ueberzug`:

![image](https://user-images.githubusercontent.com/14037062/131985985-0ecc82bc-50cb-407c-8c3f-7c24443113ec.png)

from my package manager in Manjaro.

Cheers.

**Comment by toonn** [comment]
`w3m -test` doesn't provide the information we need. Try installing both ranger-fm and ueberzug using pip. Manjaro packages weirdly old `scope.sh` which could affect image previews too.

**Comment by acampove** [comment]
Hi,

Thanks for your reply. I have uninstalled ranger and ueberzug from the package manager and installed them with pip:

![image](https://user-images.githubusercontent.com/14037062/132066598-ec40833e-a98f-4371-a775-c7fa459ad613.png)

Also I have checked the config files in the `$HOME/.config/ranger/` directory, which is ziped and attached. However when I open ranger I still cannot see any images:

![image](https://user-images.githubusercontent.com/14037062/132066332-e1e2d92b-bdd5-457e-b7ad-02ae740305e4.png)

[ranger_config.zip](https://github.com/ranger/ranger/files/7108531/ranger_config.zip)

Maybe the config files that I attached are not the ones used? I also found others in:

`/home/angelcampoverde/.local/lib/python3.9/site-packages/ranger/config`

However modifying `rc.conf` to enable previews and use ueberzug:

![image](https://user-images.githubusercontent.com/14037062/132066738-cb6305ad-927d-416a-a9e3-707245a8c0ff.png)

does not seem to be doing anything.

Cheers.

**Comment by acampove** [comment]
Oh, one more thing, I see:

![image](https://user-images.githubusercontent.com/14037062/132067090-106d8224-cc32-4fc9-8de0-0f4cfdded93b.png)

so I guess the previews are working, just not for `PNG` or `PDF` files?

**Comment by toonn** [comment]
Are you on Wayland maybe? Then ueberzug won't work.

**Comment by toonn** [comment]
Kitty may be your only option, I'm not sure any of the other methods work on Wayland.

**Comment by acampove** [comment]
Hi,

OK, then I guess we can close this. Thanks for your help anyway.
