### ISSUE TITLE
File preview fails after switch to open23

### ISSUE THREAD

**Issue by GbGp** [ranger/ranger#2442]
Hello, I just cloned this repo and it seems that after commit f0ad7a0fe9d371b6ba34ce4aaa725202d8ed5444 the file preview is no longer functional for me.

#### Runtime Environment
```
ranger version: ranger-master (50f8971a6eccb43442bb53186fa83212d0763c01)
Python version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Locale: en_US.UTF-8
```

#### Current Behavior
The preview of any file (a .txt in this case) fails with:
```Loader work process failed: Getting preview of /tmp/test.txt (Percent: 0)```
Reverting f0ad7a0fe9d371b6ba34ce4aaa725202d8ed5444 fixes the problem on my system.

#### Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/loader.py", line 427, in work
    next(item.load_generator)
  File "/usr/lib/python3.9/site-packages/ranger/core/loader.py", line 182, in generate
    self.process = process = Popen(self.args, **popenargs)
  File "/usr/lib/python3.9/subprocess.py", line 829, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python3.9/subprocess.py", line 1586, in _get_handles
    p2cread = stdin.fileno()
AttributeError: '_GeneratorContextManager' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 202, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 410, in loop
    loader.work()
  File "/usr/lib/python3.9/site-packages/ranger/core/loader.py", line 432, in work
    self.fm.notify(
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 177, in notify
    raise Exception(str(obj))
Exception: Loader work process failed: Getting preview of /tmp/test.txt (Percent: 0)
```

**Comment by toonn** [comment]
Yep, known problem. Looking into it currently. Thanks for the report anyway!

**Comment by toonn** [comment]
Would be swell if you could test #2443 : )

**Comment by GbGp** [comment]
it work, thanks!
