### ISSUE TITLE
Ranger crashes but only if its being ran with sudo and tmux

### ISSUE THREAD

**Issue by Ed-wil** [ranger/ranger#2450]
I'm using Archlinux
My terminal's st with scroll back patch and tmux
python 3.9.6
Ranger version1.9.3
the locale's en_us.UTF-8

For some reason ranger only crashes if I try to run it with sudo at the same time tmux is being attached to st.
I can still run it without sudo in tmux.
Ranger's also works fine when I'm not being attached tmux.
So I'm not really sure where to post this.

Here's the traceback.

Python` version: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.9/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by Ed-wil** [comment]
I uninstalled ranger through the pacman package manager, and installed the one from the github instead, got a no module error, had to reinstall python. But it's working fine now.

using the git version from the AUR repository also works.
