### ISSUE TITLE
crash during start-up with asterisk in parameter

### ISSUE THREAD

**Issue by v0lker** [ranger/ranger#2451]
#### Runtime Environment

- Operating system and version: macOS 10.14
- Terminal emulator and version: iterm 3.3.2, TERM=xterm-256color
- Python version: 3.9.7
- Ranger version/commit: 1.9.3
- Locale: en_GB.UTF-8

#### Current Behavior

```
$ ranger existing_directory/*
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/gui/ui.py", line 335, in redraw
    self.finalize()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/gui/ui.py", line 392, in finalize
    DisplayableContainer.finalize(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'
```

can trigger the same by passing a simple (existing) file as a parameter, instead. non-existing files are handled gracefully, though (```Inacessible paths: foo```)

#### Expected Behavior
error message of some sort, graceful exit during start-up/parameter validation

#### Steps to reproduce
1. see above
2. 
3. 

#### Traceback

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/gui/ui.py", line 335, in redraw
    self.finalize()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/gui/ui.py", line 392, in finalize
    DisplayableContainer.finalize(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'
```

**Comment by toonn** [comment]
I believe this has been fixed on master, could you check?
