### ISSUE TITLE
Ranger crashes

### ISSUE THREAD

**Issue by squidboy7** [ranger/ranger#2477]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version:  Alacritty
- Python version:  3.9.7
- Ranger version/commit:  ranger master from aur
- Locale: 

#### Current Behavior
Works perfectly if I dont move too fast
#### Expected Behavior
If i start moving around quickly like scroll between multiple files, it crashes
#### Context

It crashes. I tried to browser my files
#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
ranger version: ranger-master
Python version: 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 271, in handle_input
    self.handle_mouse()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 188, in click
    if DisplayableContainer.click(self, event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 86, in click
    self.fm.enter_dir(self.target.path)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 585, in enter_dir
    result = self.thistab.enter_dir(path, history=history)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range
```

**Comment by squidboy7** [comment]
> > IndexError: list index out of range
> 
> Looks like error which one we already fixed.
> 
> > Ranger version/commit: ranger master from aur
> 
> Could you try a master-branch from git?

ill try that out

**Comment by squidboy7** [comment]
yep it works now
