### ISSUE TITLE
Can't start ranger - upgraded to python 3.9

### ISSUE THREAD

**Issue by dquinton** [ranger/ranger#2480]
Hi there, if you can help me with this, much appreciated, as I am almost lost without ranger now! I'm having problems remembering command line tools!!

I upgraded my system - Devuan chimaera (=Debian bullseye) and python upgraded to 3.9.2 and ranger fails to start.

```
dav>01:49:23:~/Downloads$ ranger
inconsistent use of tabs and spaces in indentation (default.py, line 76)
inconsistent use of tabs and spaces in indentation (default.py, line 76)
ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
Locale: en_US.UTF-8
Current file: '/home/dav/Downloads/Compressed'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/titlebar.py", line 43, in draw
    self._print_result(self.result)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/titlebar.py", line 152, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 73, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python3/dist-packages/ranger/container/settings.py", line 246, in __getattr__
    return self.get(name, None)
  File "/usr/lib/python3/dist-packages/ranger/container/settings.py", line 234, in get
    self.__setattr__(name, value)
  File "/usr/lib/python3/dist-packages/ranger/container/settings.py", line 241, in __setattr__
    self.set(name, value, None)
  File "/usr/lib/python3/dist-packages/ranger/container/settings.py", line 193, in set
    self.signal_emit('setopt.' + name, **kws)
  File "/usr/lib/python3/dist-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3/dist-packages/ranger/container/settings.py", line 165, in _sanitize
    _colorscheme_name_to_class(signal)
  File "/usr/lib/python3/dist-packages/ranger/gui/colorscheme.py", line 132, in _colorscheme_name_to_class
    __import__(scheme_supermodule, globals(), locals(), [scheme_name], 0), scheme_name)
  File "/home/dav/.config/ranger/colorschemes/default.py", line 76
    _    elif context.file:
TabError: inconsistent use of tabs and spaces in indentation
```
Ok, then I tried ranger 1.8.0
```
dav>02:01:05:~/Downloads/ranger-1.8.0$ ./ranger.py
inconsistent use of tabs and spaces in indentation (default.py, line 76)
inconsistent use of tabs and spaces in indentation (default.py, line 76)
The option named `hostname_in_titlebar' does not exist
The option named `wrap_scroll' does not exist
ranger version: 1.8.0, executed with python 3.9.2
Locale: en_US.UTF-8
Current file: /home/dav/Downloads/ranger-1.8.0/doc
Traceback (most recent call last):
  File "/home/dav/Downloads/ranger-1.8.0/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/home/dav/Downloads/ranger-1.8.0/ranger/core/fm.py", line 362, in loop
    ui.redraw()
  File "/home/dav/Downloads/ranger-1.8.0/ranger/gui/ui.py", line 295, in redraw
    self.draw()
  File "/home/dav/Downloads/ranger-1.8.0/ranger/gui/ui.py", line 322, in draw
    DisplayableContainer.draw(self)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/home/dav/Downloads/ranger-1.8.0/ranger/gui/widgets/titlebar.py", line 41, in draw
    self._print_result(self.result)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/gui/widgets/titlebar.py", line 153, in _print_result
    self.color(*part.lst)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/gui/curses_shortcuts.py", line 67, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/container/settings.py", line 198, in __getattr__
    return self.get(name, None)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/container/settings.py", line 185, in get
    self.__setattr__(name, value)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/container/settings.py", line 192, in __setattr__
    self.set(name, value, None)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/container/settings.py", line 156, in set
    self.signal_emit('setopt.' + name, **kws)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/ext/signals.py", line 259, in signal_emit
    fnc(signal)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/container/settings.py", line 128, in _sanitize
    _colorscheme_name_to_class(signal)
  File "/home/dav/Downloads/ranger-1.8.0/ranger/gui/colorscheme.py", line 125, in _colorscheme_name_to_class
    scheme_module = getattr(__import__(scheme_supermodule,
  File "/home/dav/.config/ranger/colorschemes/default.py", line 76
    	    elif context.file:
TabError: inconsistent use of tabs and spaces in indentation
```

Then I built python 10 and got this with ranger 1.9.3

```
dav>12:23:13:~$ ranger
Traceback (most recent call last):
  File "/usr/local/bin/ranger", line 36, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'
```

I haven't yet tried an older python, as ranger should run on 3.9 anyway right?
I also removed python entirely and reinstalled it to make sure I didn't have a mish mash.
Any pointers?

**Comment by dquinton** [comment]
Forgot to mention, after the upgrade to python3.9.2, I had to make a symlink to /usr/bin/python3, as it seems ranger calls /usr/bin/python and gives this error if no symlink...

```
dav>06:26:54:~$ ranger
bash: /usr/local/bin/ranger: /usr/bin/python: bad interpreter: No such file or directory
```

Perhaps that's the wrong thing to do. Apologies also if this is not an issue with ranger itself.

**Comment by Rom1deTroyes** [comment]
> dav>01:49:23:~/Downloads$ ranger
> inconsistent use of tabs and spaces in indentation (default.py, line 76)
>[...]
>   File "/usr/lib/python3/dist-packages/ranger/gui/colorscheme.py", line 132, in _colorscheme_name_to_class
>     __import__(scheme_supermodule, globals(), locals(), [scheme_name], 0), scheme_name)
>   File "/home/dav/.config/ranger/colorschemes/default.py", line 76
>     _    elif context.file:
> TabError: inconsistent use of tabs and spaces in indentation
> ```

The problem seems to be in your `~/.config/` file : did you make some customization to your colorsheme ?
If so, you may add a [Tab] character somewhere (and Python don't like that).
Try to run ranger without using your configuration with :
```sh
ranger -c
```

-c, --clean   Activate the clean mode:  ranger will not access or create any configuration files nor will it leave any traces on your system.  This is useful when your configuration is broken, when you want to avoid clutter, etc.

So we can see if the problem comes from ranger or from the conf files.


> Forgot to mention, after the upgrade to python3.9.2, I had to make a symlink to /usr/bin/python3, as it seems ranger calls /usr/bin/python and gives this error if no symlink...
> 
> ```
> dav>06:26:54:~$ ranger
> bash: /usr/local/bin/ranger: /usr/bin/python: bad interpreter: No such file or directory
> ```
> 
> Perhaps that's the wrong thing to do. Apologies also if this is not an issue with ranger itself.

Debian provide a `python-is-python3` package that do the jobs for you :
```sh
apt show python-is-python3

Package: python-is-python3
Version: 3.9.2-1
Priority: optional
Section: python
Source: what-is-python (9)
Maintainer: Matthias Klose  <doko@debian.org>
Installed-Size: 13,3 kB
Depends: python3
Breaks: python, python-is-python2, python-is-python2-but-deprecated, python-minimal
Replaces: python, python-is-python2, python-is-python2-but-deprecated, python-minimal
Cnf-Ignore-Commands: python
Download-Size: 2 800 B
APT-Sources: http://httpredir.debian.org/debian stable/main amd64 Packages
Description: symlinks /usr/bin/python to python3
 Starting with the Debian 11 (bullseye) and Ubuntu 20.04 LTS (focal)
 releases, all python packages use explicit python3 or python2
 interpreter and do not use unversioned /usr/bin/python at all. Some
 third-party code is now predominantly python3 based, yet may use
 /usr/bin/python.
 .
 This is a convenience package which ships a symlink to point
 the /usr/bin/python interpreter at the current default python3. It may
 improve compatibility with other modern systems, whilst breaking some
 obsolete or 3rd-party software.
 .
 No packages may declare dependencies on this package.
```

**Comment by dquinton** [comment]
Hey thanks so much Rom1deTroyes, I completely missed that, the problem coming from my mods in config files.
the -c flag started it like normal.
so now to find what it is chewing on :~

**Comment by toonn** [comment]
@dquinton, you'll want to open `$XDG_CONFIG_HOME/ranger/colorschemes/default.py` and then set whitespace to be visible in your editor, `:set list` should work in Vim. You'll have to look for tabs and replace them with the appropriate amount of spaces.

**Comment by dquinton** [comment]
Yes it is the default.py file in colorschemes. I did a compare with the one shipped with ranger and they have so many differences, so I guess it would be better to replace mine for now and see if I need to make changes later.
Cheers for the good work.. life is so much easier with this tool.
