### ISSUE TITLE
Not able to use the find 'f' functionality of ranger.

### ISSUE THREAD

**Issue by gwynbleidd007** [ranger/ranger#2488]
#### Runtime Environment

- Operating system and version: Manjaro linux
- Terminal emulator and version: Kitty
- Python version: 3,9.7
- Ranger version/commit: ranger-master 
- Locale: en_IN.ISO8859-1

#### Current Behavior
On using find 'f' to go to a sub-directory, ranger crashes.
#### Expected Behavior
I should get into the sub-directory searched for.
#### Context

Not able to use the find functionality due to which folders with multiple sub directories takes long time to enter the directory I want to enter to.

#### Steps to reproduce
1. In a directory, press 'f'.
2. Type the subfolder that needs to be accessed.
3. It searches for the first few terms then it crashes as name is further entered. Though sometimes it works well too but most of the times, it crashes.

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1520, in execute
    self.fm.move(right=1)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by toonn** [comment]
This issue has been fixed on master, try updating to a more recent checkout.

**Comment by gwynbleidd007** [comment]
I am using the master version of ranger and the version I am using is 1.9.3 and the issue is there in this.

**Comment by toonn** [comment]
The version Manjaro provides doesn't actually look like the tip of the master branch.

**Comment by gwynbleidd007** [comment]
Okay yes just replaced it with the git version and this does seem to be working fine.
