### ISSUE TITLE
Typing :hide in ranger crashes the application

### ISSUE THREAD

**Issue by quantumfate** [ranger/ranger#2505]
#### Runtime Environment

- Operating system and version:
- cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.0
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
- Terminal emulator and version: alacritty 0.9.0
- Python version: 3.9.7
- Ranger version/commit: ranger-1.9.3
- Locale: DE

#### Current Behavior
typing :hide as a command in ranger makes the application crash. To be more precise it crashes when typing the "e".
But typing anything else with "e" at the 4th place doesn't crash ranger.
It crashes before I am even able to hit enter. Typing anything else doesn't crash ranger.

#### Expected Behavior
Don't crash, I guess. 

#### Context

I was just casually trying to type :hide in the command line from ranger. But I was in the process of moving files around and creating directories.

#### Possible Solutions
None, sorry. Did not find a workaround.

#### Steps to reproduce
1. open ranger
2. type :hide

#### Traceback

```
ranger version: ranger-master
Python version: 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1545, in quick
    self.fm.thisdir.refilter()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Gregaras** [comment]
Probably downloading master version of Ranger might solve the problem.

**Comment by toonn** [comment]
Yes, this issue should be fixed on the master branch. I need to cut a release but I'm really short on time.
