### ISSUE TITLE
Ranger crashes on running with sudo

### ISSUE THREAD

**Issue by RightMakesMight** [ranger/ranger#2507]
The stack trace requested I post here:

user@personal:~$ sudo ranger
ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3/dist-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
user@personal:~$ 

#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
This has probably been fixed already on the master branch, could you check?
