### ISSUE TITLE
ranger crashes when opened under directory ~/.config/ranger

### ISSUE THREAD

**Issue by kkew3** [ranger/ranger#2514]
#### Runtime Environment

- Operating system and version: macOS Catalina Version 10.15.7
- Terminal emulator and version: iTerm2 Build 3.4.14
- Python version: 3.10.0
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

When opening `ranger` under `~/.config/ranger/`, it crashes. ~/.config/ranger/rc.conf attached as rc.conf.txt:

[rc.conf.txt](https://github.com/ranger/ranger/files/7653178/rc.conf.txt)

When opening `ranger` not under `~/.config/ranger/`, say `~/.config/`, it does not crash.

When opening `ranger` without `~/.config/ranger/rc.conf`, it does not crash.

#### Expected Behavior

No crash in any directory.

#### Context

Can't use ranger from time to time.

#### Steps to reproduce

Stated above.

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.10.0 (default, Oct 13 2021, 06:44:31) [Clang 12.0.0 (clang-1200.0.32.29)]
Locale: en_US.UTF-8
Current file: '~/.config/ranger/rc.conf'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
[rc.conf.txt](https://github.com/ranger/ranger/files/7653177/rc.conf.txt)

    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by notDavid** [comment]
I get approximately the same error, when opening the files preview window of any file:
(but not if i create an empty file like `touch empty.txt`.)

**macOS** 11.6
**ranger** version: ranger 1.9.3
**Python** version: 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
**Locale**: en_US.UTF-8

```
ranger version: ranger 1.9.3
Python version: 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
Locale: en_US.UTF-8
Current file: '/Users/david/tmp/example.txt'                                                           

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/main.py", line 201, in main                
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
This is due to changes to the curses module for Python 3.10. I believe there's another open issue on this but GitHub search is letting me down again.

**Comment by notDavid** [comment]
https://github.com/ranger/ranger/issues/2498#issuecomment-976465333

**Comment by toonn** [comment]
Closing as duplicate.
