### ISSUE TITLE
Ranger crashes at startup

### ISSUE THREAD

**Issue by davsalas** [ranger/ranger#2515]
#### Runtime Environment

- Operating system and version: Fedora 35
- Terminal emulator and version: Tilix version: 1.9.4
- Python version: 3.10
- Ranger version/commit: 1.9.3

#### Current Behavior

Ranger crashes when i try to open it. It doesn't work when i try to open the default directory nor when defining a directory as an argument

#### Expected Behavior

Open normally

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.10/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by toonn** [comment]
Could you check `~/.config/ranger/bookmarks` for a path that no longer exists? And if it's not there it should be in `$XDG_DATA_HOME/ranger/bookmarks`.

**Comment by davsalas** [comment]
I created an empty file `~/.config/ranger/bookmarks`and now it all works. Thanks

**Comment by toonn** [comment]
That's not a  good solution. It probably means your real `bookmarks` are at `$XDG_DATA_HOME/ranger`.
