### ISSUE TITLE
Ranger crashing when attempting to display file preview

### ISSUE THREAD

**Issue by kirsa** [ranger/ranger#2516]
#### Runtime Environment
MacOS 12.0.1
iterm 2

#### Current Behavior
❯ ranger ~/my_config
ranger version: ranger 1.9.3
Python version: 3.10.0 (default, Oct 22 2021, 13:39:57) [Clang 13.0.0 (clang-1300.0.29.3)]
Locale: en_GB.UTF-8
Current file: '/Users/abhi/my_config/.aliases'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by kirsa** [comment]
Looks like this has already been reported so closing.
