### ISSUE TITLE
Crash when trying delete files that were previously selected in visual line mode

### ISSUE THREAD

**Issue by Gladiu** [ranger/ranger#2519]
#### Runtime Environment

- Operating system and version: Arch linux 64bit
- Terminal emulator and version: alacritty 0.9.0 (fed349aa)
- Python version: Python 3.9.9
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Ranger crashes
#### Expected Behavior
I wanted to console trash files that were previously selected
#### Context

I wanted to yank files to put them in folder, and then delete them with console Trash
#### Steps to reproduce
1. Select files in visual line mode
2. Paste files in same directory
3. Go back to previous folder
4. Delete files with d and then T to do console Trash

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.9.9 (main, Nov 20 2021, 21:30:06) [GCC 11.1.0]
Locale: en_US.UTF-8
Current file: '/home/gladiu/Programming/RPG/source/player.c'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'
```

**Comment by toonn** [comment]
Can you reproduce with the master branch?

**Comment by mlch911** [comment]
I have the same issue when I toggle the 「console trash」action.

```
ranger version: ranger 1.9.3
Python version: 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
Locale: zh_CN.UTF-8
Current file: '/Users/mlch911/Documents/Programming/Android'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'
```

**Comment by Gregaras** [comment]
Doesn't seem to crash in ranger-master v1.9.3-422-g1de6787c

**Comment by toonn** [comment]
Thanks for the reports, I'm tentatively closing this as fixed. The AUR has `ranger-git` packaged, otherwise you could install manually from the repository, as a workaround until we release the next version.
