### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pointer'

### ISSUE THREAD

**Issue by gncs** [ranger/ranger#2521]
#### Runtime Environment

- Operating system and version: Fedora 35
- Terminal emulator and version: GNOME Terminal 3.42.1 using VTE 0.66.1 +BIDI +GNUTLS +ICU +SYSTEMD

#### Current Behavior

Ranger suddenly crashed. Probably related: there was a remote directory mounted with SSHFS and that mount point broke before.

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Could you try running ranger from the master branch and see if it reproduces?

**Comment by MasterTonLab** [comment]
I have the same issue on my Fedora 35.
OS: Linux fedora35comp 5.15.14-200.fc35.x86_64 1 SMP Tue Jan 11 16:49:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ranger version: ranger 1.9.3
Python version: 3.10.1 (main, Dec  9 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
Locale: en_US.UTF-8

~/.config/ranger/rc.conf
set save_tabs_on_exit true

I open Ranegr in my terminal Sakura, it automatically opens a new tab with my home directory (/home/myusername/). And also I see saved tabs.
When trying to go to a saved tab with the Tab key, the Ranger crashes with an error.

And I understood what was the reason for the Ranger crash.
The fact is that the target path of the saved tab is on a drive that is not mounted.
I did the mount:
$ sudo mount -t xfs /dev/sdg4 /mnt/MyNewDisk4
Then I run Ranger and it no longer crashed when switching to all saved tabs.

But this kind of work of the Ranger is not correct. It need to fix this.

**Comment by Jasha10** [comment]
> Could you try running ranger from the master branch and see if it reproduces?

I had the same issue with ranger v1.9.3 and _could not_ reproduce the error on master branch.

**Comment by eMPee584** [comment]
> > Could you try running ranger from the master branch and see if it reproduces?

> I had the same issue with ranger v1.9.3 and _could not_ reproduce the error on master branch.

The problem can still be reproduced on master if the parent folder of the tab path also disappears. #2724 fixes this.
