### ISSUE TITLE
Crash when folder (tab) doesn't exist: AttributeError: 'NoneType' object has no attribute 'path'

### ISSUE THREAD

**Issue by ProgrammingLife** [ranger/ranger#2529]
#### Runtime Environment
- Operating system and version: Linux Mint 19.1
- Terminal emulator and version: gnome-terminal 3.28.1
- Python version: 3.6.8
- Ranger version/commit: ranger-master (built about 2 weeks ago)
- Locale: en_US.UTF-8

#### Current Behavior
When I start ranger it crashes because it tries to load some folders in tabs which already don't exists. I don't know how to remove those corrupted tabs, because it crashes when I try to move to the tab.

#### Expected Behavior
Running ranger 

#### Possible Solutions
Just check if folder exists before opening the tab.

#### Steps to reproduce
1. Open a few folders in tabs. Ranger should be configured to restore tabs.
2. Remove some of those folders from your system
3. Open ranger again and go to that tab -> crash

#### Traceback

```
ranger version: ranger-master 
Python version: 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/main.py", line 204, in main
    fm.loop()
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/fm.py", line 416, in loop
    ui.redraw()
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/ui.py", line 370, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/widgets/titlebar.py", line 42, in draw
    self._calc_bar()
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/widgets/titlebar.py", line 82, in _calc_bar
    self._get_left_part(bar)
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/widgets/titlebar.py", line 106, in _get_left_part
    and (self.fm.thisdir.path.startswith(self.fm.home_path + "/")
AttributeError: 'NoneType' object has no attribute 'path'
ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Gregaras** [comment]
Doesn't seem to crash for me. Instead, when I go to the tab of deleted folder Ranger directs me to the parent folder where the deleted folder was in. Tested on `ranger-master v1.9.3-430-g7cbdd92a`.

**Comment by ProgrammingLife** [comment]
@Gregaras I don't think I can easily update python without reinstalling the whole system :) Linux Mint in my case.
Anyway I have various python versions: python-3.9, 3.8 as well. I just have default python link for the system which points to:
```
/usr/bin/python3 ⇒ /usr/bin/python3.6
```
Is there a way to specify another python version for Ranger without changing python3-link?

**Comment by ProgrammingLife** [comment]
BTW, in which file does Ranger store tabs?

**Comment by Gregaras** [comment]
> BTW, in which file does Ranger store tabs?

Should be a file in `~/.local/share/ranger` called `tabs`. Wasn't able to open it through Ranger (because it didn't show that the file was there), had to access it through command line.

**Comment by serpent7776** [comment]
I just hit the same error. Here's steps to reproduce:

```sh
- mkdir -p /tmp/xxx/yyy
- ranger /tmp/xxx/yyy
- rm -rf /tmp/xxx  # outside of ranger
- # while still in /tmp/xxx in ranger open a new tab with gn
```
Results in an error:
```
ranger version: ranger-master 
Python version: 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
Locale: en_GB.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 204, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 416, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 370, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/titlebar.py", line 42, in draw
    self._calc_bar()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/titlebar.py", line 82, in _calc_bar
    self._get_left_part(bar)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/titlebar.py", line 106, in _get_left_part
    and (self.fm.thisdir.path.startswith(self.fm.home_path + "/")
AttributeError: 'NoneType' object has no attribute 'path'
```

```
$ pacman -Qi ranger | grep Version
Version         : 1.9.3+548+gf8b304f7-1
```

**Comment by serpent7776** [comment]
Not sure how should I test new version without affecting my existing installation, so I did the following:

```sh
> git clone https://github.com/ranger/ranger.git
> cd ranger/
> python3 -m venv venv
> . ./venv/bin/activate
> pip install -r requirements.txt
> python3 ./setup.py build
> python3 ./setup.py install --prefix /tmp/ranger
> cd /tmp/ranger/bin
> PYTHONPATH=/tmp/ranger/lib/python3.10/site-packages/ranger_fm-1.9.3-py3.10.egg/ ranger
```

Then I tried to reproduce the issue as described in my previous comment and ranger did not crash. A new tab was opened with directory that doesn't exist.
So it looks like it's fixed.
