### ISSUE TITLE
custom commands sshfs_lines in command.py crashes ranger

### ISSUE THREAD

**Issue by rtng** [ranger/ranger#2532]
ranger version: ranger 1.9.3
Python version: 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
Locale: None.None

Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/home/pi/.local/lib/python2.7/site-packages/ranger/core/main.py", line 413, in load_settings
    load_custom_commands(system_comm_path, custom_comm_path)
  File "/home/pi/.local/lib/python2.7/site-packages/ranger/core/main.py", line 400, in load_custom_commands
    custom_comm_path)
  File "/home/pi/.local/lib/python2.7/site-packages/ranger/core/main.py", line 389, in import_file
    module = imp.load_source(name, path)
  File "/home/pi/.config/ranger/commands.py", line 95
    show_error_in_console(f"Neither directory nor file: {selected}", fm)
                                                                  ^
SyntaxError: invalid syntax

ranger crashed.

**Comment by chu4ng** [comment]
Could you try python3 and post `sshfs_lines` from your command.py?

**Comment by rtng** [comment]
chu4ng , thanks .
i just changed ~/.config/ranger/commands.py  to '#! /usr/bin/python3'
and syntax-error warning in vim has vanished as a result ranger didn't crash at starting up
i will now test if sfs_mount will work correctly

**Comment by rtng** [comment]
oh no sorry it didn't work
i forgot that i commented all lines out to be able to start ranger again.

**Comment by rtng** [comment]
here my command.py http://ix.io/3J7q
i coppied from https://github.com/ranger/ranger/wiki/Custom-Commands#navigate-remote-hosts-via-sshfs

**Comment by chu4ng** [comment]
You can try this one. I made some changes. Also you can put it in `~/.config/ranger/plugins` and don't change commands.py.
https://files.catbox.moe/htzkuf.py

I'm testing that, but mount operation work properly.

**Comment by chu4ng** [comment]
sshfs_umount -> umount:
Set `cmd` var to `["umount", mount_path]` and unmount operation'll works too.
May be you can use that "diskutil" or change code to choose any of available, but I would like to use umount.

Also thanks for remind about that extension, lol. Code looks terrible, but this feature can be useful.
