### ISSUE TITLE
Ranger crashes on startup with viu as image preview method

### ISSUE THREAD

**Issue by amca01** [ranger/ranger#2545]
Hello,

I'm using ranger in Arch Linux.  In my `rc.conf` file, I've entered

```
set preview_images true
set preview_images_method viu
```

But when I start ranger, it crashes immediately with:

```
ranger version: ranger 1.9.3
Python version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
Locale: en_AU.UTF-8
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/usr/lib/python3.10/site-packages/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/usr/lib/python3.10/site-packages/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException
ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

This is entirely due to "viu" being chosen.  If I choose another method (say ueberzug, which has worked for others), then ranger starts fine, but doesn't preview images, except as coloured blocks.  However, in a terminal that supports image viewing (like kitty), then `viu an_image.jpg` displays fine.  Note that if I replace viu with "kitty" then ranger starts, but doesn't display the image.

Is there any way of getting ranger to use viu as its image preview method?

**Comment by markus-bauer** [comment]
You can't just set any displayer. It has to be implemented by ranger (viu isn't).

man ranger:
> "w3mimgdisplay", "ueberzug", "mpv", "iTerm2", "kitty", "terminology" or "urxvt" for image previews

Ranger supports the same preview methods as viu, like kitty or iterm. Is the problem that image display works with kitty and viu but not with kitty and ranger? 
By the way, at least for me, ueberzug also works in kitty (in x11 obviously).

 > Is there any way of getting ranger to use viu as its image preview method?

Not currently. If you want, you can try it. A starting point would be adding this to img_display.py:

```python
@register_image_displayer("viu")
class Viu(ImageDisplayer, FileManagerAware):
    def draw(self, path, start_x, start_y, width, height):
        # Example:
        process = Popen(["viu", "-w", str(width), "-h", str(height), path])
        process.wait()

    def clear(self, start_x, start_y, width, height):
        # TODO
        pass

    def quit(self):
        self.clear(0, 0, 0, 0)
```

Although I don't know if it can work, because viu expects to draw to the terminal and therefore draws over ranger/ncurses and messes with the cursor. And showing animated gifs breaks rangers ui. Also, I don't know if viu supports the positioning of the image (draw at x,y), but you could ask the developer. I don't think viu provides much over the existing preview methods. (Except animated gifs which would probably be difficult to integrate).

**Comment by toonn** [comment]
The reason the `kitty` preview method isn't working is probably that you have to install PIL (pillow on PyPI, I believe).
