### ISSUE TITLE
Ranger crashes when passed a non-directory path as an argument

### ISSUE THREAD

**Issue by tmzhuang** [ranger/ranger#2550]
#### Runtime Environment
- Operating system and version: 
Linux jupiter 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux
- Terminal emulator and version: 
alacritty 0.10.0 (8a26dee0)
- Python version: 
Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
- Ranger version/commit: 
ranger version: ranger 1.9.3
- Locale: 
en_US.UTF-8
#### Current Behavior
Ranger crashes with a python error.
#### Expected Behavior
Not too sure, I was just experimenting, but I don't think it should crash.
#### Steps to reproduce
Call ranger with any non-directory path. Eg:
```
ranger a.txt
```

#### Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'
```

**Comment by seinmon** [comment]
It seems to be happening only on compiled files (running `ranger` from `build/scripts-3.10`, and `build_scripts`). It doesn't crash if you run from the source code (`ranger.py` in the root directory of the project).

**Comment by toonn** [comment]
Yes, this issue was fixed on the master branch but hasn't gotten into a release yet. Apologies for the delays. On Arch you can install ranger-git from the AUR as an easy way to get the latest master version.
