### ISSUE TITLE
Ranger Crashes on Most Recent Update

### ISSUE THREAD

**Issue by njchristoffersen** [ranger/ranger#2563]
#### Runtime Environment

- Operating system and version: Archlinux 
- Terminal emulator and version: terminator, but checked with other terminals, same issue arises
- Python version: 3.10.2
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

ranger does not run and spits the error shown below. However, running 
```
ranger --clean
```
allows ranger to run properly, but without any of my preferences (namely, pdf viewing)

#### Expected Behavior
ranger to be able to run with preferences loaded

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.10/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!
```

**Comment by njchristoffersen** [comment]
It seemed to not like something in my
```
/home/username/.local/share/ranger
```
Nothing important was there, so I deleted the folder, let it regenerate, and ranger is back to regular functionality. Unfortunately, I did not have the foresight to try to figure out what was wrong with the folder. Leaving this open temporarily in case somebody knows the issue and wants to inform the thread what the issue was for future users.

**Comment by njchristoffersen** [comment]
> Have you tried master branch?

As in go straight to the ranger directory and running ranger directly from there? No, I didn't unfortunately.

**Comment by Gregaras** [comment]
> > Have you tried master branch?
> 
> As in go straight to the ranger directory and running ranger directly from there? No, I didn't unfortunately.

I mean download the current files from the repository or clone the repository. I'm not sure how to name it.

**Comment by seinmon** [comment]
I'm not sure, but it seems like there is an error with something you've bookmarked (or your configurations maybe?).

**Comment by markus-bauer** [comment]
self.bookmarktype(value), in this case, is an alias for Directory(value).
https://github.com/ranger/ranger/blob/7a5f820e760c7ce2f93e2a5f0e91677b46252ea9/ranger/core/fm.py#L124-L126

It fails here: 
https://github.com/ranger/ranger/blob/7a5f820e760c7ce2f93e2a5f0e91677b46252ea9/ranger/container/bookmarks.py#L239
https://github.com/ranger/ranger/blob/7a5f820e760c7ce2f93e2a5f0e91677b46252ea9/ranger/container/directory.py#L149-L150
It seems that it tries to create a Directory with a file path. The crash can be reproduced by adding a file path to your bookmarks file.
And adding a check like if os.path.isdir(value) in _load_dict avoids the crash.
It doesn't happen with ranger 1.9.3 packaged in ubuntu 21.10. I couldn't find the source for the crash though.

**Comment by toonn** [comment]
I believe there's already an open issue on this. It's slated to be fixed before the next release because it's pretty annoying. We want to simply warn about improper bookmarks and ignore them.

**Comment by hut** [comment]
Looks like a duplicate of https://github.com/ranger/ranger/issues/1896. Closing for now. If I'm mistaken, please let me know and I'll reopen.
