### ISSUE TITLE
try to trash a file get crash

### ISSUE THREAD

**Issue by WingDust** [ranger/ranger#2571]
#### Runtime Environment

- Operating system and version: Linux 5.16.9-arch1-1  + i3
- Terminal emulator and version: alacritty
- Python version: 3.10.2
- Ranger version/commit: ranger version: ranger 1.9.3 Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] 
- Locale: zh_CN.UTF-8

#### Current Behavior
try to trash a file get crash
and info show
```txt
Current file: '/run/media/1/z.zip'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
 File "/usr/lib/python3.10/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
  File "/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
#### Expected Behavior
trash a file right
#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by sarmong** [comment]
This has been fix 2 years ago in #1871.

However, since ranger didn't see a release since 2019 this is still a problem for many users.

And yes, I can download master version with Homebrew, but I don't want to use unstable version of the program.

So, it would be nice if someone could  point to a solution to this problem by modifying config files. (I assume it is in commands.py)

**Comment by Gregaras** [comment]
Seems to be similar problem: https://github.com/ranger/ranger/issues/2519

Answer by one member:
https://github.com/ranger/ranger/issues/2519#issuecomment-992906542

> Thanks for the reports, I'm tentatively closing this as fixed. The AUR has ranger-git packaged, otherwise you could install manually from the repository, as a workaround until we release the next version.

**Comment by WingDust** [comment]
May be some offend, I think use [trash-cli](https://github.com/andreafrancia/trash-cli) replace origin trash feature may be better.

**Comment by toonn** [comment]
Ranger already uses trash-cli if it's available. This problem is in a different part of the trash code and happens whether or not trash-cli is installed. Closing as it's been fixed on master. We're doing our best to make ranger ready for a new release. Master is pretty stable though, since merges don't happen that often and problems on master tend to get fixed fast.
