### ISSUE TITLE
ueberzug not displaying image previews

### ISSUE THREAD

**Issue by mqrris** [ranger/ranger#2585]
#### Runtime Environment
- Operating system and version: OpenBSD 6.9 GENERIC.MP#4 amd64
- Terminal emulator and version: st 0.8.4
- Python version: Python 3.8.12
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Not displaying image previews, just a blank empty space with no error.

#### Expected Behavior
Show image preview

#### Traceback

```
~ $  ranger --debug
ranger version: ranger 1.9.3
Python version: 3.8.12 (default, Sep  1 2021, 16:43:35) [Clang 10.0.1 ]
Locale: en_US.UTF-8
Current file: '/home/m1zqry/Downloads/gba.png'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/lib/python3.8/site-packages/ranger/core/fm.py", line 381, in loop
    ui.draw_images()
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/ui.py", line 401, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/widgets/pager.py", line 124, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/local/lib/python3.8/site-packages/ranger/core/actions.py", line 173, in notify
    raise obj
  File "/usr/local/lib/python3.8/site-packages/ranger/gui/widgets/pager.py", line 118, in draw_image
    self.fm.image_displayer.draw(self.image, self.x, self.y,
  File "/usr/local/lib/python3.8/site-packages/ranger/ext/img_display.py", line 743, in draw
    self._execute(
  File "/usr/local/lib/python3.8/site-packages/ranger/ext/img_display.py", line 740, in _execute
    self.process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by FranciscoDumont** [comment]
@mqrris What have you done, I'm having the same problem.
