### ISSUE TITLE
AttributeError when "trashing" files

### ISSUE THREAD

**Issue by raffaem** [ranger/ranger#2591]
#### Runtime Environment

- Operating system and version: Fedora Workstation 35
- Terminal emulator and version: kitty 0.24.4
- Python version: 3.10.2
- Ranger version/commit: 1.9.3 
- Locale: en_US.UTF-8

#### Current Behavior

Crash

#### Expected Behavior

Should not crash

#### Context

I marked 2 files and pressed `dT`

#### Traceback

```
$ ranger
ranger version: ranger 1.9.3
Python version: 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
Locale: en_US.UTF-8
Current file: '/home/raffaele/Documents/ranger_test/f1/o1.txt'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3.10/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
  File "/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by raffaem** [comment]
Duplicate of #2571

**Comment by toonn** [comment]
Thank you for self-closing. Working on the next release but it's slow going.

**Comment by toonn** [comment]
Thank you for self-closing. Working on the next release but it's slow going.
