### ISSUE TITLE
ranger crashes when .git directory is deleted

### ISSUE THREAD

**Issue by vitkabele** [ranger/ranger#2600]
#### Runtime Environment

- Operating system and version: Debian 11
- Terminal emulator and version: kitty 0.19.3
- Python version: 3.9.2
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

Ranger crashes

#### Expected Behavior

Ranger should not crash

#### Context

Possibly related to #1644 

#### Steps to reproduce
1. Create git repository (e.g. ranger)
2. Navigate to the repository with ranger
3. `:delete .git`, confirm
4. Press any key so that the view is refreshed
5. Enjoy the crash

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
Locale: en_US.UTF-8
Current file: '/tmp/ranger/doc'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/statusbar.py", line 104, in draw
    self._calc_bar()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/statusbar.py", line 109, in _calc_bar
    self._get_left_part(bar)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/statusbar.py", line 196, in _get_left_part
    vcsinfo = '({0:s}: {1:s})'.format(
TypeError: unsupported format string passed to NoneType.__format__

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by johny65** [comment]
This was reported back in 2020 in #1886 😃 .

**Comment by vitkabele** [comment]
My bad. I didn't notice this one. Closing this issue as duplicate then.
