### ISSUE TITLE
Ranger crashed with python 3.9.9

### ISSUE THREAD

**Issue by Vietoonet** [ranger/ranger#2606]
#### Runtime Environment

- Operating system and version: Linux Calculate 22 Mate
- Terminal emulator and version: st
- Python version: 3.9.9
- Ranger version/commit: 1.9.3
- Locale: fr_FR.UTF-8

#### Current Behavior
when executed the traceback below is displayed

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.9.9 (main, Jan 10 2022, 09:35:35) [GCC 11.2.0]
Locale: fr_FR.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.9/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.9/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.9/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

```

**Comment by Vietoonet** [comment]
ok remove ~/local/share/ranger/bookmarks file resolved the issue indeed. Thank you !
