### ISSUE TITLE
Ranger not working, referencing image display being unsupported.

### ISSUE THREAD

**Issue by asarma0804** [ranger/ranger#2620]
#### Runtime Environment

- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: kitty
- Python version: 3.10
- Ranger version/commit:1.9.3 
- Locale: en_GB.UTF-8
- 
#### Current Behavior/ Traceback:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/usr/lib/python3.10/site-packages/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/usr/lib/python3.10/site-packages/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException

ranger crashed. Please report this traceback at:
#### Expected Behavior

I would expect it to launch

#### Context

I just launched ranger. I'm not sure as to what's causing the issue, although I had recently installed i3-gaps.

**Comment by markus-bauer** [comment]
The error message isn't helpful (not your fault). Most of the time this means that you have set a wrong preview_images_method in rc.conf.
What have you set?

Ranger hasn't had a release in a while.
Try the newest version from git. I know that at least this error message is a little bit better in the master branch.

It now prints this:

```python 
raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException: 
"Strawberry" does not appear to be a valid setting for preview_images_method. 
Valid settings are: "iterm2", "kitty", "terminology", "ueberzug", "urxvt", "urxvt-full", "w3m".
```

**Comment by asarma0804** [comment]
I'll check it tomorrow and see the rc.conf file for it. Thanks for the direction
