### ISSUE TITLE
Settings that add information to the right of the "infostring" cause a crash

### ISSUE THREAD

**Issue by jmcantrell** [ranger/ranger#2641]
#### Runtime Environment

- Operating system and version: arch linux (packages updated as of 2022-06-11)
- Terminal emulator and version: alacritty 0.10.1

#### Current Behavior

Crashes with the attached traceback when opening.

#### Traceback

```
ranger version: ranger-master
Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Locale: en_US.UTF-8
Current file: '/home/jeremy/downloads'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 204, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 416, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 370, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 186, in draw
    self._draw_directory()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 426, in _draw_directory
    for txt, color in predisplay:
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by jmcantrell** [comment]
It opens fine when I change this line:
https://github.com/ranger/ranger/blob/master/ranger/gui/widgets/browsercolumn.py#L402

From:
```python
predisplay_right = infostring + sep + predisplay_right
```

To:
```python
predisplay_right = infostring + [sep] + predisplay_right
```

I'd offer a pull request, but I'm not sure I understand what this code is doing. Hopefully this helps you track it down.

**Comment by toonn** [comment]
Thanks for the report!

I think your fix is correct, I neglected to test with `vcs_aware` : /

If you PR, I'll fasttrack it, tomorrow.
