### ISSUE TITLE
tried to move a file to the trash using dT…

### ISSUE THREAD

**Issue by aloispichler** [ranger/ranger#2663]
Tried to move a file to the trash by using the keys `dT`.

#### Runtime Environment
ranger version: ranger 1.9.3
Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Locale: en_US.UTF-8

#### Current Behavior
crashes and exit

#### Expected Behavior
move a file to the trash

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3.10/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
  File "/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

```
Thank you

**Comment by markus-bauer** [comment]
I think this issue already exists:
https://github.com/ranger/ranger/issues/2361

If this is the same, then this might be fixed in the master branch (see the discussion there).

Did you search for existing issues before opening this one?

**Comment by aloispichler** [comment]
Yes, this fixes the error. Wonderful!
I realize that this fix is already 1+ year old. Please bring this change to AUR.
Thank you indeed.

**Comment by toonn** [comment]
The AUR has a `ranger-master` package that installs ranger from the master branch. There's some outstanding bugs I want to fix before releasing another (probably long-lived, let's face it) version.
