### ISSUE TITLE
NameError: name 're' is not defined

### ISSUE THREAD

**Issue by JoshuaJoma** [ranger/ranger#2668]
When starting ranger the following error occurs:
```
ranger version: ranger 1.9.3
Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
Locale: de_DE.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 413, in load_settings
    load_custom_commands(system_comm_path, custom_comm_path)
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 399, in load_custom_commands
    commands_custom = import_file('commands',
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 383, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/uwe/.config/ranger/commands.py", line 412, in <module>
    class setlocal(set_):
  File "/home/uwe/.config/ranger/commands.py", line 417, in setlocal
    PATH_RE = re.compile(r'^\s*path="?(.*?)"?\s*$')
NameError: name 're' is not defined

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

#### Runtime Environment

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-121-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-5300U CPU @ 2.30GHz
Memory: 11,4 GiB

- Terminal emulator and version: same problem on several terminals

#### Context
Error occured after upgrading Kubuntu 18.04 to 20.04

**Comment by tobiasjakobi** [comment]
This is a problem in your local `commands.py` (`/home/uwe/.config/ranger/commands.py`), not in ranger itself.

**Comment by JoshuaJoma** [comment]
Okay. Thx. Replacing my old commands.py with the last version of commands.py from the repository solved it.
