### ISSUE TITLE
ranger

### ISSUE THREAD

**Issue by andreyleonidovic** [ranger/ranger#2669]
OS MX-21 Debian
```ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
Locale: ru_RU.UTF-8
Current file: '/home/tal/Документы'

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/lib/python3.9/dist-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/local/lib/python3.9/dist-packages/ranger/gui/ui.py", line 251, in handle_input
    self.handle_keys(*keys)
  File "/usr/local/lib/python3.9/dist-packages/ranger/gui/ui.py", line 226, in handle_keys
    self.handle_key(key)
  File "/usr/local/lib/python3.9/dist-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/lib/python3.9/dist-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/local/lib/python3.9/dist-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/local/lib/python3.9/dist-packages/ranger/gui/widgets/console.py", line 217, in type_key
    self.on_line_change()
  File "/usr/local/lib/python3.9/dist-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    self.execute(cmd)
  File "/usr/local/lib/python3.9/dist-packages/ranger/gui/widgets/console.py", line 452, in execute
    cmd.execute()
  File "/usr/local/lib/python3.9/dist-packages/ranger/config/commands.py", line 1514, in execute
    self.fm.move(right=1)
  File "/usr/local/lib/python3.9/dist-packages/ranger/core/actions.py", line 528, in move
    self.thistab.enter_dir(tfile)
  File "/usr/local/lib/python3.9/dist-packages/ranger/core/tab.py", line 159, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/local/lib/python3.9/dist-packages/ranger/core/tab.py", line 49, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/local/lib/python3.9/dist-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/home/tal/.config/ranger/plugins/plugin_most_used.py", line 90, in update_current_path
    state.current_path = signal.new.path
AttributeError: 'NoneType' object has no attribute 'path'

ranger crashed.

```

**Comment by andreyleonidovic** [comment]
It's all about the plugin  'plugin_most_used.py' and I deleted it.
