### ISSUE TITLE
Immediate crash. homebrew installation on macOS

### ISSUE THREAD

**Issue by goodevilgenius** [ranger/ranger#2675]
#### Runtime Environment
- Operating system and version: macOS 12.4 (Monterey)
- Terminal emulator and version: iTerm2 3.4.8
- Python version: 3.10.5
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
See *Traceback* below

#### Context
This happened right after installing, first time running the program.

#### Possible Solutions
Installing through `pip` works. This seems limited to the homebrew installation.

#### Steps to reproduce
1. `brew install ranger`
2. `ranger`

#### Traceback

```
$ ranger
ranger version: ranger 1.9.3
Python version: 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Locale: en_US.UTF-8
Current file: '/Users/danjones/Applications'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/ext/cached_function.py", line 13, in inner_cached_function
    return cache[args]
KeyError: (<ranger.colorschemes.default.Default object at 0x10c9ac6d0>, 'in_titlebar', 'hostname', 'good')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/titlebar.py", line 43, in draw
    self._print_result(self.result)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/titlebar.py", line 152, in _print_result
    self.color(*part.lst)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/curses_shortcuts.py", line 73, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/ext/cached_function.py", line 15, in inner_cached_function
    value = fnc(*args)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/colorscheme.py", line 72, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color pair is greater than COLOR_PAIRS-1 (-1).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by command-z-z** [comment]
I think this problem is caused by `$TERM`, you maybe use `tmux-256color`, but this doesn't work in `tmux`.But you can use the following command to fix it.
add  `alias ranger='TERM=xterm-256color ranger' in your `~/.zhsrc` file or other bash files, now you use `ranger` to run ranger in `xterm-256color`. it's fine in tmux
