### ISSUE TITLE
Ranger crashes when opened inside of MTM a terminal multiplexer

### ISSUE THREAD

**Issue by TahaAbbasi-Hashemi** [ranger/ranger#2695]
sorry if the information isnt too useful, but ranger cant be opened on mtm(https://github.com/deadpixi/mtm). This may be a mtm problem or a ranger problem. The no such file issue makes me think its a ranger problem.  

#### Runtime Environment

- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: alacritty 0.10.1
- Python version: 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
crash. 

#### Expected Behavior
ranger should open 

#### Steps to reproduce
1. open mtm in any terminal window. alacritty or kitty for me. 
2. type "ranger" and hit enter
3. crash

#### Traceback
```
ranger version: ranger 1.9.3
Python version: 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.10/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Oh, actually, I was too quick. This sounded like a previous issue so I tagged it as a bug but I can't actually reproduce this. Could you check whether the issue still occurs for you on the master branch? You can run `python3 ranger.py` from the repository without installing it.

Apologies for taking so long to get around to this.

**Comment by gnull** [comment]
I had a similar crash as @TahaAbbasi-Hashemi on Ubuntu 24.04. I tried cloning master (38bb8901004b75a407ffee4b9e176bc0a436cb15) and running `python3 ranger.py`, it has worked perfectly, no crashes.

<details>
<summary>my stacktrace</summary>

```
$ ranger
ranger version: ranger 1.9.3
Python version: 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
Locale: ru_RU.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
                         ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

</details>
