### ISSUE TITLE
Ranger crash for YAML files - Color number is greater than COLORS-1 (7)

### ISSUE THREAD

**Issue by ttxtea** [ranger/ranger#2752]
#### Runtime Environment
- ranger version: ranger 1.9.3 (todays master)
- Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
- Operating system and version:  Ubuntu 22.04.1 LTS
- Terminal emulator and version: Tilix 1.9.4

#### Current Behavior
Ranger crashes when displaying YAML/yml files. I think it also crashes for some other files. For example mardown files if they include some YAML blocks.

#### Context
I noticed this behaviour first, when updating to Ubuntu 22.04

#### Steps to reproduce
1.  navigate to some yaml file and let it display on the right pannel
2.  natigate to some markdown file which has a YAML code block (in the beginning)

#### Traceback

```
raceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "~/.local/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "~/.local/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "~/.local/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "~/.local/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "~/.local/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "~/.local/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "~/.local/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "~/.local/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "~/.local/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "~/.local/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "~/.local/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "~/.local/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

```

**Comment by anktx** [comment]
same issue:
```
ranger version: ranger 1.9.3
Python version: 3.10.8 (main, Nov 20 2022, 12:02:53) [GCC 11.3.0]
Locale: en_US.UTF-8
Current file: '/home/user/esphome/esp1.yaml'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).
```

**Comment by Devidxyz** [comment]
Same issue with a simple python file:
```py
class A:
    @property
    def b(self):
        pass
```
```
ranger version: ranger 1.9.39K 2022-11-27 23:39
Python version: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
Locale: en_US.UTF-8
Current file: '/home/devid/feladat.py'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

OS: Arch, kernel: 6.0.9-arch1-1, WM: i3 4.21.1, terminal: kitty 0.26.5

**Comment by ttxtea** [comment]
So it is really not restricted to `YAML` files (sorry for the misleading issue title). It happens in the `get_color` function, at the `curses.init_pair` call. I dont which solution would make sense here. It looks as if wrong fourground / background pairs should actually be handeled by switching to default colors?

**Comment by DaikoGit** [comment]
Same issue.

```

ranger version: ranger 1.9.3
Python version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
Locale: en_US.UTF-8
Current file: '/home/daiko/strap.sh'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

OS: Arch, kernel: 6.1.3-arch1-1 , WM: i3 , terminal: cool-retro-term

**Comment by toonn** [comment]
If someone could test #2804 that'd be great because I can't reproduce the issue.

**Comment by sz-hankus** [comment]
@toonn I took a look at this issue and found that setting the `TERM` environment variable to something like `screen` (which apparently only handles 8 colors) made it easy to reproduce the issue.

**Comment by ttxtea** [comment]
A similar issue has been rasied [here](https://github.com/ranger/ranger/issues/2800).

**Comment by ttxtea** [comment]
For me the issues ceases if dont start `ranger` in `tmux`, which is my default. In the normal `tilix` terminal there seem to be enough colours.

**Comment by toonn** [comment]
@sz-hankus, that doesn't reproduce the issue for me. Still looking for testing of #2804.

**Comment by sz-hankus** [comment]
> @sz-hankus, that doesn't reproduce the issue for me. Still looking for testing of #2804.

@toon Hmm, that's strange. I tested it on a couple platforms/terminals. What I always did was set `TERM=screen`, made sure the output of `tput colors` is `8` and then tried to get ranger to generate some color which was not in the range of the standard `8` terminal colors. It usually happens when previewing code files (e.g. C, Python or JS) with syntax highlighting. Maybe you can try using `bat` to make ranger output more colors

**Comment by toonn** [comment]
That was probably why I wasn't managing to reproduce yeah. I was under the impression that the colors from the colorscheme were enough to trigger the issue. It's merged now anyway though so should no longer be an issue. I figure I'll hear about it if it's still broken : )
