### ISSUE TITLE
VCS exception when copying .git directory.

### ISSUE THREAD

**Issue by Alexey104** [ranger/ranger#2759]
**OS: archlinux
Terminal: alacritty
ranger version: ranger 1.9.3
Python version: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
Locale: en_US.UTF-8**

Hello!
I've read #1886 and have a similar problem, but with copying `.git` folder, not deletion. Attempt to yank and paste `.git` directory leads to the following results:

<details>
  <summary>Log</summary>

```
22:44:54 INFO ranger version: ranger 1.9.3
22:44:54 INFO Python version: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
22:44:54 INFO Locale: en_US.UTF-8
22:44:54 INFO Process ID: 243471
22:45:03 ERRO Notification: VCS Exception: View log for more info
22:45:03 ERRO ['git', 'ls-files', '-z', '--others', '--directory', '--ignored', '--exclude-standard']: /home/alexey/temp
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/ext/vcs/vcs.py", line 125, in _run
    output = spawn.check_output(cmd, cwd=path, decode=not retbytes)
  File "/usr/lib/python3.10/site-packages/ranger/ext/spawn.py", line 41, in check_output
    raise error
subprocess.CalledProcessError: Command '['git', 'ls-files', '-z', '--others', '--directory', '--ignored', '--exclude-standard']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/ext/vcs/vcs.py", line 249, in update_root
    self.status_subpaths = self.data_status_subpaths()
  File "/usr/lib/python3.10/site-packages/ranger/ext/vcs/git.py", line 127, in data_status_subpaths
    paths = self._run([
  File "/usr/lib/python3.10/site-packages/ranger/ext/vcs/vcs.py", line 134, in _run
    raise VcsError('{0:s}: {1:s}'.format(str(cmd), path))
ranger.ext.vcs.vcs.VcsError: ['git', 'ls-files', '-z', '--others', '--directory', '--ignored', '--exclude-standard']: /home/alexey/temp
```
</details>

It happens with any git repo, regardless of copy destination. However, no problems with `dd + p` or `dD + Return + y`, only yank operation fails (`yy + p`).

Please, let me know if you need any additional info.

**Comment by toonn** [comment]
Apologies for taking so long to reply but this does indeed sound like a bug. If you run that `git ls-files` command after copying the `.git` folder there manually, is there a more informative error message?

**Comment by Alexey104** [comment]
Hey, no need to apologize, you don't owe anything to me. Regarding the issue, this is how to reproduce it:
```
mkdir ~/git
cd ~/git
git clone https://github.com/ranger/ranger
ranger

# inside Ranger: 
:cd ranger
v # select all
yy #yank
h #back
!mkdir test
:cd test
p # paste - VCS exception occurs here
```
According to the Ranger log:
```
Command '['git', 'ls-files', '-z', '--others', '--directory', '--ignored', '--exclude-standard']' returned non-zero exit status 128.
```
If I execute this command manually in the destination directory after copying files, it does not show any errors. To return 128 (as in the log) `git` command should be executed anywhere outside of an actual git working tree:
```
cd ~/not-a-git-repo
git ls-files -z --others --directory --ignored --exclude-standard # fatal: not a git repository (returned 128)
```
The problem occurs only when `.git` directory is being copied and `set vcs_aware` is `true` in Ranger.

**Comment by toonn** [comment]
Hmm, I'm having trouble reproducing the issue. Copying repo contents (after showing hidden files like `.git` with `zh`) doesn't trigger a problem. The one thing that caused a crash for me was deleting the contents, including `.git`, after all the VCS checkmarks and such have loaded.

```
Traceback (most recent call last):
  File "/Users/toonn/src/ranger/ranger/core/main.py", line 204, in main
    fm.loop()
  File "/Users/toonn/src/ranger/ranger/core/fm.py", line 417, in loop
    ui.redraw()
  File "/Users/toonn/src/ranger/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/Users/toonn/src/ranger/ranger/gui/ui.py", line 370, in draw
    DisplayableContainer.draw(self)
  File "/Users/toonn/src/ranger/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/Users/toonn/src/ranger/ranger/gui/widgets/statusbar.py", line 110, in draw
    self._calc_bar()
  File "/Users/toonn/src/ranger/ranger/gui/widgets/statusbar.py", line 115, in _calc_bar
    self._get_left_part(bar)
  File "/Users/toonn/src/ranger/ranger/gui/widgets/statusbar.py", line 202, in _get_left_part
    vcsinfo = '({0:s}: {1:s})'.format(
              ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to NoneType.__format__
```

Maybe the crash you're experiencing has been fixed on the master branch, could you try cloning and running `ranger.py` from the repo? And it'd be great if you could confirm whether the issue I'm experiencing happens to you too.

**Comment by Alexey104** [comment]
> Does the diff make any sense? It's weird that copying would change the file content.

Yeah, that's strange, but `diff` really says that `.git/index` files differ between source and destination. 

Honestly, this VCS exception looks more like a "cosmetical" issue than a real problem. Despite the red error message during copying, I don't observe any problems working with destination directory - it behaves like a normal git repo with all original files preserved and all git commands working normally. Furthermore, even if I simply create an empty directory, name it `.git` and copy it anywhere using Ranger, I still get this VCS exception message, but nothing bad really happens.

Not sure, maybe this is something related to my specific system configuration and settings, no other users seem to complain about this. It looks like I can just safely ignore this message and don't bother. I just saw #1886 and decided to report about somehow similar issue, but I don't want to be a burden and waste your time. If you find this to be something unrelated to Ranger, feel free to close this.
