### ISSUE TITLE
"list index out of the range" in qterminal in preview image

### ISSUE THREAD

**Issue by johna23-lab** [ranger/ranger#2781]
Hi! i have this error in qterminal (1.2.0), but in xfce-terminal works fine (i can view the preview of the images), i tried the official version and the git version too.

**Comment by toonn** [comment]
Without more detail, at least the full error message, this isn't actionable. So closing until that information is added.

**Comment by txl263** [comment]
Same error.
ranger --debug
ranger version: ranger 1.9.3
Python version: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
Locale: zh_CN.UTF-8
Current file: '/home/Eric/.config/neofetch/pngs/aisaka.png'

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 381, in loop
    ui.draw_images()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 401, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/pager.py", line 124, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 173, in notify
    raise obj
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/pager.py", line 118, in draw_image
    self.fm.image_displayer.draw(self.image, self.x, self.y,
  File "/usr/lib/python3.11/site-packages/ranger/ext/img_display.py", line 178, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/ext/img_display.py", line 226, in _generate_w3m_input
    fontw, fonth = self._get_font_dimensions()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/ext/img_display.py", line 167, in _get_font_dimensions
    xpixels, ypixels = int(output[0]), int(output[1])
                           ~~~~~~^^^
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by toonn** [comment]
@txl263, can you verify whether this still occurs on the master branch?
