### ISSUE TITLE
`source ranger` alias in xonsh: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by anki-code** [ranger/ranger#2785]
Hello! ranger is cool!

I'm trying to use it in [xonsh shell](https://xon.sh/) as an alias but I've got an error: 

```xsh
# install xonsh
pip install 'xonsh[full]'
xonsh --no-rc

source ranger
# it works fine

aliases['r'] = 'source ranger'
r
# ranger version: ranger 1.9.3
# Python version: 3.11.1 (main, Dec 23 2022, 09:25:23) [Clang 14.0.0 (clang-1400.0.29.202)]
# Locale: None.UTF-8

# Traceback (most recent call last):
#   File "/opt/homebrew/lib/python3.11/site-packages/ranger/core/main.py", line 147, in main
#     curses_interrupt_handler.install_interrupt_handler()
#   File "/opt/homebrew/lib/python3.11/site-packages/ranger/ext/curses_interrupt_handler.py", line 41, in install_interrupt_handler
#     signal.signal(signal.SIGINT, _interrupt_handler)
#   File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/signal.py", line 56, in signal
#     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
#               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# ValueError: signal only works in main thread of the main interpreter
# 
# ranger crashed. Please report this traceback at:
# https://github.com/ranger/ranger/issues
```

How we can solve it on ranger or on xonsh side?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by toonn** [comment]
Since this error is happening in a Python standard library I think we can't do much about this. I wonder what Xonsh is doing different from other shells here?

Closing until someone can show Ranger can do something about this.

**Comment by toonn** [comment]
Ranger isn't sending a signal though. It's only trying to register a signal handler for SIGINT A.K.A. ^C.

**Comment by toonn** [comment]
That's not an option, we *need* to handle SIGINT.
