### ISSUE TITLE
Ranger kitty error

### ISSUE THREAD

**Issue by Dmitriy811** [ranger/ranger#2796]
when i run ranger with sudo i get an error, however on standard terminal and iterm2, no problem

```
❯ sudo ranger

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ranger/core/main.py", line 32, in main
    from ranger.container.settings import Settings
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ranger/container/settings.py", line 13, in <module>
    from ranger.gui.colorscheme import _colorscheme_name_to_class
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ranger/gui/colorscheme.py", line 33, in <module>
    from ranger.gui.color import get_color
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ranger/gui/color.py", line 74, in <module>
    curses.setupterm()
_curses.error: setupterm: could not find terminal
```

When I use ranger without sudo, kitty has no problems
MacOS monterey

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work

**Comment by Dmitriy811** [comment]
> https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work

Thanks, the problem went away after editing visudo, I don't understand why, I didn't do it before, even though I read the documentation

```
Defaults env_keep += "TERM TERMINFO"
```
