### ISSUE TITLE
`ValueError: Color number is greater than COLORS-1 (7).`

### ISSUE THREAD

**Issue by samuela** [ranger/ranger#2800]
#### Runtime Environment

- Operating system and version: Ubuntu 20.04
- Terminal emulator and version: tmux 3.0a
- Python version: 3.10.10
- Ranger version/commit: ranger 1.9.3
- Locale: en_US

#### Current Behavior
I just received an error:
```
❯ r /home/sam.ainsworth/.cache/bazel/_bazel_sam.ainsworth/137a2db70177173dc581aa36c69b306c/
ranger version: ranger 1.9.3
Python version: 3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0]
Locale: en_US.UTF-8
Current file: '/home/sam.ainsworth/.cache/bazel/_bazel_sam.ainsworth/137a2db70177173dc581aa36c69b306c/execroot/DO_NOT_BUILD_HERE'

Traceback (most recent call last):
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/nix/store/w0y8xfz4ymln8lx0h5k91w2y4mfbg7s3-ranger-1.9.3/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

It seems to happen every time i scroll past this file named `/home/sam.ainsworth/.cache/bazel/_bazel_sam.ainsworth/137a2db70177173dc581aa36c69b306c/execroot/DO_NOT_BUILD_HERE`.

`DO_NOT_BUILD_HERE` is a simple text file containing simply
```
/home/sam.ainsworth/dev/cruise
```

#### Expected Behavior
ranger not to crash

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by sz-hankus** [comment]
Hi! 
You stated tmux as your terminal emulator. Could you please provide some additional information?
1. The value of your `TERM` environment variable in tmux
2. Output of `tput colors`

**Comment by ttxtea** [comment]
Hi this is same issue as [this](https://github.com/ranger/ranger/issues/2752). It is still going on for me and it is so frequent, that it renders my most beloved file manager (I do everything with ranger) unusable.

It happens for files with URLs in them, but also some other cases.

**Comment by sz-hankus** [comment]
@ttxtea This issue is currently being addressed. It would be really helpful if you could clone and build ranger from [this branch](https://github.com/toonn/ranger/tree/too-many-colors) and report if the fix works for you.
In the meantime (while the fix is being reviewed) you can also try adding the following line to your `.tmux.conf` :
```
set -g default-terminal "screen-256color"
```

**Comment by ttxtea** [comment]
Upon cloning and running `make` I get

~~~
Your code has been rated at 9.46/10 (previous run: 9.46/10, +0.00)

make: *** [Makefile:83: test_pylint] Error 30
~~~

**Comment by sz-hankus** [comment]
Did you clone and checkout to the `too-many-colors` branch?
```
git clone https://github.com/toonn/ranger.git test
cd test
git checkout too-many-colors
make
```

**Comment by ttxtea** [comment]
Ah, sorry I am not that versed in these things. Now, being in the right branch, all unit tests pass. I only get a
~~~
Checking completeness of man page...
/usr/bin/env: ‘python’: No such file or directory
make: *** [Makefile:132: test_other] Error 127
~~~
in the end.

**Comment by sz-hankus** [comment]
No worries. 
Do you have python installed? If so, can you run it from the command line? e.g. `python` or `python3`?

**Comment by ttxtea** [comment]
yes, both `python` and `python3` map to `python3.10.6`.

**Comment by sz-hankus** [comment]
Hm, maybe skip the tests for now and just run
```
make compile
python ranger.py
``` 
Is `python` an alias in your session by any chance? You can check that with `type python`

**Comment by ttxtea** [comment]
Hi, yes `type pyton`  is aliased to `python3`.

But `make complile` and `python ranger.py` worked. I started `python ranger.py` in a `tmux` session and check the typically problematic files like `yaml` files or markdown with urls in it. All seems to work very stably right now!! Il keep testing but I think you have caught the bug!!!! Many thanks. If anything happens in the upcoming days I'll report it here.

**Comment by ttxtea** [comment]
After two weeks of ranger testing, I never encountered the `ValueError` anymore. In particular, the `yml`, `markdown` with urls not work as before. If there is anything else I can test just post it. Otherwise, I dont know how the procedure is, but I guess the `too-many-colors` branch? branch could be merged into `main`. Thanks again!

**Comment by toonn** [comment]
Ok, thanks for testing, will merge : )

FYI, there's no need to run `make` for Ranger. You can just run `ranger.py` straight from the repository. The only make target that might be interesting is `make install` for manually installing Ranger from the repo.
