### ISSUE TITLE
`:flat 1` crashes ranger

### ISSUE THREAD

**Issue by vejkse** [ranger/ranger#2812]
#### Runtime Environment

- Operating system and version: Linux 6.2.7
- Terminal emulator and version: Alacritty
- Python version: 3.10.10
- Ranger version/commit: 8875ad2f (the problem arises already with 46660c27)
- Locale: mixture of en_US.UTF-8, en_DK.UTF-8, POSIX

#### Current Behavior

When executing `:flat 1` in any directory, ranger crashes.  Tested with `ranger --clean`.

#### Expected Behavior

Not crashing and displaying all files up to depth 1.

#### Possible Solutions

Rollback to a previous version.  I have commit f8b304f7 available and it works fine.

#### Traceback

```
ranger version: ranger-master
Python version: 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
Locale: en_US.UTF-8
Current file: '/home'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 204, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 417, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 370, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 98, in draw
    directory.load_content_if_outdated()
  File "/usr/lib/python3.10/site-packages/ranger/container/directory.py", line 678, in load_content_if_outdated
    real_mtime = mtimelevel(self.path, self.flat)
  File "/usr/lib/python3.10/site-packages/ranger/container/directory.py", line 89, in mtimelevel
    for dirpath, dirnames, _ in walklevel(path, level):
  File "/usr/lib/python3.10/site-packages/ranger/container/directory.py", line 78, in walklevel
    assert os.path.isdir(some_dir)
AssertionError
```

**Comment by vejkse** [comment]
So, after looking at the `pylint` bug, which is not solved for this specific case, rather than reverting the commit 49fc14d, it suffices to add a `*` in the line:
```python
mtime = max(mtime, *[-1] + [os.stat(d).st_mtime for d in dirlist])
```

**Comment by toonn** [comment]
I've opened a PR, tried to add you as a co-author on the commit with a GitHub no-reply email. Could you confirm I used the correct committer email address for you, or whether you'd prefer not to be listed in the first place?

**Comment by vejkse** [comment]
Sorry, I just saw this, having been busy these last few days.  I think I’d just prefer not to be listed.
