### ISSUE TITLE
import PY3 failed with loading commands.py 

### ISSUE THREAD

**Issue by yorkbai** [ranger/ranger#2817]
#### Runtime Environment

- Operating system and version:  macos 10.14.6
- Terminal emulator and version:  iterm2 Build 3.5.20220627-nightly
- Python version: 3.11.2
- Ranger version/commit:  1.9.3
- Locale: 

#### Current Behavior
    1. run 'ranger' on iterm2 
    2.  checking the log info with ':diaplay_log' found the following log and all commands declear in commands.py not running normally. the error info is "command not found"
  
#### Context

Message Log:
09:35:38 INFO ranger version: ranger 1.9.3
09:35:38 INFO Python version: 3.11.2 (main, Mar  2 2023, 10:57:07) [Clang 11.0.0 (clang-1100.0.33.17)]
09:35:38 INFO Locale: en_US.UTF-8
09:35:38 INFO Process ID: 91454
09:35:38 ERRO cannot import name 'PY3' from 'ranger' (/Users/worker/Library/Python/3.11/lib/python/site-packages/ranger/__init__.py)
Traceback (most recent call last):
  File "/Users/worker/Library/Python/3.11/lib/python/site-packages/ranger/core/main.py", line 399, in load_custom_commands
    commands_custom = import_file('commands',
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/worker/Library/Python/3.11/lib/python/site-packages/ranger/core/main.py", line 383, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yorkbai/.config/ranger/commands.py", line 98, in <module>
    from ranger import PY3
ImportError: cannot import name 'PY3' from 'ranger' (/Users/worker/Library/Python/3.11/lib/python/site-packages/ranger/__init__.py)

**Comment by toonn** [comment]
The current `commands.py` isn't compatible with 1.9.3. You could replace the import with `PY3 = version_info[0] >= 3`.
