### ISSUE TITLE
Ranger crash on fedora 37 running as root

### ISSUE THREAD

**Issue by flyingrhinonz** [ranger/ranger#2831]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
                         ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues



```

**Comment by kibuff** [comment]
Had the same issue on my Raspberry Pi 4 (Raspbian 11).
Installing the package "screen" solved my problem.
If you use dnf as package manager, `sudo dnf update && sudo dnf install screen -y` should fix the problem (did not test the command, since I've never used fedora, thought.
