### ISSUE TITLE
AttributeError: 'str' object has no attribute 'path'

### ISSUE THREAD

**Issue by incandescentman** [ranger/ranger#2845]
#### Runtime Environment

- Operating system and version: MacOS 13.3.1 (a) (22E772610a)
- Terminal emulator and version: Kitty 0.28.1
- Python version: 3.11.3
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. dT (delete Trash of a folder)
2. 
3. 

#### Traceback

```
$ ranger
ranger version: ranger 1.9.3
Python version: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
Locale: en_US.UTF-8
Current file: '/Users/jay/Downloads/1920s inspiration album'

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
                 ^^^^^^
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
```

**Comment by toonn** [comment]
I think this was fixed on the master branch. Could you try running Ranger from there? Do note that on macOS Ranger will use `~/.local/share/Ranger/Trash` to move trash to, not the Finder Trash.

**Comment by incandescentman** [comment]
Thanks! How do I run from master branch? I installed it with homebrew using brew install ranger. It's version 1.9.3_2.

**Comment by toonn** [comment]
You'd simply clone the repository and then run `python3 /path/to/ranger.py`.

**Comment by incandescentman** [comment]
That works, thank you so much!

**Comment by toonn** [comment]
Ok, closing this because it's fixed on master then.

**Comment by goetzc** [comment]
Are you planning on releasing a new version? So it can be shipped by Homebrew and other package managers.

**Comment by adrian-gralak95** [comment]
+1 can confirm this is issue still to be on the latest version from apt :(
