### ISSUE TITLE
Crashing on console trash

### ISSUE THREAD

**Issue by rsaavedraxyz** [ranger/ranger#2858]
Hi.

I noticed ranger crashes on console trash.
I get the following output:

```
ranger version: ranger-master istent '--'
Python version: 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
Locale: en_GB.UTF-8
Current file: '/path/to/file.txt'

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 214, in main
    fm.loop()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 423, in loop
    ui.handle_input()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/gui/displayable.py", line 283, in press
    focused_obj.press(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 193, in press
    self.type_key(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 219, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 202, in _answer_question
    callback(answer)
  File "/home/user/.config/ranger/commands.py", line 764, in _question_callback
    self._trash_files_catch_arg_list_error(files)
  File "/home/user/.config/ranger/commands.py", line 772, in _trash_files_catch_arg_list_error
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 447, in execute_file
    return execute()
           ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 445, in execute
    return self.rifle.execute(filenames, mode, label, flags, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/ext/rifle.py", line 525, in execute
    raise CalledProcessError(exit_code, shlex.join(cmd))
subprocess.CalledProcessError: Command '/bin/sh -c 'set -- '"'"'/path/to/file.txt'"'"'; trash-put -- "$@"'' returned non-zero exit status 74.

ranger crashed.
```

**Comment by acid-bong** [comment]
Your output got two lines in the beginning mashed up, actually it's:
```
trash-put: cannot trash non existent '--'
ranger version: ranger-master
Python version: 3.11.3 (main, Jun  9 2023, 17:58:58) [GCC 12.2.1 20230428]
[...]
```
Trash-cli got updated at some point -- the current version, 0.23.2.13.2, came out this February, but some distros distributed it later (on Gentoo it was added in March and considered stable in May). And in this version the `--` separator doesn't work anymore.

Solution: in `rifle.conf` remove `--` from the line that mentions `trash-put` (the penultimate one).

**Comment by rsaavedraxyz** [comment]
Thank you @acid-bong, that works.

**Comment by toonn** [comment]
@acid-bong, is `--` only supported in recent versions or no longer supported?

**Comment by acid-bong** [comment]
Was supported, now not
