### ISSUE TITLE
Cannot delete deeply-recursive folders

### ISSUE THREAD

**Issue by bczhc** [ranger/ranger#2867]
#### Runtime Environment

- Operating system and version: Archlinux; kernel 6.3.7
- Terminal emulator and version: Alacritty-sixel 0.12.0-dev (53110c6)
- Python version: 3.11.3
- Ranger version/commit: ranger-master
- Locale: en_US.UTF-8

#### Current Behavior
Ranger crashes.

#### Expected Behavior
Not so.

#### Context

I have many very deeply recursive folders created using this Ruby script (run it for ~1s):
```ruby
#!/bin/env ruby

require 'fileutils'

while true do
  name = (0...255).map { ('a'..'z').to_a[rand(26)] }.join
  puts name
  Dir.mkdir name
  Dir.chdir name
  File.open(name.reverse, 'w') { |x| x.write "hello" }
end
```
And when I tried to delete the folder it created, `ranger` crashed. Filesystem is Btrfs.

#### Possible Solutions
`rm -rf` works fine.

#### Steps to reproduce
1. Recursively create a bunch of folders.
2. In `ranger`, do `:delete`.
3. Crashes.

#### Traceback

```
ranger version: ranger-master
Python version: 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
Locale: en_US.UTF-8
Current file: '/home/bczhc/t/depth'

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 214, in main
    fm.loop()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 423, in loop
    ui.handle_input()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/gui/displayable.py", line 283, in press
    focused_obj.press(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 193, in press
    self.type_key(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 219, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 202, in _answer_question
    callback(answer)
  File "/usr/lib/python3.11/site-packages/ranger/config/commands.py", line 779, in _question_callback
    self.fm.delete(files)
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 1647, in delete
    shutil.rmtree(path)
  File "/usr/lib/python3.11/shutil.py", line 732, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 983 more times]
  File "/usr/lib/python3.11/shutil.py", line 638, in _rmtree_safe_fd
    fullname = os.path.join(path, entry.name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 77, in join
RecursionError: maximum recursion depth exceeded

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by eMPee584** [comment]
Ok but 983 is not a common directory depth? that is ABUSE 🤣
Also, any other software using `shutil.rmtree` will fail this absurd test. Very little point on circumventing it in ranger...
Actually, this is being worked on in python: https://github.com/python/cpython/issues/89727

**Comment by dgshanee** [comment]
It shouldn't crash though, right? Even with 983 recursive folders.

**Comment by bczhc** [comment]
> It shouldn't crash though, right? Even with 983 recursive folders.

Cool! I tested with ranger 1.9.4, and it deleted them correctly. No crash happened. - Even with a very very horrible amount of recursive folders:

```console
/mnt/nvme/1 ❯ find . | wc -l                                                                                   12:25:09
10726
```

😄
