### ISSUE TITLE
ranger crashed when running it remotely

### ISSUE THREAD

**Issue by Bogfoot** [ranger/ranger#2869]
#### Runtime Environment
ranger version: ranger 1.9.3
Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Locale: en_US.UTF-8

#### Current Behavior
Crashes on launch

#### Expected Behavior
Opens on launch

#### Context
Just trying to view files remotely on my laptop

#### Steps to reproduce
1. SSH to my laptop
2. Type "ranger" in terminal
3. Crashes

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3/dist-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

```

**Comment by toonn** [comment]
This is a bug that was fixed on the master branch. Easiest fix is to clone the repo and run `ranger.py`, though you can also install it with `make install`.
