### ISSUE TITLE
Ranger crashes for color number is greater than COLORS-1

### ISSUE THREAD

**Issue by wang3522** [ranger/ranger#2877]
#### Runtime Environment

- Operating system and version:  Ubuntu Server 22.04 
- Terminal emulator and version: MobaXterm
- Python version:  3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
- Ranger version/commit:  ranger 1.9.3
- Locale:  en_US.UTF-8

#### Current Behavior
Browse a directory using ranger and it crashes when entering a subdirectory
#### Expected Behavior
No crash
#### Context

Use ranger
#### Possible Solutions
Guess it has conflicts with LS_COLORS defined in .bashrc but not sure

#### Steps to reproduce
1. run ranger in a directory
2. enter any sub dir
3. crash

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3/dist-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

```

**Comment by wang3522** [comment]
This is the LS_COLORS in my terminal
LS_COLORS='rs=0:di=1;35:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:';

**Comment by anabelle2001** [comment]
+1. Same issue encountered in the wild here. On my ubuntu 2204 box, here's my traceback.
```
╭──(anabelle@haswell-server) [~/ansible/sql (main)] [127]
╰─$ ranger
ranger version: ranger 1.9.3
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Locale: en_US.UTF-8
Current file: '/home/anabelle/ansible/sql/config.yml'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3/dist-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
I'm using fish-shell and my `$LS_COLORS` variable is undefined

**Comment by sz-hankus** [comment]
Please take a look at [#2752](https://github.com/ranger/ranger/issues/2752)

**Comment by toonn** [comment]
Yeah, this should be fixed on the master branch.
