### ISSUE TITLE
ValueError: Color number is greater than COLORS-1 (7).

### ISSUE THREAD

**Issue by webgtx** [ranger/ranger#2890]
#### Runtime Environment
- Operating system and version: Fedora Linux 37
- Terminal emulator and version: alacritty 0.10.1
- Python version:  3.11.1 
- Ranger version/commit: 1.9.3
- Locale: en

#### Current Behavior
Work's ok until you select any file to preview

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
Locale: en_US.UTF-8
Current file: '/home/dxv1d/Downloads/github-recovery-codes.txt'

Traceback (most recent call last):
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
                                       ^^^^^^^^^^^^^^^^^
  File "/home/dxv1d/.local/lib/python3.11/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by webgtx** [comment]
@rrichardscfa 
> I am getting this as well.

### Try this:
- `rpm-ostree cleanup -p`
- `rpm-ostree cleanup -m`
- `rpm-ostree cleanup --rollback`

**Comment by vejkse** [comment]
This is a known issue, that should be fixed in the current (unreleased) version of the code: https://github.com/ranger/ranger/issues/2752

**Comment by toonn** [comment]
You can try installing Ranger from the repository. `make install` should do the trick. Though you could also simply add a symlink to `ranger.py` in a directory that's on your `PATH`.

Closing as this is fixed.
