### ISSUE TITLE
help crashing 

### ISSUE THREAD

**Issue by Sparcky4860** [ranger/ranger#2891]
#### Runtime Environment
ranger version: ranger 1.9.3
Python version: 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)]
OS: macos
#### Current Behavior
Crases 

#### Expected Behavior
load prevue 
#### Context

ues ranger 

#### Steps to reproduce
hover over file that has a preview 

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Locale: None.UTF-8
Current file: '/Users/sparcky/ CFUserTextEncoding'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/ranger/core/main. py", line 201,
in main
fm. loop()
File "/usr/local/lib/python3.11/site-packages/ranger/core/fm-py", line 377, in loop
ui. redraw()
File "/usr/local/lib/python3.11/site-packages/ranger/gui/ui.py", line 333, in redraw
self.draw()
File "/usr/local/lib/python3.11/site-packages/ ranger/gui/ui.py", line 360, in draw
DisplayableContainer.draw(self)
File "/us/local/lib/python3.11/site-packages/ranger/gui/displayable-py", line 260,
in draw
displayable. draw)
File "/usr/local/lib/python3.11/site-packages/ranger/gui/widgets/view_miller.py", line 100,
in draw
DisplayableContainer.draw(self)
File "/usr/local/lib/python3.11/site-packages/ranger/gui/displayable.py", line 260,
in draw
displayable.draw()
File "/usr/local/lib/python3.11/site-packages/ ranger/gui/widgets/browsercolumn-py",
self._draw_file()
line 187,
in draw
File "/usr/local/lib/python3.11/site-packages/ranger/gui/widgets/browsercolumn-py",
line 214,
in _draw_file
Pager.draw(self)
File "/usr/local/lib/python3.11/site-packages/ranger/gui/widgets/pager.py", line 109,
in
draw
self._draw_line(i, line)
File "/usr/local/lib/python3.11/site-packages/ranger/gui/widgets/pager.py", line 139,
in _draw_line
self.set_fg_bg_attr (*chunk)
File "/usr/local/lib/python3.11/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
File "/usr/local/lib/python3.11/site-packages/ranger/gui/color.py", line 32, in get_color
curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).
ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by vejkse** [comment]
This is a known issue, that should be fixed in the current (unreleased) version of the code: https://github.com/ranger/ranger/issues/2752

**Comment by toonn** [comment]
Closing since this has been fixed. The next release is taking a while so you might want to install from the repository in the mean time.
