### ISSUE TITLE
Ranger fails to open

### ISSUE THREAD

**Issue by John-WE1DER** [ranger/ranger#2907]
#### Runtime Environment

- Operating system and version: Arch Linux; 6.5.5-zen1-1-zen 
- Terminal emulator and version: Alacritty 0.12.3-1
- Python version: 3.11.5
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

Current Behavior
Ranger is failing to open, instead outputting the traceback output below

#### Possible Solutions

Steps to reproduce
1. Attempt to open ranger via command from CLI
2. 
3. 

Traceback

```
ranger version: ranger 1.9.3
Python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
                         ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

```

**Comment by MinhTriet-Ly** [comment]
Same issue with `Ubuntu 24.04 6.8.0-45-generic, python 3.12.3`

**Comment by toonn** [comment]
I think this is fixed in the latest release.
