### ISSUE TITLE
Crashing on Image Preview of Audio File

### ISSUE THREAD

**Issue by nPHYN1T3** [ranger/ranger#2908]
#### Runtime Environment
- Operating system and version: Arch / Garuda
- Terminal emulator and version: URXVT v9.31
- Python version: 3.11.5
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
If you move the selection over an m4a file Ranger crashes trying to generate an image preview with w3m.

#### Expected Behavior
Retrieve audio preview data not try to make an image preview.

#### Context
Can't navigate directories with various files.

#### Traceback

```
Current file: '$HOME/Desktop/Aretha Sabbath - Superfools.m4a'

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 381, in loop
    ui.draw_images()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 401, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/pager.py", line 124, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 173, in notify
    raise obj
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/pager.py", line 118, in draw_image
    self.fm.image_displayer.draw(self.image, self.x, self.y,
  File "/usr/lib/python3.11/site-packages/ranger/ext/img_display.py", line 178, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/ext/img_display.py", line 243, in _generate_w3m_input
    raise ImageDisplayError('Failed to execute w3mimgdisplay', output)
ranger.ext.img_display.ImageDisplayError: ('Failed to execute w3mimgdisplay', [])
```

**Comment by nPHYN1T3** [comment]
I'm sick so I've been wasting some time with this. I switched set use_preview_script from true to false after checking how scope.sh was looking at things. Now ranger no longer crashes on m4a files though it's still coloring them incorrectly. Seems to think they are directories color wise.
