### ISSUE TITLE
Ranger refusing to open on fresh install

### ISSUE THREAD

**Issue by StarAssassin64** [ranger/ranger#2910]
#### Runtime Environment

- Operating system and version: Arch Linux (Kernel 6.4.11-arch2-1)
- Terminal emulator and version: tty
- Python version: 3.11.5
- Ranger version/commit: ranger 1.9.3 
- Locale: en_US.UTF-8

#### Current Behavior
Python error when trying to launch ranger
#### Expected Behavior
to actually open
#### Context

I am not able to open up ranger at all
#### Possible Solutions
it seems like pointer is not properly defined. I do not know how to properly define it, but that seems like that's the issue
#### Steps to reproduce
1. install ranger via pacman
2. try to open up
3. 

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.11/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pointer'
```

**Comment by I-like-stuff** [comment]
I'm having this problem as well but with NixOS :0
