### ISSUE TITLE
ranger crashed. Please report this traceback at:    --version 1.9.3

### ISSUE THREAD

**Issue by geckobob** [ranger/ranger#2919]
#### Runtime Environment

- Operating system and version: Mint 21.2
- Terminal emulator and version: Kitty 0.21.2
- Python version: 3.10.12
- Ranger version/commit: 1.9.3
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
~ $ ranger
ranger version: ranger 1.9.3
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Locale: en_US.UTF-8
Current file: '/home/rstyles/17sep23-update'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3/dist-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

```

**Comment by eiiches** [comment]
I just ran into the same issue. Changing the value of `TERM` environment variable from `screen` to `screen-256color` fixed the issue for me. `xterm-256color` and `tmux-256color` seem to work as well.

**Comment by a-b** [comment]
I was able to reproduce this behavior.

In the Kitty terminal app,  set:
```sh
export TERM=xterm
```
When I navigate to the file to get a preview, it crashes.

Setting 
```sh
export TERM=xterm-256color
```
Solves this issue.

**Comment by toonn** [comment]
Closing because this should be fixed in 1.9.4.
