### ISSUE TITLE
Using Trash crashes Ranger

### ISSUE THREAD

**Issue by luna-null** [ranger/ranger#2924]
#### Runtime Environment

- Operating system and version: 6.6.4-arch1.1
- Terminal emulator and version: alacritty 0.12.3-1
- Python version: 3.11.6
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Ranger crashes when trying to use the Trash function.

#### Expected Behavior
Ranger shouldn't crash when using the Trash function, and should just move the file to Trash.

#### Context

I can't use the Trash function in Ranger.

#### Possible Solutions
I have no clue. If I had enough time I could, but we'll see.

#### Steps to reproduce
1.  Try to use the Trash function in Ranger.

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3.11/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
                 ^^^^^^
AttributeError: 'str' object has no attribute 'path'
```

**Comment by luator** [comment]
See #1798

**Comment by 6b6279** [comment]
I have the same problem. @luator the linked issue seems to be closed, although it's unclear if the bug was fixed, considering that the last comment was a workaround. Is this perhaps a regression?

**Comment by luator** [comment]
To my understanding it is fixed on master but there hasn't been a release since then.  So I think you either need to install from source using the master branch or apply the workaround from the last comment on your local installation (this is what I did).

**Comment by 6b6279** [comment]
I see. Apparently the `ranger` package in the official Arch repository about 4 years old. Switching to `ranger-git` on AUR did it.

**Comment by belkka** [comment]
The last "release" is from 2019: https://github.com/ranger/ranger/tags.

Apparently, maintainers stopped making releases because they are out of jokes to put in release descriptions.

How about these:
- Removed vim integration, use emacs instead
- Rewritten from scratch in PHP
- Added option to opt-out of telemetry

**Comment by toonn** [comment]
The fix should be in the latest release.

More jokes might speed up the next release cycle.

**Comment by luator** [comment]
@toonn Latest release means 1.9.4, correct?  I just upgraded to ranger 1.9.4 and still get that error.

**Comment by toonn** [comment]
@luator, I hold that my statement is factually correct, the fix *should* have been in 1.9.4 but it's not : /

Still only available on the master branch.

**Comment by luator** [comment]
Thanks for checking.  I guess I should finally spent some time trying to install from master :)
