### ISSUE TITLE
New libcurses behavior breaks bulkrename

### ISSUE THREAD

**Issue by xe2io** [ranger/ranger#2934]
#### Runtime Environment
- Operating system and version: Alpine Linux 3.19
- Terminal emulator and version: foot, 1.16.2
- Python version: 3.11.6
- Ranger version/commit: 1.9.3, also tested on master [136416c7e2ecc27315fe2354ecadfe09202df7dd]
- Locale: en_US.UTF-8

#### Current Behavior
`:bulkrename` fails with `endwin() returned ERR` after first editor (default, vi) session is exited.

Message log:
```
21:51:15 INFO ranger version: ranger-master 
21:51:15 INFO Python version: 3.11.6 (main, Oct 13 2023, 15:52:55) [GCC 13.1.1 20230722]
21:51:15 INFO Locale: en_US.UTF-8
21:51:15 INFO Process ID: 28100
21:51:32 ERRO Notification: endwin() returned ERR
21:51:32 ERRO endwin() returned ERR
Traceback (most recent call last):
  File "/tmp/ranger/ranger-master/ranger/core/actions.py", line 272, in execute_console
    cmd.execute()
  File "/tmp/ranger/ranger-master/ranger/config/commands.py", line 1295, in execute
    self.fm.execute_file([File(cmdfile.name)], app='editor')
  File "/tmp/ranger/ranger-master/ranger/core/actions.py", line 446, in execute_file
    return execute()
           ^^^^^^^^^
  File "/tmp/ranger/ranger-master/ranger/core/actions.py", line 444, in execute
    return self.rifle.execute(filenames, mode, label, flags, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ranger/ranger-master/ranger/ext/rifle.py", line 440, in execute
    self.hook_before_executing(command, self._mimetype, self._app_flags)
  File "/tmp/ranger/ranger-master/ranger/core/fm.py", line 136, in <lambda>
    self.ui.suspend() if 'f' not in flags else None
    ^^^^^^^^^^^^^^^^^
  File "/tmp/ranger/ranger-master/ranger/gui/ui.py", line 160, in suspend
    curses.endwin()
_curses.error: endwin() returned ERR
```

#### Expected Behavior
Following first editor window closing, new editor instance with the changes is displayed prompting user for confirmation.

#### Context
Bulk rename files :)
  
This behavior appears to be caused by the change described in [this thread](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1944374.html)

#### Possible Solutions
Catch the new Exception to allow the bulkrename operation to continue.

#### Steps to reproduce
1. Create test directory with files and launch ranger
```
d=$(mktemp -d) && touch $d/{1..3} && ranger $d
```
3. Mark multiple files
4. Use the `:bulkrename` command
5. make some changes in the editor and save and quit
```
%s/$/-d/g
```

**Comment by bleuse** [comment]
I'm also impacted by this bug.
Running debian testing with `ranger 1.9.3-5` and `libncurses6 6.4+20231209-1`.

The proposed solution seems to work.

**Comment by randomcodepanda** [comment]
Ncurses got updated to Arch and i couldn't bulkrename anymore with the same ENDWIN error, i tried that fix and it seems to work now.

**Comment by ccolorado** [comment]
Still broken for me.

**Comment by ccolorado** [comment]
Seems broken for me ranger ranger v1.9.3 , Archlinux, kitty terminal v 0.33.1

**Comment by davidrihtarsic** [comment]
Hi, same issue here... (Archlinux, ranger 1.9.3, alacritty 0.13.2 ) but it works with [ncurses-6.4](https://archive.archlinux.org/packages/n/ncurses/ncurses-6.4_20230520-3-x86_64.pkg.tar.zst). You can downgrade ncurses package with:

```
sudo pacman -U https://archive.archlinux.org/packages/n/ncurses/ncurses-6.4_20230520-3-x86_64.pkg.tar.zst
```

**Comment by JosefLitos** [comment]
Yes, but keep in mind that version breaks switching window focus - it prints the escape sequence as if it was normal input which can trigger unwanted actions.

**Comment by ultraSsak** [comment]
I've got this in Arch, and in Debian Testing.

**Comment by Aster89** [comment]
> Seems broken for me ranger ranger v1.9.3 , Archlinux, kitty terminal v 0.33.1

For me as well, same ranger version, but on urxvt.

**Comment by georgev93** [comment]
I am also afflicted by this particular ailment. Arch/sway/alacritty. Also, I use Arch BTW. I forgot if I mentioned. But I do use Arch

**Comment by FrozenOrchestra** [comment]
Same issue for me Arch/BSPWM/Kitty.

**Comment by georgev93** [comment]
Wow... @moviuro seems quite upset with this thread...

**Comment by miblodelcarpio** [comment]
Little tip for others keenly awaiting a fix: [brn](https://github.com/nimaipatel/brn/) does the job beautifully, just like ranger's own text editor-based renaming.

**Comment by alpaca1thunder** [comment]
> Little tip for others keenly awaiting a fix: [brn](https://github.com/nimaipatel/brn/) does the job beautifully, just like ranger's own text editor-based renaming.

Have you found a way to bind it to `:bulkrename`?  I have a similar program mapped to `b` for the time being, but muscle memory keeps leading me back 😓

**Comment by miblodelcarpio** [comment]
Well, @alpaca1thunder, I've just had a quick, partially-successful try at this – you're ahead of me, I simply `S` to shell and run `brn` there – but it seems like this may be the way to go:

1. `ranger --copy-config=commands_full`
2. Rename the resulting `~/.config/ranger/commands_full.py` to `…/commands.py`
3. Change the contents of the `bulkrename` class's `execute` function to the single line `self.fm.run("brn")`

Honestly, I already have `~/.config/ranger/commands{,_full}.py` so didn't need to do the `--copy-config`, but just to try out the whole process I renamed that existing `commands_full.py` file, and performed step 1, but found that it just plain opened ranger and didn't copy the file. So, I dunno, maybe there's something busted in my setup and it'll hopefully work as documented for you. Also, `brn` itself prints out the number of files renamed, but I didn't get to figuring out how to capture that, so I end up seeing it written in the console after closing ranger!

**Comment by alpaca1thunder** [comment]
> Well, @alpaca1thunder, I've just had a quick, partially-successful try at this – you're ahead of me, I simply `S` to shell and run `brn` there – but it seems like this may be the way to go:
> 
>     1. `ranger --copy-config=commands_full`
> 
>     2. Rename the resulting `~/.config/ranger/commands_full.py` to `…/commands.py`
> 
>     3. Change the contents of the `bulkrename` class's `execute` function to the single line `self.fm.run("brn")`
> 
> 
> Honestly, I already have `~/.config/ranger/commands{,_full}.py` so didn't need to do the `--copy-config`, but just to try out the whole process I renamed that existing `commands_full.py` file, and performed step 1, but found that it just plain opened ranger and didn't copy the file. So, I dunno, maybe there's something busted in my setup and it'll hopefully work as documented for you. Also, `brn` itself prints out the number of files renamed, but I didn't get to figuring out how to capture that, so I end up seeing it written in the console after closing ranger!

This is incredible!  I spent some time last week figuring this would've required modifications to ranger itself, but I'm glad its something configurable.  Thank you so much!!

**Comment by geneotech** [comment]
> Well, @alpaca1thunder, I've just had a quick, partially-successful try at this – you're ahead of me, I simply `S` to shell and run `brn` there – but it seems like this may be the way to go:
> 
>     1. `ranger --copy-config=commands_full`
> 
>     2. Rename the resulting `~/.config/ranger/commands_full.py` to `…/commands.py`
> 
>     3. Change the contents of the `bulkrename` class's `execute` function to the single line `self.fm.run("brn")`
> 
> 
> Honestly, I already have `~/.config/ranger/commands{,_full}.py` so didn't need to do the `--copy-config`, but just to try out the whole process I renamed that existing `commands_full.py` file, and performed step 1, but found that it just plain opened ranger and didn't copy the file. So, I dunno, maybe there's something busted in my setup and it'll hopefully work as documented for you. Also, `brn` itself prints out the number of files renamed, but I didn't get to figuring out how to capture that, so I end up seeing it written in the console after closing ranger!

Note: for multiple file selection to work, use [brn2](https://github.com/lucas-mior/brn2) instead.
``bulkrename`` then has to pass the filenames as arguments:

```py
class bulkrename(Command):
    """:bulkrename

    This command calls the 'brn2' executable with a list of selected files
    passed as arguments after the '--' separator.
    """
    def execute(self):
        from ranger.container.file import File
        filenames = [f.relative_path for f in self.fm.thistab.get_selection()]
        command = ['brn2', '--'] + filenames
        self.fm.run(command)
```

Otherwise you'll always just get the entire folder contents as brn currently does not support any arguments.

**Comment by miblodelcarpio** [comment]
Perfect, thanks for this, @geneotech! I suppose the only remaining thing, if we want to go there before we get ranger's own `:bulkrename` back, is capturing the stdout printout.

**Comment by MRAAGH** [comment]
Thought I'd mention, the two "fixes" suggested in #2935 and in comments both work, and you can easily apply them manually by editing `/usr/lib/python3.12/site-packages/ranger/gui/ui.py` or wherever you have Ranger installed.

**Comment by imranhossain001** [comment]
Hoping to get it fixed.

**Comment by imranhossain001** [comment]
> Thought I'd mention, the two "fixes" suggested in #2935 and in its comments both work, and you can easily apply them manually by editing `/usr/lib/python3.12/site-packages/ranger/gui/ui.py` or wherever you have Ranger installed.

yes this [comment](https://github.com/ranger/ranger/pull/2935#issuecomment-2198142497) fixes the issue.

**Comment by rendi12345678** [comment]
> Hi, same issue here... (Archlinux, ranger 1.9.3, alacritty 0.13.2 ) but it works with [ncurses-6.4](https://archive.archlinux.org/packages/n/ncurses/ncurses-6.4_20230520-3-x86_64.pkg.tar.zst). You can downgrade ncurses package with:
> 
> ```
> sudo pacman -U https://archive.archlinux.org/packages/n/ncurses/ncurses-6.4_20230520-3-x86_64.pkg.tar.zst
> ```

thanks it works on my Arch :)

**Comment by toonn** [comment]
Could someone confirm #3039 fixes the issue?

**Comment by randomcodepanda** [comment]
> Could someone confirm #3039 fixes the issue?

It worked for me, tried it three times on different groups of files and it worked.
