### ISSUE TITLE
ranger crashed. Please report this traceback

### ISSUE THREAD

**Issue by angelf015** [ranger/ranger#2954]
#### Runtime Environment

- Operating system and version: Arch Linux x86_64 
- Terminal emulator and version: kitty 0.31.0
- Python version: Python 3.11.7
- Ranger version/commit: ranger 1.9.3
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
❯  ranger
ranger version: ranger 1.9.3
Python version: 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]
Locale: es_MX.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.11/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Sejsel** [comment]
I got the same thing on current master (38bb890). Can be fixed by removing a line that contains a directory which no longer exists in `.config/ranger/bookmarks`.

```
ranger version: ranger-master
Python version: 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
Locale: cs_CZ.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 183, in main
    fm.initialize()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 128, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.11/site-packages/ranger/container/bookmarks.py", line 49, in load
    new_dict = self._load_dict()
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/container/bookmarks.py", line 239, in _load_dict
    dct[key] = self.bookmarktype(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/container/directory.py", line 130, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by jemshid** [comment]
On Ubuntu 22.04

```
$ ranger 
ranger version: ranger 1.9.3
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Locale: en_IN.ISO8859-1
Current file: '/home/j/Dropbox/streakon/icon discord streakon.png'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3/dist-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
  File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues


```

**Comment by Edward2k** [comment]
I have the exact same crash as @jemshid. Versions and host are identical.

**Comment by foozzi** [comment]
> On Ubuntu 22.04
> 
> ```
> $ ranger 
> ranger version: ranger 1.9.3
> Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
> Locale: en_IN.ISO8859-1
> Current file: '/home/j/Dropbox/streakon/icon discord streakon.png'
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
>     fm.loop()
>   File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 383, in loop
>     ui.handle_input()
>   File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 266, in handle_input
>     self.handle_key(key)
>   File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 196, in handle_key
>     elif not DisplayableContainer.press(self, key):
>   File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 275, in press
>     focused_obj.press(key)
>   File "/usr/lib/python3/dist-packages/ranger/gui/widgets/console.py", line 188, in press
>     self.type_key(key)
>   File "/usr/lib/python3/dist-packages/ranger/gui/widgets/console.py", line 214, in type_key
>     self._answer_question(answer)
>   File "/usr/lib/python3/dist-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
>     callback(answer)
>   File "/usr/lib/python3/dist-packages/ranger/config/commands.py", line 759, in _question_callback
>     self.fm.execute_file(files, label='trash')
>   File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 459, in execute_file
>     filenames = [f.path for f in files]
>   File "/usr/lib/python3/dist-packages/ranger/core/actions.py", line 459, in <listcomp>
>     filenames = [f.path for f in files]
> AttributeError: 'str' object has no attribute 'path'
> 
> ranger crashed. Please report this traceback at:
> https://github.com/ranger/ranger/issues
> ```

The same problem 
macOS Sonoma 14.5

**Comment by vejkse** [comment]
@jemshid, @Edward2k and @foozzi’s issue is different from the original one on top; it is related to trashing.  This is an old issue that is fixed in the latest version of the code, for which there is no release, but you can just clone this git repository and run ranger from there.

**Comment by jtb-github** [comment]
I'm not sure how to clone "this" git repository for which there is no release.  
Can someone make a release that fixes this?  
And in the meantime help me by explaining how to identify and get "this"?  
Sorry and thanks!

**Comment by vejkse** [comment]
To clone this repository, you just run somewhere `git clone https://github.com/ranger/ranger`.  This will create a `ranger` directory.  The executable is then the file `ranger.py` inside that directory.  Depending on your system there may be cleaner ways of installing it, for instance for Arch Linux or derivatives: https://aur.archlinux.org/packages/ranger-git.

**Comment by userrand** [comment]
On my laptop I fixed the error by removing files or directories from `~/.local/share/ranger/bookmarks` instead of `~/.config/ranger/bookmarks` as @Sejsel suggested. I do not really use bookmarks so I removed all of the bookmarks that were maybe saved without me really wanting to save them but maybe it is sufficient to remove bookmarks that no longer exist as @Sejsel suggested.

**Comment by toonn** [comment]
I believe there's another issue for crashes related to benchmarks for directories that have disappeared with a better description.
