### ISSUE TITLE
Encoding error with image preview in python 3

### ISSUE THREAD

**Issue by rnhmjoj** [ranger/ranger#296]
I'm using the master branch of ranger and the preview method is iTerm2.
If I run `ranger.py` with python3 the preview fails to load and in the status bar the message `must be str, not bytes` appears. It works fine with python2.

How can I get a traceback?

**Comment by Vifon** [comment]
> How can I get a traceback?

Run ranger with the `--debug` option.

**Comment by rnhmjoj** [comment]
Traceback (most recent call last):
    File "/Users/michele/ranger/ranger/core/main.py", line 139, in main
      fm.loop()
    File "/Users/michele/ranger/ranger/core/fm.py", line 340, in loop
      ui.draw_images()
    File "/Users/michele/ranger/ranger/gui/ui.py", line 323, in draw_images
      self.browser.columns[-1].draw_image()
    File "/Users/michele/ranger/ranger/gui/widgets/pager.py", line 97, in draw_image
      self.fm.notify(e, bad=True)
    File "/Users/michele/ranger/ranger/gui/widgets/pager.py", line 93, in draw_image
      self.wid, self.hei)
    File "/Users/michele/ranger/ranger/ext/img_display.py", line 143, in draw
      sys.stdout.write(curses.tparm(curses.tigetstr("cup"), start_y, start_x))
    TypeError: must be str, not bytes

I tried adding a `.decode()`: it doesn't crash but it gets stuck on loading the image.

**Comment by hut** [comment]
Works for me

**Comment by nfnty** [comment]
Can't reproduce this issue. Request to reopen if you're still experiencing this issue on `master` or the latest release.
