### ISSUE TITLE
Crash after trying to trash folder

### ISSUE THREAD

**Issue by rommeswi** [ranger/ranger#2967]
#### Runtime Environment
ranger version: ranger 1.9.3
Python version: 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
Locale: en_HK.UTF-8

#### Current Behavior
Ranger crashes after trying to trash an empty folder with `d T`

#### Expected Behavior
Either display that a folder cannot be trashed or simply delete the folder

#### Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3.11/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
                 ^^^^^^
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by windupbird144** [comment]
I believe this is a duplicate of #2897.
This is a bug in version 1.9.3 and was fixed in 277e1db

**Comment by rommeswi** [comment]
I'm a bit confused. I am on Arch and should have the current version. Are the packaged versions outdated?

**Comment by windupbird144** [comment]
Generally the packages in the main repositories use the latest released version of a program. This fix hasn't been released in ranger yet.

If you want the latest developments, you want to install the `ranger-git` package from AUR which basically clones the ranger git repository and installs ranger on your machine.

**Comment by rommeswi** [comment]
Thank you, that solves my problem!
