### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pointer'

### ISSUE THREAD

**Issue by samuela** [ranger/ranger#2968]
```
root@b62e2017d34d:/workspaces/bitbop# ranger /nix/store/hp2r2f69krc0j40gr8wwpqrcilzam7cc-charge_usage
Warning: Unable to set locale.  Expect encoding problems.
ranger version: ranger 1.9.3
Python version: 3.11.8 (main, Feb  6 2024, 21:21:21) [GCC 13.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/nix/store/95pbg39mymixfw2bghigjz1jabagsa0c-ranger-1.9.3/lib/python3.11/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/nix/store/95pbg39mymixfw2bghigjz1jabagsa0c-ranger-1.9.3/lib/python3.11/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/nix/store/95pbg39mymixfw2bghigjz1jabagsa0c-ranger-1.9.3/lib/python3.11/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/nix/store/95pbg39mymixfw2bghigjz1jabagsa0c-ranger-1.9.3/lib/python3.11/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/nix/store/95pbg39mymixfw2bghigjz1jabagsa0c-ranger-1.9.3/lib/python3.11/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/nix/store/95pbg39mymixfw2bghigjz1jabagsa0c-ranger-1.9.3/lib/python3.11/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by vejkse** [comment]
This looks exactly like this issue: https://github.com/ranger/ranger/issues/2557 which is fixed in the latest version of the code, for which there is no release yet, but can be installed nonetheless.

**Comment by alexdewar** [comment]
I just hit what I think is the same issue and it is indeed fixed on the latest git version... Is there a plan to make a new release soon? It would be great to have this fix without having to build ranger from source.

**Comment by vejkse** [comment]
There is a plan: https://github.com/ranger/ranger/issues/3163.

**Comment by toonn** [comment]
And I'm working on it as we speak, please bear with us. It's not as if Ranger needs to be built BTW, it's all interpreted code : )
