### ISSUE TITLE
Seemingly no way to force caca-view previews

### ISSUE THREAD

**Issue by cyber199** [ranger/ranger#2975]
#### Runtime Environment

- Operating system and version: Linux Mint 21.3
- Terminal emulator and version: Konsole 21.12.3, Mate Terminal 1.26.0, cool-retro-term 1.2.0
- Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
- Ranger version/commit: 1.9.3
- Locale:  en_GB.UTF-8

#### Current Behavior
No way to set caca-view style previews in rc.conf, setting preview_images to false just disables images entirely, and setting preview_images_method to anything that suggests use of caca-utils (caca-utils, caca-view, caca, img2txt, libcaca) causes a crash (this is somewhat expected as I'm entering unsupported values)

#### Expected Behavior
setting preview_images_method appropriately will force use of caca-utils even in a terminal emulator that supports better image modes

#### Context

Trying to accomplish image previews using preferred method

#### Steps to reproduce
1. set preview_images_method to img2txt (implied by manpage)
2. run ranger
3. get traceback

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
  File "/usr/lib/python3/dist-packages/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
  File "/usr/lib/python3/dist-packages/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException
```

**Comment by cyber199** [comment]
Additionally setting use_preview_script to false seems to just disable all image previews

**Comment by vejkse** [comment]
This is a bit late, but `img2txt` is not one of the image preview methods — they are listed exhaustively in (the default) `rc.conf`.  To use `img2txt`, you would have to:
1. `set preview_images false` in `rc.conf`.
2. Uncomment the `img2txt` line in `scope.sh`.
