### ISSUE TITLE
Make test failing because no attribute `IAstroidchecker` in `pylint.interfaces`

### ISSUE THREAD

**Issue by roroc0** [ranger/ranger#2976]
#### Runtime Environment

- Operating system and version: Fedora Linux 39 
- Terminal emulator and version: terminator 2.1.3
- Python version: 3.12.3
- Ranger version/commit: ranger version: ranger-master
- Locale: en_GB.UTF-8

#### Current Behavior
Running `make test` outputs the following error:
```bash
  File "<home>/ranger/tests/pylint/python3.py", line 184, in Python3Checker
    __implements__ = interfaces.IAstroidChecker
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pylint.interfaces' has no attribute 'IAstroidChecker'
make: *** [Makefile:98: test_pylint] Error 1

```
#### Expected Behavior
run test
#### Steps to reproduce
1.  `make test`

**Comment by charles-gokei** [comment]
Same problem here...

When Run `make test`, follows the error:

```bash
Running pylint...
pylint ./ranger/ext ./ranger/colorschemes ./ranger/gui ./ranger/container ./ranger/core ./ranger/api ./ranger/__init__.py ./doc/tools/print_colors.py ./doc/tools/print_keys.py ./doc/tools/convert_papermode_to_metadata.py ./doc/tools/performance_test.py ./examples/plugin_hello_world.py ./examples/plugin_linemode.py ./examples/plugin_avfs.py ./examples/plugin_ipc.py ./examples/plugin_new_sorting_method.py ./examples/plugin_fasd_add.py ./examples/plugin_new_macro.py ./examples/plugin_pmount_dynamic.py ./examples/plugin_file_filter.py ./examples/plugin_chmod_keybindings.py ./examples/plugin_pmount.py ./ranger.py ./setup.py ./tests
make: pylint: Command not found
make: *** [Makefile:98: test_pylint] Error 127
```

It's ok because the `pylint` isn't installed. So it's just a matter of  install with `pip install pylint`
```bash
Collecting pylint
  Using cached pylint-3.2.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: platformdirs>=2.2.0 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (4.2.2)
Requirement already satisfied: astroid<=3.3.0-dev0,>=3.2.2 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (3.2.2)
Requirement already satisfied: isort!=5.13.0,<6,>=4.2.5 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (5.13.2)
Requirement already satisfied: mccabe<0.8,>=0.6 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (0.6.1)
Requirement already satisfied: tomlkit>=0.10.1 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (0.12.5)
Requirement already satisfied: dill>=0.3.6 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (0.3.8)
Using cached pylint-3.2.2-py3-none-any.whl (519 kB)
Installing collected packages: pylint
Successfully installed pylint-3.2.2
```

It was expected to works now, but when I execute `make test`...
```bash
Running pylint...
pylint ./ranger/ext ./ranger/colorschemes ./ranger/gui ./ranger/container ./ranger/core ./ranger/api ./ranger/__init__.py ./doc/tools/print_colors.py ./doc/tools/print_keys.py ./doc/tools/convert_papermode_to_metadata.py ./doc/tools/performance_test.py ./examples/plugin_hello_world.py ./examples/plugin_linemode.py ./examples/plugin_avfs.py ./examples/plugin_ipc.py ./examples/plugin_new_sorting_method.py ./examples/plugin_fasd_add.py ./examples/plugin_new_macro.py ./examples/plugin_pmount_dynamic.py ./examples/plugin_file_filter.py ./examples/plugin_chmod_keybindings.py ./examples/plugin_pmount.py ./ranger.py ./setup.py ./tests
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pylint/lint/run.py", line 162, in __init__
    args = _config_initialization(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pylint/config/config_initialization.py", line 61, in _config_initialization
    linter.load_plugin_modules(utils._splitstrip(config_data["load-plugins"]))
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 379, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/astroid/modutils.py", line 196, in load_module_from_name
    module = importlib.import_module(dotted_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/charles/.local/usr/src/ranger/tests/pylint/python3.py", line 182, in <module>
    class Python3Checker(checkers.BaseChecker):
  File "/home/charles/.local/usr/src/ranger/tests/pylint/python3.py", line 184, in Python3Checker
    __implements__ = interfaces.IAstroidChecker
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pylint.interfaces' has no attribute 'IAstroidChecker'
make: *** [Makefile:98: test_pylint] Error 1
```

**Comment by Xurlz** [comment]
Same problem here...

When Run `make test`, follows the error:

```bash
Running pylint...
pylint ./ranger/ext ./ranger/colorschemes ./ranger/gui ./ranger/container ./ranger/core ./ranger/api ./ranger/__init__.py ./doc/tools/print_colors.py ./doc/tools/print_keys.py ./doc/tools/convert_papermode_to_metadata.py ./doc/tools/performance_test.py ./examples/plugin_hello_world.py ./examples/plugin_linemode.py ./examples/plugin_avfs.py ./examples/plugin_ipc.py ./examples/plugin_new_sorting_method.py ./examples/plugin_fasd_add.py ./examples/plugin_new_macro.py ./examples/plugin_pmount_dynamic.py ./examples/plugin_file_filter.py ./examples/plugin_chmod_keybindings.py ./examples/plugin_pmount.py ./ranger.py ./setup.py ./tests
make: pylint: Command not found
make: *** [Makefile:98: test_pylint] Error 127
```

It's ok because the `pylint` isn't installed. So it's just a matter of  install with `pip install pylint`
```bash
Collecting pylint
  Using cached pylint-3.2.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: platformdirs>=2.2.0 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (4.2.2)
Requirement already satisfied: astroid<=3.3.0-dev0,>=3.2.2 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (3.2.2)
Requirement already satisfied: isort!=5.13.0,<6,>=4.2.5 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (5.13.2)
Requirement already satisfied: mccabe<0.8,>=0.6 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (0.6.1)
Requirement already satisfied: tomlkit>=0.10.1 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (0.12.5)
Requirement already satisfied: dill>=0.3.6 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from pylint) (0.3.8)
Using cached pylint-3.2.2-py3-none-any.whl (519 kB)
Installing collected packages: pylint
Successfully installed pylint-3.2.2
```

It was expected to works now, but when I execute `make test`...
```bash
Running pylint...
pylint ./ranger/ext ./ranger/colorschemes ./ranger/gui ./ranger/container ./ranger/core ./ranger/api ./ranger/__init__.py ./doc/tools/print_colors.py ./doc/tools/print_keys.py ./doc/tools/convert_papermode_to_metadata.py ./doc/tools/performance_test.py ./examples/plugin_hello_world.py ./examples/plugin_linemode.py ./examples/plugin_avfs.py ./examples/plugin_ipc.py ./examples/plugin_new_sorting_method.py ./examples/plugin_fasd_add.py ./examples/plugin_new_macro.py ./examples/plugin_pmount_dynamic.py ./examples/plugin_file_filter.py ./examples/plugin_chmod_keybindings.py ./examples/plugin_pmount.py ./ranger.py ./setup.py ./tests
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pylint/lint/run.py", line 162, in __init__
    args = _config_initialization(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pylint/config/config_initialization.py", line 61, in _config_initialization
    linter.load_plugin_modules(utils._splitstrip(config_data["load-plugins"]))
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 379, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/astroid/modutils.py", line 196, in load_module_from_name
    module = importlib.import_module(dotted_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/charles/.local/usr/src/ranger/tests/pylint/python3.py", line 182, in <module>
    class Python3Checker(checkers.BaseChecker):
  File "/home/charles/.local/usr/src/ranger/tests/pylint/python3.py", line 184, in Python3Checker
    __implements__ = interfaces.IAstroidChecker
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pylint.interfaces' has no attribute 'IAstroidChecker'
make: *** [Makefile:98: test_pylint] Error 1
```
My runtime environment (following the pattern of the comment above): 
- Operating system and version: Ubuntu 20.04.6 LTS
- Terminal emulator and version: Windows Terminal 1.90.11213.0
- Python version: 3.8.10
- Ranger version/commit: ranger commit: 38bb8901004b75a407ffee4b9e176bc0a436cb15 (current master's HEAD at this comment's date) 
- pylint 3.2.2
- astroid 3.2.2
- Locale: en_US.UTF-8

**Comment by roroc0** [comment]
I think pylint newer version dont support interfaces anymore:
See: [https://github.com/pylint-dev/pylint/issues/9144](https://github.com/pylint-dev/pylint/issues/9144)
Also: [https://github.com/pylint-dev/pylint-pytest/issues/12](https://github.com/pylint-dev/pylint-pytest/issues/12)

**Comment by Xurlz** [comment]
I believe that pull request's scope plan to fix this problem: #2482
