### ISSUE TITLE
sudo ranger crashing

### ISSUE THREAD

**Issue by Escillex** [ranger/ranger#2980]
#### Runtime Environment

- Operating system and version: EndeavourOS roling x86_64(i think its gemini 2.0)
- Terminal emulator and version: Kitty 0.35.1
- Python version: 3.12.3
- Ranger version/commit: ranger-master
- Locale: en_GB.UTF-8

#### Current Behavior

Crashes running it on sudo

#### Expected Behavior

Should run in sudo

#### Context
No idea how it happened tbh i was using sudo ranger just fine then this happend. I tired deleteing bookmarks reinstalling and compiling the git version through yay. im also pretty new to this linux thing so forgive me if im a bit dumb

#### Steps to reproduce
1. sudo ranger crashes
2. ranger works fine tho?

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ranger/core/main.py", line 183, in main
    fm.initialize()
  File "/usr/lib/python3.12/site-packages/ranger/core/fm.py", line 128, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.12/site-packages/ranger/container/bookmarks.py", line 49, in load
    new_dict = self._load_dict()
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ranger/container/bookmarks.py", line 239, in _load_dict
    dct[key] = self.bookmarktype(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ranger/container/directory.py", line 130, in __init__
    assert not os.path.isfile(path), "No directory given!"
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
```

**Comment by ajones239** [comment]
I get the same error without sudo. Adding the '--clean' option is a workaround.
