### ISSUE TITLE
Crash while using Cool-retro-term

### ISSUE THREAD

**Issue by spencershoe** [ranger/ranger#2982]
#### Runtime Environment

- Operating system and version:  Catchyos using plasma 6 - up to date
- Terminal emulator and version: cool-retro-term 1.2.0-3.1
- Python version: Python 3.12.3
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
 crash when moving cursor over most text files

#### Context

not really a big issue, as i have other terminal emulators, and cool-retro-term kinda sucks if we're being honest, but still thought i should post the crash here anyways.

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.12.3 (main, Apr 27 2024, 12:46:41) [GCC 13.2.1 20240417]
Locale: en_US.UTF-8
Current file: '/home/dimble/Desktop/PISS-RESTARTER.sh'

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.12/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.12/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.12/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.12/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.12/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.12/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.12/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.12/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.12/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
                                       ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by jhcole** [comment]
I'm getting this same traceback on Ubuntu 24.04 in GNOME Terminal with default settings when it tries to show the preview for a yaml file.  $TERM is xterm-256color.

```bash
ranger version: ranger 1.9.3
Python version: 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
Locale: en_US.UTF-8
Current file: '/home/john/Work/EBEC/content/.pre-commit-config.yaml'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
                                       ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by serpent7776** [comment]
I just hit the same issue when previewing a diff file. Only happens in tmux session for me. Outside tmux works fine. Tested on xfce4-terminal and lxterminal.

Related fact: in tmux session bash doesn't initialize colours, but it does outside of tmux. Ranger does use colours even in tmux, I can see directories and links coloured. Maybe that's the issue.

Ubuntu 22.04.5, $TERM is set to screen when the issue happens.

```
ranger version: ranger 1.9.3
Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Locale: en_GB.UTF-8
```

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3/dist-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).
```

**Comment by a-b** [comment]
https://github.com/ranger/ranger/issues/2919#issuecomment-2590636050
