### ISSUE TITLE
update_title causes crash when navigating to unaccessible tab

### ISSUE THREAD

**Issue by sph432** [ranger/ranger#2986]
#### Runtime Environment

- Operating system and version: Artix / N/A
- Terminal emulator and version: urxvt / v9.31 (as patched by aur/rxvt-unicode-truecolor-wide-glyphs 9.31-8), unable to reproduce on xterm as it is apparently not setting the window title at all (in theory, it is able to handle the `OSC 0` sequence used to do so)
- Python version: 3.12.3
- Ranger version/commit: master (1.9.3r720) g38bb8901
- Locale: en_US.UTF-8

#### Current Behavior
ranger crashing

#### Expected Behavior
the same as when `update_title` is set to `false` (ie. not crashing)

#### Possible Solutions
handling the `AttributeError` raised by `self.fm.thisdir` being None

#### Steps to reproduce
1. `set update_title true` in `~/.config/ranger/rc.conf`
2. 
```bash
mkdir /tmp/test
ranger /tmp/test
#<M-2> clone tab 1 to 2
#<M-1> switch to tab 1
#:quitall
rmdir /tmp/test
ranger
#<M-2> switch to tab 2
```
3. ranger crashes

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ranger/core/main.py", line 214, in main
    fm.loop()
  File "/usr/lib/python3.12/site-packages/ranger/core/fm.py", line 417, in loop
    ui.redraw()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 372, in draw
    cwd = self.fm.thisdir.path
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by sph432** [comment]
This patch fixes the issue apparently:

```patch
diff --git a/ui.py b/ui.py
index 15f68e8..094858f 100644
--- a/ui.py
+++ b/ui.py
@@ -369,33 +369,37 @@ class UI(  # pylint: disable=too-many-instance-attributes,too-many-public-method
         self.win.touchwin()
         DisplayableContainer.draw(self)
         if self._draw_title and self.settings.update_title:
-            cwd = self.fm.thisdir.path
-            if self.settings.tilde_in_titlebar \
-               and (cwd == self.fm.home_path
-                    or cwd.startswith(self.fm.home_path + "/")):
-                cwd = '~' + cwd[len(self.fm.home_path):]
-            if self.settings.shorten_title:
-                split = cwd.rsplit(os.sep, self.settings.shorten_title)
-                if os.sep in split[0]:
-                    cwd = os.sep.join(split[1:])
             try:
-                fixed_cwd = cwd.encode('utf-8', 'surrogateescape'). \
-                    decode('utf-8', 'replace')
-                titlecap = curses.tigetstr('tsl')
-                escapes = (
-                    [titlecap.decode("latin-1")]
-                    if titlecap is not None
-                    else [] + [ESCAPE_ICON_TITLE]
-                )
-                belcap = curses.tigetstr('fsl')
-                bel = belcap.decode('latin-1') if belcap is not None else ""
-                fmt_tups = [(e, fixed_cwd, bel) for e in escapes]
-            except UnicodeError:
+                cwd = self.fm.thisdir.path
+            except AttributeError:
                 pass
             else:
-                for fmt_tup in fmt_tups:
-                    sys.stdout.write("%sranger:%s%s" % fmt_tup)
-                    sys.stdout.flush()
+                if self.settings.tilde_in_titlebar \
+                   and (cwd == self.fm.home_path
+                        or cwd.startswith(self.fm.home_path + "/")):
+                    cwd = '~' + cwd[len(self.fm.home_path):]
+                if self.settings.shorten_title:
+                    split = cwd.rsplit(os.sep, self.settings.shorten_title)
+                    if os.sep in split[0]:
+                        cwd = os.sep.join(split[1:])
+                try:
+                    fixed_cwd = cwd.encode('utf-8', 'surrogateescape'). \
+                        decode('utf-8', 'replace')
+                    titlecap = curses.tigetstr('tsl')
+                    escapes = (
+                        [titlecap.decode("latin-1")]
+                        if titlecap is not None
+                        else [] + [ESCAPE_ICON_TITLE]
+                    )
+                    belcap = curses.tigetstr('fsl')
+                    bel = belcap.decode('latin-1') if belcap is not None else ""
+                    fmt_tups = [(e, fixed_cwd, bel) for e in escapes]
+                except UnicodeError:
+                    pass
+                else:
+                    for fmt_tup in fmt_tups:
+                        sys.stdout.write("%sranger:%s%s" % fmt_tup)
+                        sys.stdout.flush()
 
         self.win.refresh()
```

**Comment by sph432** [comment]
#2987

**Comment by vejkse** [comment]
This is a duplicate of https://github.com/ranger/ranger/issues/2873 for which there was already a (simpler) pending pull request.
