### ISSUE TITLE
Traceback Report - Failure To Trash Directory

### ISSUE THREAD

**Issue by ancientjpeg** [ranger/ranger#2989]
#### Runtime Environment

- Operating system and version: macOS Sonoma 14.2.1
- Terminal emulator and version: iTerm2 - Build 3.5.2
- Python version: `Python 3.12.3` provided by conda
- Ranger version/commit: 
```
$ ranger --version
ranger version: ranger 1.9.3
Python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
```
- Locale: `en_US.UTF-8`

#### Current Behavior

Trashing a directory crashes with traceback.

#### Expected Behavior

Trash should behave normally

#### Possible Solutions

Unsure. Reporting this as an issue because the exception prompted me to.

#### Steps to reproduce

1. Attempt to send a directory to trash

#### Traceback

Obfuscating my local username with `$USERNAME`.
```
ranger version: ranger 1.9.3
Python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
Locale: en_US.UTF-8
Current file: '/Users/$USERNAME/minimal/minimal_core/extras/installers/all_access/Mac_Builds/Unpacked'

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/opt/homebrew/lib/python3.12/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
                 ^^^^^^
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by vejkse** [comment]
This is an old issue that is fixed in the latest version of the code, for which there is no release, but you can just clone this git repository and run ranger from there.

**Comment by vejkse** [comment]
As far as I know, version 1.9.4 only fixed one thing, all other fixes since 1.9.3 are still unreleased.  See the last comment by cskeeters in the same issue https://github.com/ranger/ranger/issues/2361 for how to install the current working version of ranger with Homebrew.

**Comment by toonn** [comment]
Closing as fixed. I'm working towards a new release, bunch of issues I want to see fixed before then though.
