### ISSUE TITLE
ranger sometimes crashes when switching to a tab whose directory is now unavailable

### ISSUE THREAD

**Issue by vejkse** [ranger/ranger#2993]
#### Runtime Environment

- Operating system and version: linux 6.8.7.arch1-1
- Terminal emulator and version: Alacritty 0.12.3-1
- Python version: 3.11.8
- Ranger version/commit: master
- Locale: en_US.UTF-8

#### Current Behavior

ranger crashes in various circumstances when going to a tab whose directory has become inaccessible.

There was already https://github.com/ranger/ranger/issues/2873 that applies only when `update_title` is set to `true`.  There are two pull requests solving that issue.

I found two new methods to crash ranger when going to an unavailable tab in `ranger --clean`, without having to set any option.

#### Expected Behavior

ranger should not crash but signal that the directory is not available.

#### First steps to reproduce

1. Mount a drive.
2. Open a new ranger tab in that drive.
3. Go back to the other tab.
4. Unmount the drive.
5. Go back to the tab in the now unaccessible drive.  It says ‘not available’, without crashing.
6. Remount the same drive, while staying in that tab.
7. Ranger crashes.

#### Second steps to reproduce

1. Mount a drive to some path `mount_path`.
2. Make a symbolic link `outside_of_mount_path/subdir_link` somewhere on another drive pointing to a subdirectory of the mounted drive `mount_path/subdir`.
3. Open a new ranger tab, go to `outside_of_mount_path`, and from there to `subdir_link`, so that you are in `subdir`, but with the path going through the symbolic link.
4. Go back to the other tab.
5. Unmount the drive.
6. Go to the tab in the symbolic link.
7. Ranger crashes.

#### Traceback

The traceback is identical in both cases.
```
ranger version: ranger-master
Python version: 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 214, in main
    fm.loop()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 417, in loop
    ui.redraw()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/usr/lib/python3.11/site-packages/ranger/gui/ui.py", line 370, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.11/site-packages/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/statusbar.py", line 110, in draw
    self._calc_bar()
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/statusbar.py", line 116, in _calc_bar
    self._get_right_part(bar)
  File "/usr/lib/python3.11/site-packages/ranger/gui/widgets/statusbar.py", line 268, in _get_right_part
    if self.fm.thisdir.flat:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'flat'

**Comment by vejkse** [comment]
So, I ‘fixed’ this by adding a check before a bunch of three tests in `statusbar.py` which are using `self.fm.thisdir`.
```python
if self.fm.thisdir:
```
But this doesn’t seem very robust.

I think I never experienced such crashes (including #2873) before 2023. Maybe before that time, when a directory was unavailable, `self.fm.thisdir` was a placeholder object instead of `None`, preventing those crashes?

**Comment by qrvd** [comment]
Your fix was a very helpful clue. The problem seems to be that `thisdir` will in fact be set to `None` when switching to a tab with a path that no longer exists, causing the crash:

https://github.com/ranger/ranger/blob/eb2ebc4e9ce8feb2a9670575554fa81f1ce11b6f/ranger/core/actions.py#L1255-L1258

Also the code above sets `tab.thisdir` to `None`, but `self.fm.thisdir` in `statusbar.py` always refers to the `thisdir` property of the current tab so it's the same variable:
https://github.com/ranger/ranger/blob/eb2ebc4e9ce8feb2a9670575554fa81f1ce11b6f/ranger/core/fm.py#L330-L339

The commit that first sets it to None is https://github.com/ranger/ranger/commit/7a1f783ebba6351d371ed52c433605a98afb8729 and it's from 2023, so you're right about the timeline, 2023 is when these crashes started to occur.

That same commit also updates some code in `titlebar.py` adding a `if self.fm.thisdir:` check before using it. So I think the intention is that every widget should be checking that value, and they just didn't update the other code yet. Which is to say that I believe your fix is the correct way to solve this even if it didn't appear robust as you said.

**Comment by vejkse** [comment]
I found another crash:

1. Open ranger in some directory (e.g. `/tmp`).
2. Create a subdirectory `a` in that directory, e.g. by running `:mkdir a`.
3. Open a second tab and go inside `a`.
4. Go back to the first tab.
5. Rename `a` into `b`.
6. Go back to the second tab.
7. Start typing `:filter` — ranger crashes at `r`.

```
ranger version: ranger-master
Python version: 3.13.7 (main, Aug 15 2025, 12:34:02) [GCC 15.2.1 20250813]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/ranger/core/main.py", line 215, in main
    fm.loop()
    ~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/core/fm.py", line 520, in loop
    ui.handle_input()
    ~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/gui/ui.py", line 273, in handle_input
    self.handle_key(key)
    ~~~~~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/gui/ui.py", line 203, in handle_key
    elif not DisplayableContainer.press(self, key):
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/gui/displayable.py", line 283, in press
    focused_obj.press(key)
    ~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 193, in press
    self.type_key(key)
    ~~~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 222, in type_key
    self.on_line_change()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 588, in on_line_change
    if cmd and cmd.quick():
               ~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/config/commands.py", line 1655, in quick
    self.fm.thisdir.filter = self._build_regex()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'filter' and no __dict__ for setting new attributes
```
There may be many other ways to crash ranger when `self.fm.thisdir` is `None`, since there are dozens of occurrences of `self.fm.thisdir` in the whole code.

**Comment by vejkse** [comment]
So I think what happened is roughly:
1. Originally, ranger created `thisdir` when visiting for the first time the directory. When the directory disappeared from under ranger, there was no “placeholder”, but the object stayed in its now incorrect state, so that all calls like `thisdir.path` worked and didn’t lead to a crash, so didn’t need to be guarded. There was only one case where `thisdir` could be `None` and ranger crashed: when loading a saved session with directories not existing any more, so that the initialization failed: https://github.com/ranger/ranger/issues/2529.
2. Since the merge of the pull request https://github.com/ranger/ranger/pull/2724 (from 2023, including the commit mentioned above), `thisdir` can now become `None` again when the directory disappears, hence all the new crashes.  But the old crash when loading a session was taken care of in that pull request.

**Comment by toonn** [comment]
Thank you for the detailed issue report!

(Solving this will most probably slip at least one release. Hut wants to just get out what we have on master. I'm going to try to get through the backlog to merge things that seem ready this week.)
