### ISSUE TITLE
ncurses error if I run a command and quit

### ISSUE THREAD

**Issue by cuppajoeman** [ranger/ranger#3000]
#### Runtime Environment
ranger version: ranger-master 
Python version: 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]
Locale: en_CA.UTF-8
- Operating system and version: Linux ccn-20k5s16a25 6.6.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Jul 19 14:57:10 UTC 2024 x86_64 GNU/Linux
- Terminal emulator and version: xfce4 terminal

#### Current Behavior

If I open ranger then run `:chain shell ls ! ; quit` I get the following ncurses error:

```
bashTraceback (most recent call last):
  File "/usr/bin/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ranger/core/main.py", line 244, in main
    fm.ui.destroy()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 188, in destroy
    self.suspend()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 160, in suspend
    curses.endwin()
_curses.error: endwin() returned ERR
```

#### Expected Behavior

I expect it to quit without the error.

#### Context

The issue effect me because I lose a quarter of the terminal when I do this and it would be nice to exit ranger without errors

I believe this is related to #2934 but this seems to be a more minimal working example of this problem

**Comment by toonn** [comment]
Could you confirm #3039 fixes the issue?
