### ISSUE TITLE
2.5.0 - LDAP/FreeIPA user synchronization error

### ISSUE THREAD

**Issue by avs-alatau** [ranger/ranger#3001]
#### Runtime Environment
- Operating system and version:  Ubuntu 20
- Python version: Python 3.8.10
- Ranger version/commit: 2.5.0
![7566r56](https://github.com/user-attachments/assets/62ac807d-5faf-4715-a867-88a4b9ced331)
![7566r111111156](https://github.com/user-attachments/assets/bcb325c5-5a6f-4f7b-9ffe-ae4c14fb7b83)

#### Current Behavior
LDAP/FreeIPA user synchronization error
The user's first name and last name fields are written instead of the user's uid
before upgrading to version 2.5.0, version 3.0.0-SNAPSHOT was installed and the synchronization was successful and correct

#### Expected Behavior
correct synchronization of users by fields in the database

#### Context
synchronization of users from LDAP/FreeIPA

#### Possible Solutions
bug fix

**Comment by avs-alatau** [comment]
![7566r56](https://github.com/user-attachments/assets/7d43cc8c-17ce-4cd8-901d-69978dc3d4aa)

**Comment by avs-alatau** [comment]
```
13 Aug 2024 11:29:31  WARN o.a.r.u.p.PolicyMgrUserGroupBuilder [UnixUserSyncThread] - ERROR: Unable to update roles for: [Alex Grom, Mikhail Ryzh, keyadmin, Anat Zhan, admin, Dmit Vert, Black Alex, rangerusersync, rangertagsync, Nick Blacksmith, Alexander Semitas, Grateful Nik]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at com.google.gson.Gson.fromJson(Gson.java:905)
        at org.apache.ranger.unixusersync.process.PolicyMgrUserGroupBuilder.updateUsersRoles(PolicyMgrUserGroupBuilder.java:1324)
        at org.apache.ranger.unixusersync.process.PolicyMgrUserGroupBuilder.updateRoles(PolicyMgrUserGroupBuilder.java:1274)
        at org.apache.ranger.unixusersync.process.PolicyMgrUserGroupBuilder.updateUserRoles(PolicyMgrUserGroupBuilder.java:632)
        at org.apache.ranger.unixusersync.process.PolicyMgrUserGroupBuilder.addOrUpdateUsersGroups(PolicyMgrUserGroupBuilder.java:389)
        at org.apache.ranger.ldapusersync.process.LdapUserGroupBuilder.updateSink(LdapUserGroupBuilder.java:417)
        at org.apache.ranger.usergroupsync.UserGroupSync.syncUserGroup(UserGroupSync.java:115)
        at org.apache.ranger.usergroupsync.UserGroupSync.run(UserGroupSync.java:57)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        ... 10 common frames omitted
```

**Comment by avs-alatau** [comment]
after reinstalling usersync, the problem was resolved.
