### ISSUE TITLE
ranger bulkrename edwin() err

### ISSUE THREAD

**Issue by luck-xing** [ranger/ranger#3005]
#### Runtime Environment

- manjaro 
- alacritty 0.13.2: 
- Python 3.12.4: 
- Ranger-master: 
- Locale zh_CN.UTF-8: 

#### Current Behavior
ranger execute :bulkrename edwin() return err
#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
zshTraceback (most recent call last):
  File "/usr/bin/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ranger/core/main.py", line 244, in main
    fm.ui.destroy()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 188, in destroy
    self.suspend()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 160, in suspend
    curses.endwin()
_curses.error: endwin() returned ERR
```

**Comment by vejkse** [comment]
As you describe it, is sounds like a duplicate of https://github.com/ranger/ranger/issues/2934 (see there for temporary solutions) even though the traceback looks more like https://github.com/ranger/ranger/issues/3000.

**Comment by luck-xing** [comment]
> As you describe it, is sounds like a duplicate of #2934 (see there for temporary solutions) even though the traceback looks more like #3000.
> 
> 正如你所描述的，它听起来像[是#2934](https://github.com/ranger/ranger/issues/2934)的副本（参见那里的临时解决方案），尽管回溯看起来更像是#3000。

Thank you for your answer, but Manjaro seems unable to downgrade ncurses 6.5 to 6.4, and I can't find the installation package of ncurses6.4 on the Internet.

**Comment by vejkse** [comment]
Did you try to follow the instructions in https://wiki.manjaro.org/index.php/Downgrading_packages?  That old package may not work any more with its dependencies or the packages that depend on it.

In the other issue, there were other solutions that do not require to downgrade ncurse: manually editing `/usr/lib/python3.12/site-packages/ranger/gui/ui.py` or using the external tool brn2 instead of the built in `:bulkrename`.

**Comment by luck-xing** [comment]
> Did you try to follow the instructions in https://wiki.manjaro.org/index.php/Downgrading_packages? That old package may not work any more with its dependencies or the packages that depend on it.
> 
> In the other issue, there were other solutions that do not require to downgrade ncurse: manually editing `/usr/lib/python3.12/site-packages/ranger/gui/ui.py` or using the external tool brn2 instead of the built-in `:bulkrename`.

Thank you very much for your help, the problem has been solved

**Comment by toonn** [comment]
Could you confirm #3039 fixes the issue?

**Comment by acampove** [comment]
@toonn It does, thanks, I checked the master. BTW, I would release 1.9.5, people out there keep having problems with this:

https://github.com/ranger/ranger/issues/3049
