### ISSUE TITLE
ranger crashed; reporting as instructed

### ISSUE THREAD

**Issue by SSYH** [ranger/ranger#3022]
.%;888:8898898:                sam@imac151gh
                 x;XxXB%89b8:b8%b88:              -------------
              .8Xxd                8X:.           OS: Garuda Linux x86_64
            .8Xx;                    8x:.         Host: iMac15,1 (1.0)
          .tt8x          .d            x88;       Kernel: 6.11.5-zen1-1-zen
       .@8x8;          .db:              xx@;     Uptime: 9 mins
     ,tSXX°          .bbbbbbbbbbbbbbbbbbbB8x@;    Packages: 1519 (pacman)[stable]
   .SXxx            bBBBBBBBBBBBBBBBBBBBbSBX8;    Shell: fish 3.7.1
 ,888S                                     pd!    Resolution: 3840x2160
8X88/                                       q     WM: Hyprland (Wayland)
8X88/                                             Theme: Sweet [Qt], BeautyLine [GTK2], Sweet-Dark [GTK3/4]
GBB.                                              Icons: BeautyLine [Qt], BeautyLine [GTK2/3/4]
 x%88        d888@8@X@X@X88X@@XX@@X@8@X.          Terminal: alacritty 0.14.0
   dxXd    dB8b8b8B8B08bB88b998888b88x.           Terminal Font: alacritty 11
    dxx8o                      .@@;.              CPU: Intel(R) Core(TM) i5-4690 (4) @ 3.90 GHz
      dx88                   .t@x.                GPU: AMD Radeon R7 370 / R9 270X/370X [Discrete]
        d:SS@8ba89aa67a853Sxxad.                  Memory: 7799 MiB / 32038 MiB
          .d988999889889899dd.

 ╭─sam@imac151gh in ~
 ╰─λ

#### Runtime Environment

- Operating system and version: 6.11.5-zen1-1-zen

                   .%;888:8898898:                sam@imac151gh
                 x;XxXB%89b8:b8%b88:              -------------
              .8Xxd                8X:.           OS: Garuda Linux x86_64
            .8Xx;                    8x:.         Host: iMac15,1 (1.0)
          .tt8x          .d            x88;       Kernel: 6.11.5-zen1-1-zen
       .@8x8;          .db:              xx@;     Uptime: 9 mins
     ,tSXX°          .bbbbbbbbbbbbbbbbbbbB8x@;    Packages: 1519 (pacman)[stable]
   .SXxx            bBBBBBBBBBBBBBBBBBBBbSBX8;    Shell: fish 3.7.1
 ,888S                                     pd!    Resolution: 3840x2160
8X88/                                       q     WM: Hyprland (Wayland)
8X88/                                             Theme: Sweet [Qt], BeautyLine [GTK2], Sweet-Dark [GTK3/4]
GBB.                                              Icons: BeautyLine [Qt], BeautyLine [GTK2/3/4]
 x%88        d888@8@X@X@X88X@@XX@@X@8@X.          Terminal: alacritty 0.14.0
   dxXd    dB8b8b8B8B08bB88b998888b88x.           Terminal Font: alacritty 11
    dxx8o                      .@@;.              CPU: Intel(R) Core(TM) i5-4690 (4) @ 3.90 GHz
      dx88                   .t@x.                GPU: AMD Radeon R7 370 / R9 270X/370X [Discrete]
        d:SS@8ba89aa67a853Sxxad.                  Memory: 7799 MiB / 32038 MiB
          .d988999889889899dd.

 ╭─sam@imac151gh in ~
 ╰─λ

- Terminal emulator and version: alacritty
- Python version: 3.12.7 (main, Oct 1 2024, 11:15:50) [GCC 14.2.1 20240910]
- Ranger version/commit: 1.9.3

- Locale: en-us

#### Current Behavior
- see trace below

#### Expected Behavior
- ranger runs as expected

#### Context
- made me sad

#### Possible Solutions
- just doing as instructed ("Please report this traceback at:...")

#### Steps to reproduce
1. "ranger"

#### Traceback

 ╭─sam@imac151gh in ~ took 0s
[🔴] × ranger .config/hypr/hyprland.conf
ranger version: ranger 1.9.3
Python version: 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.12/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3.12/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.12/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3.12/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

 ╭─sam@imac151gh in ~ took 0s
[🔴] ×

 ╭─sam@imac151gh in ~ took 0s
[🔴] × ranger --version
ranger version: ranger 1.9.3
Python version: 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910]
Locale: en_US.UTF-8

 ╭─sam@imac151gh in ~ took 0s
 ╰─λ

![image](https://github.com/user-attachments/assets/50c7f9a9-d64b-4152-a5f9-960b8263ff68)

**Comment by vejkse** [comment]
This looks exactly like this issue: #2557 which is fixed in the latest version of the code, for which there is no release yet.  Since you are using an ArchLinux-derived distribution, you probably can get it by installing the ranger-git AUR package: https://aur.archlinux.org/packages/ranger-git.
