### ISSUE TITLE
Ranger crashed on moving single file to trash

### ISSUE THREAD

**Issue by onion108** [ranger/ranger#3026]
#### Runtime Environment

- Operating system and version: macOS 15.1 / Darwin 24.1.0 (arm64)
- Terminal emulator and version: kitty 0.37.0
- Python version: 3.13.0
- Ranger version/commit: 1.9.4 (Homebrew)
- Locale: en_US.UTF8

#### Current Behavior
`ranger` crashed when trying to move marked file to trash (only marked one file).  

#### Expected Behavior
The file should be successfully moved to the trash folder (in my case either `~/.Trash` or `~/Library/Mobile Documents/.Trash`)

#### Context

Go into my folder (basically full of C++ files) and trying to mark one file and then pressed `dT` and enter and confirmed the operation.

#### Possible Solutions
Not found yet.

#### Steps to reproduce
1. Create a folder
2. Create a file in it
3. Mark the file
4. Press `dT` and then enter
5. Confirm the operation
6. Watch it crash

#### Traceback

```
ranger version: ranger 1.9.4
Python version: 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)]
Locale: en_US.UTF-8
Current file: '/Users/onion27/Workspace/Programming/Lab/cpp/comma.cc'

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
    ~~~~~~~^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
    ~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
    ~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
    ~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
    ~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
    ~~~~~~~~^^^^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
                 ^^^^^^
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
I created an empty folder and created an empty file `a` in it and tried again (to confirm this isn't because my folder is full of C++ files which I don't think it's possible but still tried in order to be confident), here is another traceback after I do so:
```
ranger version: ranger 1.9.4
Python version: 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)]
Locale: en_US.UTF-8
Current file: '/Users/onion27/Workspace/Programming/Lab/cpp/tmp/a'

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
    ~~~~~~~^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
    ~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
    ~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
    ~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
    ~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
    ~~~~~~~~^^^^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ranger/1.9.4/libexec/lib/python3.13/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
                 ^^^^^^
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by vejkse** [comment]
This looks like a dozen other issues, for instance this one: https://github.com/ranger/ranger/issues/2361

See in particular the very last comment, by cskeeters, for a Homebrew solution.

**Comment by toonn** [comment]
I think the problem here might be having an old `commands.py`. If you haven't customized it, remove it, otherwise you'll have to diff it and make some manual changes.

**Comment by astr0gator** [comment]
@toonn 
I have the same issue. Deleted `commands.py` as per your recommendation. Now I can't launch ranger:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py312/lib/python3.12/site-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/opt/anaconda3/envs/py312/lib/python3.12/site-packages/ranger/core/main.py", line 362, in load_settings
    from ranger.config import commands as commands_default
ImportError: cannot import name 'commands' from 'ranger.config' (/opt/anaconda3/envs/py312/lib/python3.12/site-packages/ranger/config/__init__.py)

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

What I'm doing wrong? @vejkse Have you solved the puzzle? 🙂

**Comment by toonn** [comment]
What version of Ranger are you running?
Did you remove `~/.config/ranger/commands.py` or some other file?
Does Ranger run when you pass the `--clean` option?

**Comment by astr0gator** [comment]
@toonn 

1. Last version
`ranger version: ranger 1.9.4`

2. Hm.. My current `/.config/ranger`:
rc.conf
rifle.conf

3. ranger --clean:
`'str' object has no attribute 'path'` (no crash this time, file remains not deleted)

**Comment by toonn** [comment]
The fix is in master but not in any release yet.
