### ISSUE TITLE
Ranger crashes when set preview_images_method is set to sixel (worked in previous version)

### ISSUE THREAD

**Issue by yagarea** [ranger/ranger#3034]
#### Runtime Environment

- Operating system and version: archlinux 6.12.4-arch1-1
- Terminal emulator and version: alacritty 0.14.0-dev (c7213774) (sixel branch)
- Python version: Python 3.13.1
- Ranger version/commit: ranger version: ranger 1.9.4
- Locale: C.UTF-8

#### Current Behavior
Crashes on start

#### Expected Behavior
Not crash on start

#### Steps to reproduce
1. set `set preview_images_method sixel` in `.config/ranger/rc.conf` 
2. start ranger

#### Traceback

```
ranger version: ranger 1.9.4
Python version: 3.13.1 (main, Dec  4 2024, 18:05:56) [GCC 14.2.1 20240910]
Locale: C.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/ext/img_display.py", line 98, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
                            ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/ext/img_display.py", line 78, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Shorkerrr** [comment]
Exact same issue here

OS/Kernel: Arch Linux 64 Bit / 6.12.7-zen1-1-zen
Terminal Emulator: foot version: 1.19.0
ranger version: ranger 1.9.4
Python version: 3.13.1
Locale: en_SE.UTF-8

**Comment by toonn** [comment]
I can't reproduce the exception, does it still happen on latest master?

The preview isn't working for me either though so that's not much better than a crash.

**Comment by yagarea** [comment]
I have downgraded to [`ranger-git 1.9.3.730.gbd9b37fa-1`](https://aur.archlinux.org/packages/ranger-git) and everything works fine.

When I upgrade to [`1.9.4-3`](https://archlinux.org/packages/extra/any/ranger/) I get this error on start:
```
ranger version: ranger 1.9.4
Python version: 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128]
Locale: C.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/ext/img_display.py", line 98, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
                            ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ranger/ext/img_display.py", line 78, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

---

If you want me to test some other version I can do that as well.

**Comment by jgresty** [comment]
Sixel support was added in f8827271799632ffdcf937fa8714c8a30a6dc16c , and that commit is not part of 1.9.4. Some distros packaged master (eg [nixos](https://github.com/NixOS/nixpkgs/pull/280143)) to get these features without waiting on the slow release cycle.

**Comment by yagarea** [comment]
I cloned this repo and installed it using `sudo make install`
```
ranger --version
ranger version: ranger-master
Python version: 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128]
Locale: C.UTF-8
```
Image preview works as it should.

**Comment by yagarea** [comment]
Should I close this issue if it is resolved in current master branch ?

**Comment by toonn** [comment]
Yeah, let's close for now.
