### ISSUE TITLE
Kitty image preview not used in Ghostty, despite support

### ISSUE THREAD

**Issue by LRitzdorf** [ranger/ranger#3035]
#### Runtime Environment
- Terminal emulator and version: Ghostty 1.0.0-dev+0000000
- Ranger version/commit: bd9b37faee9748798f3970468bd0d1dedbf0e99f

#### Current Behavior
Under the recently-out-of-beta Ghostty, Ranger refuses to use the Kitty image protocol for image preview.

#### Expected Behavior
Ranger should use the Kitty image protocol, which [Ghostty supports](https://ghostty.org/docs/features).

#### Possible Solutions
Currently, Ranger prints an explanatory comment that Kitty image preview only works when not in a tmux session, and when `$TERM` contains the string `kitty`. Whichever check produces this should be expanded to also check for Ghostty (which sets `TERM=xterm-ghostty`).

**Comment by mbledkowski** [comment]
Same

**Comment by LRitzdorf** [comment]
@svalbardsleeperdistrict The PR hasn't even been merged yet (are you familiar with how GitHub works?) so the fix being available in your distro's package is probably quite a while off.

If you want the patch *now*, you should be able to modify your ranger installation's `img_display.py` to match the changes in the PR. (On my Arch system, that's located at `/usr/lib/python3.13/site-packages/ranger/ext/img_display.py`; YMMV on other distros.) Note that this change will be lost if your distro ships any further Ranger updates before the next full release, as your package manager will overwrite the file.

**Comment by svalbardsleeperdistrict** [comment]
@LRitzdorf Thank you.

**Comment by bhavesh-7** [comment]
> I'm having this issue as well. I read [#3036](https://github.com/ranger/ranger/pull/3036), and it said the function had been enabled, but I'm not sure if I need to change anything in Ranger config files to make it work on my end. I'm pretty inexperienced with this. Is a fix for image previews in Ghostty coming in a future Ranger version, and I just need to wait?

THIS IS JUST AN TEMPORARY FIX. 

Try to use it yourself and correct if this can be done other ways.

Solution:
Just comment out the if condition that check if the TERM contains the string "kitty", and then the picture preview works just fine for every image file extension.

You can find it in `/usr/lib/python3.13/site-packages/ranger/ext/img_display.py` this file, just search for kitty and inside late_init function you find the `if ` statement, COMMENT IT.

**Comment by svalbardsleeperdistrict** [comment]
Thank you for the reply @bhavesh-7 . I opened that file (here's the full content: ) and commented this line:

`if 'kitty' not in os.environ['TERM']:`

But after saving and attempting to run Ranger, this is what I got:

```
~> ranger
Traceback (most recent call last):
  File "/usr/bin/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
             ~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ranger/core/main.py", line 34, in main
    from ranger.core.fm import FM
  File "/usr/lib/python3.13/site-packages/ranger/core/fm.py", line 25, in <module>
    from ranger.ext.img_display import get_image_displayer
  File "/usr/lib/python3.13/site-packages/ranger/ext/img_display.py", line 589
    with NamedTemporaryFile() as tmpf:
                                      ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by bhavesh-7** [comment]
> Thank you for the reply [@bhavesh-7](https://github.com/bhavesh-7) . I opened that file ([here's the full content](https://pastebin.com/RAmbr4fW)) and commented this line:
> 
> `if 'kitty' not in os.environ['TERM']:`
> 
> But after saving and attempting to run Ranger, this is what I got:
> 
> ```
> ~> ranger
> Traceback (most recent call last):
>   File "/usr/bin/ranger", line 37, in <module>
>     sys.exit(ranger.main())  # pylint: disable=no-member
>              ~~~~~~~~~~~^^
>   File "/usr/lib/python3.13/site-packages/ranger/core/main.py", line 34, in main
>     from ranger.core.fm import FM
>   File "/usr/lib/python3.13/site-packages/ranger/core/fm.py", line 25, in <module>
>     from ranger.ext.img_display import get_image_displayer
>   File "/usr/lib/python3.13/site-packages/ranger/ext/img_display.py", line 589
>     with NamedTemporaryFile() as tmpf:
>                                       ^
> IndentationError: unindent does not match any outer indentation level
> ```

you also had to comment everything inside the function, though, do one thing, uncomment the line that you have commented and replace `kitty` with `xterm`, NOTE: This will break ranger if you try to preview images in some other terminals than ghostty or kitty.

**Comment by svalbardsleeperdistrict** [comment]
> > Thank you for the reply [@bhavesh-7](https://github.com/bhavesh-7) . I opened that file ([here's the full content](https://pastebin.com/RAmbr4fW)) and commented this line:
> > `if 'kitty' not in os.environ['TERM']:`
> > But after saving and attempting to run Ranger, this is what I got:
> > ```
> > ~> ranger
> > Traceback (most recent call last):
> >   File "/usr/bin/ranger", line 37, in <module>
> >     sys.exit(ranger.main())  # pylint: disable=no-member
> >              ~~~~~~~~~~~^^
> >   File "/usr/lib/python3.13/site-packages/ranger/core/main.py", line 34, in main
> >     from ranger.core.fm import FM
> >   File "/usr/lib/python3.13/site-packages/ranger/core/fm.py", line 25, in <module>
> >     from ranger.ext.img_display import get_image_displayer
> >   File "/usr/lib/python3.13/site-packages/ranger/ext/img_display.py", line 589
> >     with NamedTemporaryFile() as tmpf:
> >                                       ^
> > IndentationError: unindent does not match any outer indentation level
> > ```
> 
> you also had to comment everything inside the function, though, do one thing, uncomment the line that you have commented and replace `kitty` with `xterm`, like this : `if 'xterm' not in os.environ['TERM']:` . NOTE: This will break ranger if you try to preview images in some other terminals than ghostty or kitty.
> 
> THIS IS JUST A TEMPORARY FIX.

Many thanks, that worked perfectly. Will wait for the longterm fix while benefitting from this workaround.

**Comment by bhavesh-7** [comment]
I just found out you can add this line in ghostty's config:
`term = xterm-kitty` and ranger's image preview will work just fine. This does not need manual change of conditions in ranger files, this will just change the $TERM of ghostty to xterm-kitty, which is exactly the same as of kitty.

Give it a try.

**Comment by svalbardsleeperdistrict** [comment]
I tried that after undoing the previous change in the ranger file above, and it did not work. Should I have kept the change in `img_display.py`? I thought when you said no manual change is needed, you meant that one should be reset back to default - maybe I misunderstood.

**Comment by bhavesh-7** [comment]
> I tried that after undoing the previous change in the ranger file above, and it did not work. Should I have kept the change in `img_display.py`? I thought when you said no manual change is needed, you meant that one should be reset back to default - maybe I misunderstood.

I think you either misunderstood or didn't do it correctly.

In you ghostty config, `$HOME/.config/ghostty/config` add this line: `term = xterm-kitty` at the start of the file.
Then exit and open Ghostty again, and run `echo $TERM` in your terminal, if you see `xterm-kitty` you did it right, if not, then open the config file from the ghostty's Title bar itself and add the above mentioned line.

You can now undo the changes made  `/usr/lib/python3.13/site-packages/ranger/ext/img_display.py` here, that is, change `xterm` to `kitty` in  line `if 'xterm' not in os.environ['TERM']:`, save changes, exit out the terminal and see if you can preview images in ranger. This will not give you error even when you've updated kitty to any newer version.

This works for me without breaking ranger in other terminals like Blackbox-Terminal or Gnome-Terminal.

**Comment by svalbardsleeperdistrict** [comment]
> > I tried that after undoing the previous change in the ranger file above, and it did not work. Should I have kept the change in `img_display.py`? I thought when you said no manual change is needed, you meant that one should be reset back to default - maybe I misunderstood.
> 
> I think you either misunderstood or didn't do it correctly.
> 
> In you ghostty config, `$HOME/.config/ghostty/config` add this line: `term = xterm-kitty` at the start of the file. Then exit and open Ghostty again, and run `echo $TERM` in your terminal, if you see `xterm-kitty` you did it right, if not, then open the config file from the ghostty's Title bar itself and add the above mentioned line.
> 
> You can now undo the changes made `/usr/lib/python3.13/site-packages/ranger/ext/img_display.py` here, that is, change `xterm` to `kitty` in line `if 'xterm' not in os.environ['TERM']:`, save changes, exit out the terminal and see if you can preview images in ranger. This will not give you error even when you've updated kitty to any newer version.
> 
> This works for me without breaking ranger in other terminals like Blackbox-Terminal or Gnome-Terminal.

Thank you, it worked this time. The only difference was I needed to use `echo $env.TERM` instead of `echo $TERM` in that part.

**Comment by svalbardsleeperdistrict** [comment]
@bhavesh-7  Can I bring this back up with an issue I came across when attempting to do the same steps on my laptop? I use the same terminal and shell there on the same distro, but when I followed the same instructions, [this](https://i.imgur.com/Coq74jH.png) is the message I get in Ranger when an image is selected and preview is not appearing. Any ideas what may be causing this?

**Comment by yikesboy** [comment]
> [@bhavesh-7](https://github.com/bhavesh-7) Can I bring this back up? Some recent update must have broken these settings, since [this](https://i.imgur.com/Coq74jH.png) is the message I get in Ranger when an image is selected and preview is not appearing. Any ideas what may be causing this?

yup same, issue

`kitty replied "b'\x1b_Gi=5;EINVAL: temporary file not named correctly\x1b\\'"`

**Comment by toonn** [comment]
Is this when running the master branch?

**Comment by josbarros** [comment]
Hello, I've noticed that the latest versions of Ghostty (1.3.x) are breaking the Kitty image preview and generating an error similar to what @svalbardsleeperdistrict reported, in my case is this:

`File "/home/rui/.local/share/pipx/venvs/ranger-fm/lib64/python3.14/site-packages/ranger/ext/img_display.py", line 774, in _late_init
    raise ImgDisplayUnsupportedException(
        'unexpected response from terminal emulator: {r}'.format(r=resp))
ranger.ext.img_display.ImgDisplayUnsupportedException: unexpected response from terminal emulator: b'\x1b_Gi=1;EINVAL: invalid data\x1b'`

I'm running the latest ranger-master. Should I file a separate ticket here? Or in the ghostty project instead?

**Comment by vejkse** [comment]
It looks like a different issue, you have `invalid data` and not `temporary file not named correctly` (and the latter was anyway already another issue than the original one).  You should probably create a new issue.
