### ISSUE TITLE
Sshfs mountpoint, disconnected during pc sleep crashes ranger

### ISSUE THREAD

**Issue by lxyd** [ranger/ranger#315]
Hello!

Steps to reproduce:
• mount a directory via sshfs;
• open a file inside it with ranger;
• put device to sleep;
• wake up the device a couple of hours later or in a different network (mountpoint will be disconnected).

Stacktrace:

```
ranger version: 1.7.0, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: /home/user/mnt/sshfs/some/path/to/my/file.html
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/browserview.py", line 98, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/browsercolumn.py", line 164, in draw
    self._draw_file()
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/browsercolumn.py", line 194, in _draw_file
    self.set_source(f)
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/pager.py", line 157, in set_source
    self.source.close()
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by nfnty** [comment]
Fixed. Request to reopen if you're still experiencing this issue on `master`.
