### ISSUE TITLE
Crash when running vim-ack plugin from a vim instance opened from ranger

### ISSUE THREAD

**Issue by Soapbubble** [ranger/ranger#321]
Hi,

I have the following setup:
- cygwin (on Windows 7 x86_64)
- ranger (manually compiled from github for it to work on cygwin)
- vim + vundle + vim-ack plugin
  When I open a file with vim from ranger and try to use the Ack plugin with :Ack, ranger crashes as soon as I type the "A". The issue is related to ranger because there's no crash if I open vim directly from the command line.

This is the traceback:

```
ranger version: 1.7.1, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: /c/data/somefile.txt
Traceback (most recent call last):
  File "/cygdrive/c/home/sources/ranger-171/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/cygdrive/c/home/sources/ranger-171/ranger/core/fm.py", line 344, in loop
    ui.handle_input()
  File "/cygdrive/c/home/sources/ranger-171/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/cygdrive/c/home/sources/ranger-171/ranger/gui/ui.py", line 145, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/cygdrive/c/home/sources/ranger-171/ranger/gui/displayable.py", line 261, in press
    focused_obj.press(key)
  File "/cygdrive/c/home/sources/ranger-171/ranger/gui/widgets/console.py", line 173, in press
    self.type_key(key)
  File "/cygdrive/c/home/sources/ranger-171/ranger/gui/widgets/console.py", line 202, in type_key
    self.on_line_change()
  File "/cygdrive/c/home/sources/ranger-171/ranger/gui/widgets/console.py", line 425, in on_line_change
    if cmd and cmd.quick():
  File "/cygdrive/c/home/sources/ranger-171/ranger/api/commands.py", line 397, in quick
    return self._make_cmd().quick()
  File "/cygdrive/c/home/sources/ranger-171/ranger/api/commands.py", line 406, in _make_cmd
    cmd_class = self.fm.commands.get_command(self._line.split()[0])
IndexError: list index out of range
```

Thanks!
Andrei

**Comment by nfnty** [comment]
Same issue as #764 and it's already fixed.
