### ISSUE TITLE
freebsd 10.2p3 :Exception: Warning: Subwindow size out of bounds for <BrowserView> (x = 0, y = 29864864, hei = 22, wid = 80)

### ISSUE THREAD

**Issue by blackcat707** [ranger/ranger#377]
Hello, after upgrading ranger to version 1.7.1 ranger crashed.

:~ % ranger -d
ranger version: 1.7.1, executed with python 2.7.10
Locale: None.None

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/local/lib/python2.7/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/ui.py", line 253, in redraw
    self.poke()
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/displayable.py", line 238, in poke
    displayable.poke()
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/widgets/browserview.py", line 362, in poke
    self.resize(self.y, self.x, self.hei, self.wid)
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/widgets/browserview.py", line 275, in resize
    DisplayableContainer.resize(self, y, x, hei, wid)
  File "/usr/local/lib/python2.7/site-packages/ranger/gui/displayable.py", line 161, in resize
    x, y, hei, wid), bad=True)
  File "/usr/local/lib/python2.7/site-packages/ranger/core/actions.py", line 128, in notify
    raise Exception(str(text))
Exception: Warning: Subwindow size out of bounds for <BrowserView> (x = 0, y = 29864864, hei = 22, wid = 80)

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

**Comment by demonking** [comment]
seems like similiar to my errors ;) 

#317

**Comment by nfnty** [comment]
Continue discussion in #317.

**Comment by blackcat707** [comment]
Hello nfnty,

in the meantime i have upgraded my freebsd system to 11.0 Release and 
ranger and rifle are still doing their duty. I use ranger 1.7.2 and python 
2.7.13 and it works like a charme.

Someone was even so kind and ported py-ranger to pkgsrc/wip 
(www.pkgsrc.se). pkgsrc is a framework for building third-party 
software on NetBSD and other UNIX-like systems, so you can use this 
nice little file manager on many platforms!

Thank you very much for this fine piece of software.

Many greetings send from my netbsd system.

blackcat

**Comment by nfnty** [comment]
Thanks for the update. Does that mean this issue has been completely resolved?

**Comment by blackcat707** [comment]
Yes you can close the thread. After the python update i have never seen 
those warnings again. Have a nice day.
