### ISSUE TITLE
Ranger crashed on 3Gb ASCII text file containing a single line

### ISSUE THREAD

**Issue by rolfschr** [ranger/ranger#414]
I do not expect ranger to cope with this file, but the crash message asked me to report this.

```
ranger version: 1.6.1, executed with python 2.7.5
Locale: en_US.UTF-8
Current file: /path/to/file.
Traceback (most recent call last):
  File "/home/rschroeder/src/ranger/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/home/rschroeder/src/ranger/ranger/core/fm.py", line 336, in loop
    ui.redraw()
  File "/home/rschroeder/src/ranger/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/home/rschroeder/src/ranger/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/home/rschroeder/src/ranger/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/home/rschroeder/src/ranger/ranger/gui/widgets/browserview.py", line 98, in draw
    DisplayableContainer.draw(self)
  File "/home/rschroeder/src/ranger/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/home/rschroeder/src/ranger/ranger/gui/widgets/browsercolumn.py", line 164, in draw
    self._draw_file()
  File "/home/rschroeder/src/ranger/ranger/gui/widgets/browsercolumn.py", line 195, in _draw_file
    Pager.draw(self)
  File "/home/rschroeder/src/ranger/ranger/gui/widgets/pager.py", line 82, in draw
    for line, i in zip(line_gen, range(self.hei)):
  File "/home/rschroeder/src/ranger/ranger/gui/widgets/pager.py", line 216, in _generate_lines
    line = self._get_line(i).expandtabs(4)
  File "/home/rschroeder/src/ranger/ranger/gui/widgets/pager.py", line 199, in _get_line
    for l in self.source:
SystemError: Negative size passed to PyString_FromStringAndSize

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by nfnty** [comment]
This is a Python issue that is probably caused by a 32-bit int overflow. Fix by running on 64-bit arch or possibly by running on a newer Python version. Request reopen if you're still affected by this issue.
