### ISSUE TITLE
ranger crash with C locale

### ISSUE THREAD

**Issue by Ypnose** [ranger/ranger#464]
Hi,
Here we go:

```
$ LC_ALL=C ranger
ranger version: 1.7.2, executed with python 3.5.1
Locale: None.None
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 121, in main
    fm.initialize()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 115, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.5/site-packages/ranger/container/bookmarks.py", line 39, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.5/site-packages/ranger/container/bookmarks.py", line 183, in _load_dict
    for line in f:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 265: ordinal not in range(128)

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

or

```
$ LC_ALL=C.UTF-8 ranger                                                                                                                        
Warning: Unable to set locale.  Expect encoding problems.
ranger version: 1.7.2, executed with python 3.5.1
Locale: None.None
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 121, in main
    fm.initialize()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 115, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.5/site-packages/ranger/container/bookmarks.py", line 39, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.5/site-packages/ranger/container/bookmarks.py", line 183, in _load_dict
    for line in f:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 265: ordinal not in range(128)

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by hut** [comment]
Is this ranger 1.7.2 stable, or do you use the git version? I believe this is fixed in the git version already.

**Comment by Ypnose** [comment]
Stable

**Comment by nfnty** [comment]
This is an upstream issue in Python:
https://bugs.python.org/issue19846
https://bugs.python.org/issue28180

**Comment by Ypnose** [comment]
Ok, roger. Glad I'm not using this broken Python, anymore.
