### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Skyfold** [ranger/ranger#517]
I am not sure what key I pressed to set this off, but I hope this helps you improve ranger.

ranger version: 1.7.2, executed with python 2.7.10
Locale: en_US.UTF-8
Current file: /Users/SkyFold/git_projects/GasWork/GasWork-com/images
Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/core/fm.py", line 344, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/gui/ui.py", line 145, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/gui/displayable.py", line 261, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/gui/widgets/console.py", line 173, in press
    self.type_key(key)
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/gui/widgets/console.py", line 202, in type_key
    self.on_line_change()
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/gui/widgets/console.py", line 425, in on_line_change
    if cmd and cmd.quick():
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/api/commands.py", line 397, in quick
    return self._make_cmd().quick()
  File "/usr/local/Cellar/ranger/1.7.2/libexec/ranger/api/commands.py", line 406, in _make_cmd
    cmd_class = self.fm.commands.get_command(self._line.split()[0])
IndexError: list index out of range

**Comment by hut** [comment]
This happens if you type `:<tab>` while running `ranger --debug`. (works fine without --debug). Could this have been it?

**Comment by nfnty** [comment]
Reopen this issue if you're still experiencing this.
