### ISSUE TITLE
Terminator auto open problem with solarized color scheme.

### ISSUE THREAD

**Issue by w1r3dh4ck3r** [ranger/ranger#531]
I have configured ranger to open automatically in my terminator, it used to work until I changed the color scheme to solarized, now I get this error when starting automatically:

`ranger version: 1.7.1, executed with python 2.7.11+
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
    self._print_result(self.result)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/titlebar.py", line 151, in _print_result
    self.color(_part.lst)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/curses_shortcuts.py", line 57, in color
    attr = self.settings.colorscheme.get_attr(_keys)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
    value = fnc(*args)
File "/usr/lib/python2.7/dist-packages/ranger/gui/colorscheme.py", line 66, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/lib/python2.7/dist-packages/ranger/gui/color.py", line 38, in get_color
    curses.init_pair(size, fg, bg)
error: init_pair() returned ERR

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues`

If I issue the ranger command it starts normally without a problem, here is the entry in the terminator config:
`[[[terminal9]]]
      order = 1
      parent = child5
      profile = default
      command = 'ranger; zsh'
      type = Terminal
      uuid = f1c3afe8-5734-4aa6-bd7e-5071130bf154`

As I said, it works with any other color schemes, just not with solarized, that for me is the best one.

**Comment by hut** [comment]
Your environment seems to be misconfigured, either your terminal doesn't support 256 colors (which is unlikely) or your $TERM variable is incorrect. Programs using the `curses` library depend on a correctly set $TERM variable for proper color support.

This particular crash is fixed in the git version of ranger, but upgrading will probably not help you because for proper colors you still need the correct $TERM variable.

**Comment by hut** [comment]
Oh, since it only happens when you "auto open" it, try this:

1. start a terminal and type `echo $TERM` (it should output something containing `terminator` and `256color`)
2. auto-open ranger and type `:shell -w echo $TERM`

is there a difference between the two outputs?

**Comment by v1kn** [comment]
I happen to have a working tmux  tmuxinator vim and solarized on autostart.  Yeah you need to have proper settings in each and every config file of these programs.  
If you are still having this issue, check my dotfiles

**Comment by nfnty** [comment]
Reopen this issue if you're still experiencing it.
