### ISSUE TITLE
"linemode fileinfo" crash

### ISSUE THREAD

**Issue by extrasharp** [ranger/ranger#553]
just testing out ranger features i hadent looked at yet,  when i came across linemodes.
the built in "map Mi linemode fileinfo" keymapping crashes with:

 ranger version: 1.7.2, executed with python 3.5.1
Locale: en_US.UTF-8
Current file: /home/mel/.adobe
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.5/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/browserview.py", line 98, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.5/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/browsercolumn.py", line 166, in draw
    self._draw_directory()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/browsercolumn.py", line 305, in _draw_directory
    infostringdata = current_linemode.infostring(drawn, metadata)
  File "/usr/lib/python3.5/site-packages/ranger/core/linemode.py", line 99, in infostring
    fileinfo = check_output(["file", "-bL", file.path]).strip()
  File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['file', '-bL', '/home/mel/.esd_auth']' returned non-zero exit status 1

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
## 

seems when a dotfile or symbolic link is selected and you use Mi, it will crash.
however if a plain, non-hidden file is selected when you enter the mapping everything works fine

**Comment by hut** [comment]
Hey, can you test again with the most recent git version? Should be fixed now.

**Comment by extrasharp** [comment]
oh! probably shouldve metionioned i'm using the build from the arch linux official repo. 
but yea the latest git version works fine~
