### ISSUE TITLE
Ranger crashing after updating from xubuntu 15.10 to 16.04

### ISSUE THREAD

**Issue by jagnyx** [ranger/ranger#622]
Hello, ranger is crashing on start, after updating, I am unable to find solution so far. I have attached Traceback below this text.

	'ranger version: 1.7.1, executed with python 2.7.11+
	Locale: en_US.UTF-8
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
		fm.loop()
	  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 338, in loop
		ui.redraw()
	  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 265, in redraw
		self.draw()
	  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 291, in draw
		DisplayableContainer.draw(self)
	  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 246, in draw
		displayable.draw()
	  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
		self._print_result(self.result)
	  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/titlebar.py", line 151, in _print_result
		self.color(*part.lst)
	  File "/usr/lib/python2.7/dist-packages/ranger/gui/curses_shortcuts.py", line 57, in color
		attr = self.settings.colorscheme.get_attr(*keys)
	  File "/usr/lib/python2.7/dist-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
		value = fnc(*args)
	  File "/usr/lib/python2.7/dist-packages/ranger/gui/colorscheme.py", line 66, in get_attr
		return attr | color_pair(get_color(fg, bg))
	  File "/usr/lib/python2.7/dist-packages/ranger/gui/color.py", line 38, in get_color
		curses.init_pair(size, fg, bg)
	error: init_pair() returned ERR'

Thank you.
Help would be appreciated.

**Comment by hut** [comment]
You seem to be using some terminal with color problems. Upgrading to ranger 1.7.2 or changing the terminal should fix this.

**Comment by jagnyx** [comment]
@hut Thank you for spontaneous response, it appears the problem is resloved after upgrading the to 1.7.2 and I have also tweaked the my own colorscheme, in which some colours were oddly engraved.
