### ISSUE TITLE
Can't open ranger.

### ISSUE THREAD

**Issue by uroybd** [ranger/ranger#637]
Ranger exits with this traceback:

`ranger version: 1.7.2, executed with python 3.5.2
Locale: None.None
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 126, in main
    fm.initialize()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 116, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.5/site-packages/ranger/container/bookmarks.py", line 41, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.5/site-packages/ranger/container/bookmarks.py", line 188, in _load_dict
    for line in f:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 48: ordinal not in range(128)`

**Comment by arjamizo** [comment]
did you get this fixed?

**Comment by uroybd** [comment]
Yes i did, close this issue please. I use Arch Linux and like to try to
tinker here and there. So, in the process of configuring i3wm somehow my
locale settings got mis-configured. Nevermind.
