### ISSUE TITLE
Ranger crashed starting on a Google Drive directory

### ISSUE THREAD

**Issue by cunha** [ranger/ranger#646]
The traceback below happened while starting ranger in a directory that is sync'd with Google Drive (lots of files with large, weird names).

```
[1!cunhapc:~/Gdrive]% ranger
ranger version: 1.7.1, executed with python 2.7.12
Locale: en_US.UTF-8
Current file: /home/cunha/Gdrive/2016itv-ufmg-funtec
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
    self._print_result(self.result)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/titlebar.py", line 151, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/curses_shortcuts.py", line 57, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
    value = fnc(*args)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/colorscheme.py", line 66, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/lib/python2.7/dist-packages/ranger/gui/color.py", line 38, in get_color
    curses.init_pair(size, fg, bg)
error: init_pair() returned ERR
```

**Comment by nfnty** [comment]
Fixed by efd3ef7c69f5fa8cb09eace71b3d3ce1d5806680.

**Comment by butla** [comment]
This isn't strictly about the issue, but@cunha - how did you get the files synced from Google Drive? I'm looking for a way to do that from CLI/ranger.

**Comment by cpchan** [comment]
Don't know about the OP, but under Linux, I use google-drive-ocamlfuse[1] which is a fuse filesystem. Your distro might have a package already, if you use Linux.

[1] https://github.com/astrada/google-drive-ocamlfuse

**Comment by cunha** [comment]
> This isn't strictly about the issue, but@cunha - how did you get the files synced from Google Drive? I'm looking for a way to do that from CLI/ranger.

Hi, I use [Insync](https://www.insynchq.com/).
