### ISSUE TITLE
find when system is slow crashed ranger

### ISSUE THREAD

**Issue by elvis-sik** [ranger/ranger#677]
The laptop, already a bit old, had just booted, and automatically fired ranger. I started moving around the directories with `hjkl`. To load each one, it took more than 1 second. It was slow. Then I typed `f popol vuh`, that is, "find the dir popol vuh". It crashed with the following traceback:

```
~ ❯❯❯ ranger
ranger version: 1.7.2, executed with python 3.5.2
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 344, in loop
    ui.handle_input()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 145, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.5/site-packages/ranger/gui/displayable.py", line 261, in press
    focused_obj.press(key)
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 173, in press
    self.type_key(key)
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 202, in type_key
    self.on_line_change()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 425, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.5/site-packages/ranger/api/commands.py", line 397, in quick
    return self._make_cmd().quick()
  File "/usr/lib/python3.5/site-packages/ranger/config/commands.py", line 1179, in quick
    if self._count(move=asyoutype) == 1 and self.AUTO_OPEN in self.flags:
  File "/usr/lib/python3.5/site-packages/ranger/config/commands.py", line 1244, in _count
    deq = deque(cwd.files)
TypeError: 'NoneType' object is not iterable
ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

I use ranger-stable on arch.

**Comment by nfnty** [comment]
Should be fixed by `7f40b26887e299517781602a01e245895dbffd17`.
