### ISSUE TITLE
utf-8 codec error

### ISSUE THREAD

**Issue by valoq** [ranger/ranger#710]
When selecting some pdf files, preview fails and the following error appears:

"utf-8 codec can't decide byte 0xc3 in position 511: unexpected end of data"

result when run with --debug:

```
ranger version: 1.7.2, executed with python 3.5.2
Locale: en_US.UTF-8
Current file: /home/valoq/report.pdf
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 252, in safeDecode
    return string.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 511: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 331, in loop
    loader.work()
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 392, in work
    self.fm.notify(err)
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 386, in work
    next(item.load_generator)
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 196, in generate
    read = safeDecode(read)
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 255, in safeDecode
    return string.decode(chardet.detect(string)["encoding"])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 511: unexpected end of data

```
The error occurs in this [line](https://github.com/ranger/ranger/blob/master/ranger/core/loader.py#L268)

According to the python documentation, this section handles the exception correctly.
But it seems like `return string.decode(chardet.detect(string)["encoding"])`
is ignoring the 'ignore' argument in `return string.decode(codec, 'ignore')`

Or am I mistaken?

I suspect this issue is connected to this https://github.com/ranger/ranger/issues/522

**Comment by valoq** [comment]
[samplefile.pdf](https://github.com/ranger/ranger/files/573449/samplefile.pdf)

**Comment by valoq** [comment]
This is already fixed in the git version, sorry for the false alarm.
