### ISSUE TITLE
Crush: List index out of range

### ISSUE THREAD

**Issue by JAkutenshi** [ranger/ranger#722]
Hi!
Right now ranger crushed. Output:
```
Locale: en_US.UTF-8
Current file: /home/jakutenshi/pictures/2015-11-24 13.10.40.png
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 344, in loop
    ui.handle_input()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 145, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.5/site-packages/ranger/gui/displayable.py", line 261, in press
    focused_obj.press(key)
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 173, in press
    self.type_key(key)
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 202, in type_key
    self.on_line_change()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 425, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.5/site-packages/ranger/api/commands.py", line 397, in quick
    return self._make_cmd().quick()
  File "/usr/lib/python3.5/site-packages/ranger/api/commands.py", line 406, in _make_cmd
    cmd_class = self.fm.commands.get_command(self._line.split()[0])
IndexError: list index out of range
```
Thanks for RangerFM!

**Comment by Vifon** [comment]
What have you been doing when it happened?

**Comment by JAkutenshi** [comment]
@Vifon Just listed my pictures directory. I'm use w3mimgdisplay for pictures previews, if it's important.

**Comment by Vifon** [comment]
Can you reproduce it? If so, does it still happen when you run ranger with the `-c` flag (which loads the default config)?

**Comment by JAkutenshi** [comment]
I tried, but I can't reproduce the crash, sorry.

**Comment by nfnty** [comment]
Reopen this issue if you can reproduce it on `master`.
