### ISSUE TITLE
unexpected crash on running

### ISSUE THREAD

**Issue by bnvk** [ranger/ranger#728]
Crashed on running. The starting directory is all folders except for one `.md` file.

```
user@host:~/Docs$ ranger
ranger version: 1.7.1, executed with python 2.7.12+
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 316, in loop
    self.enter_dir(self.thistab.path)
  File "/usr/lib/python2.7/dist-packages/ranger/core/actions.py", line 465, in enter_dir
    result = self.thistab.enter_dir(path, history=history)
  File "/usr/lib/python2.7/dist-packages/ranger/core/tab.py", line 141, in enter_dir
    self.assign_cursor_positions_for_subdirs()
  File "/usr/lib/python2.7/dist-packages/ranger/core/tab.py", line 90, in assign_cursor_positions_for_subdirs
    path.move_to_obj(last_path)
  File "/usr/lib/python2.7/dist-packages/ranger/container/directory.py", line 516, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python2.7/dist-packages/ranger/container/directory.py", line 569, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python2.7/dist-packages/ranger/container/directory.py", line 401, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python2.7/dist-packages/ranger/container/directory.py", line 331, in load_bit_by_bit
    item.load_vcs(self)
  File "/usr/lib/python2.7/dist-packages/ranger/container/fsobject.py", line 292, in load_vcs
    self.vcs.get_status()
  File "/usr/lib/python2.7/dist-packages/ranger/ext/vcs/vcs.py", line 254, in get_status
    self.status = self.get_status_allfiles()
  File "/usr/lib/python2.7/dist-packages/ranger/ext/vcs/git.py", line 172, in get_status_allfiles
    raw = self._git(self.path, ['status', '--porcelain'], catchout=True, bytes=True)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/vcs/git.py", line 23, in _git
    return self._vcs(path, 'git', args, silent=silent, catchout=catchout, bytes=bytes)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/vcs/vcs.py", line 74, in _vcs
    raw = subprocess.check_output([cmd] + args, stderr=out, cwd=path)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ael-code** [comment]
This part of the code was changed in ranger `v1.7.2`. In any case can you provide the outcome of the command `which git`? I think that you simply doesn't have git installed

**Comment by v1kn** [comment]
@ael-code - terribly sorry for the off-topic, didn't want to open an issue just for that:  

how soon do You expect will the next release happen? 1.7.2 has been around for a while now.

**Comment by bnvk** [comment]
@ael-code yep, that fixed it- new system somehow I had not installed git yet... perhaps it should be auto installed via package manager?

**Comment by ael-code** [comment]
I would say that since vcs decoration is not a ranger main feature, in the case the vcs program (git in this case) is not found, a warning should be printed and ranger shouldn't crash.

**Comment by nfnty** [comment]
This does not happen on `master`. Should have even better logging when #740 gets merged. Hopefully a new release can be packaged soon.

**Comment by nfnty** [comment]
Reopen if you still have this problem with the latest release.
