### ISSUE TITLE
ranger don't start in a virtualenv

### ISSUE THREAD

**Issue by davidtysman** [ranger/ranger#729]
On Debian, when I run ranger inside a virtualenv 

```
ranger version: 1.7.1, executed with python 2.7.12+
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 121, in main
    fm.initialize()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 84, in initialize
    enumerate(self.start_paths))
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 83, in <genexpr>
    self.tabs = dict((n+1, Tab(path)) for n, path in
  File "/usr/lib/python2.7/dist-packages/ranger/core/tab.py", line 19, in __init__
    self.path = abspath(expanduser(path))
  File "/usr/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
```

It works ouside the virtualenv

Thanks

**Comment by ael-code** [comment]
I cannot reproduce it

**Comment by nfnty** [comment]
Unable to reproduce. You'll need to add steps to reproduce this issue. See the updated CONTRIBUTING and HACKING documents for more info. Thanks!

Related to #754.

**Comment by nfnty** [comment]
Continue discussion in #558.
