### ISSUE TITLE
file not found some issue opening "sudo ranger ".

### ISSUE THREAD

**Issue by narutowindy** [ranger/ranger#754]
ranger version: 1.8.0, executed with python 3.5.2
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 138, in main
    fm.initialize()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 84, in initialize
    enumerate(self.start_paths))
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 83, in <genexpr>
    self.tabs = dict((n + 1, Tab(path)) for n, path in
  File "/usr/lib/python3.5/site-packages/ranger/core/tab.py", line 21, in __init__
    self.path = abspath(expanduser(path))
  File "/usr/lib/python3.5/posixpath.py", line 361, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
<E> fish: getcwd() failed with errno 2/No such file or directory

**Comment by nfnty** [comment]
Unable to reproduce. You'll need to add steps to reproduce this issue. See the updated `CONTRIBUTING` and `HACKING` documents for more info. Thanks!

**Comment by nfnty** [comment]
Related to #729.

**Comment by nfnty** [comment]
Continue discussion in #558.
