### ISSUE TITLE
Crash when pressing s

### ISSUE THREAD

**Issue by throwaway217** [ranger/ranger#758]
ranger version: 1.8.1, executed with python 3.6.0
Locale: en_US.UTF-8
Current file: /home/pun/dl
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 368, in loop
    ui.handle_input()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 230, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 166, in handle_key
    self.press(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 181, in press
    quantifier=keybuffer.quantifier)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 214, in execute_console
    escape=cmd.escape_macros_for_shell)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 229, in substitute_macros
    macros = self._get_macros()
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 250, in _get_macros
    macros['confdir'] = self.fm.confpath()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 297, in confpath
    assert 0, "Should not access relpath_conf in clean mode!"
AssertionError: Should not access relpath_conf in clean mode!

**Comment by nfnty** [comment]
Can't reproduce this issue. Please, provide detailed instructions.

**Comment by throwaway217** [comment]
- install from archlinux repso
- ranger -c

**Comment by nfnty** [comment]
That's not very detailed, and can't be reproduced.

**Comment by throwaway217** [comment]
I literally just install the current ranger package from the archlinux repositories and run it from the st terminal emulator with the -c parameter.

**Comment by Eyenseo** [comment]
I too use the 1.8.1 package from archlinux and noticed the same behaviour.

But when I tried the master (10d7174613e9865b065c52e57af8b0799cd106b0) it works -> 1.8.1 from archlinux is __not__ the official 1.8.1. _But_ I had to use the clean switch (`-c`) - with the old configuration files the search (for example) doesn't work still.

**Comment by nfnty** [comment]
Was unable to reproduce due to `-O` flag. Thanks.
