### ISSUE TITLE
Crash related to AliasCommand

### ISSUE THREAD

**Issue by richboss** [ranger/ranger#764]
Ranger crashes promply after 
* opening console by typing ":"
* then typing Tab (the string "AliasCommand" is inserted automatically)
* then typing Space

Alternativly just press ":" and then SHIFT-a.
```
Locale: de_DE.UTF-8
Current file: /home/richard/.anki
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 368, in loop
    ui.handle_input()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 230, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 164, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 263, in press
    focused_obj.press(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/console.py", line 175, in press
    self.type_key(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/console.py", line 204, in type_key
    self.on_line_change()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/console.py", line 493, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.6/site-packages/ranger/api/commands.py", line 442, in quick
    return self._make_cmd().quick()
  File "/usr/lib/python3.6/site-packages/ranger/api/commands.py", line 454, in _make_cmd
    cmd_class = self.fm.commands.get_command(self._line.split()[0])
IndexError: list index out of range

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

```

It doesn't matter, if Ranger is run on Python2 or Python3. It doesn't matter if it is run with the "-c" option. The crash occurs with Ranger 1.8.1, but with 1.7.2 all the same.

What's the matter with AliasCommand anyway? It is undocumented and seems out of place. All other commands are lower case...

**Comment by Vifon** [comment]
Confirmed. It's even easier to trigger by just typing `:A`. ranger crashes immediately. :/

**Comment by nfnty** [comment]
I can't reproduce this on `master`. Test `master` and report back.

**Comment by richboss** [comment]
That's right. I tested it on master (14f6e996) and couldn't reproduce it
either. But the bug is easily reproducible on v1.8.1 and earlier.

I've traced the 'fix' in master back to commit b3d031a9, where the imports
in config/commands.py got changed. One import was edited from

from ranger.api.commands import *
to
from ranger.api.commands import Command

That made the difference.

2017-01-23 17:49 GMT+01:00 nfnty <notifications@github.com>:

**Comment by nfnty** [comment]
Great, thanks.

**Comment by c02y** [comment]
`:A` will crash ranger here.

    ranger version: 1.8.1, executed with python 3.5.2
    Locale: en_US.UTF-8
    Current file: /home/chz/Public/ranger/build
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 166, in main
        fm.loop()
      File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 373, in loop
        ui.handle_input()
      File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 245, in handle_input
        self.handle_key(key)
      File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 177, in handle_key
        elif not DisplayableContainer.press(self, key):
      File "/usr/lib/python3.5/site-packages/ranger/gui/displayable.py", line 272, in press
        focused_obj.press(key)
      File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 174, in press
        self.type_key(key)
      File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 203, in type_key
        self.on_line_change()
      File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/console.py", line 491, in on_line_change
        if cmd and cmd.quick():
      File "/usr/lib/python3.5/site-packages/ranger/api/commands.py", line 438, in quick
        return self._make_cmd().quick()
      File "/usr/lib/python3.5/site-packages/ranger/api/commands.py", line 452, in _make_cmd
        cmd_class = self.fm.commands.get_command(self._line.split()[0])
    IndexError: list index out of range

**Comment by nfnty** [comment]
@c02y Are you running on `master`?

**Comment by c02y** [comment]
Yes, the latest version from github master.

`ranger --clean` works fine, the `:A` won't crash ranger. But how can I solve the problem in my configurations files.

**Comment by nfnty** [comment]
@c02y Your `commands.py` is outdated. Look at how it's properly done in `ranger/config/commands_sample.py`, especially `from ranger.api.commands import Command`.

**Comment by c02y** [comment]
@nfnty Yes, it is, thanks.
