### ISSUE TITLE
`Home` or `End` keys make ranger crash

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#778]
When I type `Home` or `End` key in the ranger (even a new ranger session`), ranger will crash:

    ranger version: 1.8.1, executed with python 3.3.5
    Locale: en_US.UTF-8
    Current file: xxx
    Traceback (most recent call last):
      File "/usr/local/lib/python3.3/site-packages/ranger/core/main.py", line 166, in main
        fm.loop()
      File "/usr/local/lib/python3.3/site-packages/ranger/core/fm.py", line 371, in loop
        ui.draw_images()
      File "/usr/local/lib/python3.3/site-packages/ranger/gui/ui.py", line 371, in draw_images
        if self.browser.pager.visible:
    AttributeError: 'NoneType' object has no attribute 'visible'

**Comment by nfnty** [comment]
Repost this issue and completely fill in the issue template. Do NOT delete the issue template.
