### ISSUE TITLE
ranger crashes on missing ~/.config/ranger/history

### ISSUE THREAD

**Issue by jdietrch** [ranger/ranger#781]
Ranger crashes when `~/.config/ranger/history` is missing.

Below is a traceback from the latest `master`.
```
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ git log | head
commit f1c99cb6d6cc7b8f8eff4e9e6c799468c07d2f33
Author: nfnty <git@nfnty.se>
Date:   Thu Jan 26 06:19:40 2017 +0100

    core.fm: `loop()`: Remove useless `if` statement

commit c78ee48d36bac7fe76ae500ed3aa3f5e20a9f74b
Author: nfnty <git@nfnty.se>
Date:   Thu Jan 26 06:13:29 2017 +0100

jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ rm -r ~/.config/ranger
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ python ranger.py --debug
ranger version: 1.8.1, executed with python 2.7.9
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/core/main.py", line 147, in main
    fm.initialize()
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/core/fm.py", line 124, in initialize
    self.ui.initialize()
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/gui/ui.py", line 106, in initialize
    self.setup()
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/gui/ui.py", line 274, in setup
    self.console = Console(self.win)
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/gui/widgets/console.py", line 44, in __init__
    fobj = open(self.historypath, 'r')
IOError: [Errno 2] No such file or directory: '/home/jdietrch/.config/ranger/history'

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ 
```

**Comment by nfnty** [comment]
Thanks!
