### ISSUE TITLE
crashes when previewing some files

### ISSUE THREAD

**Issue by jmckernon** [ranger/ranger#784]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux
- Terminal emulator and version: xterm
- Python version: 3.6.0
- Ranger version/commit: 1.8.1.86.g9220c310-1

#### CURRENT BEHAVIOR
Ranger crashes and exits when files of certain types are highlighted and it tries to preview them. The crash only happens when preview_files is on. The file types affected include .rar, .jpeg, .epub. They all seem to suffer from the same UnicodeDecodeError (see traceback below). This started happening after running a system upgrade in arch linux. The crash doesn't happen when running the stable 1.8.1 Ranger release.

#### STEPS TO REPRODUCE
1. make sure preview_files is on
1. navigate to a directory containing an image file
2. move focus down until image file is highlighted

#### TRACEBACK
```
ranger version: 1.8.1, executed with python 3.6.0
Locale: en_GB.UTF-8
Current file: /home/james/James Passport.jpeg
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 166, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 365, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 307, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 334, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 167, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 182, in _draw_file
    if self.target is None or not self.target.has_preview():
  File "/usr/lib/python3.6/site-packages/ranger/container/file.py", line 89, in has_preview
    if self.is_binary():
  File "/usr/lib/python3.6/site-packages/ranger/container/file.py", line 64, in is_binary
    if self.firstbytes and control_characters & set(self.firstbytes):
  File "/usr/lib/python3.6/site-packages/ranger/container/file.py", line 58, in firstbytes
    self._firstbytes = fobj.read(N_FIRST_BYTES)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by nfnty** [comment]
Thanks!
