### ISSUE TITLE
List Index Out of Range when opening image preview in Gnome Terminal

### ISSUE THREAD

**Issue by uberbrodt** [ranger/ranger#789]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: OpenSUSE Tumbleweed 
- Terminal emulator and version: Gnome-Terminal 3.22.1
- Python version: 2.7.13
- Ranger version/commit: 1.8.1 

#### EXPECTED BEHAVIOR
Navigate to an image file, should show inline image preview via w3m

#### CURRENT BEHAVIOR
No image shows up, got stack trace via -debug flag

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

#### CONTEXT
Can't view image previews. I verified that w3m image previews are working in Ranger with xTerm and Terminator. Pretty sure this is gnome-terminal issue, since w3mimagedisplay fails with no output with `-test` flag.

If nothing else, you should put a note in the Wiki that Gnome Terminal still isn't working.

#### POSSIBLE SOLUTIONS
I'll report to Gnome.

#### STEPS TO REPRODUCE

1. 
2. 
3. 
4. 
5. 

#### TRACEBACK

```
ranger version: 1.8.1, executed with python 2.7.13
Locale: en_US.UTF-8
Current file: /home/cbrodt/Pictures/1_001.png
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python2.7/site-packages/ranger/core/fm.py", line 366, in loop
    ui.draw_images()
  File "/usr/lib/python2.7/site-packages/ranger/gui/ui.py", line 355, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python2.7/site-packages/ranger/gui/widgets/pager.py", line 101, in draw_image
    self.fm.notify(e, bad=True)
  File "/usr/lib/python2.7/site-packages/ranger/gui/widgets/pager.py", line 97, in draw_image
    self.wid, self.hei)
  File "/usr/lib/python2.7/site-packages/ranger/ext/img_display.py", line 106, in draw
    start_y, width, height))
  File "/usr/lib/python2.7/site-packages/ranger/ext/img_display.py", line 140, in _generate_w3m_input
    fontw, fonth = self._get_font_dimensions()
  File "/usr/lib/python2.7/site-packages/ranger/ext/img_display.py", line 95, in _get_font_dimensions
    xpixels, ypixels = int(output[0]), int(output[1])
IndexError: list index out of range
```

**Comment by nfnty** [comment]
You should report this upstream.

**Comment by j-lakeman** [comment]
Same with Gnome Console and Black Box.
Any updates on this?

**Comment by uberbrodt** [comment]
I'm going to go ahead and close this since I'm not actively using either ranger or gnome-terminal any longer. I do think this comes down to a configuration issue.
