### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'load_if_outdated'

### ISSUE THREAD

**Issue by sirsurthur** [ranger/ranger#793]
ranger version: 1.8.1
Python version: 3.6.0
Locale: fr_FR.UTF-8
Current file: '/home/julien/Justin Hurwitz featuring Emma Stone/La La Land Original Motion Picture Soundtrack'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 158, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 365, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 337, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 364, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 158, in draw
    self.target.pointed_obj.load_if_outdated() or \
AttributeError: 'NoneType' object has no attribute 'load_if_outdated'

ranger crashed. Please report this traceback at:
https://github.com/hut/ranger/issues

**Comment by sirsurthur** [comment]
This happened with the git version of ranger, when I was trying to delete a folder with an  empty folder in it.

**Comment by nfnty** [comment]
Thanks!
