### ISSUE TITLE
Linemode fileinfo crash

### ISSUE THREAD

**Issue by aureooms** [ranger/ranger#800]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux
- Terminal emulator and version: Terminator
- Python version: 3.6
- Ranger version/commit: 1.8.1

#### EXPECTED BEHAVIOR
Key sequence Mi should change linemode to show info.

#### CURRENT BEHAVIOR
Key sequence Mi crashes.

#### STEPS TO REPRODUCE
1. Open ranger
2. Navigate to folder containing file
3. Press M then i

#### TRACEBACK

```console
ranger version: 1.8.1, executed with python 3.6.0
Locale: en_US.UTF-8
Current file: /home/aureooms/.cache/memoize/R
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 362, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 295, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 322, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 99, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 168, in draw
    self._draw_directory()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 348, in _draw_directory
    infostringdata = current_linemode.infostring(drawn, metadata)
  File "/usr/lib/python3.6/site-packages/ranger/core/linemode.py", line 107, in infostring
    fileinfo = fileinfo.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by nfnty** [comment]
Already been fixed by d07c60e464a5e70ae8a762f828221b235ce11818.
