### ISSUE TITLE
Ranger crashes with traceback on iTerm2 image preview with Python 3.6

### ISSUE THREAD

**Issue by jared-hess** [ranger/ranger#807]
#### ISSUE DESCRIPTION
When running ranger with Python version 3.6 on most recent Master and debug enabled, and the iTerm2 preview method configured, attempting to preview a PNG image causes ranger to crash with a traceback. Without debug enabled it will not crash, but will display "TypeError: write() argument must be str, not bytes" at the bottom of the screen. Forcing ranger to run on Python 2.7.13 does not result in a crash and the image is displayed correctly.

#### ISSUE TYPE
- Bug report (crash)

#### RUNTIME ENVIRONMENT

- Operating system: Arch
- Terminal emulator and version: iTerm2 (over SSH)
- Python version: 3.6.0
- Ranger version/commit: ranger-master 1.9.0b4

#### POSSIBLE SOLUTIONS

Looks like tparm is returning bytes, I assume correcting the encoding should fix this.

#### STEPS TO REPRODUCE

1. Run python 3.6
2. Configure iTerm2 Image Preview method
3. Attempt to preview an image
4. Ranger will crash

#### TRACEBACK

```
ranger version: ranger-master 1.9.0b4
Python version: 3.6.0 (default, Jan 16 2017, 12:12:55) [GCC 6.3.1 20170109]
Locale: en_US.UTF-8
Current file: '/home/jared/box_plot.png'

Traceback (most recent call last):
  File "/home/jared/build/ranger/ranger/core/main.py", line 168, in main
    fm.loop()
  File "/home/jared/build/ranger/ranger/core/fm.py", line 377, in loop
    ui.draw_images()
  File "/home/jared/build/ranger/ranger/gui/ui.py", line 401, in draw_images
    self.browser.columns[-1].draw_image()
  File "/home/jared/build/ranger/ranger/gui/widgets/pager.py", line 115, in draw_image
    self.fm.notify(ex, bad=True)
  File "/home/jared/build/ranger/ranger/core/actions.py", line 161, in notify
    raise obj
  File "/home/jared/build/ranger/ranger/gui/widgets/pager.py", line 111, in draw_image
    self.wid, self.hei)
  File "/home/jared/build/ranger/ranger/ext/img_display.py", line 213, in draw
    sys.stdout.write(curses.tparm(curses.tigetstr("cup"), start_y, start_x))
TypeError: write() argument must be str, not bytes

```

**Comment by nfnty** [comment]
Thanks!
