### ISSUE TITLE
Corrupt history file crashes ranger: UnicodeDecodeError

### ISSUE THREAD

**Issue by Xenopathic** [ranger/ranger#817]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: urxvt v9.22
- Python version: 3.6.0
- Ranger version/commit: ranger-stable 1.8.1 
- Locale: en_GB.utf-8

#### EXPECTED BEHAVIOR
A corrupt history file should print a warning, then ranger should continue to open and work as usual (albeit without history). Failing that, ranger should quit with a sensible error that describes the problem.

#### CURRENT BEHAVIOR
A corrupted history file, in my case caused by unexpected power loss, crashes ranger with an obscure error:

```
ranger version: 1.8.1, executed with python 3.6.0
Locale: en_GB.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 126, in main
    fm.initialize()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 126, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 93, in initialize
    self.setup()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 262, in setup
    self.console = Console(self.win)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/console.py", line 45, in __init__
    for line in f:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 0: invalid continuation byte
```

#### STEPS TO REPRODUCE
1) Put random garbage into the history file, or alternatively use the history file I've attached (zipped to allow upload to GitHub)
2) Attempt to open ranger.

[history.zip](https://github.com/ranger/ranger/files/801063/history.zip)

**Comment by nfnty** [comment]
Thanks!
