### ISSUE TITLE
memory issues with previewing many larges pictures

### ISSUE THREAD

**Issue by bnvk** [ranger/ranger#820]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Debian Jessie
- GNOME Terminal 3.22.1 Using VTE version 0.46.1 +GNUTLS
- Python version: 2.7.13
- Ranger version/commit: 1.7.1
- Locale: en

#### EXPECTED BEHAVIOR

Scanning through long list of high resolution photos should release memory accordingly.

#### CURRENT BEHAVIOR

Memory usage increases until ranger locks ups and often causes other system lags and crashing

#### CONTEXT

Previewing pictures in multiple directories

#### POSSIBLE SOLUTIONS

Assuming overall system is not locked up, manually killing the ranger process (that was scrubbing through pictures) allows memory to be freed up.

#### STEPS TO REPRODUCE

1. Browse through folders of hundreds of decently sized >= 3MB pictures
2. Browse from image to image quickly
3. Watch your memory usage steadily increase

#### TRACEBACK

```
user@hostname:~$ ranger
ranger version: 1.7.1, executed with python 2.7.13
Locale: en_US.UTF-8
Current file: /home/user/Pictures/IMG_0167.JPG
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/browserview.py", line 98, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/browsercolumn.py", line 164, in draw
    self._draw_file()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/browsercolumn.py", line 185, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/pager.py", line 76, in draw
    self.clear_image()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/pager.py", line 42, in clear_image
    self.fm.image_displayer.clear(self.x, self.y, self.wid, self.hei)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/img_display.py", line 75, in clear
    fontw, fonth = _get_font_dimensions()
  File "/usr/lib/python2.7/dist-packages/ranger/ext/img_display.py", line 251, in _get_font_dimensions
    stdout=PIPE, universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by nfnty** [comment]
Can you reproduce this problem on `master` and/or using Python 3?

**Comment by kajzersoze** [comment]
In my case it's w3mimgdisplay that is growing big, ranger is ok.
