### ISSUE TITLE
Crashes when previews csv files

### ISSUE THREAD

**Issue by adam8157** [ranger/ranger#833]
```
adam@mbp:~$ ranger
ranger version: ranger-master 1.9.0b5
Python version: 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
Locale: None.None
Current file: '/home/adam/dropbox/backup/google.csv'

Traceback (most recent call last):
  File "/home/adam/binary/bundle/ranger/ranger/core/main.py", line 169, in main
    fm.loop()
  File "/home/adam/binary/bundle/ranger/ranger/core/fm.py", line 373, in loop
    ui.redraw()
  File "/home/adam/binary/bundle/ranger/ranger/gui/ui.py", line 337, in redraw
    self.draw()
  File "/home/adam/binary/bundle/ranger/ranger/gui/ui.py", line 364, in draw
    DisplayableContainer.draw(self)
  File "/home/adam/binary/bundle/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/home/adam/binary/bundle/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/browsercolumn.py", line 172, in draw
    self._draw_file()
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/browsercolumn.py", line 199, in _draw_file
    Pager.draw(self)
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/home/adam/binary/bundle/ranger/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
TypeError: str

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

That file is a simple csv exported from Google Contacts

**Comment by nfnty** [comment]
Try running with `ranger --clean` and also with Python 3.

**Comment by adam8157** [comment]
```
adam@mbp:~$ ranger --clean
ranger version: ranger-master 1.9.0b5
Python version: 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
Locale: None.None
Current file: '/home/adam/dropbox/backup/google.csv'

Traceback (most recent call last):
  File "/home/adam/binary/bundle/ranger/ranger/core/main.py", line 169, in main
    fm.loop()
  File "/home/adam/binary/bundle/ranger/ranger/core/fm.py", line 373, in loop
    ui.redraw()
  File "/home/adam/binary/bundle/ranger/ranger/gui/ui.py", line 337, in redraw
    self.draw()
  File "/home/adam/binary/bundle/ranger/ranger/gui/ui.py", line 364, in draw
    DisplayableContainer.draw(self)
  File "/home/adam/binary/bundle/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/home/adam/binary/bundle/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/browsercolumn.py", line 172, in draw
    self._draw_file()
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/browsercolumn.py", line 199, in _draw_file
    Pager.draw(self)
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/home/adam/binary/bundle/ranger/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/home/adam/binary/bundle/ranger/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
TypeError: str

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

` python3 ranger --clean` doesn't crash, but preview displays weird characters

**Comment by nfnty** [comment]
Could you upload that file (need to upload the whole thing as is; could be encoding related)? Or try to bisect that file until you find what's causing it?

**Comment by adam8157** [comment]
```
1687e0f41f172cef6923f75f4c6f1038f19671dc is the first bad commit
commit 1687e0f41f172cef6923f75f4c6f1038f19671dc
Author: nfnty <git@nfnty.se>
Date:   Fri Jan 20 16:09:19 2017 +0100

    linting: pylint: Enable `broad-except`, Improve logging

    Handle exceptions explicitly to prevent unexpected errors from causing
    problems.

    Improve exception and notification logging.

:040000 040000 c92f10af96225573aca9f1bd6d5450af11002ed8 cefa4ce3bc2403ad84185aeadb0b99c0d70ab744 M      doc
:040000 040000 18d290529b2d4c950fd66b812c1eec22e86e31b4 2884ba802ce05db7e30b5aedea4c1e5ad0f201a8 M      examples
:100644 100644 d2729ce49effb6c1ad03200795f812ef0d57edd6 d108c93fb205622eaeb6fe2039c546e9b95bc419 M      pylintrc
:040000 040000 4937927770f7852e6556d57d86a640b1e19ef4b6 f1afb3cc8a2aee6ff3cb9f0431d6824b37c30cda M      ranger
```

[google.csv.zip](https://github.com/ranger/ranger/files/850578/google.csv.zip)

**Comment by j-degreef** [comment]
@adam8157 @nfnty 
I've just downloaded a cvs of my google contacts and I have the exact same problem.

ranger version: ranger-master 1.9.0b5
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Locale: None.None

**Comment by nfnty** [comment]
This issue is caused by the file being encoded with little-endian UTF-16.

**Comment by nfnty** [comment]
Thanks!

**Comment by j-degreef** [comment]
You're welcome ;)

**Comment by jcguu95** [comment]
I'm experiencing the same issue too. It even crashes my terminal so I didn't have a chance to view the error log.

**Comment by toonn** [comment]
@jcguu95, what version of ranger are you running and is it specifically csv files that cause crashes?

**Comment by jcguu95** [comment]
@toonn Thanks for getting it back to me. I later realized that it isn't ranger's problem. My terminal isn't compatible with emojis..
