### ISSUE TITLE
Support for file:// URI

### ISSUE THREAD

**Issue by has2k1** [ranger/ranger#836]
Provide support for opening `file://` directory paths

#### ISSUE TYPE
- Improvement/feature request

#### EXPECTED BEHAVIOR

These two commands should be equivalent

```
$ ranger file:///home/user
$ ranger /home/user
``` 

#### CURRENT BEHAVIOR

*Version 1.8.1*
```pytb

$ ranger file:///home/usr

ranger version: 1.8.1, executed with python 3.5.3
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib64/python3.5/site-packages/ranger/core/fm.py", line 362, in loop
    ui.redraw()
  File "/usr/lib64/python3.5/site-packages/ranger/gui/ui.py", line 295, in redraw
    self.draw()
  File "/usr/lib64/python3.5/site-packages/ranger/gui/ui.py", line 322, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib64/python3.5/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib64/python3.5/site-packages/ranger/gui/widgets/titlebar.py", line 40, in draw
    self._calc_bar()
  File "/usr/lib64/python3.5/site-packages/ranger/gui/widgets/titlebar.py", line 85, in _calc_bar
    self._get_left_part(bar)
  File "/usr/lib64/python3.5/site-packages/ranger/gui/widgets/titlebar.py", line 107, in _get_left_part
    self.fm.thisdir.path.startswith(self.fm.home_path):
AttributeError: 'NoneType' object has no attribute 'path'
```

*Current Master*

```
$ ranger.py file:///home/user
Inaccessible paths: ['file:///home/user']
```

#### CONTEXT
I am trying to integrate ranger with other programs on the system and some of them open the
file manager with a URI path.

#### POSSIBLE SOLUTIONS
When opened with a file path, ranger should check if the path is in URI form, if so strip out the scheme (file://) info and treat the remaining characters as the path.

**Comment by nfnty** [comment]
Thanks!
