### ISSUE TITLE
Ranger-1.7.2: AttributeError: 'Tags' object has no attribute 'tags'

### ISSUE THREAD

**Issue by kaenan** [ranger/ranger#851]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Fedora 25 (kernel 4.10.8-200.fc25.x86_64)
- Terminal emulator and version: st v0.7
- Python version: python 3.5.3
- Ranger version: 1.7.2
- Locale: en-US.UTF-8

#### EXPECTED BEHAVIOR
The program should run.

#### CURRENT BEHAVIOR
It crashes.

#### CONTEXT
...

#### STEPS TO REPRODUCE
1. Install ranger from fedora repo
2. Run `ranger` in the terminal

#### TRACEBACK
```
ranger version: 1.7.2, executed with python 3.5.3
Locale: en_US.UTF-8
Current file: /home/kaen/bin
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.5/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/browserview.py", line 98, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.5/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/browsercolumn.py", line 166, in draw
    self._draw_directory()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/browsercolumn.py", line 247, in _draw_directory
    tagged = self.fm.tags and drawn.realpath in self.fm.tags
  File "/usr/lib/python3.5/site-packages/ranger/container/tags.py", line 24, in __contains__
    return item in self.tags
AttributeError: 'Tags' object has no attribute 'tags'
```

**Comment by nfnty** [comment]
You need to upgrade ranger.
