### ISSUE TITLE
"Mi" command crashes ranger when in alternate viewmode

### ISSUE THREAD

**Issue by AvianY** [ranger/ranger#887]
#### ISSUE TYPE
- Bug report

#### STEPS TO REPRODUCE

1. open ranger with " ranger --choosedir=$HOME/rangerdir; LASTDIR=`cat $HOME/rangerdir`; cd "$LASTDIR" "
2. go to alternate viewmode with "~"
3. type "Mi"
4. crashes...
5. 

#### TRACEBACK
```
ranger version: 1.8.1, executed with python 3.6.1
Locale: en_US.UTF-8
Current file: /home/aviany/cloud/Programs/ranger/bookmarks
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 362, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 295, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 322, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 99, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 168, in draw
    self._draw_directory()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 348, in _draw_directory
    infostringdata = current_linemode.infostring(drawn, metadata)
  File "/usr/lib/python3.6/site-packages/ranger/core/linemode.py", line 107, in infostring
    fileinfo = fileinfo.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by randynobx** [comment]
This is an issue with the linemode implementation and occurs even in the default viewmode. I know that this is a known issue to @Vifon and myself at the very least.

Fix will likely require a rewrite of the linemode implementation; which we have been discussing.

**Comment by Vifon** [comment]
Please check on the latest version from Git.

**Comment by DmitryMyadzelets** [comment]
The `ranger version: ranger 1.9.2` still has this problem.

**Comment by toonn** [comment]
1.9.2 isn't the latest release and the master branch has moved past 1.9.3, the current `linemode.py` doesn't even contain calls to `decode` and I can't reproduce the issue.
