### ISSUE TITLE
`ranger --clean` tries to access relpath_conf in clean mode (crashes on r, cd, @, etc.)

### ISSUE THREAD

**Issue by R3load** [ranger/ranger#890]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: `Arch Linux 4.11.5-1-ARCH`
- Terminal emulator and version: `terminator 1.91`
- Python version: `3.6.1`
- Ranger version/commit: `1.8.1`
- Locale:
```
LANG=en_GB.UTF-8
LC_CTYPE=en_GB.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE=C
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES=en_GB.UTF-8
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```

#### EXPECTED BEHAVIOR

Typing `cd`, `r`, `@`, etc. should open the console with some pretyped text

#### CURRENT BEHAVIOR

Crashes with AssertionError.

#### STEPS TO REPRODUCE

1. Run `ranger --clean`
2. Type any of the following: `r`, `cd`, `s`, `!`, `@`, or `#` (and probably some others too)

#### TRACEBACK

```
ranger version: 1.8.1, executed with python 3.6.1
Locale: en_GB.UTF-8
Current file: /home/hdqn/.config/ranger/bookmarks
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 368, in loop
    ui.handle_input()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 230, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 166, in handle_key
    self.press(key)
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 181, in press
    quantifier=keybuffer.quantifier)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 214, in execute_console
    escape=cmd.escape_macros_for_shell)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 229, in substitute_macros
    macros = self._get_macros()
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 250, in _get_macros
    macros['confdir'] = self.fm.confpath()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 297, in confpath
    assert 0, "Should not access relpath_conf in clean mode!"
AssertionError: Should not access relpath_conf in clean mode!

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by Vifon** [comment]
Should be already fixed in the devel version, it's related to #848. I can reproduce it on `v1.8.1` but not on `master`.

I'm closing the issue. Please reopen if it's still a problem.
