### ISSUE TITLE
Error when starting in non-existing directory

### ISSUE THREAD

**Issue by heynemax** [ranger/ranger#892]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Ubuntu 17.04
- Terminal emulator and version: Bash 4.4.7
- Python version: 2.7.13
- Ranger version/commit: 1.8.1
- Locale: en_US.UTF-8

#### EXPECTED BEHAVIOR

Ranger should start normally and may choose another directory to show if the current doesn't exists

#### CURRENT BEHAVIOR

Ranger crashes with an `OSError` (see Traceback)

#### CONTEXT

I tried to start ranger in a terminal that was still open, but the current working directory was removed in the meantime.

#### POSSIBLE SOLUTIONS

Catch that exception and choose another folder to show.

#### STEPS TO REPRODUCE

```
mkdir tmp
cd tmp
rm -r ../tmp
ranger
```

#### TRACEBACK

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 126, in main
    fm.initialize()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 86, in initialize
    enumerate(self.start_paths))
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 85, in <genexpr>
    self.tabs = dict((n + 1, Tab(path)) for n, path in
  File "/usr/lib/python2.7/dist-packages/ranger/core/tab.py", line 21, in __init__
    self.path = abspath(expanduser(path))
  File "/usr/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or 
```

**Comment by freed00m** [comment]
It happens when you have tabs where the directory was deleted as well. Even with python 3

```
ranger version: ranger-master 1.9.1
Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/home/frdm/src/ranger/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/home/frdm/src/ranger/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/home/frdm/src/ranger/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/home/frdm/src/ranger/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/home/frdm/src/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/frdm/src/ranger/ranger/gui/widgets/titlebar.py", line 42, in draw
    self._calc_bar()
  File "/home/frdm/src/ranger/ranger/gui/widgets/titlebar.py", line 82, in _calc_bar
    self._get_left_part(bar)
  File "/home/frdm/src/ranger/ranger/gui/widgets/titlebar.py", line 106, in _get_left_part
    and (self.fm.thisdir.path.startswith(self.fm.home_path + "/")
AttributeError: 'NoneType' object has no attribute 'path'
```

Currently pulled master `fa1d8811 2018-09-07 `

**Comment by toonn** [comment]
I agree the error should be caught and replaced with a nicer message. I'm not sure I agree ranger should just open another existing directory though, it could lead to confusion or unfortunate mishaps.

Let's say someone wants to delete the contents of a folder so they're poised to do `ranger ~/some/folder<CR>vdD<CR>yq`. They'd end up deleting a bunch of stuff they didn't intend on deleting. You could say this is far fetched but imagine cd dropped you in a completely different directory if you misspelled a name, it's confusing.

If we do implement opening a different existing path I'd suggest either `~ with / as fallback` or moving up the path and opening the deepest existing directory.

**Comment by freed00m** [comment]
@toonn What if there was message "path no longer exists" and the history was still kept, so the user would have keep going `..` while some path would exists.

I think that would be less confusing than my explanations.
