### ISSUE TITLE
Error: "nocbreak() returned ERR" after leaving shell

### ISSUE THREAD

**Issue by fdw** [ranger/ranger#898]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
Ubuntu 16.04
ranger-stable 1.7.1
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
zsh 5.1.1

#### EXPECTED BEHAVIOR
Using the keybinding `S` (or `:shell zsh'') in ranger, I can open a shell in the current directory. After I exit this session, I expect to be in ranger again and can work there.

#### CURRENT BEHAVIOR
Ranger crashes.

#### CONTEXT
I cannot use the shell command, because ranger crashes after I use it.

#### STEPS TO REPRODUCE

1. Open ranger - `ranger`
2. Execute shell - `:shell zsh`
3. Exit shell session - `exit`

#### TRACEBACK
```
Traceback (most recent call last):
  File "/usr/bin/ranger", line 39, in <module>
    sys.exit(ranger.main())
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 153, in main
    fm.ui.destroy()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 125, in destroy
    self.suspend()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 96, in suspend
    curses.nocbreak()
_curses.error: nocbreak() returned ERR
```

**Comment by hut** [comment]
Thank you for the bug report. What terminal do you use?

**Comment by fdw** [comment]
I use https://launchpad.net/terminator v0.98

**Comment by Vifon** [comment]
I cannot reproduce it with seemingly the same setup as yours. Could you post your ncurses version?

**Comment by fdw** [comment]
According to apt-get, I have ncurses 6.0+20160213.

After some trial & error, I found the following interesting detail:
When I start ranger from bash, and go into zsh (using `:shell zsh`), and exit the shell again, ranger is stopped too - I am dropped to the bash prompt. It seems to me that my zsh is doing something unexptected on `exit`.

**Comment by Vifon** [comment]
Do you have any fancy zsh config?

**Comment by fdw** [comment]
Yes, I do: https://github.com/fdw/dotfiles/blob/master/zshrc

I already suspected the config, but so far I haven't found anything - I removed all plugins, and the behavior stayed the same; the options also seem innocent (and haven't changed for quite a while).
It might be the plugin manager (https://github.com/zplug/zplug), but I haven't found a similar bug in their issue tracker or noticed any other strange behavior; only ranger breaks.

One other thing I just noticed while trying things out: If I start a zsh inside a zsh, and call `ranger` in there, it works as expected. Why, I don't know...

**Comment by Vifon** [comment]
Try running `:shell zsh -f`, which will run the vanilla zsh without your config.

**Comment by fdw** [comment]
Yeah, that works. So it seems to be a problem between my zsh config and ranger.

**Comment by fdw** [comment]
I replaced zgen with zplug, and ranger works again :)

Do you think I should file a bug with zgen, even though I can't really describe what it's doing wrong?

**Comment by cjbassi** [comment]
I'm having the same issue and I'm using zplug. Did you mean to say that you replaced zplug with zgen and ranger works again?
