### ISSUE TITLE
Ranger crashes with the provided traceback

### ISSUE THREAD

**Issue by graysoncroom** [ranger/ranger#905]
Reporting a traceback after ranger crashed.

#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch linux
- Terminal emulator and version: urxvt
- Python version: 3.6.1
- Ranger version/commit: 1.8.1
- Locale: en_us

#### EXPECTED BEHAVIOR

Ranger should have started when I ran the command: ranger

#### CURRENT BEHAVIOR

Ranger crashes with a traceback.

#### CONTEXT

I can not use ranger.

#### STEPS TO REPRODUCE

1.  Start ranger.
Sorry, I just want to submit this to help you guys improve ranger.
Not really sure what went wrong or why.
Let me know if you need any more information to debug this.

#### TRACEBACK

```
ranger version: 1.8.1, executed with python 3.6.1
Locale: None.None
Current file: /home/grayson/Backups
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 362, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 295, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 322, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 99, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 168, in draw
    self._draw_directory()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 268, in _draw_directory
    tagged = self.fm.tags and drawn.realpath in self.fm.tags
  File "/usr/lib/python3.6/site-packages/ranger/container/tags.py", line 26, in __contains__
    return item in self.tags
AttributeError: 'Tags' object has no attribute 'tags'

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issue
```

**Comment by Vifon** [comment]
Are your configs up to date? You probably need to update them.

**Comment by graysoncroom** [comment]
@Vifon rc.conf was missing, so it was user error. Sorry for the late response.
