### ISSUE TITLE
Renaming directories causes a crash

### ISSUE THREAD

**Issue by bnvk** [ranger/ranger#911]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Raspbian (Debian 9 / Stretch)
- Terminal emulator and version: GNOME Shell 
- Python version: 2.7.9
- Ranger version/commit: ranger-master 1.9.0b5
- Locale: None.None

#### EXPECTED BEHAVIOR

Renaming directories should not crash ranger

#### CURRENT BEHAVIOR

While browsing arround and performing `:rename` of a directory causes ranger to crash.

#### CONTEXT

Ranger crashed while performing file renaming of a directory

#### STEPS TO REPRODUCE

1. Start ranger on a directory `ranger path/to/dir`
2. Perform `:rename` on a directory
3. Observe crash

#### TRACEBACK

```
user@host:~/Music/Frank Waln $ ranger
ranger version: ranger-master 1.9.0b5
Python version: 2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]
Locale: None.None
Current file: '/home/pi/Cloud/Music/Frank Waln'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 168, in main
    fm.loop()
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/fm.py", line 373, in loop
    ui.redraw()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/ui.py", line 337, in redraw
    self.draw()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/ui.py", line 364, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/widgets/browsercolumn.py", line 172, in draw
    self._draw_file()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/widgets/browsercolumn.py", line 187, in _draw_file
    if self.target is None or not self.target.has_preview():
  File "/usr/local/lib/python2.7/dist-packages/ranger/container/file.py", line 91, in has_preview
    if self.is_binary():
  File "/usr/local/lib/python2.7/dist-packages/ranger/container/file.py", line 66, in is_binary
    if self.firstbytes and CONTROL_CHARACTERS & self.firstbytes:
  File "/usr/local/lib/python2.7/dist-packages/ranger/container/file.py", line 59, in firstbytes
    with open(self.path, 'rb') as fobj:
IOError: [Errno 21] Is a directory: '/home/pi/Cloud/Music/Frank Waln'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
user@host:~/Music/Frank Waln $ cd ../
```

**Comment by toonn** [comment]
Can't reproduce this anymore so I'm guessing it was fixed?
