### ISSUE TITLE
no image preview with os x sierra

### ISSUE THREAD

**Issue by stepstein** [ranger/ranger#913]
#### ISSUE TYPE

- Bug report
- Improvement/feature request

#### RUNTIME ENVIRONMENT

- Operating system and version: os x 10.12.3
- Terminal emulator and version: iterm 3.0.15
- Python version: 2.7.10
- Ranger version/commit: 1.8.1
- Locale: 

#### EXPECTED BEHAVIOR

ranger should display images thorugh imgcat.

set preview_images true
and 
set preview_images iterm2
in the rc.conf file

W3MIMGDISPLAY_PATH=/usr/local/bin/imgcat
in ~/.profile
#### CURRENT BEHAVIOR

ERROR: Unknown option flag: -test
				 Usage: imgcat [-p] filename ...

No image shows up.

#### STEPS TO REPRODUCE

1. 
2. 
3. 
4. 
5. 

#### TRACEBACK

ranger -d --confdir=~/.config/ranger
ranger version: 1.8.1, executed with python 2.7.10
Locale: de_CH.UTF-8
Current file: /Users/stephensteiner/Desktop/Bildschirmfoto 2017-07-09 um 12.19.01.png
Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/core/fm.py", line 366, in loop
    ui.draw_images()
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/ui.py", line 355, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/widgets/pager.py", line 101, in draw_image
    self.fm.notify(e, bad=True)
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/widgets/pager.py", line 97, in draw_image
    self.wid, self.hei)
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/ext/img_display.py", line 106, in draw
    start_y, width, height))
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/ext/img_display.py", line 140, in _generate_w3m_input
    fontw, fonth = self._get_font_dimensions()
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/ext/img_display.py", line 95, in _get_font_dimensions
    xpixels, ypixels = int(output[0]), int(output[1])
IndexError: list index out of range

```

```

**Comment by ryanrms** [comment]
This would also be useful for Qterminal as it sounds like they plan to support the imgcat / the OSC 1337 protocol for displaying images inline. https://github.com/lxqt/qtermwidget/issues/207

**Comment by toonn** [comment]
Why are you running 1.8.1? 1.9.1 is definitely in homebrew. Not sure why you're setting `W3MIMGDISPLAY_PATH`, afaik setting the iterm2 method should suffice.
Your setting lines aren't correct either it should be:
```
set preview_images True
set preview_images_method iterm2
```
Note the `_method` suffix.

**Comment by jsatk** [comment]
I'm having the same issue.
