### ISSUE TITLE
ranger <path> command crash

### ISSUE THREAD

**Issue by qoxxxx** [ranger/ranger#930]
Trying to run `ranger <file>` returns

```
ranger version: ranger-master 1.9.0b5
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Locale: None.None

Traceback (most recent call last):
  File "/home/user/ranger-master/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/home/user/ranger-master/ranger/core/fm.py", line 381, in loop
    ui.redraw()
  File "/home/user/ranger-master/ranger/gui/ui.py", line 339, in redraw
    self.finalize()
  File "/home/user/ranger-master/ranger/gui/ui.py", line 392, in finalize
    DisplayableContainer.finalize(self)
  File "/home/user/ranger-master/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/home/user/ranger-master/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'
```

Is it possible to open ranger with files, not directories, in argument ? To open tabs with thoses files selected. Not sure it's supposed to be supported for multiple files since there's the `--selectfile` flag.

I'm on Ubuntu 16.04.

**Comment by whilealive** [comment]
Similar error here (no argument is given)
 `ranger` returns

```
ranger version: 1.8.1, executed with python 3.6.2
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 126, in main
    fm.initialize()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 123, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.6/site-packages/ranger/container/bookmarks.py", line 41, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.6/site-packages/ranger/container/bookmarks.py", line 192, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.6/site-packages/ranger/container/directory.py", line 141, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!
```

I'm on Arch Linux.

**Comment by asmjmisc** [comment]
You are correct. Files are opened via `--selectfile`. I think the what can be done here is updating the usage/help message for the command to point out that [path] is actually [dir], and not just any arbitrary filesystem path. JM2C.

**Comment by magnetophon** [comment]
I'm getting a similar, but different error:
```
f.fm.thisdir.path
AttributeError: 'NoneType' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

Ranger 1.8 used to just say you're not supposed to open files with ranger, only paths.
I'd prefer ranger to just open the dir the file is in, without complaining.

**Comment by kbd** [comment]
Just started using ranger, quickly ran into this bug.

> I'd prefer ranger to just open the dir the file is in, without complaining.

Except it'd be better if the specified file was selected... which would make it the same as `--selectfile`. Why isn't that the default behavior if you specify a file argument to `ranger`?

**Comment by toonn** [comment]
Note that `--selectfile` used to be necessary because `rifle` wasn't its own command yet so calling `ranger /path/to/somefile` would do what `rifle /path/to/somefile` does now.

**Comment by toonn** [comment]
It would be awesome if some people could test #1132, you'll need to clone it from github and then you can run `ranger.py` as if it's `ranger`.
