### ISSUE TITLE
Ranger crashed with "AssertionError: No directory given!"

### ISSUE THREAD

**Issue by heartb1t** [ranger/ranger#936]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux
- Terminal emulator and version: Terminator 1.91
- Python version: Python 3.6.2
- Ranger version/commit: ranger-stable 1.8.1
- Locale: en.US.UTF-8

#### EXPECTED BEHAVIOR
Start ranger normally on my user (it works with sudo).

#### CURRENT BEHAVIOR
Ranger presents a error message with the latest calls.

#### CONTEXT
There's not really much to say here. I was using ranger normally and after I quit it to do something on my terminal I couldn't make it work anymore.

#### POSSIBLE SOLUTIONS
I don't really know what's going on, so I can't help much, sorry.

#### STEPS TO REPRODUCE
1. Type 'ranger' in terminal or through a i3 binding

#### TRACEBACK
This is ranger in debug mode:
```
ranger version: 1.8.1, executed with python 3.6.2
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 94, in main
    load_settings(fm, arg.clean)
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 287, in load_settings
    fm.source(custom_conf)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 353, in source
    self.execute_console(line)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 221, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib/python3.6/site-packages/ranger/config/commands.py", line 441, in execute
    (linemode, "/".join(FileSystemObject.linemode_dict)), bad=True)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 153, in notify
    raise Exception(str(text))
Exception: Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime
```

And this is trying to open ranger normally
```
Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime
ranger version: 1.8.1, executed with python 3.6.2
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 126, in main
    fm.initialize()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 123, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.6/site-packages/ranger/container/bookmarks.py", line 41, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.6/site-packages/ranger/container/bookmarks.py", line 192, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.6/site-packages/ranger/container/directory.py", line 141, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!
```

**Comment by heartb1t** [comment]
Maybe I'll take some time to answer to whatever people may ask me, but I'll do it as soon as I can.

**Comment by heartb1t** [comment]
Well, I managed to get it working after reinstalling it. It was probably due to some plugin error, since I haven't installed any yet and it keeps working. It can be closed now.
