### ISSUE TITLE
ranger crashes when trying to view keybindings

### ISSUE THREAD

**Issue by phlind** [ranger/ranger#937]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Mac OS X 10.11.6
- Terminal emulator and version: iTerm2 3.0.15
- Python version: ranger is executed with 2.7.10 (I also have a newer version installed)
- Ranger version/commit: 1.8.1
- Locale: DE

#### EXPECTED BEHAVIOR
`:help` and pressing `k` should show the keybindings

#### CURRENT BEHAVIOR
ranger crashes

#### STEPS TO REPRODUCE

1. In ranger type the command `:help` in the console
2. Press `k`.

#### TRACEBACK

```
ranger version: 1.8.1, executed with python 2.7.10
Locale: de_DE.UTF-8
Current file: /usr/local/opt/python3/bin/wheel3
Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/core/fm.py", line 368, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/ui.py", line 230, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/ui.py", line 164, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/displayable.py", line 263, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/widgets/console.py", line 175, in press
    self.type_key(key)
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/widgets/console.py", line 201, in type_key
    self._answer_question(answer)
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/gui/widgets/console.py", line 184, in _answer_question
    callback(answer)
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/config/commands.py", line 980, in callback
    self.fm.dump_keybindings()
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/core/actions.py", line 1183, in dump_keybindings
    recurse([], self.fm.ui.keymaps[context])
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/core/actions.py", line 1176, in recurse
    recurse(keys, value)
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/core/actions.py", line 1178, in recurse
    write("%12s %s\n" % (construct_keybinding(keys), value))
  File "/usr/local/Cellar/ranger/1.8.1/libexec/ranger/core/actions.py", line 1170, in write
    temporary_file.write(string.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 41: ordinal not in range(128)

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by Vifon** [comment]
Is it still reproducible on the current master branch?

**Comment by zzzdeb** [comment]
yes it is. Ubuntu 04.18, i3-gaps, ranger version: ranger 1.9.2
Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Locale: None.None
installed with pip

**Comment by Vifon** [comment]
A minute ago I installed ranger with pip on a clean Ubuntu 18.04 VM (Vagrant box `ubuntu/bionic64`) and I still cannot reproduce it, sorry.

**Comment by toonn** [comment]
Sounds like we're accidentally [reencoding as `utf-8` if the string already is](https://stackoverflow.com/questions/24475393/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-23-ordinal).

Maybe `ascii` really means "use locale's encoding" and therefor it doesn't happen for you, @Vifon, I assume you're using a utf8 locale?

**Comment by apnewberry** [comment]
On Ubuntu 18.04, pressing `k` breaks in the apt version, but it works in the pip version under either py2 or py3.

Breaks: 
```
/usr/bin/ranger --version                            
ranger-stable 1.8.1

Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0]
```

Works: 
 ```
venv/bin/ranger --version
ranger version: ranger 1.9.2
Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Locale: None.None

```

Works: 
```
ranger --version
ranger version: ranger 1.9.2
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
Locale: en_US.UTF-8
```

**Comment by toonn** [comment]
@zzzdeb, hmm, are you sure it reproduces with 1.9.2?
