### ISSUE TITLE
Crash while using photorec 

### ISSUE THREAD

**Issue by roorco** [ranger/ranger#950]
#### ISSUE TYPE
- Bug report
#### RUNTIME ENVIRONMENT

- Operating system and version:  manjaro 

- Terminal emulator and version: urxvt 9.22 
- Python version: 3.6
- Ranger version/commit: 1.8.1

#### CURRENT BEHAVIOR
It crashes during photorec was performing a scan.

#### TRACEBACK

```
Traceback (most recent call last):                             
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main                                              
    fm.loop()                  
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 362, in loop                                                
    ui.redraw()                
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 295, in redraw                                               
    self.draw()                
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 322, in draw                                                 
    DisplayableContainer.draw(self)                            
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw                                        
    displayable.draw()         
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 99, in draw                                 
    DisplayableContainer.draw(self)                            
  File "/usr/lib/python3.6/site-packageRanger s/ranger/gui/displayable.py", line 248, in draw                                        
    displayable.draw()         
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 166, in draw                              
    self._draw_file()          
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in _draw_file                        
    Pager.close(self)          
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 52, in close                                      
    self.clear_image()         
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 45, in clear_image                                
    self.fm.image_displayer.clear(self.x, self.y, self.wid, self.hei)                                                         
  File "/usr/lib/python3.6/site-packages/ranger/ext/img_display.py", line 114, in clear                                       
    fontw, fonth = self._get_font_dimensions()                 
  File "/usr/lib/python3.6/site-packages/ranger/ext/img_display.py", line 92, in _get_font_dimensions                         
    stdout=PIPE, universal_newlines=True)                      
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__                                                              
    restore_signals, start_new_session)                        
  File "/usr/lib/python3.6/subprocess.py", line 1267, in _execute_child                                                       
    restore_signals, start_new_session, preexec_fn)            
OSError: [Errno 12] Impossibile allocare memoria       
```

**Comment by Vifon** [comment]
It seems your system has run out of memory. Not much more ranger can do. I'm closing for now, if you think it's more than this, please reopen.
