### ISSUE TITLE
Ranger crash on m3u file

### ISSUE THREAD

**Issue by sirsurthur** [ranger/ranger#990]
ranger version: ranger-master 1.9.0b5
Python version: 3.6.3 (default, Oct 24 2017, 14:48:20) [GCC 7.2.0]
Locale: fr_FR.UTF-8
Current file: '/home/julien/Musique/***.m3u'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 387, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by sirsurthur** [comment]
ranger
ranger version: ranger-master 1.9.0b6
Python version: 3.6.3 (default, Oct 24 2017, 14:48:20) [GCC 7.2.0]
Locale: fr_FR.UTF-8
Current file: '/***.nfo'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 387, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

**Comment by nonamethanks** [comment]
Had the exact same error today. This is the file that caused the crash, zipped: 
[index.zip](https://github.com/ranger/ranger/files/1564291/index.zip)

Funnily enough, ranger crashes on the zipped file too.

**Comment by Vifon** [comment]
I cannot reproduce it on Python 3.5.2 and 2.7.12 but I can on 3.6.3. After some quick research it seems it might have been caused (or rather exposed as I suppose we should handle this case) by this change. https://github.com/python/cpython/pull/2302

**Comment by Vifon** [comment]
And thanks a lot for a test file @nonamethanks!

**Comment by sikmir** [comment]
The same crash for me.

**Comment by beanaroo** [comment]
I believe I came across the same issue:
```
<FE><FF>^@p^@a^@r^@a^@m^@(^@^M^@
^@      ^@      ^@$^@S^@e^@r^@v^@e^@r^@,^@^M^@
^@      ^@      ^@$^@S^@e^@r^@v^@i^@c^@e^@n^@a^@m^@e^@,^@^M^@
^@      ^@      ^@[^@s^@w^@i^@t^@c^@h^@]^@ ^@$^@s^@t^@o^@p^@,^@^M^@
^@      ^@      ^@[^@s^@w^@i^@t^@c^@h^@]^@ ^@$^@s^@t^@a^@r^@t^@^M^@
^@ ^@ ^@ ^@ ^@)^@^M^@
```
Is the `less` output of the top of the file.

**Comment by punzik** [comment]
Same issue on preview utf16 text file. File dump:

    00000000  ff fe 4c 00 69 00 6e 00  6b 00 3a 00 20 00 2f 00  |..L.i.n.k.:. ./.|
    00000010  76 00 61 00 72 00 2f 00  6c 00 6f 00 67 00 2f 00  |v.a.r./.l.o.g./.|
    00000020  73 00 79 00 73 00 6c 00  6f 00 67 00              |s.y.s.l.o.g.|

**Comment by toonn** [comment]
#1045 seems to suggest this may be triggered by an old `scope.sh` so try removing it if you don't customize it.

**Comment by sirsurthur** [comment]
Just tried but did not work. Still got this crash.

**Comment by toonn** [comment]
Yes, this issue is probably unrelated but it's still worth a shot since there were similar issues where this was the problem.

**Comment by toonn** [comment]
#1082 might be the same bug.

**Comment by annata83** [comment]
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8
Current file: '/home/niko/torrents/ES6 For Everyone/00 - getting setup.mp4'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character
#############################################################################
Is this the same issue?

**Comment by toonn** [comment]
@annata83 does look like it, have you tried removing `scope.sh` and removing/commenting out the line `set preview_script ...` in `rc.conf`?

**Comment by annata83** [comment]
@toonnI just did after you confirm that it actually looks like the same type of thing and it works.

**Comment by toonn** [comment]
@sirsurthur just noticed you're on 1.9.0b5-6, could you try the stable release?
